### PR TITLE
fix issues from klocwork and coverity

### PR DESCRIPTION
**Pull request by JanDorniak99**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/767)

### CODE REVIEW

**Review by igchor — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/767#-:-MGbo5AaEQBHdiH6qDY_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by lukaszstolarczuk — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/767#-:-MGc3n3R2tIe5nNkAWzu:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by igchor — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/767)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/767)* status: all files reviewed, 2 unresolved discussions (waiting on @JanDorniak99)

___
*[src/libpmemkv.hpp, line 402 at r2](https://reviewable.io/reviews/pmem/pmemkv/767#-MGcJRo695ef1MDyKQBG:-MGcJRo695ef1MDyKQBH:b-ec91fs) ([raw file](https://github.com/pmem/pmemkv/blob/980a434577d3fedcfdea6cd73b865a05905288b5/src/libpmemkv.hpp#L402)):*
> ```cpp
> inline config &config::operator=(config &&other) noexcept
> {
> 	if (this == &other)
> ```

Hm, thb this is quite an important fix. I believe it would be good to also fix this for previous stable branches. Could you remove this fix from this PR, and make a separate PR (with only this fix) for stable-1.0?
___
*[src/libpmemkv.hpp, line 876 at r2](https://reviewable.io/reviews/pmem/pmemkv/767#-MGcJrifCRJr1vX2QzlM:-MGcJrifCRJr1vX2QzlN:b3kqx) ([raw file](https://github.com/pmem/pmemkv/blob/980a434577d3fedcfdea6cd73b865a05905288b5/src/libpmemkv.hpp#L876)):*
> ```cpp
> {
> 	if (this == &other)
> 		return *this;
> ```

.

**Review by JanDorniak99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/767)* status: all files reviewed, 2 unresolved discussions (waiting on @igchor)

___
*[src/libpmemkv.hpp, line 402 at r2](https://reviewable.io/reviews/pmem/pmemkv/767#-MGcJRo695ef1MDyKQBG:-MGcOtf59igOsoQUSbBd:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/980a434577d3fedcfdea6cd73b865a05905288b5/src/libpmemkv.hpp#L402)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Hm, thb this is quite an important fix. I believe it would be good to also fix this for previous stable branches. Could you remove this fix from this PR, and make a separate PR (with only this fix) for stable-1.0?
</blockquote></details>

Done.
___
*[src/libpmemkv.hpp, line 876 at r2](https://reviewable.io/reviews/pmem/pmemkv/767#-MGcJrifCRJr1vX2QzlM:-MGcOtqW-rXwO3OqWn0E:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/980a434577d3fedcfdea6cd73b865a05905288b5/src/libpmemkv.hpp#L876)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by lukaszstolarczuk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/767#-:-MGcwIrR3CKyj6ewJBZ0:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @igchor)

**Review by igchor — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/767)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
