### PR TITLE
clean up poolset parts in run-build.sh

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
and extend logging in this script.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/778)

### CODE REVIEW

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/778#-:-MHM4dYM5GqOOt1hFc5Z:bnfp4nl)* status: 0 of 3 files reviewed, all discussions resolved

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/778)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[utils/docker/run-build.sh, line 239 at r1](https://reviewable.io/reviews/pmem/pmemkv/778#-MHM7Faw2uZDw1WzhMtI:-MHM7DS-BX9lcXZTTz2U:b-2j51da) ([raw file](https://github.com/pmem/pmemkv/blob/250962779469dba00df0f981b4978554ff8e65bc/utils/docker/run-build.sh#L239)):*
> ```Shell
> 	rm -rf build
> 	rm -rf $EXAMPLE_TEST_DIR
> 	rm /dev/shm/pmemkv_open_ex_pool.part*
> ```

```
 pmempool rm -f  ${WORKDIR}/examples/example.poolset 
``` 
would be more consistent and less error prone.

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/778)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @karczex)

___
*[utils/docker/run-build.sh, line 239 at r1](https://reviewable.io/reviews/pmem/pmemkv/778#-MHM7Faw2uZDw1WzhMtI:-MHMEGVq8MJCavX3ujXI:b-pkyw5m) ([raw file](https://github.com/pmem/pmemkv/blob/250962779469dba00df0f981b4978554ff8e65bc/utils/docker/run-build.sh#L239)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

```
 pmempool rm -f  ${WORKDIR}/examples/example.poolset 
``` 
would be more consistent and less error prone. 

</blockquote></details>

Done. That's perfect, thanks

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/778#-:-MHML_BSDTwKySv9KgiN:bnfp4nl)* status: 0 of 3 files reviewed, all discussions resolved

**Review by karczex — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/778)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
