### PR TITLE
Fix a bunch of typos.

### PR DESCRIPTION
**Pull request by kilobyte**
Only automated changes; I see a lot of abysmal grammar but reviewing all of that would be a lot of work.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/963)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 29 of 29 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/963)* status: all files reviewed, 1 unresolved discussion (waiting on @kilobyte)

___
*[src/valgrind/valgrind.h, line 1078 at r1](https://reviewable.io/reviews/pmem/pmemkv/963#-MVFlRn9Djgrf64GXgKI:-MVFlRnACstsrlCmtxkH:b-mtu2bu) ([raw file](https://github.com/pmem/pmemkv/blob/df02d5d7e90b6a36ab3edf8b265848535cbe64f0/src/valgrind/valgrind.h#L1078)):*
> ```objc
> /* Use these to write the name of your wrapper.  NOTE: duplicates
>    VG_WRAP_FUNCTION_Z{U,Z} in pub_tool_redir.h.  NOTE also: inserts
>    the default behaviour equivalence class tag "0000" into the name.
> ```

I'd not touch this file, is just a valgrind header ;)

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/963)* status: all files reviewed, 2 unresolved discussions (waiting on @kilobyte)

___
*[ChangeLog, line 45 at r1](https://reviewable.io/reviews/pmem/pmemkv/963#-MVG4XYbALf_iMj8su8D:-MVG4XYbALf_iMj8su8E:b-e8g67v) ([raw file](https://github.com/pmem/pmemkv/blob/df02d5d7e90b6a36ab3edf8b265848535cbe64f0/ChangeLog#L45)):*
> ```
> 
> 	This is the last bugfix release for pmemkv 1.0 version.
> 	Maintenance of this version is no longer supported.
> ```

Is it ok to change the ChangeLog?

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/963)* status: all files reviewed, 2 unresolved discussions (waiting on @igchor and @kilobyte)

___
*[ChangeLog, line 45 at r1](https://reviewable.io/reviews/pmem/pmemkv/963#-MVG4XYbALf_iMj8su8D:-MVGCFYdE90EyGQSAQXQ:b-mwn3r1) ([raw file](https://github.com/pmem/pmemkv/blob/df02d5d7e90b6a36ab3edf8b265848535cbe64f0/ChangeLog#L45)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Is it ok to change the ChangeLog?
</blockquote></details>

I'd say - why not - it's just a file ;) it's not linked anywhere..

**Review by kilobyte — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/963)* status: all files reviewed, 2 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[src/valgrind/valgrind.h, line 1078 at r1](https://reviewable.io/reviews/pmem/pmemkv/963#-MVFlRn9Djgrf64GXgKI:-MVNA2I3Ek0-vzhzaJNb:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/df02d5d7e90b6a36ab3edf8b265848535cbe64f0/src/valgrind/valgrind.h#L1078)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I'd not touch this file, is just a valgrind header ;)
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/963#-:-MVQ7nt6CE3oJR4YDWXC:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)

**Pull request merged**
