### PR TITLE
[tests] Fix Memkind related test

### PR DESCRIPTION
**Pull request by KFilipek**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1018)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1018)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @KFilipek)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/1018#-MeUMLndCgIo8jjfp-OY:-MeUMLne4Fn8ePDMgATE:b-4siq80) (no related file):*
pls update docs as well

---
*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/1018#-MeUMOxa8nWSLtZBivVB:-MeUMOxa8nWSLtZBivVC:b-ecv3gk) (no related file):*
pls update the commit msg - test worked just fine previously, this is just a good update

---

**Review by KFilipek — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1018)* status: all files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/1018#-MeUMLndCgIo8jjfp-OY:-MeUhiIr33L1SkXJGEUJ:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls update docs as well
</blockquote></details>

Done.

---
*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/1018#-MeUMOxa8nWSLtZBivVB:-MeUhiaf3I5Ov0DP2Vfl:b-hkppw0) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls update the commit msg - test worked just fine previously, this is just a good update
</blockquote></details>

Done. Changed for 2 memkind engines

---

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1018)* status: all files reviewed, 1 unresolved discussion (waiting on @KFilipek)

___
*[doc/libpmemkv.7.md, line 123 at r2](https://reviewable.io/reviews/pmem/pmemkv/1018#-MeUrqZ9611Ppq1b8tHl:-MeUrqZ9611Ppq1b8tHm:b-q9n4pa) ([raw file](https://github.com/pmem/pmemkv/blob/0ed64be0d8508f8146fef21bd7e9454146f75165/doc/libpmemkv.7.md#L123)):*
> ```Markdown
> * **size** --  Specifies size of the database [in bytes]
> 	+ type: uint64_t
> 	+ min value: 16777216 (16MB)
> ```

perhaps add ref to the actual const in their code (in case this will change and we forget to update our docs)

**Review by KFilipek — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1018)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[doc/libpmemkv.7.md, line 123 at r2](https://reviewable.io/reviews/pmem/pmemkv/1018#-MeUrqZ9611Ppq1b8tHl:-MeVP5nf8z44qgerTLOB:btg7kb3) ([raw file](https://github.com/pmem/pmemkv/blob/0ed64be0d8508f8146fef21bd7e9454146f75165/doc/libpmemkv.7.md#L123)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps add ref to the actual const in their code (in case this will change and we forget to update our docs)
</blockquote></details>

Done. I've added information where this value can be found when neccessary.

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1018#-:-MeYaXPB3pUlpAiTA2WB:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1018#-:-MeYu2lLBgTx16sF1QlR:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1018#-:-MeZ4Y4qEG7FE15b9kb_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KFilipek)

**Pull request merged**
