### PR TITLE
[gh-pages] add 'reports' sub-section with initial performance measurements

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
Preview:
https://lukaszstolarczuk.github.io/pmemkv/#performance-reports

// the external storage space is just too long waiting time, so for now we publish this one into GH; later on, we move on to the new storage place (I hope 😸 )

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1048)

### CODE REVIEW

**Comment by karczex** [comment]
___
*[reports/index.md, line 1 at r2](https://reviewable.io/reviews/pmem/pmemkv/1048#-MlAMWoh66qJMxmoLBSa:-MlAMWoh66qJMxmoLBSb:b-9g9c3j) ([raw file](https://github.com/pmem/pmemkv/blob/fd88ae2edfc4ebe54a3e9ceffa8347babe2341f1/reports/index.md#L1)):*
> ```Markdown
> ---
> ```

Is reports directory really needed? Probably you may just add `perdormace_reports.md` to main directory. Or even add section to README.md.

**Review by KFilipek — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1048#-:-MlARwaQ9ueF6kB4vBCm:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1048)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @karczex and @KFilipek)

___
*[reports/index.md, line 1 at r2](https://reviewable.io/reviews/pmem/pmemkv/1048#-MlAMWoh66qJMxmoLBSa:-MlAStn20Zyw-7uM20P8:b-v57im5) ([raw file](https://github.com/pmem/pmemkv/blob/fd88ae2edfc4ebe54a3e9ceffa8347babe2341f1/reports/index.md#L1)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Is reports directory really needed? Probably you may just add `perdormace_reports.md` to main directory. Or even add section to README.md.
</blockquote></details>

hah, good catch. Dir is not needed, but I think we may have this list of reports (perhaps not only performance ones) quite long, someday... so the separate `reports.md` seems like a good idea.

**Review by karczex — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1048#-:-MlDjF1dEQbtnstDyxBA:bnfp4nl)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @KFilipek)

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1048#-:-MlEZAqf8PzjcQGCLBWA:bnfp4nl)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @KFilipek)

**Pull request merged**
