### PR TITLE
Change include ifdefs to include guards in engines .h files

### PR DESCRIPTION
**Pull request by karczex**
This is rather trivial approach to make engine.cc little bit more
maintainable

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/953)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/953)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @karczex)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/953#-MUss_a755ixqpcel8wS:-MUss_a755ixqpcel8wT:beatk5l) (no related file):*
I'm not sure if that's helpful, you can now easily forget to check for this `if` imho - it seems to fade into other #preprocessor stuff

anyway, if we want to go with this change, pls update CONTRIBUTING.md

---

**Comment by KFilipek** [comment]
As I see it's still draft

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/953)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @KFilipek)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/953#-MUss_a755ixqpcel8wS:-MUwY9yn6s2U7Pxo5x8C:b3uu4nw) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I'm not sure if that's helpful, you can now easily forget to check for this `if` imho - it seems to fade into other #preprocessor stuff

anyway, if we want to go with this change, pls update CONTRIBUTING.md
</blockquote></details>

I made this change mostly as starting point for the discussion. 
As @kfilipek mentioned, cleanup of this file is needed - and this is first, very simple approach. We may (or even should) consider something more sophisticated. Do you have any better idea how to remove those ifdefs on includes?

In general, I think, include guards in headers are easier to maintain, than `ifdefed` includes in engine.cc 

---

**Comment by KFilipek** [comment]
> I made this change mostly as starting point for the discussion.

I know, szanuje.
In MongoDB they initialize engines in _*\_init.cpp_ (e.g. [devnull_unit.cpp](https://github.com/mongodb/mongo/blob/master/src/mongo/db/storage/devnull/devnull_init.cpp)). Every engine implements Factory interface (_StorageEngine::Factory_) which is registered by _ServiceContext::ConstructorActionRegisterer_. After registration MongoDB takes proper factory using engine name defined in engine itself. There is no changes needed inside MongoDB code and I believe this is a way we want in PmemKV. I will make simple example of this approach.

**Comment by karczex** [comment]
@KFilipek Is doing more generic solution of this problem.

**Pull request closed without merging**
