### PR TITLE
Update examples

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
- extend 'open' example (with re-open scenario),
- extend a little config example and its CMake,
- code and docs minor cleanups,
- enable more examples execution in CI and compilation of all of them.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1045)

### CODE REVIEW

**Review by karczex — COMMENTED** [review]
> Reviewed 8 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1045)* status: 8 of 9 files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[examples/pmemkv_open_cpp/pmemkv_open.cpp, line 37 at r1](https://reviewable.io/reviews/pmem/pmemkv/1045#-Mk1X05BBqfsPzPGmrzv:-Mk1X05BBqfsPzPGmrzw:bqmyg0c) ([raw file](https://github.com/pmem/pmemkv/blob/0570a7b7e5e2082d2a7091b20d30647950f10bc7/examples/pmemkv_open_cpp/pmemkv_open.cpp#L37)):*
> ```cpp
>  * pmempool create -l "pmemkv" obj ../examples/example.poolset
>  *
>  * Word of explanation: "pmemkv" is a pool layout used by cmap engine.
> ```

We should rethink using pmempool in examples.
___
*[examples/pmemkv_open_cpp/pmemkv_open.cpp, line 86 at r1](https://reviewable.io/reviews/pmem/pmemkv/1045#-Mk1XLRt7Gl0UsR3YFE2:-Mk1XLRt7Gl0UsR3YFE3:b-jwqejz) ([raw file](https://github.com/pmem/pmemkv/blob/0570a7b7e5e2082d2a7091b20d30647950f10bc7/examples/pmemkv_open_cpp/pmemkv_open.cpp#L86)):*
> ```cpp
> 
> 	LOG("Closing database");
> 	delete kv;
> ```

Another thing, we should rethink, is using raw pointers in examples. Maybe it should be just pmemkv object, or unique_ptr.

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1045)* status: 5 of 12 files reviewed, all discussions resolved (waiting on @karczex)

___
*[examples/pmemkv_open_cpp/pmemkv_open.cpp, line 37 at r1](https://reviewable.io/reviews/pmem/pmemkv/1045#-Mk1X05BBqfsPzPGmrzv:-Mk1g7Zi9yOoEFF-JRWJ:bqljsei) ([raw file](https://github.com/pmem/pmemkv/blob/0570a7b7e5e2082d2a7091b20d30647950f10bc7/examples/pmemkv_open_cpp/pmemkv_open.cpp#L37)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

We should rethink using pmempool in examples.
</blockquote></details>

that's why I extended the comment - it's possible to use it, but not advised

do you have something specific in mind, we should write here instead?
___
*[examples/pmemkv_open_cpp/pmemkv_open.cpp, line 86 at r1](https://reviewable.io/reviews/pmem/pmemkv/1045#-Mk1XLRt7Gl0UsR3YFE2:-Mk1seyt0nFInMvHYbRH:b-njuan8) ([raw file](https://github.com/pmem/pmemkv/blob/0570a7b7e5e2082d2a7091b20d30647950f10bc7/examples/pmemkv_open_cpp/pmemkv_open.cpp#L86)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Another thing, we should rethink, is using raw pointers in examples. Maybe it should be just pmemkv object, or unique_ptr. 
</blockquote></details>

we had some examples with this approach and some with that. I've made more examples with kv objects and added the comment in basic_example for clarity.

**Review by KFilipek — CHANGES_REQUESTED** [review]
> Reviewed 4 of 9 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1045)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[examples/pmemkv_open_cpp/pmemkv_open.cpp, line 99 at r2](https://reviewable.io/reviews/pmem/pmemkv/1045#-Mk1yZuH1ruKwgziuL1H:-Mk1yZuI1OFivSFPRGbd:b-nstn9s) ([raw file](https://github.com/pmem/pmemkv/blob/6ae4de42f41d313b1b7807d85f290f10bbd17e1a/examples/pmemkv_open_cpp/pmemkv_open.cpp#L99)):*
> ```
> kv = new db();
> ```
why not automatic like before?

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1045)* status: 6 of 12 files reviewed, 1 unresolved discussion (waiting on @KFilipek)

___
*[examples/pmemkv_open_cpp/pmemkv_open.cpp, line 99 at r2](https://reviewable.io/reviews/pmem/pmemkv/1045#-Mk1yZuH1ruKwgziuL1H:-Mk20GWR8R43nwOWfu7r:bklb9p4) ([raw file](https://github.com/pmem/pmemkv/blob/6ae4de42f41d313b1b7807d85f290f10bbd17e1a/examples/pmemkv_open_cpp/pmemkv_open.cpp#L99)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> kv = new db();
> ```
why not automatic like before?
</blockquote></details>

I'm not sure what do you mean?

**Review by KFilipek — APPROVED** [review]
> Reviewed 2 of 9 files at r1, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1045)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

___
*[examples/pmemkv_open_cpp/pmemkv_open.cpp, line 99 at r2](https://reviewable.io/reviews/pmem/pmemkv/1045#-Mk1yZuH1ruKwgziuL1H:-Mk2EHI_7RehL1smuocu:bipb5ro) ([raw file](https://github.com/pmem/pmemkv/blob/6ae4de42f41d313b1b7807d85f290f10bbd17e1a/examples/pmemkv_open_cpp/pmemkv_open.cpp#L99)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I'm not sure what do you mean?
</blockquote></details>

Discussed offline, it's ok

**Review by igchor — APPROVED** [review]
:lgtm:

> Reviewed 3 of 9 files at r1, 4 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1045#-:-Mk2N_fGBxLrmtBVrJz-:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1045)* status: 11 of 12 files reviewed, all discussions resolved (waiting on @igchor and @KFilipek)

___
*[examples/pmemkv_open_cpp/pmemkv_open.cpp, line 99 at r2](https://reviewable.io/reviews/pmem/pmemkv/1045#-Mk1yZuH1ruKwgziuL1H:-Mk2O9yi1eKzqxTXPnHR:b-nd312l) ([raw file](https://github.com/pmem/pmemkv/blob/6ae4de42f41d313b1b7807d85f290f10bbd17e1a/examples/pmemkv_open_cpp/pmemkv_open.cpp#L99)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Discussed offline, it's ok
</blockquote></details>

I've only added the `kv = nullptr` line, as discussed, just to show good practice

**Comment by karczex** [comment]
___
*[examples/pmemkv_open_cpp/pmemkv_open.cpp, line 37 at r1](https://reviewable.io/reviews/pmem/pmemkv/1045#-Mk1X05BBqfsPzPGmrzv:-Mk75ydjBTMJZfX2qxQ-:b-w06hop) ([raw file](https://github.com/pmem/pmemkv/blob/0570a7b7e5e2082d2a7091b20d30647950f10bc7/examples/pmemkv_open_cpp/pmemkv_open.cpp#L37)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

that's why I extended the comment - it's possible to use it, but not advised

do you have something specific in mind, we should write here instead?
</blockquote></details>

Since we have create_if_missing, we should use it in examples instead of using pmempool. I think, currently it is unnecessary leaking the abstraction - especially it is example, so it should show best practice of using pmemkv.
As I can see, we even suggest using create_if_missing in the comment.

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1045)* status: 11 of 12 files reviewed, all discussions resolved (waiting on @igchor and @KFilipek)

___
*[examples/pmemkv_open_cpp/pmemkv_open.cpp, line 37 at r1](https://reviewable.io/reviews/pmem/pmemkv/1045#-Mk1X05BBqfsPzPGmrzv:-Mk79S1s5tWcoET8TYWf:b-9mjxl3) ([raw file](https://github.com/pmem/pmemkv/blob/0570a7b7e5e2082d2a7091b20d30647950f10bc7/examples/pmemkv_open_cpp/pmemkv_open.cpp#L37)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Since we have create_if_missing, we should use it in examples instead of using pmempool. I think, currently it is unnecessary leaking the abstraction - especially it is example, so it should show best practice of using pmemkv.
As I can see, we even suggest using create_if_missing in the comment. 
</blockquote></details>

hmm.. "yes" and "no" - we have plenty of examples showing the best possible approach (see e.g. "pmemkv_basic_*").
In this example, we show different approach, which may be useful for some use cases. If some beginners will encounter this example they will read our comments and know there are better ways.
soo... I'd leave it as is.

**Review by karczex — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1045#-:-MkBS-QGEMtVFD-V9jLn:bnfp4nl)* status: 11 of 12 files reviewed, all discussions resolved (waiting on @igchor and @KFilipek)

**Pull request merged**
