### PR TITLE
Add KVDK Engine

### PR DESCRIPTION
**Pull request by ZiyanShi**
This branch is based on work of Mr. Paweł Karczewski.
It contains wrappers for KVDK to add an unordered and an ordered engine to pmemkv.
Newly added modules has not passed ctest yet. We are still debugging.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1056)

### CODE REVIEW

**Review by igchor — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r1, 1 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1056)* status: 2 of 9 files reviewed, 5 unresolved discussions (waiting on @igchor and @ZiyanShi)

___
*[src/engines-experimental/kvdk_sorted.cc, line 36 at r3](https://reviewable.io/reviews/pmem/pmemkv/1056#-MtNu6Um73N55VAUqHU7:-MtNu6Um73N55VAUqHU8:b6fcqcv) ([raw file](https://github.com/pmem/pmemkv/blob/11a872b8e5aabb7d034242b971a8d25d79d60b5c/src/engines-experimental/kvdk_sorted.cc#L36)):*
> ```cpp
> 	storage_engine::Configs engine_configs;
> 	engine_configs.pmem_file_size = cfg->get_size();
> 	engine_configs.pmem_segment_blocks = (1ull << 10);
> ```

Shouldn't this be configured (through pmemkv config)?
___
*[src/engines-experimental/kvdk_sorted.cc, line 39 at r3](https://reviewable.io/reviews/pmem/pmemkv/1056#-MtNuG3zE3ISWke3H0Wd:-MtNuG3zE3ISWke3H0We:bf1tprn) ([raw file](https://github.com/pmem/pmemkv/blob/11a872b8e5aabb7d034242b971a8d25d79d60b5c/src/engines-experimental/kvdk_sorted.cc#L39)):*
> ```cpp
> 	engine_configs.hash_bucket_num = (1ull << 20);
> 
> 	auto status = storage_engine::Engine::Open(cfg->get_path(), &engine,
> ```

If this call can fail, I belive you should propagate the error to the user. You can do that by throwing an exception: https://github.com/pmem/pmemkv/blob/master/src/exceptions.h Those exceptions correspond to statuses.

For example throw internal::invalid_argument here it will be returned from pmemkv_open() as invalid_argument status to the user
___
*[src/engines-experimental/kvdk_sorted.cc, line 63 at r3](https://reviewable.io/reviews/pmem/pmemkv/1056#-MtNvY-nEqFLgySQDPyv:-MtNvY-o1sWe5ooVkSdo:b-uqymbz) ([raw file](https://github.com/pmem/pmemkv/blob/11a872b8e5aabb7d034242b971a8d25d79d60b5c/src/engines-experimental/kvdk_sorted.cc#L63)):*
> ```cpp
> 
> 	auto iter = engine->NewSortedIterator(collection);
> 	if (!iter)
> ```

Is it only possible for empty collection or can this indicate an error?
___
*[src/engines-experimental/kvdk_sorted.cc, line 401 at r3](https://reviewable.io/reviews/pmem/pmemkv/1056#-MtNwcl9EmAxRenTlhUQ:-MtNwcl9EmAxRenTlhUR:btjnfpj) ([raw file](https://github.com/pmem/pmemkv/blob/11a872b8e5aabb7d034242b971a8d25d79d60b5c/src/engines-experimental/kvdk_sorted.cc#L401)):*
> ```cpp
> {
> 	LOG("read_range, pos=" << pos << " n=" << n);
> 	throw std::runtime_error("kvdk_sorted current does not support random access.");
> ```

So, in kvdk is always returned by copy, right?
___
*[src/engines-experimental/kvdk_unsorted.cc, line 87 at r3](https://reviewable.io/reviews/pmem/pmemkv/1056#-MtNwn_fE9bW4qdaHbV4:-MtNwn_fE9bW4qdaHbV5:bwmszoi) ([raw file](https://github.com/pmem/pmemkv/blob/11a872b8e5aabb7d034242b971a8d25d79d60b5c/src/engines-experimental/kvdk_unsorted.cc#L87)):*
> ```cpp
> {
> 	LOG("remove key=" << std::string(key.data(), key.size()));
> 	auto status = exists(key);
> ```

Can there be a race in this scenario? E.g. this thread calls exists which returns status::OK, then some other thread removes the element. In such case, the return status will be

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1056)* status: 2 of 9 files reviewed, 5 unresolved discussions (waiting on @igchor and @ZiyanShi)

___
*[src/engines-experimental/kvdk_unsorted.cc, line 87 at r3](https://reviewable.io/reviews/pmem/pmemkv/1056#-MtNwn_fE9bW4qdaHbV4:-MtO8dKt7__SWW6FxmuA:bsgs4mk) ([raw file](https://github.com/pmem/pmemkv/blob/11a872b8e5aabb7d034242b971a8d25d79d60b5c/src/engines-experimental/kvdk_unsorted.cc#L87)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Can there be a race in this scenario? E.g. this thread calls exists which returns status::OK, then some other thread removes the element. In such case, the return status will be 
</blockquote></details>

... status::OK where it should be NOT_FOUND. Myabe if kvdk does not return information about whether key existed or not, we should just return what engine->Delete returned and document this?

**Review by karczex — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1056)* status: 3 of 9 files reviewed, 11 unresolved discussions (waiting on @igchor, @karczex, and @ZiyanShi)

___
*[-- commits, line 1 at r3](https://reviewable.io/reviews/pmem/pmemkv/1056#-MtRhRSU1DM17JwiFF-0):*
Your commits are little bit messy. As it's a draft it is OK, but please organize it (or squash) before marking it as ready for review. 
___
*[cmake/kvdk.cmake, line 6 at r3](https://reviewable.io/reviews/pmem/pmemkv/1056#-MtRpBwCBHUGf8AFc2EU:-MtRpBwCBHUGf8AFc2EV:bjysrb) ([raw file](https://github.com/pmem/pmemkv/blob/11a872b8e5aabb7d034242b971a8d25d79d60b5c/cmake/kvdk.cmake#L6)):*
> ```CMake
> message(STATUS "Checking for module 'kvdk'")
> 
> if(PKG_CONFIG_FOUND)
> ```

Please add else() similar to one in `libpmemobj++.cmake`
___
*[src/engines-experimental/kvdk_sorted.cc, line 149 at r3](https://reviewable.io/reviews/pmem/pmemkv/1056#-MtRtYP43tBveA715f2c:-MtRtYP43tBveA715f2d:b-llffe6) ([raw file](https://github.com/pmem/pmemkv/blob/11a872b8e5aabb7d034242b971a8d25d79d60b5c/src/engines-experimental/kvdk_sorted.cc#L149)):*
> ```cpp
> 		return status::OK;
> 
> 	for (iter->Seek(key1_copy); iter->Valid() && (iter->Key() <= key2_copy);
> ```

Isn't it possible to create two sorted iterators and compare it instead of getting key for each element? Comparison of long strings may be slow.
___
*[src/engines-experimental/kvdk_sorted.cc, line 269 at r3](https://reviewable.io/reviews/pmem/pmemkv/1056#-MtRvRYiErvPQDwotZ30:-MtRvRYiErvPQDwotZ31:bwd12gt) ([raw file](https://github.com/pmem/pmemkv/blob/11a872b8e5aabb7d034242b971a8d25d79d60b5c/src/engines-experimental/kvdk_sorted.cc#L269)):*
> ```cpp
> 		return status::NOT_FOUND;
> 
> 	for (iter->Seek(key1_copy); iter->Valid() && (iter->Key() <= key2_copy);
> ```

You call 
```C++
iter->Key() 
```
twice here. As it's std::string you have to do copy twice.



_Code quote:_
```cpp
	for (iter->Seek(key1_copy); iter->Valid() && (iter->Key() <= key2_copy);
	     iter->Next()) {
		auto key = iter->Key();
```
___
*[src/engines-experimental/kvdk_sorted.cc, line 381 at r3](https://reviewable.io/reviews/pmem/pmemkv/1056#-MtRxNIHDaHZCSiegXIY:-MtRxNII7iGu0mFVHRDk:b6fu4t0) ([raw file](https://github.com/pmem/pmemkv/blob/11a872b8e5aabb7d034242b971a8d25d79d60b5c/src/engines-experimental/kvdk_sorted.cc#L381)):*
> ```cpp
> 			return status::OK;
> 		else
> 			return status::NOT_SUPPORTED;
> ```

Probably should be `status::NOT_FOUND`
___
*[src/engines-experimental/kvdk_sorted.cc, line 390 at r3](https://reviewable.io/reviews/pmem/pmemkv/1056#-MtRzy0jEdn3LiAqD22u:-MtRzy0jEdn3LiAqD22v:b-rqsr5c) ([raw file](https://github.com/pmem/pmemkv/blob/11a872b8e5aabb7d034242b971a8d25d79d60b5c/src/engines-experimental/kvdk_sorted.cc#L390)):*
> ```cpp
> 	LOG("key");
> 	if (iterator->Valid()) {
> 		key_local = iterator->Key();
> ```

As local_key is global for all calls to `key()` it would not work properly in such case: 
```C++
auto first_key = it.key();
it.next()
auto second_key = it.key()
// Here first_key points to the same data as second_key, but with wrong length.
```

Please look at this (wrong!) code snippet: 
```C++
#include <iostream>
#include <string>
#include <string_view>

int main(int argc, char* argv[]) {

	std::string a = "bsdfg";
	std::string b = "a";

	std::string foo = a;
	auto bar = std::string_view(foo);
	std::cout << "bar size: " <<  bar.size() << " bar value: " << bar << std::endl;
	foo = b;
	std::cout << "bar size: " <<  bar.size() << " bar value: " << bar << std::endl;
}
```

it returns: 
``` 
bar size: 5 bar value: bsdfg
bar size: 5 bar value: adfg
```
which is not what you want.



_Code quote:_
```cpp
		key_local = iterator->Key();
		return string_view{key_local};
```

**Review by karczex — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1056)* status: 3 of 9 files reviewed, 12 unresolved discussions (waiting on @igchor, @karczex, and @ZiyanShi)

___
*[src/engines-experimental/kvdk_unsorted.cc, line 13 at r3](https://reviewable.io/reviews/pmem/pmemkv/1056#-MtS60RJ9B3aVPyEKud5:-MtS60RJ9B3aVPyEKud6:bh79syr) ([raw file](https://github.com/pmem/pmemkv/blob/11a872b8e5aabb7d034242b971a8d25d79d60b5c/src/engines-experimental/kvdk_unsorted.cc#L13)):*
> ```cpp
> {
> 
> status kvdk_unsorted::status_mapper(storage_engine::Status s)
> ```

You should share this function between both of your engines. Please consider adding some header. 
___
*[src/engines-experimental/kvdk_unsorted.cc, line 87 at r3](https://reviewable.io/reviews/pmem/pmemkv/1056#-MtNwn_fE9bW4qdaHbV4:-MtS7B307hZYP6ScLeHx:b1okbrw) ([raw file](https://github.com/pmem/pmemkv/blob/11a872b8e5aabb7d034242b971a8d25d79d60b5c/src/engines-experimental/kvdk_unsorted.cc#L87)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

... status::OK where it should be NOT_FOUND. Myabe if kvdk does not return information about whether key existed or not, we should just return what engine->Delete returned and document this?
</blockquote></details>

Good point. It also apply to sorted engine. 
@igchor As all tests passed, it seems, we don't have test for such scenario.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 2 of 8 files at r1, 1 of 7 files at r2, 3 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1056)* status: 6 of 11 files reviewed, 33 unresolved discussions (waiting on @igchor, @karczex, @lukaszstolarczuk, and @ZiyanShi)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/1056#-MuLeEpXA0whR5Qsp23S:-MuLeEpXA0whR5Qsp23T:blzacr6) (no related file):*
please update test `wrong_engine_name_test.cc` with new engines

---
*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/1056#-MuLefDJDroBDrrDo_QJ:-MuLefDJDroBDrrDo_QK:b-ewqawg) (no related file):*
please take a look at our guideline for creating a new engine - I believe at least CI scripts and documentation should be updated:

https://github.com/pmem/pmemkv/blob/master/CONTRIBUTING.md#updating-common-source

---
___
*[CMakeLists.txt, line 34 at r4](https://reviewable.io/reviews/pmem/pmemkv/1056#-MuLTrKWBJVSiaCEkM7i:-MuLTrKWBJVSiaCEkM7j:b-etfnyq) ([raw file](https://github.com/pmem/pmemkv/blob/32c37c38f85e57796ff4f2982a040e2832c9aa00/CMakeLists.txt#L34)):*
> ```CMake
> 
> # Each engine can be enabled separately.
> option(ENGINE_CMAP "enable cmap engine" OFF)
> ```

when this PR will be ready (won't be a draft), please make sure to revert all these `OFF`s back to `ON`s
___
*[CMakeLists.txt, line 331 at r4](https://reviewable.io/reviews/pmem/pmemkv/1056#-MuLU9jW2I6G9vYwnU9f:-MuLU9jW2I6G9vYwnU9g:bddvlg8) ([raw file](https://github.com/pmem/pmemkv/blob/32c37c38f85e57796ff4f2982a040e2832c9aa00/CMakeLists.txt#L331)):*
> ```CMake
> 	include(kvdk)
> 	list(APPEND PKG_CONFIG_REQUIRES kvdk)
> endif()
> ```

I believe we have to also add RPM_ and DEB_ dependencies. Without this, it won't be possible to properly build pmemkv's package with these new engines turned on.
___
*[cmake/kvdk.cmake, line 7 at r4](https://reviewable.io/reviews/pmem/pmemkv/1056#-MuLUesfElPcDVxgauLY:-MuLUesfElPcDVxgauLZ:bstja90) ([raw file](https://github.com/pmem/pmemkv/blob/32c37c38f85e57796ff4f2982a040e2832c9aa00/cmake/kvdk.cmake#L7)):*
> ```CMake
> 
> if(PKG_CONFIG_FOUND)
>     pkg_check_modules(kvdk kvdk)
> ```

please add the keyword REQUIRED (similarly to how it's done in the abovementioned `libpmemobj++.cmake`).
___
*[cmake/kvdk.cmake, line 10 at r4](https://reviewable.io/reviews/pmem/pmemkv/1056#-MuLWFFm75qkGd394dhH:-MuLWFFnEfgsBu9xsJRP:b-5737tq) ([raw file](https://github.com/pmem/pmemkv/blob/32c37c38f85e57796ff4f2982a040e2832c9aa00/cmake/kvdk.cmake#L10)):*
> ```CMake
> endif()
> 
> include_directories(${kvdk_INCLUDE_DIRS})
> ```

based on the current CI error (`kvdk/engine.hpp: No such file or directory`) I believe these variable for INCLUDE_DIRS may be unset or set improperly (please check in your build - `CMakeCache.txt` file has all the values of CMake variables).
___
*[src/engines-experimental/kvdk_sorted.cc, line 118 at r4](https://reviewable.io/reviews/pmem/pmemkv/1056#-MuLZf2p3Xh6yN0Vgv29:-MuLZf2p3Xh6yN0Vgv2A:b-cb7yuz) ([raw file](https://github.com/pmem/pmemkv/blob/32c37c38f85e57796ff4f2982a040e2832c9aa00/src/engines-experimental/kvdk_sorted.cc#L118)):*
> ```cpp
> }
> 
> // count elements in range [key1, key2]
> ```

the range is actually `(key1, key2)` both keys are excluded
___
*[src/engines-experimental/kvdk_sorted.cc, line 165 at r4](https://reviewable.io/reviews/pmem/pmemkv/1056#-MuL_-Bh72kXY34COiog:-MuL_-Bh72kXY34COioh:b-n2kmas) ([raw file](https://github.com/pmem/pmemkv/blob/32c37c38f85e57796ff4f2982a040e2832c9aa00/src/engines-experimental/kvdk_sorted.cc#L165)):*
> ```cpp
> 		return status::NOT_FOUND;
> 
> 	for (iter->SeekToLast(); iter->Valid() && (iter->Key() > key_copy);
> ```

I guess you should seek to `key_copy` and then go `next`
___
*[src/engines-experimental/kvdk_sorted.cc, line 186 at r4](https://reviewable.io/reviews/pmem/pmemkv/1056#-MuL_7TxEd_GsCzveaAT:-MuL_7TxEd_GsCzveaAU:b3kqx) ([raw file](https://github.com/pmem/pmemkv/blob/32c37c38f85e57796ff4f2982a040e2832c9aa00/src/engines-experimental/kvdk_sorted.cc#L186)):*
> ```cpp
> 		return status::NOT_FOUND;
> 
> 	for (iter->SeekToLast(); iter->Valid() && (iter->Key() >= key_copy);
> ```

.
___
*[src/engines-experimental/kvdk_sorted.cc, line 285 at r4](https://reviewable.io/reviews/pmem/pmemkv/1056#-MuLay9AAsvno0VGxpQ6:-MuLay9B6Mu7HS2PIuHF:b-ebn2mj) ([raw file](https://github.com/pmem/pmemkv/blob/32c37c38f85e57796ff4f2982a040e2832c9aa00/src/engines-experimental/kvdk_sorted.cc#L285)):*
> ```cpp
> {
> 	LOG("put key=" << std::string(key.data(), key.size())
> 		       << ", value.size=" << std::to_string(value.size()));
> ```

Why do we print `value.size`? please just print `key` and `value`

I know we have the same issue in other engines, please just fix here for now :wink: 
___
*[src/engines-experimental/kvdk_sorted.cc, line 305 at r4](https://reviewable.io/reviews/pmem/pmemkv/1056#-MuLa8KZ4kVk4Xhp_oJ6:-MuLa8K_95mw3yWnEPrQ:b-2gt9p3) ([raw file](https://github.com/pmem/pmemkv/blob/32c37c38f85e57796ff4f2982a040e2832c9aa00/src/engines-experimental/kvdk_sorted.cc#L305)):*
> ```cpp
> 	LOG("create write iterator");
> 
> 	throw std::runtime_error("kvdk_sorted current does not support write iterator.");
> ```

`current` -> `currently`
___
*[src/engines-experimental/kvdk_sorted.cc, line 329 at r4](https://reviewable.io/reviews/pmem/pmemkv/1056#-MuLaC_t0bw9v-CMc6bT:-MuLaC_t0bw9v-CMc6bU:b-2gt9p3) ([raw file](https://github.com/pmem/pmemkv/blob/32c37c38f85e57796ff4f2982a040e2832c9aa00/src/engines-experimental/kvdk_sorted.cc#L329)):*
> ```cpp
> {
> 	LOG("seek to key=" << std::string(key.data(), key.size()));
> 	throw std::runtime_error("kvdk_sorted current does not support write iterator.");
> ```

`current` -> `currently`
___
*[src/engines-experimental/kvdk_sorted.cc, line 336 at r4](https://reviewable.io/reviews/pmem/pmemkv/1056#-MuLaDr8311D0jDwbIrD:-MuLaDr8311D0jDwbIrE:b-2gt9p3) ([raw file](https://github.com/pmem/pmemkv/blob/32c37c38f85e57796ff4f2982a040e2832c9aa00/src/engines-experimental/kvdk_sorted.cc#L336)):*
> ```cpp
> {
> 	LOG("key");
> 	throw std::runtime_error("kvdk_sorted current does not support write iterator.");
> ```

`current` -> `currently`
___
*[src/engines-experimental/kvdk_sorted.cc, line 344 at r4](https://reviewable.io/reviews/pmem/pmemkv/1056#-MuLaFb68c3Gmtho3DA8:-MuLaFb68c3Gmtho3DA9:b-2gt9p3) ([raw file](https://github.com/pmem/pmemkv/blob/32c37c38f85e57796ff4f2982a040e2832c9aa00/src/engines-experimental/kvdk_sorted.cc#L344)):*
> ```cpp
> {
> 	LOG("read_range, pos=" << pos << " n=" << n);
> 	throw std::runtime_error("kvdk_sorted current does not support write iterator.");
> ```

`current` -> `currently`
___
*[src/engines-experimental/kvdk_sorted.cc, line 383 at r4](https://reviewable.io/reviews/pmem/pmemkv/1056#-MuLbQZHA4WINtWyS6-s:-MuLbQZHA4WINtWyS6-t:b-2gt9p3) ([raw file](https://github.com/pmem/pmemkv/blob/32c37c38f85e57796ff4f2982a040e2832c9aa00/src/engines-experimental/kvdk_sorted.cc#L383)):*
> ```cpp
> {
> 	LOG("read_range, pos=" << pos << " n=" << n);
> 	throw std::runtime_error("kvdk_sorted current does not support random access.");
> ```

`current` -> `currently`
___
*[src/engines-experimental/kvdk_status.h, line 1 at r4](https://reviewable.io/reviews/pmem/pmemkv/1056#-MuLbSnn-5nc2hKaw3Uw:-MuLbSnn-5nc2hKaw3Ux:b-mf0o9g) ([raw file](https://github.com/pmem/pmemkv/blob/32c37c38f85e57796ff4f2982a040e2832c9aa00/src/engines-experimental/kvdk_status.h#L1)):*
> ```objc
> #pragma once
> ```

this pragma is not required, since we have a header guard
___
*[src/engines-experimental/kvdk_status.h, line 3 at r4](https://reviewable.io/reviews/pmem/pmemkv/1056#-MuLbaAA2n3p8NxtwAxV:-MuLbaAA2n3p8NxtwAxW:bpjuiy7) ([raw file](https://github.com/pmem/pmemkv/blob/32c37c38f85e57796ff4f2982a040e2832c9aa00/src/engines-experimental/kvdk_status.h#L3)):*
> ```objc
> #pragma once
> 
> #ifndef KVDK_STATUS_MAPPER_H
> ```

please rename this header guard with `LIBPMEMKV_` (like e.g. in another header `LIBPMEMKV_KVDK_SORTED_H`)
___
*[src/engines-experimental/kvdk_status.h, line 20 at r4](https://reviewable.io/reviews/pmem/pmemkv/1056#-MuLbo8p-GG2gCORq4DR:-MuLbo8p-GG2gCORq4DS:bkzy225) ([raw file](https://github.com/pmem/pmemkv/blob/32c37c38f85e57796ff4f2982a040e2832c9aa00/src/engines-experimental/kvdk_status.h#L20)):*
> ```objc
> } /* namespace pmem */
> 
> #endif /* KVDK_STATUS_MAPPER_H */
> ```

please add one extra enter (the red icon suggests you're missing it)
___
*[src/engines-experimental/kvdk_unsorted.cc, line 87 at r3](https://reviewable.io/reviews/pmem/pmemkv/1056#-MtNwn_fE9bW4qdaHbV4:-MuLcv8zCr5x3GATeqmo:bgbe119) ([raw file](https://github.com/pmem/pmemkv/blob/11a872b8e5aabb7d034242b971a8d25d79d60b5c/src/engines-experimental/kvdk_unsorted.cc#L87)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Good point. It also apply to sorted engine. 
@igchor As all tests passed, it seems, we don't have test for such scenario. 
</blockquote></details>

@karczex, not all tests are enabled right now
___
*[src/engines-experimental/kvdk_unsorted.cc, line 60 at r4](https://reviewable.io/reviews/pmem/pmemkv/1056#-MuLbDBF6D9CeQ3gqJRd:-MuLbDBF6D9CeQ3gqJRe:b-r3hrmt) ([raw file](https://github.com/pmem/pmemkv/blob/32c37c38f85e57796ff4f2982a040e2832c9aa00/src/engines-experimental/kvdk_unsorted.cc#L60)):*
> ```cpp
> {
> 	LOG("put key=" << std::string(key.data(), key.size())
> 		       << ", value.size=" << std::to_string(value.size()));
> ```

. (print `key` and `value`; not its size)
___
*[tests/CMakeLists.txt, line 2307 at r4](https://reviewable.io/reviews/pmem/pmemkv/1056#-MuLcQOA1-4_i1uYULp2:-MuLcQOB5obVdeDg64zu:b-enyvy3) ([raw file](https://github.com/pmem/pmemkv/blob/32c37c38f85e57796ff4f2982a040e2832c9aa00/tests/CMakeLists.txt#L2307)):*
> ```CMake
> endif(ENGINE_DRAM_VCMAP)
> ################################################################################
> ############################# KVDK_UNSORTED ####################################
> ```

you're missing quite a few tests here (and for sorted engine, as well).

at best, please copy-paste all available tests from another engine. If the test is failing, leave it commented out for a moment until you figure it out, and then you'll have to just uncomment them.
___
*[tests/engines/kvdk_unsorted/default.cmake, line 1 at r4](https://reviewable.io/reviews/pmem/pmemkv/1056#-MuLfXUH-P4yYqoSBtww:-MuLfXUH-P4yYqoSBtwx:b-xfred1) ([raw file](https://github.com/pmem/pmemkv/blob/32c37c38f85e57796ff4f2982a040e2832c9aa00/tests/engines/kvdk_unsorted/default.cmake#L1)):*
> ```CMake
> # SPDX-License-Identifier: BSD-3-Clause
> ```

I believe you don't have to create a separate cmake script for sorted and unsorted engine. You can just create one file `tests/engines/kvdk/default.cmake` and use it for both engines.

**Comment by lukaszstolarczuk** [comment]
I believe this PR is outdated. Please rebase and re-open if you feel like this PR should continue.

**Pull request closed without merging**
