### PR TITLE
cmake: fix TEST_DB_SIZE calculation for memkind based engines

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
- [x] two first commits to be dropped (this PR is based on #846)

run and checked on Ubuntu 18.04 on my fork: https://github.com/lukaszstolarczuk/pmemkv/runs/1530722935?check_suite_focus=true

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/857)

### CODE REVIEW

**Comment by lukaszstolarczuk** [comment]
re-based to stable-1.2 where it originally came up

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/857#-:-MOGrzxPEWrUfUF5kP6h:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved

**Review by KFilipek — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/857)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[tests/ctest_helpers.cmake, line 268 at r1](https://reviewable.io/reviews/pmem/pmemkv/857#-MOWT_oE-1dNttwGy8Oi:-MOWT_oE-1dNttwGy8Oj:b-v6ovjp) ([raw file](https://github.com/pmem/pmemkv/blob/7fd11321cb8fdccdb04cbe47528dc7ccf15cf3a3/tests/ctest_helpers.cmake#L268)):*
> ```CMake
> 
> 		# Limit size DB_SIZE with arbitrary threshold
> 		set(TEST_DB_SIZE_THRESHOLD 2147483646) # (almost 2GB; value for nproc=256 minus 2 bytes)
> ```

Can we do optional parametrization through cmake .. -Dsth?

**Review by KFilipek — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/857#-:-MOWUAKQEJW2a2HIPx_T:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[tests/ctest_helpers.cmake, line 268 at r1](https://reviewable.io/reviews/pmem/pmemkv/857#-MOWT_oE-1dNttwGy8Oi:-MOWU6-eDGOHeQbb6B1a:b-27zlxd) ([raw file](https://github.com/pmem/pmemkv/blob/7fd11321cb8fdccdb04cbe47528dc7ccf15cf3a3/tests/ctest_helpers.cmake#L268)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Can we do optional parametrization through cmake .. -Dsth?
</blockquote></details>

OFC, can be as separate PR, this LGTM

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/857)* status: all files reviewed, 1 unresolved discussion (waiting on @KFilipek)

___
*[tests/ctest_helpers.cmake, line 268 at r1](https://reviewable.io/reviews/pmem/pmemkv/857#-MOWT_oE-1dNttwGy8Oi:-MOYArid1VW7alsoL9bk:b7jcwb3) ([raw file](https://github.com/pmem/pmemkv/blob/7fd11321cb8fdccdb04cbe47528dc7ccf15cf3a3/tests/ctest_helpers.cmake#L268)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

OFC, can be as separate PR, this LGTM
</blockquote></details>

I'll take a look at this, but just a disclaimer - this calculation is required for about 2 tests right now, so I'm not sure if we want to expose a sep. CMake option (but maybe some cache string will do the job, I'll see..)

**Pull request merged**
