### PR TITLE
Extend contributing.md to encourage putting major changes to ChangeLog

### PR DESCRIPTION
**Pull request by igchor**
Also, create template for newest release.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/899)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/899)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @igchor)

___
*[ChangeLog, line 10 at r1](https://reviewable.io/reviews/pmem/pmemkv/899#-MSYBDoNDZQ202i0pUhp:-MSYBDoNDZQ202i0pUhq:b8tgcjp) ([raw file](https://github.com/pmem/pmemkv/blob/6afc5e7a1baa0647476a63ec673ad189f5439694/ChangeLog#L10)):*
> ```
> 	Major fixes:
> 	-
> ```

should we copy the same known issues (for vcmap)?
___
*[CONTRIBUTING.md, line 41 at r1](https://reviewable.io/reviews/pmem/pmemkv/899#-MSYAbtK7hca0QUdgjsx:-MSYAbtK7hca0QUdgjsy:bpgvxf2) ([raw file](https://github.com/pmem/pmemkv/blob/6afc5e7a1baa0647476a63ec673ad189f5439694/CONTRIBUTING.md#L41)):*
> ```Markdown
> We take outside code contributions to `PMEMKV` through GitHub pull requests.
> 
> If your add a new feature, implement new engine or fix critical bug please append
> ```

1. if you add
2. **a** new engine
3. fix **a** critical bug
___
*[CONTRIBUTING.md, line 42 at r1](https://reviewable.io/reviews/pmem/pmemkv/899#-MSYB0XO9KskZng81Xmy:-MSYB0XO9KskZng81Xmz:b-v0clqm) ([raw file](https://github.com/pmem/pmemkv/blob/6afc5e7a1baa0647476a63ec673ad189f5439694/CONTRIBUTING.md#L42)):*
> ```Markdown
> 
> If your add a new feature, implement new engine or fix critical bug please append
> appropriate entry to ChangeLog under newest release.
> ```

sidenote: this is going to be tricky, when we apply a major fix in a stable branch...

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/899)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[ChangeLog, line 10 at r1](https://reviewable.io/reviews/pmem/pmemkv/899#-MSYBDoNDZQ202i0pUhp:-MSaxPrK-hzmyF46KsX5:b-2yvw1o) ([raw file](https://github.com/pmem/pmemkv/blob/6afc5e7a1baa0647476a63ec673ad189f5439694/ChangeLog#L10)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

should we copy the same known issues (for vcmap)?
</blockquote></details>

They are both closed already
___
*[CONTRIBUTING.md, line 41 at r1](https://reviewable.io/reviews/pmem/pmemkv/899#-MSYAbtK7hca0QUdgjsx:-MSaxiw_040RwJkpO4Wd:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/6afc5e7a1baa0647476a63ec673ad189f5439694/CONTRIBUTING.md#L41)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

1. if you add
2. **a** new engine
3. fix **a** critical bug
</blockquote></details>

Done.
___
*[CONTRIBUTING.md, line 42 at r1](https://reviewable.io/reviews/pmem/pmemkv/899#-MSYB0XO9KskZng81Xmy:-MSaxlutA2B0YaHlNLbG:bm34dzj) ([raw file](https://github.com/pmem/pmemkv/blob/6afc5e7a1baa0647476a63ec673ad189f5439694/CONTRIBUTING.md#L42)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

sidenote: this is going to be tricky, when we apply a major fix in a stable branch...
</blockquote></details>

Yeah, should we skip adding content to ChageLog on stable branch fixes?

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/899)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)

___
*[ChangeLog, line 10 at r1](https://reviewable.io/reviews/pmem/pmemkv/899#-MSYBDoNDZQ202i0pUhp:-MSb8EDg0LjEnp1tCnQG:b-y6ndm6) ([raw file](https://github.com/pmem/pmemkv/blob/6afc5e7a1baa0647476a63ec673ad189f5439694/ChangeLog#L10)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

They are both closed already
</blockquote></details>

sry, I was thinking of the issue we talked about yesterday (https://github.com/pmem/pmemkv/issues/894). I't totally new, but still probably need to put it in the ChangeLog...
___
*[CONTRIBUTING.md, line 42 at r1](https://reviewable.io/reviews/pmem/pmemkv/899#-MSYB0XO9KskZng81Xmy:-MSb7cbtBR4kZ-BehxAv:bj7dau2) ([raw file](https://github.com/pmem/pmemkv/blob/6afc5e7a1baa0647476a63ec673ad189f5439694/CONTRIBUTING.md#L42)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Yeah, should we skip adding content to ChageLog on stable branch fixes?
</blockquote></details>

I guess that's reasonable.
But also - if we add some fix on stable branch we won't have there the template for new release... so we'll still have to put the issue manually into the ChangeLog (during merging back or during the releasing).

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/899)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[ChangeLog, line 10 at r1](https://reviewable.io/reviews/pmem/pmemkv/899#-MSYBDoNDZQ202i0pUhp:-MTu33sGEChnZ-Qsu-Ic:busawm7) ([raw file](https://github.com/pmem/pmemkv/blob/6afc5e7a1baa0647476a63ec673ad189f5439694/ChangeLog#L10)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

sry, I was thinking of the issue we talked about yesterday (https://github.com/pmem/pmemkv/issues/894). I't totally new, but still probably need to put it in the ChangeLog...
</blockquote></details>

Fixed ;)

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/899)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Pull request merged**
