### PR TITLE
CI: update valgrind to 3.17

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1039)

### CODE REVIEW

**Review by karczex — COMMENTED** [review]
Please describe in commit message why we need to update valgrind. 

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1039#-:-Mj3XxXA2zRt2JPVG5L3:bt8toya)* status: 0 of 1 files reviewed, all discussions resolved

**Review by lukaszstolarczuk — COMMENTED** [review]
@karczex, done.

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1039#-:-Mj43Qsr1I3S2uyaI6Mu:b-vkdfub)* status: 0 of 1 files reviewed, all discussions resolved

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1039#-:-Mk2O-rVBgeHruKkret4:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved

**Review by karczex — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1039#-:-MkBSD55EJ_fpq9ilVvj:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved

**Pull request merged**
