### PR TITLE
remove wrapper structures for pmem::obj::string

### PR DESCRIPTION
**Pull request by KFilipek**
This PR have following:

- docker_images: update libpmemobj++ installation script
- csmap: remove unnecessary key structure

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/822)

### CODE REVIEW

**Review by igchor — COMMENTED** [review]
Could you also do the same for stree?

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/822#-:-MJXmeCVBqJTwz1vFdsk:bhbybbj)* status: 0 of 2 files reviewed, all discussions resolved

**Review by igchor — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/822)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by szyrom — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/822#-:-MJ_v55f4cJEjzmB7Ynl:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/822)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by igchor — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/822#-:-MJbLsLACVeD_x4_67V5:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
