### PR TITLE
Add stats API for pmemkv

### PR DESCRIPTION
**Pull request by szyrom**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/751)

### CODE REVIEW

**Review by igchor — COMMENTED** [review]
> Reviewed 11 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/751)* status: 11 of 12 files reviewed, 8 unresolved discussions (waiting on @szyrom)

___
*[doc/libpmemkv.7.md, line 77 at r1](https://reviewable.io/reviews/pmem/pmemkv/751#-MF50J6h-oQvccOs5ix6:-MF50J6i2aCeWCFMaKsx:bqjpw8w) ([raw file](https://github.com/pmem/pmemkv/blob/76630656a6577586f6cfb086f4a1f9f497c1feaa/doc/libpmemkv.7.md#L77)):*
> ```Markdown
> * **oid** -- Pointer to oid (for details see **libpmemobj**(7)) which points to engine data. If oid is null, engine will allocate new data, otherwise it will use existing one.
> 	+ type: object
> * **pmemobj_stats_enabled** -- Enables or disables runtime collection of statistics. There are two types of statistics: persistent and transient ones. Persistent statistics survive pool restarts, whereas transient ones don’t. Statistics are not recalculated after enabling; any operations that occur between disabling and re-enabling will not be reflected in subsequent values.
> ```

Hm, do we want to have per-backend config options? Maybe we should have just `enable_stats` which would work for all engines (which support statistics). I think that the possibility to set transient and persistent statistics separately is quite generic.  
___
*[doc/libpmemkv.7.md, line 78 at r1](https://reviewable.io/reviews/pmem/pmemkv/751#-MF517HiC9JAMGbeCxTa:-MF517HiC9JAMGbeCxTb:bn2q5z9) ([raw file](https://github.com/pmem/pmemkv/blob/76630656a6577586f6cfb086f4a1f9f497c1feaa/doc/libpmemkv.7.md#L78)):*
> ```Markdown
> 	+ type: object
> * **pmemobj_stats_enabled** -- Enables or disables runtime collection of statistics. There are two types of statistics: persistent and transient ones. Persistent statistics survive pool restarts, whereas transient ones don’t. Statistics are not recalculated after enabling; any operations that occur between disabling and re-enabling will not be reflected in subsequent values.
> If pmemobj_stats_enabled is set to 0, only transcient statistics are enabled. If set to 1, both transcient and persistent statistics are enabled. If set to 2, only persistent statistics are enabled. If set to 3, all statistics are disabled. Only transient statistics are enabled by default. Enabling persistent statistics may have non-trivial performance impact.
> ```

Myabe we should also expose those numbers as an enum?
___
*[doc/libpmemkv.7.md, line 79 at r1](https://reviewable.io/reviews/pmem/pmemkv/751#-MF5-PLHDqS7S_xxHCqc:-MF5-PLI0FrCSYb7D_BL:b2mukbr) ([raw file](https://github.com/pmem/pmemkv/blob/76630656a6577586f6cfb086f4a1f9f497c1feaa/doc/libpmemkv.7.md#L79)):*
> ```Markdown
> * **pmemobj_stats_enabled** -- Enables or disables runtime collection of statistics. There are two types of statistics: persistent and transient ones. Persistent statistics survive pool restarts, whereas transient ones don’t. Statistics are not recalculated after enabling; any operations that occur between disabling and re-enabling will not be reflected in subsequent values.
> If pmemobj_stats_enabled is set to 0, only transcient statistics are enabled. If set to 1, both transcient and persistent statistics are enabled. If set to 2, only persistent statistics are enabled. If set to 3, all statistics are disabled. Only transient statistics are enabled by default. Enabling persistent statistics may have non-trivial performance impact.
> Currently available statistics are: stats.heap.curr_allocated, stats.heap.run_allocated, stats.heap.run_active (for details see <https://pmem.io/pmdk/manpages/linux/master/libpmemobj/pmemobj_ctl_get.3>). These statistics are being gathered per persistent memory pool, not by en engine.
> ```

In the last sentence, are you writing about a case where engine is created inside already existing pool (via OID)?
___
*[src/libpmemkv.h, line 39 at r1](https://reviewable.io/reviews/pmem/pmemkv/751#-MF524yf3A-klYVeZpBl:-MF524yf3A-klYVeZpBm:b-y38ule) ([raw file](https://github.com/pmem/pmemkv/blob/76630656a6577586f6cfb086f4a1f9f497c1feaa/src/libpmemkv.h#L39)):*
> ```objc
> 		uint64_t heap_run_allocated;
> 		uint64_t heap_run_active;
> 	};
> ```

maybe add some reserved space in this structure in case we would need that for some other backends:

```
union pmemkv_statistics {
 struct {
};
uint8_t reserved[64];
}:
```
___
*[src/libpmemkv.hpp, line 153 at r1](https://reviewable.io/reviews/pmem/pmemkv/751#-MF5-ygH8WNnHAM_eSnr:-MF5-ygH8WNnHAM_eSns:bd2571x) ([raw file](https://github.com/pmem/pmemkv/blob/76630656a6577586f6cfb086f4a1f9f497c1feaa/src/libpmemkv.hpp#L153)):*
> ```cpp
> 					       "TRANSACTION_SCOPE_ERROR",
> 					       "DEFRAG_ERROR",
> 					       "COMPARATOR_MISMATCH"};
> ```

Please also extend this array
___
*[src/pmemobj_engine.h, line 112 at r1](https://reviewable.io/reviews/pmem/pmemkv/751#-MF51qmPBiho7_OBjPo4:-MF51qmPBiho7_OBjPo5:bux521v) ([raw file](https://github.com/pmem/pmemkv/blob/76630656a6577586f6cfb086f4a1f9f497c1feaa/src/pmemobj_engine.h#L112)):*
> ```objc
> 		ret = pmemobj_ctl_get(pmpool.handle(), "stats.enabled", &stat->stats_enabled);
> 		if (ret != 0) {
> 			out_err_stream("stats") << "Failed to query \"stats.enabled\".";
> ```

you can use ERR() macro
___
*[tests/CMakeLists.txt, line 150 at r1](https://reviewable.io/reviews/pmem/pmemkv/751#-MF5ASUH2VUe2s4Sc-It:-MF5ASUIESKk9SdTkcK0:bw9c7h) ([raw file](https://github.com/pmem/pmemkv/blob/76630656a6577586f6cfb086f4a1f9f497c1feaa/tests/CMakeLists.txt#L150)):*
> ```CMake
> build_test_ext(NAME pmemobj_put_get_std_map_oid SRC_FILES engine_scenarios/pmemobj/put_get_std_map_oid.cc LIBS json libpmemobj_cpp)
> build_test_ext(NAME pmemobj_stats_set_get SRC_FILES engine_scenarios/pmemobj/stats_set_get.cc LIBS json)
> ```

I guess there should also be some test of the pmemkv_stat function itself ;d
___
*[tests/engine_scenarios/pmemobj/stats_set_get.cc, line 79 at r1](https://reviewable.io/reviews/pmem/pmemkv/751#-MF5AZWmBAOzPE_qSh--:-MF5AZWmBAOzPE_qSh-0:b-84lf16) ([raw file](https://github.com/pmem/pmemkv/blob/76630656a6577586f6cfb086f4a1f9f497c1feaa/tests/engine_scenarios/pmemobj/stats_set_get.cc#L79)):*
> ```cpp
> {
> 	pmem::kv::db kv;
> 	auto s = config.put_int64("pmemobj_stats_enabled", 3);
> ```

After merging karczex PR we could add config.put_stats_enabled()

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 3 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/751)* status: 11 of 12 files reviewed, 15 unresolved discussions (waiting on @igchor and @szyrom)

___
*[doc/libpmemkv.3.md.in, line 191 at r1](https://reviewable.io/reviews/pmem/pmemkv/751#-MFBxItlCeUZKUlJe_Jd:-MFBxItlCeUZKUlJe_Je:b-ljs5ix) ([raw file](https://github.com/pmem/pmemkv/blob/76630656a6577586f6cfb086f4a1f9f497c1feaa/doc/libpmemkv.3.md.in#L191)):*
> ```
> `int pmemkv_stats(pmemkv_db *db, pmemkv_statistics *statistics);`
> 
> :	Retrieves engine statistics and saves them in the 'statistics' structure.
> ```

pls change apostrophes in this line into `
___
*[doc/libpmemkv.3.md.in, line 197 at r1](https://reviewable.io/reviews/pmem/pmemkv/751#-MFBx6PU9-rPeL0AOw6U:-MFBx6PU9-rPeL0AOw6V:b-wr7230) ([raw file](https://github.com/pmem/pmemkv/blob/76630656a6577586f6cfb086f4a1f9f497c1feaa/doc/libpmemkv.3.md.in#L197)):*
> ```
> 		* heap_run_allocated,
> 		* heap_run_active.
> 	For more details about above parameters meaning, see https://pmem.io/pmdk/manpages/linux/master/libpmemobj/pmemobj_ctl_get.3
> ```

perhaps just `**pmemobj_ctl_get**(3)` like we have for other refs to manpages
___
*[doc/libpmemkv.7.md, line 79 at r1](https://reviewable.io/reviews/pmem/pmemkv/751#-MFBxau_-VCxy7IPSrNU:-MFBxau_-VCxy7IPSrNV:b-k57wwp) ([raw file](https://github.com/pmem/pmemkv/blob/76630656a6577586f6cfb086f4a1f9f497c1feaa/doc/libpmemkv.7.md#L79)):*
> ```Markdown
> * **pmemobj_stats_enabled** -- Enables or disables runtime collection of statistics. There are two types of statistics: persistent and transient ones. Persistent statistics survive pool restarts, whereas transient ones don’t. Statistics are not recalculated after enabling; any operations that occur between disabling and re-enabling will not be reflected in subsequent values.
> If pmemobj_stats_enabled is set to 0, only transcient statistics are enabled. If set to 1, both transcient and persistent statistics are enabled. If set to 2, only persistent statistics are enabled. If set to 3, all statistics are disabled. Only transient statistics are enabled by default. Enabling persistent statistics may have non-trivial performance impact.
> Currently available statistics are: stats.heap.curr_allocated, stats.heap.run_allocated, stats.heap.run_active (for details see <https://pmem.io/pmdk/manpages/linux/master/libpmemobj/pmemobj_ctl_get.3>). These statistics are being gathered per persistent memory pool, not by en engine.
> ```

. (ref to manpage)
___
*[doc/libpmemkv.7.md, line 79 at r1](https://reviewable.io/reviews/pmem/pmemkv/751#-MFBxgdo9FexgF7vgEOI:-MFBxgdo9FexgF7vgEOJ:b48i3cg) ([raw file](https://github.com/pmem/pmemkv/blob/76630656a6577586f6cfb086f4a1f9f497c1feaa/doc/libpmemkv.7.md#L79)):*
> ```Markdown
> * **pmemobj_stats_enabled** -- Enables or disables runtime collection of statistics. There are two types of statistics: persistent and transient ones. Persistent statistics survive pool restarts, whereas transient ones don’t. Statistics are not recalculated after enabling; any operations that occur between disabling and re-enabling will not be reflected in subsequent values.
> If pmemobj_stats_enabled is set to 0, only transcient statistics are enabled. If set to 1, both transcient and persistent statistics are enabled. If set to 2, only persistent statistics are enabled. If set to 3, all statistics are disabled. Only transient statistics are enabled by default. Enabling persistent statistics may have non-trivial performance impact.
> Currently available statistics are: stats.heap.curr_allocated, stats.heap.run_allocated, stats.heap.run_active (for details see <https://pmem.io/pmdk/manpages/linux/master/libpmemobj/pmemobj_ctl_get.3>). These statistics are being gathered per persistent memory pool, not by en engine.
> ```

**an** engine
___
*[src/libpmemkv.hpp, line 162 at r1](https://reviewable.io/reviews/pmem/pmemkv/751#-MFByU8wBNFlB-MLTez1:-MFByU8wBNFlB-MLTez2:b-rkz3zp) ([raw file](https://github.com/pmem/pmemkv/blob/76630656a6577586f6cfb086f4a1f9f497c1feaa/src/libpmemkv.hpp#L162)):*
> ```cpp
> 
> /*! \union statistics
> 	\brief A union for statistics retrieval.
> ```

`retrieval` -> `data` ?
___
*[src/libpmemkv.hpp, line 164 at r1](https://reviewable.io/reviews/pmem/pmemkv/751#-MFByXG-Aopuk2wdxusN:-MFByXG-Aopuk2wdxusO:bpzxyd1) ([raw file](https://github.com/pmem/pmemkv/blob/76630656a6577586f6cfb086f4a1f9f497c1feaa/src/libpmemkv.hpp#L164)):*
> ```cpp
> 	\brief A union for statistics retrieval.
> 
> 	See [libpmemkv(3)](https://pmem.io/pmemkv/master/manpages/libpmemkv.3.html) for
> ```

are these links working in doxygen format?
___
*[tests/CMakeLists.txt, line 150 at r1](https://reviewable.io/reviews/pmem/pmemkv/751#-MF5ASUH2VUe2s4Sc-It:-MFC-2Ix2IksBdoIrxs2:bf02g36) ([raw file](https://github.com/pmem/pmemkv/blob/76630656a6577586f6cfb086f4a1f9f497c1feaa/tests/CMakeLists.txt#L150)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I guess there should also be some test of the pmemkv_stat function itself ;d
</blockquote></details>

at least extend `tests/c_api/null_db_config.c` and perhaps add `ASSERT_STATUS(kv.stats(), status::NOT_SUPPORTED);` in `tests/engines/blackhole/blackhole_test`
___
*[tests/engine_scenarios/pmemobj/error_handling_stats.cc, line 18 at r1](https://reviewable.io/reviews/pmem/pmemkv/751#-MFBztte9_P9jCpnZOjM:-MFBztte9_P9jCpnZOjN:b-q0qqz7) ([raw file](https://github.com/pmem/pmemkv/blob/76630656a6577586f6cfb086f4a1f9f497c1feaa/tests/engine_scenarios/pmemobj/error_handling_stats.cc#L18)):*
> ```cpp
> 
> 	/* wrong pmemobj_stats_enabled parameter */
> 	UT_ASSERTeq(pmem::kv::status::INVALID_ARGUMENT, s);
> ```

please use new ASSERT_STATUS macro
___
*[tests/engine_scenarios/pmemobj/stats_set_get.cc, line 79 at r1](https://reviewable.io/reviews/pmem/pmemkv/751#-MF5AZWmBAOzPE_qSh--:-MFBzCE5DwPx15_8ovDN:b32v57) ([raw file](https://github.com/pmem/pmemkv/blob/76630656a6577586f6cfb086f4a1f9f497c1feaa/tests/engine_scenarios/pmemobj/stats_set_get.cc#L79)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

After merging karczex PR we could add config.put_stats_enabled()
</blockquote></details>

+1

**Review by pbalcer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/751)* status: 11 of 12 files reviewed, 17 unresolved discussions (waiting on @igchor, @karczex, and @szyrom)

___
*[doc/libpmemkv.3.md.in, line 197 at r1](https://reviewable.io/reviews/pmem/pmemkv/751#-MFGn1UFAEMz114lPMut:-MFUQAdMAb0fuiJ5I8Hr:b-knwbvl) ([raw file](https://github.com/pmem/pmemkv/blob/76630656a6577586f6cfb086f4a1f9f497c1feaa/doc/libpmemkv.3.md.in#L197)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

> ```
> For more details about above parameters meaning, see https://pmem.io/pmdk/manpages/linux/master/libpmemobj/pmemobj_ctl_get.3
> ```
As pmemkv is meant to be simple abstraction layer, pointing to documentation of lower layer, without even brief description may be little confusing. 
</blockquote></details>

More than that, any time you introduce an interface like this it makes the abstraction "leaky"... My preference would be to generalize the stats.

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/751)* status: 11 of 12 files reviewed, 17 unresolved discussions (waiting on @igchor, @karczex, and @szyrom)

___
*[src/libpmemkv.h, line 39 at r1](https://reviewable.io/reviews/pmem/pmemkv/751#-MF524yf3A-klYVeZpBl:-MFU_DazEv4CcRyP35jo:bf9qe25) ([raw file](https://github.com/pmem/pmemkv/blob/76630656a6577586f6cfb086f4a1f9f497c1feaa/src/libpmemkv.h#L39)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

@igchor Why we couldn't extend it later if needed?
</blockquote></details>

Hm, I though it will be problematic for compatibility but I guess you're right. If, in future we extend the structure (by adding something at the end or creating new union type) then the old library version should still work.

**Pull request closed without merging**
