### PR TITLE
doc: update Doxygen readme and comments

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
extend inaccurate info and fix missing docs and links.

- [x] add more snippets
- [x] generate and check correctness

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/884)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/884)* status: 0 of 2 files reviewed, 2 unresolved discussions

___
*[src/libpmemkv.hpp, line 66 at r1](https://reviewable.io/reviews/pmem/pmemkv/884#-MR6-7Cr8LwU_9xHXx8o:-MR6-7Cr8LwU_9xHXx8p:br1zltj) ([raw file](https://github.com/pmem/pmemkv/blob/0788482cef97caa896b91ee043386897e70af9a8/src/libpmemkv.hpp#L66)):*
> ```cpp
>  * Function type ...
>  */
> typedef int comparator_function(string_view key1, string_view key2);
> ```

are we using this function somewhere? Am I missing something...?
___
*[src/libpmemkv.hpp, line 401 at r1](https://reviewable.io/reviews/pmem/pmemkv/884#-MR6-TMp5AvuH0WLf-b1:-MR6-TMp5AvuH0WLf-b2:bsp0sdt) ([raw file](https://github.com/pmem/pmemkv/blob/0788482cef97caa896b91ee043386897e70af9a8/src/libpmemkv.hpp#L401)):*
> ```cpp
> 
> /**
>  * ...
> ```

should we have a description for these operators? I found them in pmem::kv namespace ( https://pmem.io/pmemkv/master/doxygen/namespacepmem_1_1kv.html )

**Review by igchor — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/884)* status: all files reviewed, 7 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[examples/pmemkv_open_cpp/pmemkv_open.cpp, line 27 at r2](https://reviewable.io/reviews/pmem/pmemkv/884#-MRU_z6X7IPEMDC9Mahe:-MRU_z6Y9c4C7QRRuOcw:bice0zc) ([raw file](https://github.com/pmem/pmemkv/blob/413673f1ed31c715b00b6b9fe3b005599bb00003/examples/pmemkv_open_cpp/pmemkv_open.cpp#L27)):*
> ```cpp
>  * This example expects a path to already created pool
>  * (in pmemkv context it usually equals to a database).
>  *
> ```

Hm, I think this sentence does not clarify much. Maybe we could just write "... path to already created database pool" and then add some link to our (not yet existent ? ;d) documentation about poolsets in pmemkv?
___
*[src/libpmemkv.hpp, line 66 at r1](https://reviewable.io/reviews/pmem/pmemkv/884#-MR6-7Cr8LwU_9xHXx8o:-MRUb9Ch4QWR09ILalz8:b-jsnq4w) ([raw file](https://github.com/pmem/pmemkv/blob/0788482cef97caa896b91ee043386897e70af9a8/src/libpmemkv.hpp#L66)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

are we using this function somewhere? Am I missing something...?
</blockquote></details>

Hm, you might be write, I think it was added by mistake (following analogy for callbacks).
___
*[src/libpmemkv.hpp, line 401 at r1](https://reviewable.io/reviews/pmem/pmemkv/884#-MR6-TMp5AvuH0WLf-b1:-MRUbag89pIo_LcmoThd:bnrxlvw) ([raw file](https://github.com/pmem/pmemkv/blob/0788482cef97caa896b91ee043386897e70af9a8/src/libpmemkv.hpp#L401)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

should we have a description for these operators? I found them in pmem::kv namespace ( https://pmem.io/pmemkv/master/doxygen/namespacepmem_1_1kv.html )
</blockquote></details>

I would add descption for operator<< but I don';t think it's necessary for comparisons.
___
*[src/libpmemkv.hpp, line 64 at r2](https://reviewable.io/reviews/pmem/pmemkv/884#-MRUb0-F2A0NFEUz6sHP:-MRUb0-GBYHDGiSjret3:b-cuc9yu) ([raw file](https://github.com/pmem/pmemkv/blob/413673f1ed31c715b00b6b9fe3b005599bb00003/src/libpmemkv.hpp#L64)):*
> ```cpp
> typedef void get_v_function(string_view value);
> /**
>  * Function type ...
> ```

why `...`?
___
*[src/libpmemkv.hpp, line 80 at r2](https://reviewable.io/reviews/pmem/pmemkv/884#-MRUbHzV4ybLTUEqzAaR:-MRUbHzV4ybLTUEqzAaS:b-mvjvo3) ([raw file](https://github.com/pmem/pmemkv/blob/413673f1ed31c715b00b6b9fe3b005599bb00003/src/libpmemkv.hpp#L80)):*
> ```cpp
> 	\brief Status returned by most of pmemkv functions.
> 
> 	Each function in pmem::kv::db class (except for db::close() and
> ```

I would remove this 'except' part. Now it would also contain new_iterator, new_tx and perhaps more.
___
*[src/libpmemkv.hpp, line 88 at r2](https://reviewable.io/reviews/pmem/pmemkv/884#-MRUbS38EnVmqpjSVUaE:-MRUbS38EnVmqpjSVUaF:b-xqoup7) ([raw file](https://github.com/pmem/pmemkv/blob/413673f1ed31c715b00b6b9fe3b005599bb00003/src/libpmemkv.hpp#L88)):*
> ```cpp
> 	possible that in future versions it will return status::INVALID_ARGUMENT.
> 	Recommended way to check for an error is to compare status with status::OK
> 	(see pmem::kv::db basic example).
> ```

Add a link to this example?
___
*[src/libpmemkv.hpp, line 122 at r2](https://reviewable.io/reviews/pmem/pmemkv/884#-MRUbV_O5XphGLYJ5Lz5:-MRUbV_O5XphGLYJ5Lz6:b3kre) ([raw file](https://github.com/pmem/pmemkv/blob/413673f1ed31c715b00b6b9fe3b005599bb00003/src/libpmemkv.hpp#L122)):*
> ```cpp
> 
> /**
>  * ...
> ```

?

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/884)* status: all files reviewed, 6 unresolved discussions (waiting on @igchor)

___
*[examples/pmemkv_open_cpp/pmemkv_open.cpp, line 27 at r2](https://reviewable.io/reviews/pmem/pmemkv/884#-MRU_z6X7IPEMDC9Mahe:-MRUoLvp0hRe6sAEbwL0:b-o784ek) ([raw file](https://github.com/pmem/pmemkv/blob/413673f1ed31c715b00b6b9fe3b005599bb00003/examples/pmemkv_open_cpp/pmemkv_open.cpp#L27)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Hm, I think this sentence does not clarify much. Maybe we could just write "... path to already created database pool" and then add some link to our (not yet existent ? ;d) documentation about poolsets in pmemkv?
</blockquote></details>

hmm.. I think "database pool" might be good enough for now. I'll file an issue to update docs about pool(sets) in pmemkv
___
*[src/libpmemkv.hpp, line 66 at r1](https://reviewable.io/reviews/pmem/pmemkv/884#-MR6-7Cr8LwU_9xHXx8o:-MRUpRCR62cf86-Q4Nlh:b-ky3n5x) ([raw file](https://github.com/pmem/pmemkv/blob/0788482cef97caa896b91ee043386897e70af9a8/src/libpmemkv.hpp#L66)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Hm, you might be write, I think it was added by mistake (following analogy for callbacks).
</blockquote></details>

I'll remove it then.
___
*[src/libpmemkv.hpp, line 401 at r1](https://reviewable.io/reviews/pmem/pmemkv/884#-MR6-TMp5AvuH0WLf-b1:-MRUqH_2ARQ5j3nXpvVH:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/0788482cef97caa896b91ee043386897e70af9a8/src/libpmemkv.hpp#L401)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I would add descption for operator<< but I don';t think it's necessary for comparisons.
</blockquote></details>

Done.
___
*[src/libpmemkv.hpp, line 64 at r2](https://reviewable.io/reviews/pmem/pmemkv/884#-MRUb0-F2A0NFEUz6sHP:-MRUpTbVCdaa2dBvhwaB:b1ogdk2) ([raw file](https://github.com/pmem/pmemkv/blob/413673f1ed31c715b00b6b9fe3b005599bb00003/src/libpmemkv.hpp#L64)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

why `...`?
</blockquote></details>

to remind myself to put a content here in case this typedef is staying with us ;)
___
*[src/libpmemkv.hpp, line 80 at r2](https://reviewable.io/reviews/pmem/pmemkv/884#-MRUbHzV4ybLTUEqzAaR:-MRUq6QMB9qZwqaozsTG:bu64ac7) ([raw file](https://github.com/pmem/pmemkv/blob/413673f1ed31c715b00b6b9fe3b005599bb00003/src/libpmemkv.hpp#L80)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I would remove this 'except' part. Now it would also contain new_iterator, new_tx and perhaps more.
</blockquote></details>

I simplified it.
___
*[src/libpmemkv.hpp, line 88 at r2](https://reviewable.io/reviews/pmem/pmemkv/884#-MRUbS38EnVmqpjSVUaE:-MRUotapCHLDLEOOBd4F:b-jpe6yz) ([raw file](https://github.com/pmem/pmemkv/blob/413673f1ed31c715b00b6b9fe3b005599bb00003/src/libpmemkv.hpp#L88)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Add a link to this example?
</blockquote></details>

hmm doxygen will make a link to db class and it will be included as the snippet... if you think we should add link to the example source then it'd be probably better just to include a simple piece of a code here instead...
___
*[src/libpmemkv.hpp, line 122 at r2](https://reviewable.io/reviews/pmem/pmemkv/884#-MRUbV_O5XphGLYJ5Lz5:-MRUqI4O9PkLCYLJ__wD:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/413673f1ed31c715b00b6b9fe3b005599bb00003/src/libpmemkv.hpp#L122)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.

**Review by KFilipek — COMMENTED** [review]
> Reviewed 2 of 14 files at r2, 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/884)* status: all files reviewed, 6 unresolved discussions (waiting on @igchor)

**Review by KFilipek — COMMENTED** [review]
> Reviewed 8 of 14 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/884)* status: all files reviewed, 8 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[examples/README, line 34 at r3](https://reviewable.io/reviews/pmem/pmemkv/884#-MS84THU56kqIkPyqVJK:-MS84THU56kqIkPyqVJL:b-k8e1hy) ([raw file](https://github.com/pmem/pmemkv/blob/227fc81f2b8319a86581ebd34d6de2b86e7ca8a0/examples/README#L34)):*
> ```
> 		- pthread available in the OS
> 
> pmemkv_open_cpp/pmemkv_open_cpp -- contains example usage
> ```

contains example -> example of
___
*[examples/README, line 37 at r3](https://reviewable.io/reviews/pmem/pmemkv/884#-MS84Fzm0aUvL03k-E6Y:-MS84Fzn8yclETRfPUvZ:b-k8e1hy) ([raw file](https://github.com/pmem/pmemkv/blob/227fc81f2b8319a86581ebd34d6de2b86e7ca8a0/examples/README#L37)):*
> ```
> 		of pmemkv for already existing pools (and poolsets)
> 
> pmemkv_pmemobj_cpp/pmemkv_pmemobj_basic.cpp -- contains example usage
> ```

contains example -> example of

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/884)* status: 4 of 17 files reviewed, 8 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[examples/README, line 34 at r3](https://reviewable.io/reviews/pmem/pmemkv/884#-MS84THU56kqIkPyqVJK:-MS8ZBHx2Kqg2mpVMP5q:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/227fc81f2b8319a86581ebd34d6de2b86e7ca8a0/examples/README#L34)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

contains example -> example of
</blockquote></details>

Done.
___
*[examples/README, line 37 at r3](https://reviewable.io/reviews/pmem/pmemkv/884#-MS84Fzm0aUvL03k-E6Y:-MS8ZBaJ2rzNm2B3KPqP:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/227fc81f2b8319a86581ebd34d6de2b86e7ca8a0/examples/README#L37)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

contains example -> example of
</blockquote></details>

Done.

**Review by KFilipek — COMMENTED** [review]
:lgtm:

> Reviewed 13 of 13 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/884#-:-MSDPRnvCwJLuUXDcBl3:bnfp4nl)* status: all files reviewed, 6 unresolved discussions (waiting on @igchor)

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/884#-:-MSgCrFm-cun5fGZgOKG:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

**Pull request merged**
