### PR TITLE
Doc build refactor

### PR DESCRIPTION
**Pull request by karczex**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/760)

### CODE REVIEW

**Comment by karczex** [comment]
https://github.com/karczex/pmemkv/actions/runs/226692897
https://github.com/karczex/pmemkv/pull/4

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/760)* status: 0 of 4 files reviewed, 9 unresolved discussions (waiting on @karczex)

___
*[.github/workflows/gha.yml, line 58 at r1](https://reviewable.io/reviews/pmem/pmemkv/760#-MFjZ7HO0V2-0qDv9Hmm:-MFjZ7HO0V2-0qDv9Hmn:b-biu49t) ([raw file](https://github.com/pmem/pmemkv/blob/26d0659bb0bf7adf33be140d83cd1baf0a8da107/.github/workflows/gha.yml#L58)):*
> ```YAML
>       env:
>         DOC_UPDATE_GITHUB_TOKEN: ${{ secrets.DOC_UPDATE_GITHUB_TOKEN }}
>         DOC_UPDATE_BOT_NAME: ${{ secrets.DOC_UPDATE_BOT_NAME }}
> ```

Does it work fine (have you tested it) when secrets.DOC_UPDATE_BOT_NAME is empty?
___
*[.github/workflows/gha.yml, line 59 at r1](https://reviewable.io/reviews/pmem/pmemkv/760#-MFjaQdTEyWidPIbY8iQ:-MFjaQdTEyWidPIbY8iR:b-owb4wv) ([raw file](https://github.com/pmem/pmemkv/blob/26d0659bb0bf7adf33be140d83cd1baf0a8da107/.github/workflows/gha.yml#L59)):*
> ```YAML
>         DOC_UPDATE_GITHUB_TOKEN: ${{ secrets.DOC_UPDATE_GITHUB_TOKEN }}
>         DOC_UPDATE_BOT_NAME: ${{ secrets.DOC_UPDATE_BOT_NAME }}
>         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
> ```

Hm, so how did it worked for travis before this patch: https://github.com/pmem/pmemkv/pull/754/files?
It seems there was just one variable (GITHUB_TOKEN)?
___
*[.github/workflows/gha.yml, line 60 at r1](https://reviewable.io/reviews/pmem/pmemkv/760#-MFj_JFMEF1espHTKaqd:-MFj_JFMEF1espHTKaqe:bj8ss96) ([raw file](https://github.com/pmem/pmemkv/blob/26d0659bb0bf7adf33be140d83cd1baf0a8da107/.github/workflows/gha.yml#L60)):*
> ```YAML
>         DOC_UPDATE_BOT_NAME: ${{ secrets.DOC_UPDATE_BOT_NAME }}
>         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
>         GITHUB_USER_NAME: ${{ github.actor }}
> ```

Is this pmem if run on PR?
___
*[.github/workflows/gha.yml, line 68 at r1](https://reviewable.io/reviews/pmem/pmemkv/760#-MFjZOP65M6HAZgTDPv5:-MFjZOP65M6HAZgTDPv6:b-x1gypp) ([raw file](https://github.com/pmem/pmemkv/blob/26d0659bb0bf7adf33be140d83cd1baf0a8da107/.github/workflows/gha.yml#L68)):*
> ```YAML
>                   refs/heads/stable-1.1
>                   refs/heads/stable-1.2
>                   ' , github.ref)
> ```

github.ref? what is it for?
___
*[utils/docker/build.sh, line 99 at r1](https://reviewable.io/reviews/pmem/pmemkv/760#-MFjZd0rAiqVm3vhrg1E:-MFjZd0rAiqVm3vhrg1F:b-rpyyvg) ([raw file](https://github.com/pmem/pmemkv/blob/35b921dc46f63d983b6614d1997ca1120e96f516/utils/docker/build.sh#L99)):*
> ```Shell
> 
> # Only run doc update on $GITHUB_REPO master or stable branch
> if [[ -z "${CI_BRANCH}" || -z "${TARGET_BRANCHES[${CI_BRANCH}]}" || "$CI_EVENT_TYPE" == "pull_request" || "$CI_REPO_SLUG" != "${GITHUB_REPO}" ]]; then
> ```

Without this, how can you disable running doc update on your fork? If I understand correctly, it will just fail for now (if you don't setup secrets)?
___
*[utils/docker/run-doc-update.sh, line 15 at r1](https://reviewable.io/reviews/pmem/pmemkv/760#-MFj_5pH-9t9c4Nat8lM:-MFj_5pH-9t9c4Nat8lN:b-ac81gq) ([raw file](https://github.com/pmem/pmemkv/blob/26d0659bb0bf7adf33be140d83cd1baf0a8da107/utils/docker/run-doc-update.sh#L15)):*
> ```Shell
> source `dirname $0`/valid-branches.sh
> 
> BOT_NAME=${DOC_UPDATE_BOT_NAME=="pmem-bot"}
> ```

shouldn't this be "${DOCK_UPDATE_BOT_NAME:-"pmem"}" ? (`:-` instead of  `==`)?
___
*[utils/docker/run-doc-update.sh, line 16 at r1](https://reviewable.io/reviews/pmem/pmemkv/760#-MFj_0FY3Xh82KHg7BF0:-MFj_0FZA1mnx50INv7V:b32ucp) ([raw file](https://github.com/pmem/pmemkv/blob/26d0659bb0bf7adf33be140d83cd1baf0a8da107/utils/docker/run-doc-update.sh#L16)):*
> ```Shell
> 
> BOT_NAME=${DOC_UPDATE_BOT_NAME=="pmem-bot"}
> GITHUB_UPSTREAM_USER_NAME="${GITHUB_UPSTREAM_USER_NAME:="pmem"}"
> ```


.
___
*[utils/docker/run-doc-update.sh, line 16 at r1](https://reviewable.io/reviews/pmem/pmemkv/760#-MFj_g-t6ramWm0H3Ch7:-MFj_g-t6ramWm0H3Ch8:bfkbg4m) ([raw file](https://github.com/pmem/pmemkv/blob/26d0659bb0bf7adf33be140d83cd1baf0a8da107/utils/docker/run-doc-update.sh#L16)):*
> ```Shell
> 
> BOT_NAME=${DOC_UPDATE_BOT_NAME=="pmem-bot"}
> GITHUB_UPSTREAM_USER_NAME="${GITHUB_UPSTREAM_USER_NAME:="pmem"}"
> ```

Is there a possibility that this variable is empty? If you set it to github.actor then it should always be set?
___
*[utils/docker/run-doc-update.sh, line 52 at r1](https://reviewable.io/reviews/pmem/pmemkv/760#-MFj_XdD9yiRCIFr3kmZ:-MFj_XdD9yiRCIFr3km_:b-3fkfe8) ([raw file](https://github.com/pmem/pmemkv/blob/26d0659bb0bf7adf33be140d83cd1baf0a8da107/utils/docker/run-doc-update.sh#L52)):*
> ```Shell
> make -j$(nproc) doc
> cp ${REPO_DIR}/build/man/tmp/*.md ${REPO_DIR}/doc/
> cp -r ${REPO_DIR}/doc $ARTEFACTS_DIR/
> ```

why not ${ARTIFACTS_DIR}?

**Review by igchor — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/760)* status: all files reviewed, 9 unresolved discussions (waiting on @karczex)

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/760)* status: 3 of 4 files reviewed, 9 unresolved discussions (waiting on @igchor and @karczex)

___
*[.github/workflows/gha.yml, line 59 at r1](https://reviewable.io/reviews/pmem/pmemkv/760#-MFjaQdTEyWidPIbY8iQ:-MFjf6m_EzGu-zNzM1CW:b-oueu61) ([raw file](https://github.com/pmem/pmemkv/blob/26d0659bb0bf7adf33be140d83cd1baf0a8da107/.github/workflows/gha.yml#L59)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Hm, so how did it worked for travis before this patch: https://github.com/pmem/pmemkv/pull/754/files?
It seems there was just one variable (GITHUB_TOKEN)?
</blockquote></details>

GITHUB_TOKEN is token generated per github action session 
DOC_UPDATE_GITHUB_TOKEN (formerly GITHUB_TOKEN) is permanent token generated for github account. 
It seems it sopped working on GHA.
___
*[.github/workflows/gha.yml, line 60 at r1](https://reviewable.io/reviews/pmem/pmemkv/760#-MFj_JFMEF1espHTKaqd:-MFjckji1UubPfu8IufA:bfyaovw) ([raw file](https://github.com/pmem/pmemkv/blob/26d0659bb0bf7adf33be140d83cd1baf0a8da107/.github/workflows/gha.yml#L60)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Is this pmem if run on PR?
</blockquote></details>

yes. However docs are not built on PRs. 
___
*[.github/workflows/gha.yml, line 68 at r1](https://reviewable.io/reviews/pmem/pmemkv/760#-MFjZOP65M6HAZgTDPv5:-MFjcwN4E6YluYDQBiL9:b-jvs820) ([raw file](https://github.com/pmem/pmemkv/blob/26d0659bb0bf7adf33be140d83cd1baf0a8da107/.github/workflows/gha.yml#L68)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

github.ref? what is it for?
</blockquote></details>


The branch or tag ref that triggered the workflow. For example, refs/heads/feature-branch-1. If neither a branch or tag is available for the event type, the variable will not exist.

https://docs.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables
___
*[utils/docker/build.sh, line 99 at r1](https://reviewable.io/reviews/pmem/pmemkv/760#-MFjZd0rAiqVm3vhrg1E:-MFjeQp5CUDzKA5SuJm9:bje3ok0) ([raw file](https://github.com/pmem/pmemkv/blob/35b921dc46f63d983b6614d1997ca1120e96f516/utils/docker/build.sh#L99)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Without this, how can you disable running doc update on your fork? If I understand correctly, it will just fail for now (if you don't setup secrets)?
</blockquote></details>

yes, it would fail on fork if you do not setup secrets, but only for  master, stable-1.0, stable-1.1 and stable-1.2 branches 
___
*[utils/docker/run-doc-update.sh, line 15 at r1](https://reviewable.io/reviews/pmem/pmemkv/760#-MFj_5pH-9t9c4Nat8lM:-MFjjMgS66mdiLIhBu71:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/26d0659bb0bf7adf33be140d83cd1baf0a8da107/utils/docker/run-doc-update.sh#L15)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

shouldn't this be "${DOCK_UPDATE_BOT_NAME:-"pmem"}" ? (`:-` instead of  `==`)?
</blockquote></details>

Done.
___
*[utils/docker/run-doc-update.sh, line 16 at r1](https://reviewable.io/reviews/pmem/pmemkv/760#-MFj_0FY3Xh82KHg7BF0:-MFjjMUv8VtiybattYgj:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/26d0659bb0bf7adf33be140d83cd1baf0a8da107/utils/docker/run-doc-update.sh#L16)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[utils/docker/run-doc-update.sh, line 16 at r1](https://reviewable.io/reviews/pmem/pmemkv/760#-MFj_g-t6ramWm0H3Ch7:-MFjj8i17M7Vn6jAUxXe:b-826dku) ([raw file](https://github.com/pmem/pmemkv/blob/26d0659bb0bf7adf33be140d83cd1baf0a8da107/utils/docker/run-doc-update.sh#L16)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Is there a possibility that this variable is empty? If you set it to github.actor then it should always be set?
</blockquote></details>

It's running in docker, so you have to setup all env variables explicitly in build.sh anyway.  
___
*[utils/docker/run-doc-update.sh, line 52 at r1](https://reviewable.io/reviews/pmem/pmemkv/760#-MFj_XdD9yiRCIFr3kmZ:-MFjj6pV2chK5OU3kh2e:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/26d0659bb0bf7adf33be140d83cd1baf0a8da107/utils/docker/run-doc-update.sh#L52)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

why not ${ARTIFACTS_DIR}?
</blockquote></details>

Done.

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/760)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @igchor and @karczex)

___
*[.github/workflows/gha.yml, line 59 at r1](https://reviewable.io/reviews/pmem/pmemkv/760#-MFjaQdTEyWidPIbY8iQ:-MFk1mcyCcrFA6MSEs5u:b2lf45w) ([raw file](https://github.com/pmem/pmemkv/blob/26d0659bb0bf7adf33be140d83cd1baf0a8da107/.github/workflows/gha.yml#L59)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

GITHUB_TOKEN is token generated per github action session 
DOC_UPDATE_GITHUB_TOKEN (formerly GITHUB_TOKEN) is permanent token generated for github account. 
It seems it sopped working on GHA.
</blockquote></details>

Ok, but I don';t see any reference to DOC_UPDATE_GITHUB_TOKEN in the repo before Luke's patch. Only the GITHUB_TOKEN one. So the, problem was name collision? That's why we switched to DOC_UPDATE_GITHUB_TOKEN? 
___
*[.github/workflows/gha.yml, line 60 at r1](https://reviewable.io/reviews/pmem/pmemkv/760#-MFj_JFMEF1espHTKaqd:-MFk01hYBOvBh3JY7WH4:b-81la7d) ([raw file](https://github.com/pmem/pmemkv/blob/26d0659bb0bf7adf33be140d83cd1baf0a8da107/.github/workflows/gha.yml#L60)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

yes. However docs are not built on PRs. 
</blockquote></details>

Right
___
*[.github/workflows/gha.yml, line 68 at r1](https://reviewable.io/reviews/pmem/pmemkv/760#-MFjZOP65M6HAZgTDPv5:-MFk0ERBAhmg19MUjKzL:b-wzb8t3) ([raw file](https://github.com/pmem/pmemkv/blob/26d0659bb0bf7adf33be140d83cd1baf0a8da107/.github/workflows/gha.yml#L68)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>


The branch or tag ref that triggered the workflow. For example, refs/heads/feature-branch-1. If neither a branch or tag is available for the event type, the variable will not exist.

https://docs.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables

</blockquote></details>

So why is it here? Wouldn't it be better to have just master and stable branches here?
___
*[utils/docker/build.sh, line 99 at r1](https://reviewable.io/reviews/pmem/pmemkv/760#-MFjZd0rAiqVm3vhrg1E:-MFk0w7yDmkU4j2y4Ohc:b-4ujlej) ([raw file](https://github.com/pmem/pmemkv/blob/35b921dc46f63d983b6614d1997ca1120e96f516/utils/docker/build.sh#L99)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

yes, it would fail on fork if you do not setup secrets, but only for  master, stable-1.0, stable-1.1 and stable-1.2 branches 
</blockquote></details>

Hm, in that case, those variables should be documented somewhere in readme. Btw, I think it would be better to make it optional (e.g. only run_doc update if the DOC_UPDATE_BOT_NAME is set - maybe it's possible to add such dependency on a GHA job?). For us (the developers) it will be clear why some job failed but I would not like to see issues opened because a master branch of someone's fork failed ;d

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/760)* status: 3 of 4 files reviewed, 5 unresolved discussions (waiting on @igchor and @karczex)

___
*[utils/docker/run-doc-update.sh, line 18 at r2](https://reviewable.io/reviews/pmem/pmemkv/760#-MFk2Sx26XTwoD_qtC8s:-MFk2Sx26XTwoD_qtC8t:bpd6p89) ([raw file](https://github.com/pmem/pmemkv/blob/a809740e013c6e27052c0f7f7b9ce02e5bfcdd27/utils/docker/run-doc-update.sh#L18)):*
> ```Shell
> GITHUB_UPSTREAM_USER_NAME="${GITHUB_UPSTREAM_USER_NAME:-"pmem"}"
> REPO_NAME="pmemkv"
> ARTIFACTS_DIR=$(mktemp -d -t ARTIFACTS-XXX)
> ```

I see a problem with mktemp (also in other places, e.g. REPO_DIR). The dir will be different in all builds and there will be more changes in the PR. Why not leave it as it was?

**Comment by karczex** [comment]
___
*[.github/workflows/gha.yml, line 59 at r1](https://reviewable.io/reviews/pmem/pmemkv/760#-MFjaQdTEyWidPIbY8iQ:-MFkCpmR8gLriT2FwP8L:b-l08swk) ([raw file](https://github.com/pmem/pmemkv/blob/26d0659bb0bf7adf33be140d83cd1baf0a8da107/.github/workflows/gha.yml#L59)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Ok, but I don';t see any reference to DOC_UPDATE_GITHUB_TOKEN in the repo before Luke's patch. Only the GITHUB_TOKEN one. So the, problem was name collision? That's why we switched to DOC_UPDATE_GITHUB_TOKEN? 
</blockquote></details>

All variables which starts with "GITHUB_" are reserved on GHA, and some are always provided  (like GITHUB_TOKEN).

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/760)* status: 3 of 4 files reviewed, 5 unresolved discussions (waiting on @igchor and @karczex)

___
*[.github/workflows/gha.yml, line 68 at r1](https://reviewable.io/reviews/pmem/pmemkv/760#-MFjZOP65M6HAZgTDPv5:-MFkBNydDpzIME762YtM:b-9e6uc3) ([raw file](https://github.com/pmem/pmemkv/blob/26d0659bb0bf7adf33be140d83cd1baf0a8da107/.github/workflows/gha.yml#L68)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

So why is it here? Wouldn't it be better to have just master and stable branches here?
</blockquote></details>

it's exactly that. 
```
contains( search, item )

Returns true if search contains item
```

https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#contains

**Comment by karczex** [comment]
___
*[.github/workflows/gha.yml, line 58 at r1](https://reviewable.io/reviews/pmem/pmemkv/760#-MFjZ7HO0V2-0qDv9Hmm:-MFkECp044eOgBf1Wure:bt6pp4l) ([raw file](https://github.com/pmem/pmemkv/blob/26d0659bb0bf7adf33be140d83cd1baf0a8da107/.github/workflows/gha.yml#L58)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Does it work fine (have you tested it) when secrets.DOC_UPDATE_BOT_NAME is empty?
</blockquote></details>

Yes, it works as expected 
https://github.com/karczex/pmemkv/runs/1036859327?check_suite_focus=true
 Build failed with 
```
fatal: unable to access 'https://github.com/pmem-bot/pmemkv/': The requested URL returned error: 403 
```
as I don't have configured TOKEN for pmem-bot account.

**Comment by karczex** [comment]
___
*[utils/docker/build.sh, line 99 at r1](https://reviewable.io/reviews/pmem/pmemkv/760#-MFjZd0rAiqVm3vhrg1E:-MFkJG7o1w6cptD6RiYC:bxbtwps) ([raw file](https://github.com/pmem/pmemkv/blob/35b921dc46f63d983b6614d1997ca1120e96f516/utils/docker/build.sh#L99)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Hm, in that case, those variables should be documented somewhere in readme. Btw, I think it would be better to make it optional (e.g. only run_doc update if the DOC_UPDATE_BOT_NAME is set - maybe it's possible to add such dependency on a GHA job?). For us (the developers) it will be clear why some job failed but I would not like to see issues opened because a master branch of someone's fork failed ;d
</blockquote></details>

That's fair point. I would investigate if such thing is possible on GHA (probably is). IMO good place to document it is CONTRIBUTING.md

**Comment by karczex** [comment]
___
*[utils/docker/run-doc-update.sh, line 18 at r2](https://reviewable.io/reviews/pmem/pmemkv/760#-MFk2Sx26XTwoD_qtC8s:-MFozV-H5jbf1gso28T3:b-qa6s2n) ([raw file](https://github.com/pmem/pmemkv/blob/a809740e013c6e27052c0f7f7b9ce02e5bfcdd27/utils/docker/run-doc-update.sh#L18)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I see a problem with mktemp (also in other places, e.g. REPO_DIR). The dir will be different in all builds and there will be more changes in the PR. Why not leave it as it was?
</blockquote></details>

That's somehow good point :) 
The fact, that this path appears in gh-pages PR is bug in generation of c++ documentation. 
Please look here:  https://pmem.io/pmemkv/master/doxygen/classpmem_1_1kv_1_1config.html 
include statement is wrong:
```c
#include </pmemkv/doc_update/pmemkv/src/libpmemkv.hpp>  
```

**Comment by karczex** [comment]
GHA run without DOC_UPDATE_BOT_NAME variable set: https://github.com/karczex/pmemkv
/runs/1041629392?check_suite_focus=true 

Run passed, however PR with documentation was not submitted.

**Comment by karczex** [comment]
Successful run with opened PR to my fork  
 https://github.com/karczex/pmemkv/runs/1042029278?check_suite_focus=true

**Review by igchor — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/760)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by szyrom — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 1 of 1 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/760)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
