### PR TITLE
Update docs links

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
- change the hierarchy, for easier "look" (in my opinion)
- make visible links only to master and latest stable branch (move the rest to the bottom of the page)
- add links to new manpages (tx and iterator)

preview: https://lukaszstolarczuk.github.io/pmemkv/

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/870)

### CODE REVIEW

**Review by szyrom — APPROVED** [review]
:lgtm: + probably after the merge of PR with iterators (in order to provide a proper URL)

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/870#-:-MPETMTn0yQy3YMFFWFp:b-s9q3ag)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Review by karczex — COMMENTED** [review]
You have old version in the preview. 

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/870#-:-MPoTfEP1KcgUxCGdlhU:b-uqjokd)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Comment by lukaszstolarczuk** [comment]
> You have old version in the preview.
> 
> > _[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/870#-:-MPoTfEP1KcgUxCGdlhU:b-uqjokd)_ status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

sorry, I've pushed gh-pages to origin in the meantime; now it should look better (links to manpages may not work; I'll check this)

**Review by igchor — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/870)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/870#-:-MQr9fc3ABwrPzXbAgqc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Pull request merged**
