### PR TITLE
[stable-1.2] Fixes for docker images

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
- [x] temporary commit to be dropped

there's still one known issue - TBB installed without pkg-config is incompatible with our examples (#838)
preview: https://github.com/pmem/pmemkv/runs/2951206748?check_suite_focus=true

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1006)

### CODE REVIEW

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1006#-:-MdWe5gc-SyFpdL9RkBo:bnfp4nl)* status: 0 of 7 files reviewed, all discussions resolved

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1006)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[utils/docker/images/Dockerfile.opensuse-leap-latest, line 62 at r1](https://reviewable.io/reviews/pmem/pmemkv/1006#-MdXm2aN71M6XNlMXxfg:-MdXm2aN71M6XNlMXxfh:b-41k76g) ([raw file](https://github.com/pmem/pmemkv/blob/d684e702c4e952a8ec951223bcc836878c5f7017/utils/docker/images/Dockerfile.opensuse-leap-latest#L62)):*
> ```
> 	rpm-build \
> 	sudo \
> 	systemd \
> ```

really? why?
___
*[utils/docker/images/install-pmdk.sh, line 19 at r1](https://reviewable.io/reviews/pmem/pmemkv/1006#-MdXmjwT7ccxmJNqdJqU:-MdXmjwT7ccxmJNqdJqV:b-d0rqi0) ([raw file](https://github.com/pmem/pmemkv/blob/d684e702c4e952a8ec951223bcc836878c5f7017/utils/docker/images/install-pmdk.sh#L19)):*
> ```Shell
> PREFIX=${2:-/usr}
> 
> PMDK_VERSION="1.11.0-rc2"
> ```

Is it affecting INSTALLING.md?

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1006)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @karczex)

___
*[utils/docker/images/Dockerfile.opensuse-leap-latest, line 62 at r1](https://reviewable.io/reviews/pmem/pmemkv/1006#-MdXm2aN71M6XNlMXxfg:-MdXv9cu0uaqyFywoi-d:b-2ln2jo) ([raw file](https://github.com/pmem/pmemkv/blob/d684e702c4e952a8ec951223bcc836878c5f7017/utils/docker/images/Dockerfile.opensuse-leap-latest#L62)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

really? why?
</blockquote></details>

ndctl requires it (it was found on QB)
We either didn't test it for some time or just opensuse stopped putting this package as a default in their OS... or something :wink:
___
*[utils/docker/images/install-pmdk.sh, line 19 at r1](https://reviewable.io/reviews/pmem/pmemkv/1006#-MdXmjwT7ccxmJNqdJqU:-MdXvP8q4-v1kypbCEnE:b-y9ixbp) ([raw file](https://github.com/pmem/pmemkv/blob/d684e702c4e952a8ec951223bcc836878c5f7017/utils/docker/images/install-pmdk.sh#L19)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Is it affecting INSTALLING.md?
</blockquote></details>

I don't think so... we say in there `Install latest PMDK:/obj-cpp/memkind` anyway... and I believe it's a good suggestion, the newest versions usually works better :)

The requirement (prerequisites) is still the same, the least version we support is 1.8 (e.g. `libpmem and libpmemobj, which are part of PMDK - Persistent Memory Development Kit 1.8`) and that's true (at least, from the perspective of our code; not from perspective of evolving OSes)

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1006#-:-Md_vaVF-sBQ1MHYKCcp:bnfp4nl)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Pull request merged**
