### PR TITLE
examples: add example which adds elements until oom

### PR DESCRIPTION
**Pull request by igchor**
It can be used to approximate space overhead per engine.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/987)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/987)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @igchor)

___
*[examples/CMakeLists.txt, line 122 at r1](https://reviewable.io/reviews/pmem/pmemkv/987#-MYiC9J1DQ-Nc9Wpqy27:-MYiC9J1DQ-Nc9Wpqy28:bk3rpka) ([raw file](https://github.com/pmem/pmemkv/blob/b8b0592ec4594acf3d287d05c86f0123d1210cb1/examples/CMakeLists.txt#L122)):*
> ```CMake
> endif()
> 
> add_example(pmemkv_fill_cpp pmemkv_fill_cpp/pmemkv_fill.cpp)
> ```

perhaps add here a comment that here is/are example(s) with no engine hardcoded
___
*[examples/pmemkv_fill_cpp/CMakeLists.txt, line 2 at r1](https://reviewable.io/reviews/pmem/pmemkv/987#-MYiBu7yDGxS1C_HSrQ3:-MYiBu7yDGxS1C_HSrQ4:bb6ht36) ([raw file](https://github.com/pmem/pmemkv/blob/b8b0592ec4594acf3d287d05c86f0123d1210cb1/examples/pmemkv_fill_cpp/CMakeLists.txt#L2)):*
> ```CMake
> # SPDX-License-Identifier: BSD-3-Clause
> # Copyright 2020, Intel Corporation
> ```

2021
___
*[examples/pmemkv_fill_cpp/CMakeLists.txt, line 5 at r1](https://reviewable.io/reviews/pmem/pmemkv/987#-MYiBxhg--XcTgu_qQPm:-MYiBxhg--XcTgu_qQPn:b2nhc9q) ([raw file](https://github.com/pmem/pmemkv/blob/b8b0592ec4594acf3d287d05c86f0123d1210cb1/examples/pmemkv_fill_cpp/CMakeLists.txt#L5)):*
> ```CMake
> 
> cmake_minimum_required(VERSION 3.3)
> project(pmemkv_basic C)
> ```

CXX
___
*[examples/pmemkv_fill_cpp/pmemkv_fill.cpp, line 6 at r1](https://reviewable.io/reviews/pmem/pmemkv/987#-MYiCiSZ9duIhffeu0Ux:-MYiCiSZ9duIhffeu0Uy:bv5edib) ([raw file](https://github.com/pmem/pmemkv/blob/b8b0592ec4594acf3d287d05c86f0123d1210cb1/examples/pmemkv_fill_cpp/pmemkv_fill.cpp#L6)):*
> ```cpp
> /*
>  * pmemkv_fill.cpp -- example which calculates how many elements fit
>  * into pmemkv
> ```

here or in the Usage we could explain in more details what's going on in the example (I know parameters are quite self-explanatory, but that's for us, not necessarily for all users)
___
*[examples/pmemkv_fill_cpp/pmemkv_fill.cpp, line 40 at r1](https://reviewable.io/reviews/pmem/pmemkv/987#-MYiFA7E9Rh3RSE2THOB:-MYiFA7E9Rh3RSE2THOC:b-lgy97p) ([raw file](https://github.com/pmem/pmemkv/blob/b8b0592ec4594acf3d287d05c86f0123d1210cb1/examples/pmemkv_fill_cpp/pmemkv_fill.cpp#L40)):*
> ```cpp
> 	} while (s == status::OK);
> 
> 	ASSERT(s == status::OUT_OF_MEMORY);
> ```

what if we got here a really big file size (and e.g. 8b key/value) and it won't reach the OOM?

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/987)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[examples/CMakeLists.txt, line 122 at r1](https://reviewable.io/reviews/pmem/pmemkv/987#-MYiC9J1DQ-Nc9Wpqy27:-MYiXeclBCsUo2a_Nwh6:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/b8b0592ec4594acf3d287d05c86f0123d1210cb1/examples/CMakeLists.txt#L122)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps add here a comment that here is/are example(s) with no engine hardcoded
</blockquote></details>

Done.
___
*[examples/pmemkv_fill_cpp/CMakeLists.txt, line 2 at r1](https://reviewable.io/reviews/pmem/pmemkv/987#-MYiBu7yDGxS1C_HSrQ3:-MYiXfM9Cs9G7CeSgWWY:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/b8b0592ec4594acf3d287d05c86f0123d1210cb1/examples/pmemkv_fill_cpp/CMakeLists.txt#L2)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

2021
</blockquote></details>

Done.
___
*[examples/pmemkv_fill_cpp/CMakeLists.txt, line 5 at r1](https://reviewable.io/reviews/pmem/pmemkv/987#-MYiBxhg--XcTgu_qQPm:-MYiXhIe75AzhKHHcGIF:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/b8b0592ec4594acf3d287d05c86f0123d1210cb1/examples/pmemkv_fill_cpp/CMakeLists.txt#L5)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

CXX
</blockquote></details>

Done.
___
*[examples/pmemkv_fill_cpp/pmemkv_fill.cpp, line 6 at r1](https://reviewable.io/reviews/pmem/pmemkv/987#-MYiCiSZ9duIhffeu0Ux:-MYiXzp8DSQ7GJ_O4CYB:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/b8b0592ec4594acf3d287d05c86f0123d1210cb1/examples/pmemkv_fill_cpp/pmemkv_fill.cpp#L6)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

here or in the Usage we could explain in more details what's going on in the example (I know parameters are quite self-explanatory, but that's for us, not necessarily for all users)
</blockquote></details>

Done.
___
*[examples/pmemkv_fill_cpp/pmemkv_fill.cpp, line 40 at r1](https://reviewable.io/reviews/pmem/pmemkv/987#-MYiFA7E9Rh3RSE2THOB:-MYiY-PgAlwa_j7TBpZR:bqifnas) ([raw file](https://github.com/pmem/pmemkv/blob/b8b0592ec4594acf3d287d05c86f0123d1210cb1/examples/pmemkv_fill_cpp/pmemkv_fill.cpp#L40)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

what if we got here a really big file size (and e.g. 8b key/value) and it won't reach the OOM?
</blockquote></details>

It must stop eventually, if there is something other than OUT_OF_MEMORY then that's a bug imo.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/987)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @igchor)

___
*[examples/CMakeLists.txt, line 122 at r1](https://reviewable.io/reviews/pmem/pmemkv/987#-MYiC9J1DQ-Nc9Wpqy27:-MYj22_S2RIz5l8LxEgE:bb74ptu) ([raw file](https://github.com/pmem/pmemkv/blob/b8b0592ec4594acf3d287d05c86f0123d1210cb1/examples/CMakeLists.txt#L122)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thx!
___
*[examples/pmemkv_fill_cpp/pmemkv_fill.cpp, line 40 at r1](https://reviewable.io/reviews/pmem/pmemkv/987#-MYiFA7E9Rh3RSE2THOB:-MYj2Oxs6msBPWE6E-5F:b-i7d2i) ([raw file](https://github.com/pmem/pmemkv/blob/b8b0592ec4594acf3d287d05c86f0123d1210cb1/examples/pmemkv_fill_cpp/pmemkv_fill.cpp#L40)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

It must stop eventually, if there is something other than OUT_OF_MEMORY then that's a bug imo.
</blockquote></details>

I meant the case when we have `num > uint64_t.MAX` - we'd eventually start overriding existing keys and we'll get into an infinite loop...?
___
*[examples/pmemkv_fill_cpp/pmemkv_fill.cpp, line 9 at r2](https://reviewable.io/reviews/pmem/pmemkv/987#-MYjIXkf9IBEGqAuHKon:-MYjIXkgCnLcgRtCdHr6:bozu3i8) ([raw file](https://github.com/pmem/pmemkv/blob/b5f801f4fa1d72d70d5b546991cc972209327a7d/examples/pmemkv_fill_cpp/pmemkv_fill.cpp#L9)):*
> ```cpp
>  * to the database until OUT_OF_MEMORY status is returned. It then prints
>  * number of elements inserted.
>  */
> ```

we could actually add some warning that this may take a while to finish up... I guess for big numbers we could also add some printing (e.g. every 1000 keys or something) to show that the example is still alive

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/987)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[examples/pmemkv_fill_cpp/pmemkv_fill.cpp, line 40 at r1](https://reviewable.io/reviews/pmem/pmemkv/987#-MYiFA7E9Rh3RSE2THOB:-MYoe_lp-8jqEVh0iq9W:b3nr80o) ([raw file](https://github.com/pmem/pmemkv/blob/b8b0592ec4594acf3d287d05c86f0123d1210cb1/examples/pmemkv_fill_cpp/pmemkv_fill.cpp#L40)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I meant the case when we have `num > uint64_t.MAX` - we'd eventually start overriding existing keys and we'll get into an infinite loop...?
</blockquote></details>

If that happens we have bigger problems. For such number of element the size of the database would be > 18 exabytes and we would not be able to even address all of them on 64-bit arch ;d
___
*[examples/pmemkv_fill_cpp/pmemkv_fill.cpp, line 9 at r2](https://reviewable.io/reviews/pmem/pmemkv/987#-MYjIXkf9IBEGqAuHKon:-MYodThh6EY7xdi1DqlD:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/b5f801f4fa1d72d70d5b546991cc972209327a7d/examples/pmemkv_fill_cpp/pmemkv_fill.cpp#L9)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

we could actually add some warning that this may take a while to finish up... I guess for big numbers we could also add some printing (e.g. every 1000 keys or something) to show that the example is still alive
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/987#-:-MYonkIy0vJZLC-SFS-L:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

___
*[examples/pmemkv_fill_cpp/pmemkv_fill.cpp, line 40 at r1](https://reviewable.io/reviews/pmem/pmemkv/987#-MYiFA7E9Rh3RSE2THOB:-MYonHMTAGrC85dN2Hx-:bi7lypl) ([raw file](https://github.com/pmem/pmemkv/blob/b8b0592ec4594acf3d287d05c86f0123d1210cb1/examples/pmemkv_fill_cpp/pmemkv_fill.cpp#L40)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

If that happens we have bigger problems. For such number of element the size of the database would be > 18 exabytes and we would not be able to even address all of them on 64-bit arch ;d
</blockquote></details>

haha, ok, fair enough.. :D

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/987#-:-MYstfRy3C9efYBl-Z1r:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Pull request merged**
