### PR TITLE
Add information in README about discontinuation of the project

### PR DESCRIPTION
**Pull request by szadam**
Preview: https://github.com/szadam/pmemkv/blob/master/README.md

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1087)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1087)* status: all files reviewed, 3 unresolved discussions (waiting on @szadam)

___
*[`README.md` line 32 at r1](https://reviewable.io/reviews/pmem/pmemkv/1087#-NOFWWs--8dPjTjyVBvE:-NOFWWs--8dPjTjyVBvF:b17xr2i) ([raw file](https://github.com/pmem/pmemkv/blob/c9f27802d7a239e0670e1710d5f6b4fa39f2bb75/README.md#L32)):*
> ```Markdown
> 
> Up-to-date, current support/maintenance status of branches/releases is available on
> [pmem.io](https://pmem.io/pmemkv/index.html#releases-support-status).
> ```

pls drop this information about current support statuses - we'll drop that from the microsite
___
*[`README.md` line 78 at r1](https://reviewable.io/reviews/pmem/pmemkv/1087#-NOFDlKJ6hRJEXcDawJ7:-NOFDlKJ6hRJEXcDawJ8:b-pax763) ([raw file](https://github.com/pmem/pmemkv/blob/c9f27802d7a239e0670e1710d5f6b4fa39f2bb75/README.md#L78)):*
> ```Markdown
> * **Python** - https://github.com/pmem/pmemkv-python
> * **Ruby** - https://github.com/pmem/pmemkv-ruby
> ```

BTW, we have to do the same update on all these pmemkv-* repos
___
*[`README.md` line 114 at r1](https://reviewable.io/reviews/pmem/pmemkv/1087#-NOFOShK9dsUfQ5pKXca:-NOFOShK9dsUfQ5pKXcb:b-le8an1) ([raw file](https://github.com/pmem/pmemkv/blob/c9f27802d7a239e0670e1710d5f6b4fa39f2bb75/README.md#L114)):*
> ```Markdown
> 
> ## Contact us
> For more information about **pmemkv** contact us using dedicated email: pmdk_support@intel.com.
> ```

pls rather use a similar message to the one worked out in the pmemstream's PR

**Review by szadam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1087)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[`README.md` line 32 at r1](https://reviewable.io/reviews/pmem/pmemkv/1087#-NOFWWs--8dPjTjyVBvE:-NOy9pC97FErr8Ib_SlS:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/c9f27802d7a239e0670e1710d5f6b4fa39f2bb75/README.md#L32)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls drop this information about current support statuses - we'll drop that from the microsite
</blockquote></details>

Done.
___
*[`README.md` line 114 at r1](https://reviewable.io/reviews/pmem/pmemkv/1087#-NOFOShK9dsUfQ5pKXca:-NOy9rWz2cFoprE1IuSF:b-k0emsx) ([raw file](https://github.com/pmem/pmemkv/blob/c9f27802d7a239e0670e1710d5f6b4fa39f2bb75/README.md#L114)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls rather use a similar message to the one worked out in the pmemstream's PR
</blockquote></details>

I suggest sth like that.

**Review by szadam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1087)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[`README.md` line 114 at r1](https://reviewable.io/reviews/pmem/pmemkv/1087#-NOFOShK9dsUfQ5pKXca:-NPXrJ_hAe3-kqKdptXm:bb7f2mf) ([raw file](https://github.com/pmem/pmemkv/blob/c9f27802d7a239e0670e1710d5f6b4fa39f2bb75/README.md#L114)):*
<details><summary><i>Previously, szadam (Adam Szopiński) wrote…</i></summary><blockquote>

I suggest sth like that.
</blockquote></details>

done

**Review by lukaszstolarczuk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1087#-:-NPXvoLJ6tznAYnfouYf:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @szadam)

**Pull request merged**
