### PR TITLE
re-add soversion

### PR DESCRIPTION
**Pull request by kilobyte**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/492)

### CODE REVIEW

**Comment by lukaszstolarczuk** [comment]
yeah, that's not this easy :P
1. you have to fix "RPM build errors" along with this change.
2. also, shouldn't it be "1" now instead of "0"?
3. and, it should be for stable-1.0 branch, not master, I believe

**Comment by kilobyte** [comment]
I don't quite have any idea how to fix cpack, both here and for new Fedora's RPM.

**Comment by igchor** [comment]
The ABI is actually not compatible (we moved config_from_json) to separate lib

**Comment by lukaszstolarczuk** [comment]
Since this PR is covered with some updates in #499 I'm closing it.

**Pull request closed without merging**
