### PR TITLE
Split jenkins build into dynamic stages

### PR DESCRIPTION
**Pull request by karczex**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/792)

### CODE REVIEW

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/792)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @karczex)

___
*[utils/docker/run-build.sh, line 248 at r1](https://reviewable.io/reviews/pmem/pmemkv/792#-MHzP5XN-Z6fynroYdr4:-MHzP5XN-Z6fynroYdr5:b-48syx0) ([raw file](https://github.com/pmem/pmemkv/blob/dbd1201090ca46403d8f6d83b50bc557a9f18243/utils/docker/run-build.sh#L248)):*
> ```Shell
> if [ "${INTERRUPT_ON_FAILURE}" == "OFF" ]; then
> 	echo "Do not interrupt test session on failures"
> 	set +e
> ```

Imho disabling `set -e` for the whole script is not a good idea. If we want to only continue in case of failing ctest tests  I would prefer disabling `set -e` just for ctest command (and reenable it after the command). I think any env error should terminate the whole job.

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/792)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @igchor)

___
*[utils/docker/run-build.sh, line 248 at r1](https://reviewable.io/reviews/pmem/pmemkv/792#-MHzP5XN-Z6fynroYdr4:-MHzQM-w-FFAxtDTbLlq:b-bbjr82) ([raw file](https://github.com/pmem/pmemkv/blob/dbd1201090ca46403d8f6d83b50bc557a9f18243/utils/docker/run-build.sh#L248)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Imho disabling `set -e` for the whole script is not a good idea. If we want to only continue in case of failing ctest tests  I would prefer disabling `set -e` just for ctest command (and reenable it after the command). I think any env error should terminate the whole job.
</blockquote></details>

I disagree. We also want to continue in case of failing make command. You may have i.e. 4 builds during one test session, and don't want to stop testing after first. And in case of any failures in this script, return code would be non-zero, so whole test session will be failed.

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/792)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @igchor)

___
*[utils/docker/run-build.sh, line 248 at r1](https://reviewable.io/reviews/pmem/pmemkv/792#-MHzP5XN-Z6fynroYdr4:-MIOtLHM--8C8z_jogge:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/dbd1201090ca46403d8f6d83b50bc557a9f18243/utils/docker/run-build.sh#L248)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

I disagree. We also want to continue in case of failing make command. You may have i.e. 4 builds during one test session, and don't want to stop testing after first. And in case of any failures in this script, return code would be non-zero, so whole test session will be failed.  
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/792)* status: all files reviewed, 3 unresolved discussions (waiting on @igchor and @karczex)

___
*[utils/docker/run-build.sh, line 20 at r2](https://reviewable.io/reviews/pmem/pmemkv/792#-MIOzWypAkauED2sHVDB:-MIOzWyq-bBJrjIq4BWr:baqltr5) ([raw file](https://github.com/pmem/pmemkv/blob/4a6a2859e571b17cfcb9cc0e7fd6c9f9b920550b/utils/docker/run-build.sh#L20)):*
> ```Shell
> TESTS_LONG=${TESTS_LONG:-OFF}
> 
> function workspace_cleanup() {
> ```

you can move this into `prepare-for-build.sh`, where we have common functions and then use it in `run-test-building.sh` and perhaps also in `run-compatibility.sh` (and perhaps in more scripts...?)
___
*[utils/docker/run-build.sh, line 260 at r2](https://reviewable.io/reviews/pmem/pmemkv/792#-MIOzkQN4y1CB02RFWd7:-MIOzkQN4y1CB02RFWd8:b-uqefe8) ([raw file](https://github.com/pmem/pmemkv/blob/4a6a2859e571b17cfcb9cc0e7fd6c9f9b920550b/utils/docker/run-build.sh#L260)):*
> ```Shell
> 	exit 1
> fi
> ```

redundant empty line...?

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/792#-:-MIPFr1r0DcQRfaS3RCN:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @karczex)

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/792)* status: 1 of 5 files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[utils/docker/run-build.sh, line 20 at r2](https://reviewable.io/reviews/pmem/pmemkv/792#-MIOzWypAkauED2sHVDB:-MITmmNLEzJfr4_5QD_E:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/4a6a2859e571b17cfcb9cc0e7fd6c9f9b920550b/utils/docker/run-build.sh#L20)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you can move this into `prepare-for-build.sh`, where we have common functions and then use it in `run-test-building.sh` and perhaps also in `run-compatibility.sh` (and perhaps in more scripts...?)
</blockquote></details>

Done.
___
*[utils/docker/run-build.sh, line 260 at r2](https://reviewable.io/reviews/pmem/pmemkv/792#-MIOzkQN4y1CB02RFWd7:-MITmgLJ0JEO_M_s9rNT:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/4a6a2859e571b17cfcb9cc0e7fd6c9f9b920550b/utils/docker/run-build.sh#L260)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

redundant empty line...?
</blockquote></details>

Done.

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/792#-:-MIU5Wkb8OXPYIqE67t2:bnfp4nl)* status: 1 of 5 files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

**Review by lukaszstolarczuk — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/792#-:-MIU67FbDY1lkA1IYpYQ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
