### PR TITLE
Update Jenkins files

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/859)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/859)* status: 0 of 3 files reviewed, 1 unresolved discussion

___
*[utils/jenkins/pmemkv_linux.jenkins, line 115 at r1](https://reviewable.io/reviews/pmem/pmemkv/859#-MOG-UXG-38foSj-4l09:-MOG-UXG-38foSj-4l0A:b2pbdx7) ([raw file](https://github.com/pmem/pmemkv/blob/4d5ca233e56a32221228ce8391661a4fdcf62285/utils/jenkins/pmemkv_linux.jenkins#L115)):*
> ```
> 								break
> 							}
> 						def ENV_VAL="export DEFAULT_TEST_DIR=${TEST_DIR}; export WORKDIR=${WORKSPACE_DIR}/${PMEMKV_DIR}; export SCRIPTSDIR=\$WORKDIR/utils/docker; export TESTS_LONG=ON; export TERM=xterm-256color; ${COV_PARAM}"
> ```

@karczex , we only set colored output in run-build.sh, but perhaps it's worth to set this for the whole environemnt? (where to do this at best?)

**Review by KFilipek — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/859#-:-MOWTMos1biw2gX7wYC2:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

**Review by igchor — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/859)* status: all files reviewed, 1 unresolved discussion

**Comment by karczex** [comment]
___
*[utils/jenkins/pmemkv_linux.jenkins, line 115 at r1](https://reviewable.io/reviews/pmem/pmemkv/859#-MOG-UXG-38foSj-4l09:-MOf_jzv8-mGfI9yUWKJ:b5gwdul) ([raw file](https://github.com/pmem/pmemkv/blob/4d5ca233e56a32221228ce8391661a4fdcf62285/utils/jenkins/pmemkv_linux.jenkins#L115)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

@karczex , we only set colored output in run-build.sh, but perhaps it's worth to set this for the whole environemnt? (where to do this at best?)
</blockquote></details>


Your solution is pretty OK If you don't want to refactor half of jenkins related codebase :)

Probably you may also hardcode it in  run_bash_script method (utils/jenkins/lib/api.groovy) somehow. 

Best approach is to change way of handling env variables in run_bash_script method. Currently env variables have to be explicitly set up in lambda. Instead of it, list of environment variables may be passed as separate argument, extended by some default variables (if not present on the list already) and applied before lambda is running.

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/859#-:-MOfeoFM1X2k_8B6ZO69:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

**Pull request merged**
