### PR TITLE
Parametrized test path

### PR DESCRIPTION
**Pull request by karczex**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/447)

### CODE REVIEW

**Comment by karczex** [comment]
1. It needs additional time to setup environment (probably with some changes in docker files)  for caching engine, and it's not tested in CI anyway, so I decided to move it to another PR.  
2. For granularity during development process. If you want I may merge those commits.

**Comment by lukaszstolarczuk** [comment]
> 1. It needs additional time to setup environment (probably with some changes in docker files)  for caching engine, and it's not tested in CI anyway, so I decided to move it to another PR.
> 2. For granularity during development process. If you want I may merge those commits.

1. ok, make sense, but testing caching on Travis is not needed for now (and it's low priority), so you can apply these changes of yours into the caching test code and put TODO mark or file an issue to fix/check it later

2. yeah, squashing these commits seems like a good option to me

**Comment by karczex** [comment]
___
*[tests/test_suite.h, line 51 at r3](https://reviewable.io/reviews/pmem/pmemkv/447#-Lpgio6z4lAhQg1Piyhg:-Lph98c23Z2ai9OJ2PqC:b-itykza) ([raw file](https://github.com/pmem/pmemkv/blob/dc2539076b0e88cf66da62722ceebfae2f0d07ff/tests/test_suite.h#L51)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

is it value or size? or both together...? ;)
</blockquote></details>

It's size. Do you have idea how to name it better?

**Comment by karczex** [comment]
___
*[tests/test_suite.h, line 65 at r3](https://reviewable.io/reviews/pmem/pmemkv/447#-LpgjGtb3jeVFIzOTGrE:-LphG1I-74gU1iHsQCpt:by33dm9) ([raw file](https://github.com/pmem/pmemkv/blob/dc2539076b0e88cf66da62722ceebfae2f0d07ff/tests/test_suite.h#L65)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you said in the comment: "specifies if engine should treat path as file or dir" and here you are treating it exactly like dir... something's not right ;) did you mean "if ( ! use_file)" ?
</blockquote></details>

It add file name to path if needed. Do I miss something?

**Comment by karczex** [comment]
___
*[tests/engines-experimental/tree3_test.cc, line 959 at r2](https://reviewable.io/reviews/pmem/pmemkv/447#-LpgcxZF380qYmOpprF5:-Lph_R7g3JFlAY3CE72J:b-x85r8v) ([raw file](https://github.com/pmem/pmemkv/blob/d7c825fc3e715d33b33b3573740b259893eb780c/tests/engines-experimental/tree3_test.cc#L959)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

We may do this as another quest, to merge valgrind wrapper into test binary (something like this patch: https://github.com/karczex/pmemkv/commit/6eae46a034fa9dd392571e733d1ea9e3694bfea7) , make test paths non-collidable and enable parallel testing in CI
</blockquote></details>

I checked this... indeed doesn't work. 
https://travis-ci.org/karczex/pmemkv/jobs/589870783

**Pull request merged**
