### PR TITLE
tests: update params for radix memcheck tests

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
these tests are long enough, so dial down the params a little.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1020)

### CODE REVIEW

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1020#-:-Mf7Oqe22drgp7C5tnme:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved

**Review by igchor — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1020#-:-Mf88-EREDWprMC8MrAj:bnfp4nl)* status: 0 of 2 files reviewed, all discussions resolved

**Comment by lukaszstolarczuk** [comment]
The last approach, I promise 😉 

Some of the tests were stubbornly timeouting, so we've decided to turn them off temporarily.

**Review by igchor — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1020#-:-MfHkzSqAjwYDvaXHrBq:bnfp4nl)* status: 0 of 2 files reviewed, all discussions resolved

**Pull request merged**
