### PR TITLE
Increase vcmap db size accordingly to nproc

### PR DESCRIPTION
**Pull request by karczex**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/820)

### CODE REVIEW

**Review by lukaszstolarczuk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/820)* status: all files reviewed, 4 unresolved discussions (waiting on @karczex)

___
*[tests/ctest_helpers.cmake, line 310 at r1](https://reviewable.io/reviews/pmem/pmemkv/820#-MJWSPCe3n2SIjlVvY3V:-MJWSPCe3n2SIjlVvY3W:bkp8vvw) ([raw file](https://github.com/pmem/pmemkv/blob/4fd1323bc352a769a12cf66448f17c319aa9cc6a/tests/ctest_helpers.cmake#L310)):*
> ```
> *  1024
> ```
pls remove double space between * and 1024
___
*[tests/ctest_helpers.cmake, line 313 at r1](https://reviewable.io/reviews/pmem/pmemkv/820#-MJWTY7_6HddaOyZZrr8:-MJWTY7a-aat1GBxQvNL:b3kqx) ([raw file](https://github.com/pmem/pmemkv/blob/4fd1323bc352a769a12cf66448f17c319aa9cc6a/tests/ctest_helpers.cmake#L313)):*
> ```CMake
> 
> 		#Limit size DB_SIZE with arbitrary chosen threshold
> 		math(EXPR TEST_DB_SIZE_THRESHOLD "256 * 4 * 2 *  1024 * 1024")
> ```

.
___
*[tests/ctest_helpers.cmake, line 314 at r1](https://reviewable.io/reviews/pmem/pmemkv/820#-MJWTdjSEHVe_qdqiGwq:-MJWTdjSEHVe_qdqiGwr:b3jgctn) ([raw file](https://github.com/pmem/pmemkv/blob/4fd1323bc352a769a12cf66448f17c319aa9cc6a/tests/ctest_helpers.cmake#L314)):*
> ```CMake
> 		#Limit size DB_SIZE with arbitrary chosen threshold
> 		math(EXPR TEST_DB_SIZE_THRESHOLD "256 * 4 * 2 *  1024 * 1024")
> 		if( TEST_DB_SIZE GREATER ${TEST_DB_SIZE_THRESHOLD} )
> ```

redundant trailing space within parentheses
___
*[tests/ctest_helpers.cmake, line 315 at r1](https://reviewable.io/reviews/pmem/pmemkv/820#-MJWVhpL-S-PzYy177or:-MJWVhpM0zpyqm4YIqOP:bk3nlmb) ([raw file](https://github.com/pmem/pmemkv/blob/4fd1323bc352a769a12cf66448f17c319aa9cc6a/tests/ctest_helpers.cmake#L315)):*
> ```CMake
> 		math(EXPR TEST_DB_SIZE_THRESHOLD "256 * 4 * 2 *  1024 * 1024")
> 		if( TEST_DB_SIZE GREATER ${TEST_DB_SIZE_THRESHOLD} )
> 			set(TEST_DB_SIZE ${TEST_DB_SIZE_THRESHOLD})
> ```

please add some INFO/WARNING message in such case, that these tests may fail, or something...

**Comment by lukaszstolarczuk** [comment]
something's wrong with you commit author, I guess :wink:

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/820)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[tests/ctest_helpers.cmake, line 310 at r1](https://reviewable.io/reviews/pmem/pmemkv/820#-MJWSPCe3n2SIjlVvY3V:-MJWfSFU4wvhAtQNFyOY:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/4fd1323bc352a769a12cf66448f17c319aa9cc6a/tests/ctest_helpers.cmake#L310)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

> ```
> *  1024
> ```
pls remove double space between * and 1024
</blockquote></details>

Done.
___
*[tests/ctest_helpers.cmake, line 313 at r1](https://reviewable.io/reviews/pmem/pmemkv/820#-MJWTY7_6HddaOyZZrr8:-MJWfSV743VZB89hq_sS:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/4fd1323bc352a769a12cf66448f17c319aa9cc6a/tests/ctest_helpers.cmake#L313)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/ctest_helpers.cmake, line 314 at r1](https://reviewable.io/reviews/pmem/pmemkv/820#-MJWTdjSEHVe_qdqiGwq:-MJWfUgODkz4aOeyDxWl:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/4fd1323bc352a769a12cf66448f17c319aa9cc6a/tests/ctest_helpers.cmake#L314)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

redundant trailing space within parentheses
</blockquote></details>

Done.
___
*[tests/ctest_helpers.cmake, line 315 at r1](https://reviewable.io/reviews/pmem/pmemkv/820#-MJWVhpL-S-PzYy177or:-MJWi8Eu2HOGNdHd8LB9:boalus2) ([raw file](https://github.com/pmem/pmemkv/blob/4fd1323bc352a769a12cf66448f17c319aa9cc6a/tests/ctest_helpers.cmake#L315)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

please add some INFO/WARNING message in such case, that these tests may fail, or something...
</blockquote></details>

part of cmake command output with hacked nproc command 
```
CMake Warning at tests/ctest_helpers.cmake:315 (message):
  TEST_DB_SIZE reached threshold: 2147483648.  This may cause failures in
  some tests of memkind based engines
Call Stack (most recent call first):
  tests/CMakeLists.txt:747 (add_engine_test)


-- Found Doxygen: /usr/bin/doxygen (found version "1.8.20") found components: doxygen dot 
-- Configuring done
-- Generating done
-- Build files have been written to: /opt/workspace/pmemkv/build 
```

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/820)* status: all files reviewed, 3 unresolved discussions (waiting on @karczex)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/820#-MJX9hp5A8CsCgnLOxev:-MJX9hp5A8CsCgnLOxew:b-ph10py) (no related file):*
perhaps, in commit message ref. to the issue using  `Fixes: #798`

and there's still something wrong with commit author...?

---
___
*[tests/ctest_helpers.cmake, line 314 at r1](https://reviewable.io/reviews/pmem/pmemkv/820#-MJWTdjSEHVe_qdqiGwq:-MJX92L8Boqhwus68XPY:brq4qo3) ([raw file](https://github.com/pmem/pmemkv/blob/4fd1323bc352a769a12cf66448f17c319aa9cc6a/tests/ctest_helpers.cmake#L314)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

Done.
</blockquote></details>

there's still a trailing whitespace next to open parenthesis
___
*[tests/ctest_helpers.cmake, line 315 at r1](https://reviewable.io/reviews/pmem/pmemkv/820#-MJWVhpL-S-PzYy177or:-MJX9EJW1rYsJ3hjw8bl:b-yndfic) ([raw file](https://github.com/pmem/pmemkv/blob/4fd1323bc352a769a12cf66448f17c319aa9cc6a/tests/ctest_helpers.cmake#L315)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

part of cmake command output with hacked nproc command 
```
CMake Warning at tests/ctest_helpers.cmake:315 (message):
  TEST_DB_SIZE reached threshold: 2147483648.  This may cause failures in
  some tests of memkind based engines
Call Stack (most recent call first):
  tests/CMakeLists.txt:747 (add_engine_test)


-- Found Doxygen: /usr/bin/doxygen (found version "1.8.20") found components: doxygen dot 
-- Configuring done
-- Generating done
-- Build files have been written to: /opt/workspace/pmemkv/build 
```

Done.
</blockquote></details>

perhaps, a small fix - make it: `WARNING "Calculated TEST_DB_SIZE...` and add '.' at the end of the sentence

**Review by lukaszstolarczuk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/820)* status: all files reviewed, 2 unresolved discussions (waiting on @karczex)

___
*[tests/ctest_helpers.cmake, line 315 at r3](https://reviewable.io/reviews/pmem/pmemkv/820#-MJXXh8AAApKGnAdlAjd:-MJXXh8BAuesF-ZxLzLE:by6tkue) ([raw file](https://github.com/pmem/pmemkv/blob/02538f057dcf21ea68c38634f876f7e2e7aafe9a/tests/ctest_helpers.cmake#L315)):*
> ```CMake
> 		math(EXPR TEST_DB_SIZE_THRESHOLD "256 * 4 * 2 * 1024 * 1024")
> 		if(TEST_DB_SIZE GREATER ${TEST_DB_SIZE_THRESHOLD})
> 			message(WARNING "Calculated TEST_DB_SIZE reached threshold: ${TEST_DB_SIZE_THRESHOLD}. This may cause failures in some tests of memkind based engines.")t
> ```

suddenly 't'... :wink: (at the end of line)

**Review by szyrom — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/820)* status: all files reviewed, 2 unresolved discussions (waiting on @karczex)

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/820)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @karczex, @lukaszstolarczuk, and @szyrom)

___
*[tests/ctest_helpers.cmake, line 315 at r3](https://reviewable.io/reviews/pmem/pmemkv/820#-MJXXh8AAApKGnAdlAjd:-MJahYsp-nJewIvjoL6w:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/02538f057dcf21ea68c38634f876f7e2e7aafe9a/tests/ctest_helpers.cmake#L315)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

suddenly 't'... :wink: 
</blockquote></details>

Done.

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/820)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk and @szyrom)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/820#-MJX9hp5A8CsCgnLOxev:-MJb9I8zE9TtaIppAX9y:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps, in commit message ref. to the issue using  `Fixes: #798`

and there's still something wrong with commit author...?
</blockquote></details>

Done.

---

**Review by KFilipek — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/820)* status: all files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

**Review by lukaszstolarczuk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/820)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/820#-MJbaJq5938J8ArjeK7g:-MJbaJq5938J8ArjeK7h:b8nsw6q) (no related file):*
hmm.. one more thing, I believe we agreed this should go to the stable-1.1 branch

---

**Comment by lukaszstolarczuk** [comment]
337 commits...? yeah, nope! :smile: (forgot to push branch anew, I guess)

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/820)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @KFilipek, @lukaszstolarczuk, and @szyrom)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/820#-MJbaJq5938J8ArjeK7g:-MJg2lqyA6172UOFPIQG:bto99fg) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hmm.. one more thing, I believe we agreed this should go to the stable-1.1 branch
</blockquote></details>

There is no affected test, nor cmake facility on stable-1.1 branch. I rebased it to stable-1.2.

---

**Review by lukaszstolarczuk — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/820#-:-MJg5k-sB0yJEt1sONuU:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

**Pull request merged**
