### PR TITLE
Fixes in examples

### PR DESCRIPTION
**Pull request by karczex**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/993)

### CODE REVIEW

**Review by igchor — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/993)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/993)* status: all files reviewed, 3 unresolved discussions (waiting on @karczex)

___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 32 at r1](https://reviewable.io/reviews/pmem/pmemkv/993#-M_uSTJe5BCpdNp1Hi_e:-M_uSTJf1DjJdnJfxiQi:bvnt8zm) ([raw file](https://github.com/pmem/pmemkv/blob/5bd6707abdc08ce89db1025e472107744f72e3c3/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L32)):*
> ```cpp
> {
> 	/* See libpmemkv_config(3) for more detailed example of config creation */
> 	LOG("Creating config");
> ```

you could make it "Creating a new config" and perhaps add an empty line before this (it will be hopefully a bit clearer to read the example's output)
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 189 at r1](https://reviewable.io/reviews/pmem/pmemkv/993#-M_uRiAt2GGIeJqHu_hU:-M_uRiAt2GGIeJqHu_hV:b-euy50g) ([raw file](https://github.com/pmem/pmemkv/blob/5bd6707abdc08ce89db1025e472107744f72e3c3/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L189)):*
> ```cpp
> 				       std::string(current_value.size(), 'x')) == 0);
> 			LOG("Value after commit = " + current_value);
> 		} while (w_it.next() == status::OK);
> ```

next will actually take us above the "5" and we wanted to modify elements "lower than 5"
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 192 at r1](https://reviewable.io/reviews/pmem/pmemkv/993#-M_uQrslC3hz-vOFlACJ:-M_uQrslC3hz-vOFlACK:b-otpr03) ([raw file](https://github.com/pmem/pmemkv/blob/5bd6707abdc08ce89db1025e472107744f72e3c3/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L192)):*
> ```cpp
> 		/* write iterator is being destroyed now */
> 	}
> }
> ```

I tried to compile this example (standalone) and got an error with pthread - the solution is to add in pmemkv_iterator_cpp/CMakeLists.txt:

`target_link_libraries(... pthread)` (line 13)

can you pls add this within this PR...?

**Review by KFilipek — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/993)* status: all files reviewed, 4 unresolved discussions (waiting on @karczex)

___
*[examples/pmemkv_basic_cpp/pmemkv_basic.cpp, line 50 at r1](https://reviewable.io/reviews/pmem/pmemkv/993#-M_zDnTODt9QWWheokvo:-M_zDnTODt9QWWheokvp:bq164w3) ([raw file](https://github.com/pmem/pmemkv/blob/5bd6707abdc08ce89db1025e472107744f72e3c3/examples/pmemkv_basic_cpp/pmemkv_basic.cpp#L50)):*
> ```
> db kv = db();
> ```
I believe that 
```
db kv;
``` 
is enough.
Your line will create object and then do default (shallow) copy assignment (we don't provide any copy assignment operator for that class).
@igchor correct me if I'm wrong.

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/993)* status: all files reviewed, 4 unresolved discussions (waiting on @karczex and @KFilipek)

___
*[examples/pmemkv_basic_cpp/pmemkv_basic.cpp, line 50 at r1](https://reviewable.io/reviews/pmem/pmemkv/993#-M_zDnTODt9QWWheokvo:-Ma2XtXvCQofpMfvTw8B:bl3h6ct) ([raw file](https://github.com/pmem/pmemkv/blob/5bd6707abdc08ce89db1025e472107744f72e3c3/examples/pmemkv_basic_cpp/pmemkv_basic.cpp#L50)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> db kv = db();
> ```
I believe that 
```
db kv;
``` 
is enough.
Your line will create object and then do default (shallow) copy assignment (we don't provide any copy assignment operator for that class).
@igchor correct me if I'm wrong.
</blockquote></details>

Those two lines are exactly the same (both will call default ctor)

**Review by KFilipek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/993)* status: all files reviewed, 4 unresolved discussions (waiting on @igchor and @karczex)

___
*[examples/pmemkv_basic_cpp/pmemkv_basic.cpp, line 50 at r1](https://reviewable.io/reviews/pmem/pmemkv/993#-M_zDnTODt9QWWheokvo:-Ma7oXt_3tBdLFXQrQkZ:b-9k0pgu) ([raw file](https://github.com/pmem/pmemkv/blob/5bd6707abdc08ce89db1025e472107744f72e3c3/examples/pmemkv_basic_cpp/pmemkv_basic.cpp#L50)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Those two lines are exactly the same (both will call default ctor)
</blockquote></details>

Indeed, but second version will look more cleaner, I think

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/993#-:-Ma8NiYk18RlF92Vmv4_:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @KFilipek)

___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 32 at r1](https://reviewable.io/reviews/pmem/pmemkv/993#-M_uSTJe5BCpdNp1Hi_e:-Ma8NFro7b04JkAqz1Uj:b-5qi8hg) ([raw file](https://github.com/pmem/pmemkv/blob/5bd6707abdc08ce89db1025e472107744f72e3c3/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L32)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

I don't get the point of this new line.
</blockquote></details>

Nah, it's ok. I just thought it may be a bit better readable, but it's ok.

**Review by igchor — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/993)* status: all files reviewed, 1 unresolved discussion (waiting on @KFilipek)

**Pull request merged**
