### PR TITLE
wrap c-style pointers into unique_ptr in libpmemkv.hpp

### PR DESCRIPTION
**Pull request by JanDorniak99**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/840)

### CODE REVIEW

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/840)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @JanDorniak99)

___
*[src/libpmemkv.hpp, line 153 at r1](https://reviewable.io/reviews/pmem/pmemkv/840#-MLlIJfd1XZhKABZlSxn:-MLlIJfd1XZhKABZlSxo:b-ih2quw) ([raw file](https://github.com/pmem/pmemkv/blob/dd9247722dcf2579bb4c49471f10e85b642e4543/src/libpmemkv.hpp#L153)):*
> ```cpp
> 	explicit config(pmemkv_config *cfg) noexcept;
> 
> 	config(const config &other) = delete;
> ```

You can entirely remove move/copy ctors and assignment ops.
___
*[src/libpmemkv.hpp, line 194 at r1](https://reviewable.io/reviews/pmem/pmemkv/840#-MLlHLHf7--WGi9VRPsU:-MLlHLHf7--WGi9VRPsV:b2e2d8h) ([raw file](https://github.com/pmem/pmemkv/blob/dd9247722dcf2579bb4c49471f10e85b642e4543/src/libpmemkv.hpp#L194)):*
> ```cpp
> 	int init() noexcept;
> 
> 	std::unique_ptr<pmemkv_config, std::function<void(pmemkv_config *)>> _config;
> ```

you don't have to use std::function. I believe you can write it as this:

```
std::unique_ptr<pmemkv_config, decltype(&pmemkv_config_delete)> config_;
```

and then

```
config_(cfg, &pmemkv_config_delete);
```
___
*[src/libpmemkv.hpp, line 194 at r1](https://reviewable.io/reviews/pmem/pmemkv/840#-MLlHbXb3Kt_haqhaCPw:-MLlHbXb3Kt_haqhaCPx:b-2vqqzy) ([raw file](https://github.com/pmem/pmemkv/blob/dd9247722dcf2579bb4c49471f10e85b642e4543/src/libpmemkv.hpp#L194)):*
> ```cpp
> 	int init() noexcept;
> 
> 	std::unique_ptr<pmemkv_config, std::function<void(pmemkv_config *)>> _config;
> ```

by the way, could you change names of the variables from _config to config_. I believe using underscores at the beggining is a bad practice. https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier
___
*[src/libpmemkv.hpp, line 269 at r1](https://reviewable.io/reviews/pmem/pmemkv/840#-MLlIDf19WUL6LbxXRX9:-MLlIDf19WUL6LbxXRXA:b3kqx) ([raw file](https://github.com/pmem/pmemkv/blob/dd9247722dcf2579bb4c49471f10e85b642e4543/src/libpmemkv.hpp#L269)):*
> ```cpp
> 
> private:
> 	std::unique_ptr<pmemkv_db, std::function<void(pmemkv_db *)>> _db;
> ```

.
___
*[src/libpmemkv.hpp, line 854 at r1](https://reviewable.io/reviews/pmem/pmemkv/840#-MLlJF718tb7V1zM3-uv:-MLlJF718tb7V1zM3-uw:b-c6xxak) ([raw file](https://github.com/pmem/pmemkv/blob/dd9247722dcf2579bb4c49471f10e85b642e4543/src/libpmemkv.hpp#L854)):*
> ```cpp
> inline void db::close() noexcept
> {
> 	if (this->_db.get() != nullptr)
> ```

You can implement it as this->_db.reset(nullptr);

**Review by JanDorniak99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/840)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @igchor)

___
*[src/libpmemkv.hpp, line 194 at r1](https://reviewable.io/reviews/pmem/pmemkv/840#-MLlHLHf7--WGi9VRPsU:-MLlz2F92cF2uSKLQZhY:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/dd9247722dcf2579bb4c49471f10e85b642e4543/src/libpmemkv.hpp#L194)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

you don't have to use std::function. I believe you can write it as this:

```
std::unique_ptr<pmemkv_config, decltype(&pmemkv_config_delete)> config_;
```

and then

```
config_(cfg, &pmemkv_config_delete);
```

</blockquote></details>

Done.
___
*[src/libpmemkv.hpp, line 194 at r1](https://reviewable.io/reviews/pmem/pmemkv/840#-MLlHbXb3Kt_haqhaCPw:-MLm9pUj-OPmWyINsCkt:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/dd9247722dcf2579bb4c49471f10e85b642e4543/src/libpmemkv.hpp#L194)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

by the way, could you change names of the variables from _config to config_. I believe using underscores at the beggining is a bad practice. https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier
</blockquote></details>

Done.
___
*[src/libpmemkv.hpp, line 269 at r1](https://reviewable.io/reviews/pmem/pmemkv/840#-MLlIDf19WUL6LbxXRX9:-MLlz8dv9ObeUd9b4g2K:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/dd9247722dcf2579bb4c49471f10e85b642e4543/src/libpmemkv.hpp#L269)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/libpmemkv.hpp, line 854 at r1](https://reviewable.io/reviews/pmem/pmemkv/840#-MLlJF718tb7V1zM3-uv:-MLlz9AnBQCfSaQJUzYS:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/dd9247722dcf2579bb4c49471f10e85b642e4543/src/libpmemkv.hpp#L854)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

You can implement it as this->_db.reset(nullptr);
</blockquote></details>

Done.

**Review by igchor — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/840)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JanDorniak99)

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/840)* status: all files reviewed, 1 unresolved discussion (waiting on @JanDorniak99)

___
*[src/libpmemkv.hpp, line 809 at r2](https://reviewable.io/reviews/pmem/pmemkv/840#-MMFj5wP44Wx-M3QNLBP:-MMFj5wP44Wx-M3QNLBQ:bygjciu) ([raw file](https://github.com/pmem/pmemkv/blob/53d263609bddeced223da2e163fd0612e4a39b4b/src/libpmemkv.hpp#L809)):*
> ```cpp
>  * @return pmem::kv::status
>  */
> inline status db::open(const std::string &engine_name) noexcept
> ```

I suggest to use other overload of this method, instead of implementing it twice: 

```C++
                                                               
inline status db::open(const std::string &engine_name) noexcept                  
{                                                                                
    return open(engine_name, config());                               
}                                                                                   
```

tested on c++11 with gcc

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/840#-:-MMFrHSo2xvzy3zufWmY:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @JanDorniak99 and @karczex)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/840#-MMFrJ2M2d8Sjw0gfZ7w:-MMFrJ2M2d8Sjw0gfZ7x:bi2uysx) (no related file):*
I believe renaming of the variable could be done in sep. commit, but you don't have to change it, just FYI for future, I guess...

---
___
*[src/libpmemkv.hpp, line 809 at r2](https://reviewable.io/reviews/pmem/pmemkv/840#-MMFj5wP44Wx-M3QNLBP:-MMFqXEv1BM1G3fjgVuo:b-if8s9w) ([raw file](https://github.com/pmem/pmemkv/blob/53d263609bddeced223da2e163fd0612e4a39b4b/src/libpmemkv.hpp#L809)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

I suggest to use other overload of this method, instead of implementing it twice: 

```C++
                                                               
inline status db::open(const std::string &engine_name) noexcept                  
{                                                                                
    return open(engine_name, config());                               
}                                                                                   
```

tested on c++11 with gcc 


</blockquote></details>

@karczex, with that impl. you're not passing null as config, I believe, and in some cases it is allowed (e.g. blackhole does not require any config).

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/840)* status: all files reviewed, 2 unresolved discussions (waiting on @JanDorniak99 and @karczex)

___
*[src/libpmemkv.hpp, line 809 at r2](https://reviewable.io/reviews/pmem/pmemkv/840#-MMFj5wP44Wx-M3QNLBP:-MMGJ9Ol3KZ_3ePCxIZ_:b-n0cakx) ([raw file](https://github.com/pmem/pmemkv/blob/53d263609bddeced223da2e163fd0612e4a39b4b/src/libpmemkv.hpp#L809)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

@karczex, with that impl. you're not passing null as config, I believe, and in some cases it is allowed (e.g. blackhole does not require any config).
</blockquote></details>

We are passing it anyway (see the use of pmemkv_open). I guess we could even make only one db::open function:

```
open(const std::string &engine_name, config&& cfg = config{});
```

**Comment by karczex** [comment]
___
*[src/libpmemkv.hpp, line 809 at r2](https://reviewable.io/reviews/pmem/pmemkv/840#-MMFj5wP44Wx-M3QNLBP:-MMGWtqY-bjkkMGfhaaj:b-3w208n) ([raw file](https://github.com/pmem/pmemkv/blob/53d263609bddeced223da2e163fd0612e4a39b4b/src/libpmemkv.hpp#L809)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

We are passing it anyway (see the use of pmemkv_open). I guess we could even make only one db::open function:

```
open(const std::string &engine_name, config&& cfg = config{});
```
</blockquote></details>

@igchor I agree, it's even better.

**Review by JanDorniak99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/840)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @igchor and @karczex)

___
*[src/libpmemkv.hpp, line 809 at r2](https://reviewable.io/reviews/pmem/pmemkv/840#-MMFj5wP44Wx-M3QNLBP:-MMKuH0g6B-t-vUsrgPP:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/53d263609bddeced223da2e163fd0612e4a39b4b/src/libpmemkv.hpp#L809)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

@igchor I agree, it's even better. 
</blockquote></details>

Done.

**Review by igchor — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/840)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)

**Pull request merged**
