### PR TITLE
iterators: fix uncaught exception in write_range()

### PR DESCRIPTION
**Pull request by JanDorniak99**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/900)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/900)* status: all files reviewed, 1 unresolved discussion (waiting on @JanDorniak99)

___
*[src/libpmemkv.hpp, line 1073 at r1](https://reviewable.io/reviews/pmem/pmemkv/900#-MSYS4xPDR-UXqsS-SWI:-MSYS4xPDR-UXqsS-SWJ:b-qz9hd8) ([raw file](https://github.com/pmem/pmemkv/blob/6548e52922b98c073dc95f2055b40cdf53fafd15/src/libpmemkv.hpp#L1073)):*
> ```cpp
> 		} catch (std::out_of_range &e) {
> 			return {status::INVALID_ARGUMENT};
> 		}
> ```

shouldn't it be shrunk already in `pmemkv_write_iterator_write_range`? if not maybe we should return proper value already there (in C API), not catch it here...?

**Review by igchor — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/900)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[src/libpmemkv.hpp, line 1073 at r1](https://reviewable.io/reviews/pmem/pmemkv/900#-MSYS4xPDR-UXqsS-SWI:-MSatv3T7dwO2W9L7dvJ:b12h4f6) ([raw file](https://github.com/pmem/pmemkv/blob/6548e52922b98c073dc95f2055b40cdf53fafd15/src/libpmemkv.hpp#L1073)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

shouldn't it be shrunk already in `pmemkv_write_iterator_write_range`? if not maybe we should return proper value already there (in C API), not catch it here...?
</blockquote></details>

It should be ok already, but coverity will complain - this is mostly to silence it. (This info could probably go to the commit msg).

**Review by JanDorniak99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/900)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[src/libpmemkv.hpp, line 1073 at r1](https://reviewable.io/reviews/pmem/pmemkv/900#-MSYS4xPDR-UXqsS-SWI:-MScBYrA0qRD43cHFy2j:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/6548e52922b98c073dc95f2055b40cdf53fafd15/src/libpmemkv.hpp#L1073)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

It should be ok already, but coverity will complain - this is mostly to silence it. (This info could probably go to the commit msg).
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/900#-:-MScHnxJ8Ghpz7sjszhp:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JanDorniak99)

**Review by KFilipek — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/900#-:-MScK_AU8rJErznDzyGz:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JanDorniak99)

**Pull request merged**
