### PR TITLE
parameterize tests to work with fixed size keys

### PR DESCRIPTION
**Pull request by JanDorniak99**
---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/883)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 2 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/883)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @JanDorniak99)

___
*[tests/common/unittest.hpp, line 238 at r2](https://reviewable.io/reviews/pmem/pmemkv/883#-MRKJJ3WBFEBLQotvtYc:-MRKJJ3X5AwWtzxyomq-:bvt2us) ([raw file](https://github.com/pmem/pmemkv/blob/7164e8adbea2542d18633bc80b9012bc23542fa9/tests/common/unittest.hpp#L238)):*
> ```cpp
> {
> 	if (str.size() < size)
> 		return str + std::string(size - str.size(), 'x');
> ```

the `'x'` should be a param
___
*[tests/common/unittest.hpp, line 243 at r2](https://reviewable.io/reviews/pmem/pmemkv/883#-MRKOz_GCSkPqjwi8U6D:-MRKOz_GCSkPqjwi8U6E:b-luih6p) ([raw file](https://github.com/pmem/pmemkv/blob/7164e8adbea2542d18633bc80b9012bc23542fa9/tests/common/unittest.hpp#L243)):*
> ```cpp
> }
> 
> static inline std::string generate_key(size_t number, std::string prefix = "",
> ```

it's not generating per se, so maybe rename to "key_from_number" (?)
___
*[tests/engine_scenarios/concurrent/put_get_remove_gen_params.cc, line 32 at r2](https://reviewable.io/reviews/pmem/pmemkv/883#-MRKNNq56NT1rrhW2bEN:-MRKNNq56NT1rrhW2bEO:b4kpdcm) ([raw file](https://github.com/pmem/pmemkv/blob/7164e8adbea2542d18633bc80b9012bc23542fa9/tests/engine_scenarios/concurrent/put_get_remove_gen_params.cc#L32)):*
> ```cpp
> 			postfix.push_back(charset[(size_t)rand() % charset_size]);
> 		}
> 		std::string gen_key = generate_key(k, "", postfix);
> ```

if you make it this way, we always have keys starting with a number and a random prefix; what we wanted here are totally random keys (with a full charset possible). To fix this I'd just add another gen_key method (in unittest.hpp) to generate key without `to_string(number)`

**Review by JanDorniak99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/883)* status: 0 of 10 files reviewed, 3 unresolved discussions (waiting on @JanDorniak99 and @lukaszstolarczuk)

___
*[tests/common/unittest.hpp, line 238 at r2](https://reviewable.io/reviews/pmem/pmemkv/883#-MRKJJ3WBFEBLQotvtYc:-MRPBhBk9Ibht6BUKB2i:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/7164e8adbea2542d18633bc80b9012bc23542fa9/tests/common/unittest.hpp#L238)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

the `'x'` should be a param
</blockquote></details>

Done.
___
*[tests/common/unittest.hpp, line 243 at r2](https://reviewable.io/reviews/pmem/pmemkv/883#-MRKOz_GCSkPqjwi8U6D:-MRPBhUOALaYFbZkawnF:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/7164e8adbea2542d18633bc80b9012bc23542fa9/tests/common/unittest.hpp#L243)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

it's not generating per se, so maybe rename to "key_from_number" (?)
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 2 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/883)* status: 2 of 10 files reviewed, 2 unresolved discussions (waiting on @JanDorniak99)

___
*[tests/common/unittest.hpp, line 255 at r3](https://reviewable.io/reviews/pmem/pmemkv/883#-MRPnm-hESLt6O-2Oa9K:-MRPnm-hESLt6O-2Oa9L:bfh5gfh) ([raw file](https://github.com/pmem/pmemkv/blob/eb13f15c3158a2fa5c3c60c0774d78f61b917716/tests/common/unittest.hpp#L255)):*
> ```cpp
> }
> 
> static inline std::string gen_key(std::string str)
> ```

rename to.. hmm `aligned_key` (?) \+ a short description for this function please

**Review by JanDorniak99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/883)* status: 1 of 10 files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[tests/common/unittest.hpp, line 255 at r3](https://reviewable.io/reviews/pmem/pmemkv/883#-MRPnm-hESLt6O-2Oa9K:-MRTwmVNC2KPXQHemp0F:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/eb13f15c3158a2fa5c3c60c0774d78f61b917716/tests/common/unittest.hpp#L255)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

rename to.. hmm `aligned_key` (?) \+ a short description for this function please
</blockquote></details>

Done.
___
*[tests/engine_scenarios/concurrent/put_get_remove_gen_params.cc, line 32 at r2](https://reviewable.io/reviews/pmem/pmemkv/883#-MRKNNq56NT1rrhW2bEN:-MRU6R2975VgGSIVjLYh:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/7164e8adbea2542d18633bc80b9012bc23542fa9/tests/engine_scenarios/concurrent/put_get_remove_gen_params.cc#L32)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

if you make it this way, we always have keys starting with a number and a random prefix; what we wanted here are totally random keys (with a full charset possible). To fix this I'd just add another gen_key method (in unittest.hpp) to generate key without `to_string(number)`
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 3 of 10 files at r3, 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/883)* status: all files reviewed, 4 unresolved discussions (waiting on @JanDorniak99)

___
*[tests/common/unittest.hpp, line 235 at r4](https://reviewable.io/reviews/pmem/pmemkv/883#-MRVMLVf7plbyO_84NH_:-MRVMLVf7plbyO_84NHa:b-d6ldne) ([raw file](https://github.com/pmem/pmemkv/blob/1c362c9545cc1172759f96f5df160c593369d06d/tests/common/unittest.hpp#L235)):*
> ```cpp
> }
> 
> static inline std::string allign_to_size(size_t size, std::string str,
> ```

mispell "align"
___
*[tests/common/unittest.hpp, line 254 at r4](https://reviewable.io/reviews/pmem/pmemkv/883#-MRVMNf17VfcfWLKm4KX:-MRVMNf23n0tVAEN5lo4:b-pim5nd) ([raw file](https://github.com/pmem/pmemkv/blob/1c362c9545cc1172759f96f5df160c593369d06d/tests/common/unittest.hpp#L254)):*
> ```cpp
> /* It returns a key filled/shrank to a certain size. It's necessary during testing engines
>  * with fixed size keys */
> static inline std::string alligned_key(std::string str)
> ```

mispell "aligned"
___
*[tests/engine_scenarios/concurrent/put_get_remove_gen_params.cc, line 32 at r2](https://reviewable.io/reviews/pmem/pmemkv/883#-MRKNNq56NT1rrhW2bEN:-MRVJgiXEraoXBPWwxwO:b-ucfknh) ([raw file](https://github.com/pmem/pmemkv/blob/7164e8adbea2542d18633bc80b9012bc23542fa9/tests/engine_scenarios/concurrent/put_get_remove_gen_params.cc#L32)):*
<details><summary><i>Previously, JanDorniak99 (Jan Dorniak) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks!
___
*[tests/engine_scenarios/persistent/overwrite_verify.cc, line 12 at r4](https://reviewable.io/reviews/pmem/pmemkv/883#-MRVMXuZAkrNTxEeii7b:-MRVMXuZAkrNTxEeii7c:byh08b4) ([raw file](https://github.com/pmem/pmemkv/blob/1c362c9545cc1172759f96f5df160c593369d06d/tests/engine_scenarios/persistent/overwrite_verify.cc#L12)):*
> ```cpp
> 	std::string key = alligned_key("key1");
> 
> 	std::string expected_value = alligned_key("value1");
> ```

value also should be aligned?
___
*[tests/engine_scenarios/persistent/put_remove_verify.cc, line 2 at r4](https://reviewable.io/reviews/pmem/pmemkv/883#-MRVMjspBZ82tKDf3TmY:-MRVMjspBZ82tKDf3TmZ:b-8mxykb) ([raw file](https://github.com/pmem/pmemkv/blob/1c362c9545cc1172759f96f5df160c593369d06d/tests/engine_scenarios/persistent/put_remove_verify.cc#L2)):*
> ```cpp
> // SPDX-License-Identifier: BSD-3-Clause
> /* Copyright 2020, Intel Corporation */
> ```

-2021

**Review by JanDorniak99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/883)* status: 4 of 10 files reviewed, 4 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[tests/common/unittest.hpp, line 235 at r4](https://reviewable.io/reviews/pmem/pmemkv/883#-MRVMLVf7plbyO_84NH_:-MRYrvDD7eq8FEoljUND:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/1c362c9545cc1172759f96f5df160c593369d06d/tests/common/unittest.hpp#L235)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

mispell "align"
</blockquote></details>

Done.
___
*[tests/common/unittest.hpp, line 254 at r4](https://reviewable.io/reviews/pmem/pmemkv/883#-MRVMNf17VfcfWLKm4KX:-MRYrvTPCNJgOiz2SPBH:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/1c362c9545cc1172759f96f5df160c593369d06d/tests/common/unittest.hpp#L254)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

mispell "aligned"
</blockquote></details>

Done.
___
*[tests/engine_scenarios/persistent/overwrite_verify.cc, line 12 at r4](https://reviewable.io/reviews/pmem/pmemkv/883#-MRVMXuZAkrNTxEeii7b:-MRYtJyA5TxNhKoWrKXC:bwhleki) ([raw file](https://github.com/pmem/pmemkv/blob/1c362c9545cc1172759f96f5df160c593369d06d/tests/engine_scenarios/persistent/overwrite_verify.cc#L12)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

value also should be aligned?
</blockquote></details>

I think yes (in case of robinhood, from get method we always return string with size of 8 bytes)
___
*[tests/engine_scenarios/persistent/put_remove_verify.cc, line 2 at r4](https://reviewable.io/reviews/pmem/pmemkv/883#-MRVMjspBZ82tKDf3TmY:-MRYsbgQAb5B69iCm6sd:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/1c362c9545cc1172759f96f5df160c593369d06d/tests/engine_scenarios/persistent/put_remove_verify.cc#L2)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

-2021
</blockquote></details>

Done.

**Review by lukaszstolarczuk — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/883#-:-MRZC3yN7GR2UUM4bltv:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JanDorniak99)

**Review by igchor — COMMENTED** [review]
> Reviewed 4 of 10 files at r3, 3 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/883)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JanDorniak99)

___
*[tests/engine_scenarios/persistent/overwrite_verify.cc, line 10 at r5](https://reviewable.io/reviews/pmem/pmemkv/883#-MRsvQvD2ZQ6Mdqzw0ch:-MRsvQvD2ZQ6Mdqzw0ci:b-quu7i3) ([raw file](https://github.com/pmem/pmemkv/blob/68b2cf9a18e8daae1a5e07f87bc48d2c7b675b29/tests/engine_scenarios/persistent/overwrite_verify.cc#L10)):*
> ```cpp
> static void insert(pmem::kv::db &kv)
> {
> 	std::string key = aligned_key("key1");
> ```

maybe, to be more consistent we could name this function key_from_string or something like this?

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/883)* status: all files reviewed, 1 unresolved discussion (waiting on @JanDorniak99)

___
*[tests/common/unittest.hpp, line 254 at r5](https://reviewable.io/reviews/pmem/pmemkv/883#-MRssVU675TtzRvd5pUj:-MRssVU675TtzRvd5pUk:b7lzc20) ([raw file](https://github.com/pmem/pmemkv/blob/68b2cf9a18e8daae1a5e07f87bc48d2c7b675b29/tests/common/unittest.hpp#L254)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
> /* It returns a key filled/shrank to a certain size. It's necessary during testing engines
>  * with fixed size keys */
> static inline std::string aligned_key(std::string str)
> {
> 	return str;
> }
> ```
</details>

I don't get it. It's just passthrough strings.

**Review by JanDorniak99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/883)* status: 4 of 10 files reviewed, 1 unresolved discussion (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[tests/common/unittest.hpp, line 254 at r5](https://reviewable.io/reviews/pmem/pmemkv/883#-MRssVU675TtzRvd5pUj:-MRsxHedAr6T3nyj7AJL:bth9yy7) ([raw file](https://github.com/pmem/pmemkv/blob/68b2cf9a18e8daae1a5e07f87bc48d2c7b675b29/tests/common/unittest.hpp#L254)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

> ```
> /* It returns a key filled/shrank to a certain size. It's necessary during testing engines
>  * with fixed size keys */
> static inline std::string aligned_key(std::string str)
> {
> 	return str;
> }
> ```
I don't get it. It's just passthrough strings.  
</blockquote></details>

For now yes, but when we will add engine with fixed size keys (robinhood) there will additionally be: if (currently_tested = "robinhood") str = align_to_size(str, 8);

**Review by karczex — COMMENTED** [review]
> Reviewed 3 of 10 files at r3, 5 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/883)* status: 4 of 10 files reviewed, 1 unresolved discussion (waiting on @igchor, @JanDorniak99, @karczex, and @lukaszstolarczuk)

___
*[tests/engine_scenarios/concurrent/put_get_remove_gen_params.cc, line 57 at r5](https://reviewable.io/reviews/pmem/pmemkv/883#-MRswjIkD9-ZjQXoK1fL:-MRswjIkD9-ZjQXoK1fM:b-1g7p30) ([raw file](https://github.com/pmem/pmemkv/blob/68b2cf9a18e8daae1a5e07f87bc48d2c7b675b29/tests/engine_scenarios/concurrent/put_get_remove_gen_params.cc#L57)):*
> ```
> 		std::string key = key_from_number(i, "in_");
> 		std::string val = key_from_number(i, "in_", "!");
> ```
This usage suggest, the name "key_from_number" is not the best :) 
Maybe something like str_from_number, or entry_from_number  would be better?

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/883)* status: 4 of 10 files reviewed, 2 unresolved discussions (waiting on @igchor, @JanDorniak99, @karczex, and @lukaszstolarczuk)

___
*[tests/common/unittest.hpp, line 185 at r6](https://reviewable.io/reviews/pmem/pmemkv/883#-MRt1M1v6XvDZA2cHv01:-MRt1M1v6XvDZA2cHv02:b-nb1ihk) ([raw file](https://github.com/pmem/pmemkv/blob/b43636153a41693268ec86281c2145bc0be1bc1f/tests/common/unittest.hpp#L185)):*
> ```cpp
> pmem::kv::db INITIALIZE_KV(std::string engine, pmem::kv::config &&config)
> {
> 	currently_tested = engine;
> ```

This variable is set but not used.

**Review by JanDorniak99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/883)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[tests/common/unittest.hpp, line 185 at r6](https://reviewable.io/reviews/pmem/pmemkv/883#-MRt1M1v6XvDZA2cHv01:-MRtoJhv0thxG1UYMUUZ:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/b43636153a41693268ec86281c2145bc0be1bc1f/tests/common/unittest.hpp#L185)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

This variable is set but not used. 
</blockquote></details>

Done.

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/883#-:-MRuA8n-BZh7MZCXB-eD:bnfp4nl)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @igchor, @karczex, and @lukaszstolarczuk)

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 10 of 10 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/883)* status: all files reviewed, 2 unresolved discussions (waiting on @JanDorniak99 and @karczex)

___
*[tests/common/unittest.hpp, line 248 at r7](https://reviewable.io/reviews/pmem/pmemkv/883#-MRu44X7ELKR199zILES:-MRu44X7ELKR199zILET:b-bmy4ho) ([raw file](https://github.com/pmem/pmemkv/blob/30407083a0797501c318e86b1103dd491b427739/tests/common/unittest.hpp#L248)):*
> ```cpp
> }
> 
> /* It returns a entry filled/shrank to a certain size. It's necessary during testing
> ```

an entry

**Review by JanDorniak99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/883)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

___
*[tests/common/unittest.hpp, line 248 at r7](https://reviewable.io/reviews/pmem/pmemkv/883#-MRu44X7ELKR199zILES:-MRyCoosB8zlDJBoUIYX:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/30407083a0797501c318e86b1103dd491b427739/tests/common/unittest.hpp#L248)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

an entry
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/883)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/883#-:-MRyISVH9Hd50HwrNFsd:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JanDorniak99)

**Pull request merged**
