### PR TITLE
fix memkind based engines to return appropiate status on kv.open()

### LINKED ISSUE #565: memkind-based engines returns UNKNOWN_ERROR for wrong path/size in config
vsmap and vsmap returns PMEMKV_STATUS_UNKNOWN_ERROR for wrong path in config instead of PMEMKV_STATUS_INVALID_ARGUMENT.  

Test:  https://github.com/pmem/pmemkv/pull/564/commits/26d3d628f39155f2c565ed4f7eee430251051fcb 
Log: [NonExistingPath.log](https://github.com/pmem/pmemkv/files/3997870/NonExistingPath.log)

### PR DESCRIPTION
**Pull request by JanDorniak99**
Fixes #565

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/992)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/992)* status: 1 of 6 files reviewed, 5 unresolved discussions (waiting on @JanDorniak99)

___
*[src/engines/vcmap.h, line 65 at r2](https://reviewable.io/reviews/pmem/pmemkv/992#-M_u5Tyk4XOYn29ieTBQ:-M_u5Tyk4XOYn29ieTBR:b-btwmd8) ([raw file](https://github.com/pmem/pmemkv/blob/753260aae688650f71806cfa98cfe0072a982bf3/src/engines/vcmap.h#L65)):*
> ```objc
> 		try {
> 			return std::unique_ptr<engine_base>(new vcmap(std::move(cfg)));
> 		} catch (std::invalid_argument &e) {
> ```

since this is `std::` can't we handle this in libpmemkv.cc (https://github.com/pmem/pmemkv/blob/master/src/libpmemkv.cc#L79) ?
___
*[tests/engine_scenarios/memkind/error_handling.cc, line 9 at r2](https://reviewable.io/reviews/pmem/pmemkv/992#-M_u54dADd3BwyeqlbSN:-M_u54dADd3BwyeqlbSO:b-44wcwb) ([raw file](https://github.com/pmem/pmemkv/blob/753260aae688650f71806cfa98cfe0072a982bf3/tests/engine_scenarios/memkind/error_handling.cc#L9)):*
> ```cpp
> 
> using namespace libmemkind::pmem;
> using namespace pmem;
> ```

do we need this using?
___
*[tests/engine_scenarios/memkind/error_handling.cc, line 17 at r2](https://reviewable.io/reviews/pmem/pmemkv/992#-M_u4u7rCI1EmPcaShTM:-M_u4u7rCI1EmPcaShTN:bglyqr) ([raw file](https://github.com/pmem/pmemkv/blob/753260aae688650f71806cfa98cfe0072a982bf3/tests/engine_scenarios/memkind/error_handling.cc#L17)):*
> ```cpp
> 	auto s = cfg.put_path(non_existent_path);
> 	ASSERT_STATUS(s, pmem::kv::status::OK);
> 	s = cfg.put_size(83886080);
> ```

and perhaps we should test for "little" size...? (not sure if memkind has a min. size value)
are there any other possibilities to throw "invalid_argument" by memkind?
___
*[tests/engine_scenarios/memkind/error_handling.cc, line 21 at r2](https://reviewable.io/reviews/pmem/pmemkv/992#-M_u4EIhCqvdv34RJu7r:-M_u4EIhCqvdv34RJu7s:b-u2266z) ([raw file](https://github.com/pmem/pmemkv/blob/753260aae688650f71806cfa98cfe0072a982bf3/tests/engine_scenarios/memkind/error_handling.cc#L21)):*
> ```cpp
> 
> 	pmem::kv::db kv;
> 	/* Not-existent path supplied */
> ```

`Non-`
___
*[tests/engine_scenarios/memkind/error_handling.cc, line 27 at r2](https://reviewable.io/reviews/pmem/pmemkv/992#-M_u4fWr8uGvOrlSsvKe:-M_u4fWr8uGvOrlSsvKf:b-uyfqww) ([raw file](https://github.com/pmem/pmemkv/blob/753260aae688650f71806cfa98cfe0072a982bf3/tests/engine_scenarios/memkind/error_handling.cc#L27)):*
> ```cpp
> 	XXX: Remove that when we won't support memkind < 1.12 */
> 	try {
> 		auto alloc = allocator<int>(non_existent_path, 100000000);
> ```

do we need this allocator? shouldn't `open` throw the error?

**Review by JanDorniak99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/992)* status: 1 of 8 files reviewed, 5 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[src/engines/vcmap.h, line 65 at r2](https://reviewable.io/reviews/pmem/pmemkv/992#-M_u5Tyk4XOYn29ieTBQ:-M_yNayD3Qc1kCNmZI6o:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/753260aae688650f71806cfa98cfe0072a982bf3/src/engines/vcmap.h#L65)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

since this is `std::` can't we handle this in libpmemkv.cc (https://github.com/pmem/pmemkv/blob/master/src/libpmemkv.cc#L79) ?
</blockquote></details>

Done.
___
*[tests/engine_scenarios/memkind/error_handling.cc, line 9 at r2](https://reviewable.io/reviews/pmem/pmemkv/992#-M_u54dADd3BwyeqlbSN:-M_yU1zaCep-EAPnVM0o:b-ada44i) ([raw file](https://github.com/pmem/pmemkv/blob/753260aae688650f71806cfa98cfe0072a982bf3/tests/engine_scenarios/memkind/error_handling.cc#L9)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

do we need this using?
</blockquote></details>

I think yes because in older memkind's versions (1.8?) namespace is pmem, and in newer versions is libmemkind::pmem. With these usings, it works for both versions.
___
*[tests/engine_scenarios/memkind/error_handling.cc, line 17 at r2](https://reviewable.io/reviews/pmem/pmemkv/992#-M_u4u7rCI1EmPcaShTM:-M_ydkMFEwCnsizB7OaL:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/753260aae688650f71806cfa98cfe0072a982bf3/tests/engine_scenarios/memkind/error_handling.cc#L17)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

and perhaps we should test for "little" size...? (not sure if memkind has a min. size value)
are there any other possibilities to throw "invalid_argument" by memkind?
</blockquote></details>

Done.
___
*[tests/engine_scenarios/memkind/error_handling.cc, line 21 at r2](https://reviewable.io/reviews/pmem/pmemkv/992#-M_u4EIhCqvdv34RJu7r:-M_yPSwR1QSypQtakYTI:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/753260aae688650f71806cfa98cfe0072a982bf3/tests/engine_scenarios/memkind/error_handling.cc#L21)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`Non-`
</blockquote></details>

Done.
___
*[tests/engine_scenarios/memkind/error_handling.cc, line 27 at r2](https://reviewable.io/reviews/pmem/pmemkv/992#-M_u4fWr8uGvOrlSsvKe:-M_yPeZRB_pL2EibhUVU:b-eqcso8) ([raw file](https://github.com/pmem/pmemkv/blob/753260aae688650f71806cfa98cfe0072a982bf3/tests/engine_scenarios/memkind/error_handling.cc#L27)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

do we need this allocator? shouldn't `open` throw the error?
</blockquote></details>

It is done to check if memkind already is with changed error handling. Thanks to that, we can assert if the status returned from the pmemkv is appropriate.

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/992)* status: 1 of 9 files reviewed, 6 unresolved discussions (waiting on @JanDorniak99 and @lukaszstolarczuk)

___
*[tests/engine_scenarios/memkind/error_handling.cc, line 8 at r2](https://reviewable.io/reviews/pmem/pmemkv/992#-M_tnmzV56jqqIezsXjp:-M_tnmzV56jqqIezsXjq:baiw0rj) ([raw file](https://github.com/pmem/pmemkv/blob/753260aae688650f71806cfa98cfe0072a982bf3/tests/engine_scenarios/memkind/error_handling.cc#L8)):*
> ```cpp
> #include "pmem_allocator.h"
> 
> using namespace libmemkind::pmem;
> ```

It would be little bit more readable if you use libmmekind::pmem explicitly instead of polluting code with mixed namespeaces.

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/992)* status: 1 of 9 files reviewed, 6 unresolved discussions (waiting on @JanDorniak99 and @lukaszstolarczuk)

___
*[tests/engine_scenarios/memkind/error_handling.cc, line 27 at r2](https://reviewable.io/reviews/pmem/pmemkv/992#-M_u4fWr8uGvOrlSsvKe:-M_yrXbb8ZXVtNDbUFm7:b-uik5go) ([raw file](https://github.com/pmem/pmemkv/blob/753260aae688650f71806cfa98cfe0072a982bf3/tests/engine_scenarios/memkind/error_handling.cc#L27)):*
<details><summary><i>Previously, JanDorniak99 (Jan Dorniak) wrote…</i></summary><blockquote>

It is done to check if memkind already is with changed error handling. Thanks to that, we can assert if the status returned from the pmemkv is appropriate.
</blockquote></details>

pmemkv is supposed to work with different vesrions of memkind, so it's probably the easiest way to test it. We may remove this code when we change minimum version of dependency (and obviously no one will remember to do this).

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 2 of 5 files at r2, 3 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/992)* status: 6 of 9 files reviewed, 5 unresolved discussions (waiting on @JanDorniak99 and @karczex)

___
*[tests/CMakeLists.txt, line 205 at r3](https://reviewable.io/reviews/pmem/pmemkv/992#-M_ypcZO8UZ4B9TG_E53:-M_ypcZO8UZ4B9TG_E54:bnaes0h) ([raw file](https://github.com/pmem/pmemkv/blob/ebc74bcb02d09e769fe1ab839799134dac38d8e9/tests/CMakeLists.txt#L205)):*
> ```CMake
> 
> # Tests for memkind engines
> if (ENGINE_VCMAP OR ENGINE_VSMAP)
> ```

actually, I believe we don't require this `if`. If there's no memkind library found it will just add an empty string to the list (in the `build_test_ext` function). It may be easily forgotten when we add a new memkind-based engine.
___
*[tests/ctest_helpers.cmake, line 132 at r3](https://reviewable.io/reviews/pmem/pmemkv/992#-M_yqLAWB8SWejrtyVC5:-M_yqLAWB8SWejrtyVC6:b-cfkgri) ([raw file](https://github.com/pmem/pmemkv/blob/ebc74bcb02d09e769fe1ab839799134dac38d8e9/tests/ctest_helpers.cmake#L132)):*
> ```CMake
> 
> # Function to build test with custom build options (e.g. passing defines),
> # link it with custom library/-ies (supports 'json', 'libpmemobj_cpp' and
> ```

this "supports" part of the comment will become outdated quickly (like right now :D ) - please, perhaps, remove the whole sentence in the `()`
___
*[tests/engine_scenarios/memkind/error_handling.cc, line 8 at r2](https://reviewable.io/reviews/pmem/pmemkv/992#-M_tnmzV56jqqIezsXjp:-M_yrws62ML0cV5WMzgd:bbhyxgw) ([raw file](https://github.com/pmem/pmemkv/blob/753260aae688650f71806cfa98cfe0072a982bf3/tests/engine_scenarios/memkind/error_handling.cc#L8)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

It would be little bit more readable if you use libmmekind::pmem explicitly instead of polluting code with mixed namespeaces.  
</blockquote></details>

see comment below ;)
___
*[tests/engine_scenarios/memkind/error_handling.cc, line 9 at r2](https://reviewable.io/reviews/pmem/pmemkv/992#-M_u54dADd3BwyeqlbSN:-M_yqsirElmZITgXhdLU:b5i53fj) ([raw file](https://github.com/pmem/pmemkv/blob/753260aae688650f71806cfa98cfe0072a982bf3/tests/engine_scenarios/memkind/error_handling.cc#L9)):*
<details><summary><i>Previously, JanDorniak99 (Jan Dorniak) wrote…</i></summary><blockquote>

I think yes because in older memkind's versions (1.8?) namespace is pmem, and in newer versions is libmemkind::pmem. With these usings, it works for both versions.
</blockquote></details>

ok, it makes sense. You can consider, though, using `USE_LIBMEMKIND_NAMESPACE` definition (we have in the project).
___
*[tests/engine_scenarios/memkind/error_handling.cc, line 27 at r2](https://reviewable.io/reviews/pmem/pmemkv/992#-M_u4fWr8uGvOrlSsvKe:-M_yrpK22YAPzntZqOXh:bf2rcvu) ([raw file](https://github.com/pmem/pmemkv/blob/753260aae688650f71806cfa98cfe0072a982bf3/tests/engine_scenarios/memkind/error_handling.cc#L27)):*
<details><summary><i>Previously, JanDorniak99 (Jan Dorniak) wrote…</i></summary><blockquote>

It is done to check if memkind already is with changed error handling. Thanks to that, we can assert if the status returned from the pmemkv is appropriate.
</blockquote></details>

och, ok, great
___
*[tests/engine_scenarios/memkind/error_handling.cc, line 79 at r3](https://reviewable.io/reviews/pmem/pmemkv/992#-M_yrTE_2dKHol8xYzfQ:-M_yrTE_2dKHol8xYzfR:btx6e3f) ([raw file](https://github.com/pmem/pmemkv/blob/ebc74bcb02d09e769fe1ab839799134dac38d8e9/tests/engine_scenarios/memkind/error_handling.cc#L79)):*
> ```cpp
> {
> 	if (argc < 2)
> 		UT_FATAL("usage: %s engine non_existent_path", argv[0]);
> ```

if you believe we need the extra param (with proper path) please update this.
You can also consider only passing the proper path and extend it here e.g. with some (non-existing) suffix.

**Review by JanDorniak99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/992)* status: 5 of 9 files reviewed, 4 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

___
*[tests/CMakeLists.txt, line 205 at r3](https://reviewable.io/reviews/pmem/pmemkv/992#-M_ypcZO8UZ4B9TG_E53:-M_yw5rmBsxevnC3hkqd:by6u9p) ([raw file](https://github.com/pmem/pmemkv/blob/ebc74bcb02d09e769fe1ab839799134dac38d8e9/tests/CMakeLists.txt#L205)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

actually, I believe we don't require this `if`. If there's no memkind library found it will just add an empty string to the list (in the `build_test_ext` function). It may be easily forgotten when we add a new memkind-based engine.
</blockquote></details>

Without this, it was failing on CI: https://github.com/pmem/pmemkv/runs/2575565704?check_suite_focus=true#step:5:2630
___
*[tests/ctest_helpers.cmake, line 132 at r3](https://reviewable.io/reviews/pmem/pmemkv/992#-M_yqLAWB8SWejrtyVC5:-M_yv2eR1O6yKJXxwhck:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/ebc74bcb02d09e769fe1ab839799134dac38d8e9/tests/ctest_helpers.cmake#L132)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

this "supports" part of the comment will become outdated quickly (like right now :D ) - please, perhaps, remove the whole sentence in the `()`
</blockquote></details>

Done.
___
*[tests/engine_scenarios/memkind/error_handling.cc, line 79 at r3](https://reviewable.io/reviews/pmem/pmemkv/992#-M_yrTE_2dKHol8xYzfQ:-M_yvPDu8KUrAT2ZuzY-:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/ebc74bcb02d09e769fe1ab839799134dac38d8e9/tests/engine_scenarios/memkind/error_handling.cc#L79)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

if you believe we need the extra param (with proper path) please update this.
You can also consider only passing the proper path and extend it here e.g. with some (non-existing) suffix.
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 3 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/992)* status: 8 of 9 files reviewed, 5 unresolved discussions (waiting on @JanDorniak99, @karczex, and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/992#-M_z-sAK1rg9rORnF-DA:-M_z-sAK1rg9rORnF-DB:b6ru0jz) (no related file):*
`appropiate` -> `appropriate` in commit msg 

---
___
*[utils/docker/images/install-memkind.sh, line 12 at r4](https://reviewable.io/reviews/pmem/pmemkv/992#-M_z1qTqByV6TW3_xq1K:-M_z1qTqByV6TW3_xq1L:b5xnt2l) ([raw file](https://github.com/pmem/pmemkv/blob/54ecd7d3e9f91a5e64394a9dc5713f7893ca7def/utils/docker/images/install-memkind.sh#L12)):*
> ```Shell
> set -e
> 
> # contains better error handling in pmem_allocator
> ```

I just realized we don't use this script in any images (on regular CI), pls make sure you've tested it with new and old memkind

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/992)* status: all files reviewed, 4 unresolved discussions (waiting on @JanDorniak99, @karczex, and @lukaszstolarczuk)

___
*[tests/CMakeLists.txt, line 205 at r3](https://reviewable.io/reviews/pmem/pmemkv/992#-M_ypcZO8UZ4B9TG_E53:-M_z2K0jDr-tfF1mKvx8:b-kdc1ea) ([raw file](https://github.com/pmem/pmemkv/blob/ebc74bcb02d09e769fe1ab839799134dac38d8e9/tests/CMakeLists.txt#L205)):*
<details><summary><i>Previously, JanDorniak99 (Jan Dorniak) wrote…</i></summary><blockquote>

Without this, it was failing on CI: https://github.com/pmem/pmemkv/runs/2575565704?check_suite_focus=true#step:5:2630
</blockquote></details>

och, right, mea culpa, we build these tests even when we don't run them

**Review by JanDorniak99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/992)* status: all files reviewed, 4 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/992#-M_z-sAK1rg9rORnF-DA:-M_z6YhI-3GplZHtAkoV:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`appropiate` -> `appropriate` in commit msg 
</blockquote></details>

Done.

---
___
*[utils/docker/images/install-memkind.sh, line 12 at r4](https://reviewable.io/reviews/pmem/pmemkv/992#-M_z1qTqByV6TW3_xq1K:-M_z6bcz775Dyf_AyRTT:bt5p72o) ([raw file](https://github.com/pmem/pmemkv/blob/54ecd7d3e9f91a5e64394a9dc5713f7893ca7def/utils/docker/images/install-memkind.sh#L12)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I just realized we don't use this script in any images (on regular CI), pls make sure you've tested it with new and old memkind
</blockquote></details>

It seems to be ok (tested on our ubuntu20.04 docker image with both versions)

**Review by KFilipek — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 5 files at r2, 1 of 6 files at r3, 2 of 4 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/992)* status: all files reviewed, 4 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

___
*[tests/engine_scenarios/memkind/error_handling.cc, line 9 at r2](https://reviewable.io/reviews/pmem/pmemkv/992#-M_u54dADd3BwyeqlbSN:-M_zG-YwAfmke8n6Cs-3:bnuykcz) ([raw file](https://github.com/pmem/pmemkv/blob/753260aae688650f71806cfa98cfe0072a982bf3/tests/engine_scenarios/memkind/error_handling.cc#L9)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

ok, it makes sense. You can consider, though, using `USE_LIBMEMKIND_NAMESPACE` definition (we have in the project).
</blockquote></details>

`using libmemkind::pmem;` don't works?
Just asking.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/992#-:-Ma8BbT1EHpXUc1CZkea:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/992)* status: all files reviewed, 2 unresolved discussions (waiting on @JanDorniak99 and @karczex)

___
*[utils/docker/images/install-memkind.sh, line 13 at r6](https://reviewable.io/reviews/pmem/pmemkv/992#-Ma8jijODA3gFtZ497E8:-Ma8jijODA3gFtZ497E9:b1wywjm) ([raw file](https://github.com/pmem/pmemkv/blob/3ff43405a9d5bc63615e2a449bd44bbd4b1e1719/utils/docker/images/install-memkind.sh#L13)):*
> ```Shell
> 
> # contains better error handling in pmem_allocator
> MEMKIND_VERSION=64a37d4ca46a8a2419871e859d611fff85d0e843
> ```

Shouldn;t we have regular tests 1.11? Maybe we can have 1.11 in our regular OSes and version from master in Other_OS?

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/992)* status: all files reviewed, 2 unresolved discussions (waiting on @igchor, @JanDorniak99, and @karczex)

___
*[utils/docker/images/install-memkind.sh, line 13 at r6](https://reviewable.io/reviews/pmem/pmemkv/992#-Ma8jijODA3gFtZ497E8:-Ma8kvzHDScBQ0p6zlBN:b-b1lpa4) ([raw file](https://github.com/pmem/pmemkv/blob/3ff43405a9d5bc63615e2a449bd44bbd4b1e1719/utils/docker/images/install-memkind.sh#L13)):*
<details><summary><i>Previously, JanDorniak99 (Jan Dorniak) wrote…</i></summary><blockquote>

Actually, we use this script only in other OSes. In regular tests we install memkind via e.g. apt get-install libmemkind-dev on Ubuntu
</blockquote></details>

I think we should rely on a stable Memkind version and we test the "unstable" (newest) one in Centos8, ArchLinux-base, and Ubuntu18.04... and I think it's ok.

Nonetheless, if we decide to change this, I guess it shouldn't be done in this PR ;)

**Review by KFilipek — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/992#-:-Ma901_rCorUJuBm84Mz:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @igchor, @JanDorniak99, and @karczex)

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/992#-:-MaD1T5z1SJlfCwLrw-v:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor and @JanDorniak99)

**Pull request merged**
