### PR TITLE
Update CMake files

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
the most important changes:
- cleanup top-level and tests' CMake files, especially with sub-sections delimiters,
- add check in examples dir to build any example,
- simplify doc's CMake.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/872)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/872)* status: 0 of 14 files reviewed, 3 unresolved discussions

___
*[doc/CMakeLists.txt, line 124 at r1](https://reviewable.io/reviews/pmem/pmemkv/872#-MPjE1Ra2ME9iuuNHhdL:-MPjE1Ra2ME9iuuNHhdM:b-a4lpng) ([raw file](https://github.com/pmem/pmemkv/blob/f59cf15132595274648ddfbc44d1848ce51b0d06/doc/CMakeLists.txt#L124)):*
> ```CMake
> 		WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR})
> else()
> 	message(WARNING "Neither C or C++ docs could be built. "
> ```

should we fail or warn...? I think it could fail, because it can be easily disabled by cmake option... but on the other hand BUILD_DOC and BUILD_EXAMPLES are enabled by default...
___
*[examples/CMakeLists.txt, line 108 at r1](https://reviewable.io/reviews/pmem/pmemkv/872#-MPjE5z6DB7_j6mEBKrU:-MPjE5z6DB7_j6mEBKrV:byb1a58) ([raw file](https://github.com/pmem/pmemkv/blob/f59cf15132595274648ddfbc44d1848ce51b0d06/examples/CMakeLists.txt#L108)):*
> ```CMake
> 
> if(NOT ENGINE_CMAP AND NOT ENGINE_CSMAP AND NOT ENGINE_RADIX)
> 	message(WARNING "None of engines required for examples was enabled, "
> ```

should we fail or warn...?
___
*[tests/ctest_helpers.cmake, line 315 at r1](https://reviewable.io/reviews/pmem/pmemkv/872#-MPjEBCqAPgEKjgolOzH:-MPjEBCqAPgEKjgolOzI:b-37ytaa) ([raw file](https://github.com/pmem/pmemkv/blob/f59cf15132595274648ddfbc44d1848ce51b0d06/tests/ctest_helpers.cmake#L315)):*
> ```CMake
> 		# (value for nproc=256 minus 2 bytes).
> 		# Can be overwritten in CMake cache using build param: -DTEST_DB_SIZE_THRESHOLD=<size>
> 		set(TEST_DB_SIZE_THRESHOLD 2147483646 CACHE STRING "Limit calculated size of the TEST_DB_SIZE for some of the memkind tests")
> ```

this check was requested in some old PR's review (by @kfilipek ). I'm wondering if we should have such DB_SIZE (or some threshold) variable set up globally, for all tests, not just for this, *jmalloc* calculation. I personally think it's ok like this.

**Review by karczex — COMMENTED** [review]
> Reviewed 10 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/872)* status: 10 of 14 files reviewed, 6 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[CMakeLists.txt, line 45 at r1](https://reviewable.io/reviews/pmem/pmemkv/872#-MPoXCUJ88X4XAdihilI:-MPoXCUJ88X4XAdihilJ:bbk9bt2) ([raw file](https://github.com/pmem/pmemkv/blob/f59cf15132595274648ddfbc44d1848ce51b0d06/CMakeLists.txt#L45)):*
> ```CMake
> set(PMEMKV_ROOT_DIR ${CMAKE_CURRENT_SOURCE_DIR})
> 
> include(cmake/helpers.cmake)
> ```

I would rather left includes at the beginning of files.
___
*[CMakeLists.txt, line 49 at r1](https://reviewable.io/reviews/pmem/pmemkv/872#-MPoXp7xC7v507wVFW7m:-MPoXp7xC7v507wVFW7n:b8wcl11) ([raw file](https://github.com/pmem/pmemkv/blob/f59cf15132595274648ddfbc44d1848ce51b0d06/CMakeLists.txt#L49)):*
> ```CMake
> 
> # Specify and print the build type
> if(EXISTS "${PMEMKV_ROOT_DIR}/.git")
> ```

Please add some comment, as it's not obvious (and little bit tricky), why you set different defaults  accordingly to existence of .git directory 
___
*[cmake/packages.cmake, line 38 at r1](https://reviewable.io/reviews/pmem/pmemkv/872#-MPoasTo4PB25W6zeADA:-MPoasTo4PB25W6zeADB:bl3kprn) ([raw file](https://github.com/pmem/pmemkv/blob/f59cf15132595274648ddfbc44d1848ce51b0d06/cmake/packages.cmake#L38)):*
> ```CMake
> set(CPACK_PACKAGE_VERSION_MAJOR ${VERSION_MAJOR})
> set(CPACK_PACKAGE_VERSION_MINOR ${VERSION_MINOR})
> #set(CPACK_PACKAGE_VERSION_PATCH ${VERSION_PATCH})
> ```

Why it's commented? 
___
*[doc/CMakeLists.txt, line 124 at r1](https://reviewable.io/reviews/pmem/pmemkv/872#-MPjE1Ra2ME9iuuNHhdL:-MPoblkd6auiLSJAo41d:b-s2p52j) ([raw file](https://github.com/pmem/pmemkv/blob/f59cf15132595274648ddfbc44d1848ce51b0d06/doc/CMakeLists.txt#L124)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

should we fail or warn...? I think it could fail, because it can be easily disabled by cmake option... but on the other hand BUILD_DOC and BUILD_EXAMPLES are enabled by default...
</blockquote></details>

We should not fail build for such trivial problem. If you want to fail build (which is OK), building docs shouldn't be default. 

In general, disabling default building of docs may speed up development if someone (like me) do a lot of builds with default parameters. 
___
*[examples/CMakeLists.txt, line 108 at r1](https://reviewable.io/reviews/pmem/pmemkv/872#-MPjE5z6DB7_j6mEBKrU:-MPodwSA-H377DZyTMYM:b-ps2jqo) ([raw file](https://github.com/pmem/pmemkv/blob/f59cf15132595274648ddfbc44d1848ce51b0d06/examples/CMakeLists.txt#L108)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

should we fail or warn...?
</blockquote></details>

probably warn. 
___
*[tests/ctest_helpers.cmake, line 315 at r1](https://reviewable.io/reviews/pmem/pmemkv/872#-MPjEBCqAPgEKjgolOzH:-MPofCrh0Pp_rFZBtwok:b-k1eet0) ([raw file](https://github.com/pmem/pmemkv/blob/f59cf15132595274648ddfbc44d1848ce51b0d06/tests/ctest_helpers.cmake#L315)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

this check was requested in some old PR's review (by @kfilipek ). I'm wondering if we should have such DB_SIZE (or some threshold) variable set up globally, for all tests, not just for this, *jmalloc* calculation. I personally think it's ok like this.
</blockquote></details>

I think we may left it as is, and add more non numeric options if needed.

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/872)* status: 10 of 14 files reviewed, 5 unresolved discussions (waiting on @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[CMakeLists.txt, line 45 at r1](https://reviewable.io/reviews/pmem/pmemkv/872#-MPoXCUJ88X4XAdihilI:-MPtIJCZ-DbqH3USAja6:bfddemg) ([raw file](https://github.com/pmem/pmemkv/blob/f59cf15132595274648ddfbc44d1848ce51b0d06/CMakeLists.txt#L45)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

I would rather left includes at the beginning of files.
</blockquote></details>

yeeaah... me too, but some of the functions in the helpers class require `PMEMKV_ROOT_DIR` to be set, and also we use one function right below (`set_version`). In general I'd put this include along with others (see section `## Setup environment` below), but it has to be next to this set_version.
As an alternative - we can move this include with the set_version call to the mentioned section below or move ROOT_DIR to the top of the file.
___
*[CMakeLists.txt, line 49 at r1](https://reviewable.io/reviews/pmem/pmemkv/872#-MPoXp7xC7v507wVFW7m:-MPtJlKeEeL2iqB9lrIC:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/f59cf15132595274648ddfbc44d1848ce51b0d06/CMakeLists.txt#L49)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Please add some comment, as it's not obvious (and little bit tricky), why you set different defaults  accordingly to existence of .git directory 
</blockquote></details>

Done.
___
*[cmake/packages.cmake, line 38 at r1](https://reviewable.io/reviews/pmem/pmemkv/872#-MPoasTo4PB25W6zeADA:-MPtJo9y-di-wSRJEy4s:bewrxk) ([raw file](https://github.com/pmem/pmemkv/blob/f59cf15132595274648ddfbc44d1848ce51b0d06/cmake/packages.cmake#L38)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Why it's commented? 
</blockquote></details>

tbh, I copied this approach from libpmemobj-cpp, and am not sure if we want to use this var or not...
___
*[doc/CMakeLists.txt, line 124 at r1](https://reviewable.io/reviews/pmem/pmemkv/872#-MPjE1Ra2ME9iuuNHhdL:-MPtKgQi59mMKt3KJEXC:b5pcp87) ([raw file](https://github.com/pmem/pmemkv/blob/f59cf15132595274648ddfbc44d1848ce51b0d06/doc/CMakeLists.txt#L124)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

We should not fail build for such trivial problem. If you want to fail build (which is OK), building docs shouldn't be default. 

In general, disabling default building of docs may speed up development if someone (like me) do a lot of builds with default parameters. 
</blockquote></details>

ok, warning it is. The discussion about disabling examples/docs build by default is totally different conversation ;) and tbh I don't have an opinion - since we use ccache it builds on my machine quite quickly.

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/872)* status: 10 of 14 files reviewed, 3 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[CMakeLists.txt, line 45 at r1](https://reviewable.io/reviews/pmem/pmemkv/872#-MPoXCUJ88X4XAdihilI:-MQupWr--0kGAgNEPRWv:b-mq73ax) ([raw file](https://github.com/pmem/pmemkv/blob/f59cf15132595274648ddfbc44d1848ce51b0d06/CMakeLists.txt#L45)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

yeeaah... me too, but some of the functions in the helpers class require `PMEMKV_ROOT_DIR` to be set, and also we use one function right below (`set_version`). In general I'd put this include along with others (see section `## Setup environment` below), but it has to be next to this set_version.
As an alternative - we can move this include with the set_version call to the mentioned section below or move ROOT_DIR to the top of the file.
</blockquote></details>

Moving ROOT_DIR to the top will be OK

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/872)* status: 8 of 14 files reviewed, 3 unresolved discussions (waiting on @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[CMakeLists.txt, line 45 at r1](https://reviewable.io/reviews/pmem/pmemkv/872#-MPoXCUJ88X4XAdihilI:-MQvAmx319ZgrUU7qiXP:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/f59cf15132595274648ddfbc44d1848ce51b0d06/CMakeLists.txt#L45)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Moving ROOT_DIR to the top will be OK
</blockquote></details>

Done.

**Review by KFilipek — COMMENTED** [review]
> Reviewed 1 of 14 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/872)* status: 12 of 14 files reviewed, 4 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

___
*[cmake/packages.cmake, line 38 at r2](https://reviewable.io/reviews/pmem/pmemkv/872#-MQvzf1x2d7-tax5vY5t:-MQvzf1x2d7-tax5vY5u:b-qrx79m) ([raw file](https://github.com/pmem/pmemkv/blob/072b7668fcd3fecf5d107d23f75dea3a8f1bc878/cmake/packages.cmake#L38)):*
> ```CMake
> set(CPACK_PACKAGE_VERSION_MAJOR ${VERSION_MAJOR})
> set(CPACK_PACKAGE_VERSION_MINOR ${VERSION_MINOR})
> #set(CPACK_PACKAGE_VERSION_PATCH ${VERSION_PATCH})
> ```

remove if not necessary

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/872)* status: 12 of 14 files reviewed, 4 unresolved discussions (waiting on @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[cmake/packages.cmake, line 38 at r2](https://reviewable.io/reviews/pmem/pmemkv/872#-MQvzf1x2d7-tax5vY5t:-MQw7uP3-UKHsEQjAFYb:b-7low08) ([raw file](https://github.com/pmem/pmemkv/blob/072b7668fcd3fecf5d107d23f75dea3a8f1bc878/cmake/packages.cmake#L38)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

remove if not necessary
</blockquote></details>

you guys tell me if we want to use it or not (I copy-pasted it from libpmemobj-cpp, but it's also not used there) ;)

I'm not sure if this "PATCH" variable provides any value...

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/872#-:-MR-hYOkDmODmPpZaMkv:bnfp4nl)* status: 12 of 14 files reviewed, 4 unresolved discussions (waiting on @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[examples/CMakeLists.txt, line 108 at r1](https://reviewable.io/reviews/pmem/pmemkv/872#-MPjE5z6DB7_j6mEBKrU:-MR-hRlr8QAvE6ersYyv:b-9bjit0) ([raw file](https://github.com/pmem/pmemkv/blob/f59cf15132595274648ddfbc44d1848ce51b0d06/examples/CMakeLists.txt#L108)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

probably warn. 
</blockquote></details>

yes, warn is fine

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/872)* status: 12 of 14 files reviewed, 2 unresolved discussions (waiting on @karczex and @KFilipek)

___
*[cmake/packages.cmake, line 38 at r2](https://reviewable.io/reviews/pmem/pmemkv/872#-MQvzf1x2d7-tax5vY5t:-MR-pUsYABSfcW9SycPT:b4x4h6o) ([raw file](https://github.com/pmem/pmemkv/blob/072b7668fcd3fecf5d107d23f75dea3a8f1bc878/cmake/packages.cmake#L38)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you guys tell me if we want to use it or not (I copy-pasted it from libpmemobj-cpp, but it's also not used there) ;)

I'm not sure if this "PATCH" variable provides any value...
</blockquote></details>

actually, after some thinking, I removed it. Done.

**Review by KFilipek — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 14 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/872#-:-MR005bLACuHT2c4kzXq:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)

**Review by karczex — COMMENTED** [review]
> Reviewed 1 of 14 files at r1, 3 of 4 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/872)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/872#-:-MR07bum5Qq0Lkwq8Q5V:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Pull request merged**
