### PR TITLE
Update dockers

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
// all OSes build preview: https://github.com/lukaszstolarczuk/pmemkv/runs/2971957885?check_suite_focus=true
// (opensuse failed for random reason...?)

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/991)

### CODE REVIEW

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/991#-:-M_yn9cf3VqSh-cg49HG:bnfp4nl)* status: 0 of 24 files reviewed, all discussions resolved

**Review by KFilipek — COMMENTED** [review]
:lgtm:

> Reviewed 24 of 24 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/991#-:-M_ypANJ1741784TwczN:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Review by lukaszstolarczuk — COMMENTED** [review]
after @karczex's review (in https://github.com/pmem/libpmemobj-cpp/pull/1073) I've added minor updates here

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/991#-:-Ma-7GcuBLKR9DaLixHm:b-p57fs2)* status: 14 of 24 files reviewed, all discussions resolved (waiting on @KFilipek)

**Review by KFilipek — COMMENTED** [review]
> Reviewed 15 of 15 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/991)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Comment by lukaszstolarczuk** [comment]
I've bumped PMDK and pmemkv-java to the newest versions.

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/991#-:-MdpW6_YDvu47DLiBwZX:bnfp4nl)* status: 20 of 24 files reviewed, 1 unresolved discussion (waiting on @KFilipek and @lukaszstolarczuk)

___
*[utils/docker/images/Dockerfile.ubuntu-20.04_bindings, line 12 at r5](https://reviewable.io/reviews/pmem/pmemkv/991#-MdpVWSh4-pRZK8sS0wa:-MdpVWSh4-pRZK8sS0wb:bb0ckjv) ([raw file](https://github.com/pmem/pmemkv/blob/f8e935646381eee4bbed178e79ffb79e807a3cc0/utils/docker/images/Dockerfile.ubuntu-20.04_bindings#L12)):*
> ```
> 
> # Pull base image
> FROM registry.hub.docker.com/library/ubuntu:20.04
> ```

I wonder if it's possible to build this image on top of pmemkv one.

**Review by KFilipek — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/991)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

**Pull request merged**
