### PR TITLE
doc: change maintainer contact info

### PR DESCRIPTION
**Pull request by igchor**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/903)

### CODE REVIEW

**Review by JanDorniak99 — COMMENTED** [review]
> Reviewed 16 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/903)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm: , but 2021 ;)

> Reviewed 16 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/903#-:-MSgRSlUCve6bapn9fW6:b-i5buxd)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)

___
*[utils/docker/images/Dockerfile.archlinux-base-latest, line 2 at r1](https://reviewable.io/reviews/pmem/pmemkv/903#-MSgREPs6FF18dY7nnF0:-MSgREPs6FF18dY7nnF1:b3kqx) ([raw file](https://github.com/pmem/pmemkv/blob/3e4e10683ef5065cdc9359965a161570cf06b291/utils/docker/images/Dockerfile.archlinux-base-latest#L2)):*
> ```
> # SPDX-License-Identifier: BSD-3-Clause
> # Copyright 2016-2020, Intel Corporation
> ```

.

**Review by KFilipek — COMMENTED** [review]
> Reviewed 15 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/903)* status: all files reviewed, 2 unresolved discussions (waiting on @igchor)

___
*[utils/docker/images/Dockerfile.debian-testing, line 2 at r1](https://reviewable.io/reviews/pmem/pmemkv/903#-MSgXwQc1Wsr3HEVf5HZ:-MSgXwQd9pGqdhQ6XBoY:b-v2nkgd) ([raw file](https://github.com/pmem/pmemkv/blob/3e4e10683ef5065cdc9359965a161570cf06b291/utils/docker/images/Dockerfile.debian-testing#L2)):*
> ```
> # SPDX-License-Identifier: BSD-3-Clause
> # Copyright 2016-2020, Intel Corporation
> ```

2021 and other occurences

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/903)* status: all files reviewed, 2 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[utils/docker/images/Dockerfile.archlinux-base-latest, line 2 at r1](https://reviewable.io/reviews/pmem/pmemkv/903#-MSgREPs6FF18dY7nnF0:-MSlHHcK6ccf-0-AoJzZ:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/3e4e10683ef5065cdc9359965a161570cf06b291/utils/docker/images/Dockerfile.archlinux-base-latest#L2)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[utils/docker/images/Dockerfile.debian-testing, line 2 at r1](https://reviewable.io/reviews/pmem/pmemkv/903#-MSgXwQc1Wsr3HEVf5HZ:-MSlHHvt0GiGbVAPWQlI:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/3e4e10683ef5065cdc9359965a161570cf06b291/utils/docker/images/Dockerfile.debian-testing#L2)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

2021 and other occurences
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 13 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/903)* status: all files reviewed, 1 unresolved discussion (waiting on @KFilipek)

**Review by KFilipek — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/903#-:-MSlK7oP1ujMZ_aHX0tg:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Pull request merged**
