### PR TITLE
Extend compatibility test

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/740)

### CODE REVIEW

**Comment by karczex** [comment]
___
*[utils/docker/run-compatibility.sh, line 23 at r1](https://reviewable.io/reviews/pmem/pmemkv/740#-MF0abRj5qgseeVntEy8:-MF0abRk9Nggs2flTXF7:bb9qihn) ([raw file](https://github.com/pmem/pmemkv/blob/a25b4187a96c80cd2a95b91a61422f7c5948fe87/utils/docker/run-compatibility.sh#L23)):*
> ```Shell
> 	cd $WORKDIR/build
> 
> 	git clone https://github.com/pmem/pmemkv pmemkv-${version}
> ```

You don't need to clone repo every time - just checkout to proper version and install (if you do not trust `make clean` you may remove build directory every time).

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/740)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[utils/docker/run-compatibility.sh, line 32 at r2](https://reviewable.io/reviews/pmem/pmemkv/740#-MFBEn-sDxsUNXQ5UGCv:-MFBEn-sDxsUNXQ5UGCw:bukw4p) ([raw file](https://github.com/pmem/pmemkv/blob/94e73d32a0434b813b7db487c3693166acd25c36/utils/docker/run-compatibility.sh#L32)):*
> ```Shell
> 
> 	# checkout HEAD/current version again and cleanup build dir
> 	git checkout ${current_version}
> ```

It would be better to save version on the beginning of this function and restore it at the end, then using variable from outside scope.

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/740)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @karczex)

___
*[utils/docker/run-compatibility.sh, line 32 at r2](https://reviewable.io/reviews/pmem/pmemkv/740#-MFBEn-sDxsUNXQ5UGCv:-MFCBU4-9eq7FXL48IOk:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/94e73d32a0434b813b7db487c3693166acd25c36/utils/docker/run-compatibility.sh#L32)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

It would be better to save version on the beginning of this function and restore it at the end, then using variable from outside scope.
</blockquote></details>

Done.

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/740#-:-MFElA1NAPH5ydnjaw7m:bnfp4nl)* status: 0 of 2 files reviewed, all discussions resolved

**Pull request merged**
