### PR TITLE
Fix for errormsg on NOT_FOUND 

### PR DESCRIPTION
**Pull request by karczex**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/914)

### CODE REVIEW

**Review by igchor — APPROVED** [review]
:lgtm:, maybe just add some comment or create an issue to remember we need to fix the checks for invalid argument?

> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/914#-:-MT5v5CTA2nAJpMWxZtX:bkthwq2)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @igchor)

**Review by KFilipek — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/914)* status: all files reviewed, 2 unresolved discussions (waiting on @karczex)

___
*[src/out.h, line 7 at r2](https://reviewable.io/reviews/pmem/pmemkv/914#-MT69yMYEXMcqdXMUSTl:-MT69yMYEXMcqdXMUSTm:bxnhl6u) ([raw file](https://github.com/pmem/pmemkv/blob/303d4d6b9d77d850d0b191f251064aeffde071b9/src/out.h#L7)):*
> ```objc
> #define LIBPMEMKV_OUT_H
> 
> #include "libpmemkv.hpp"
> ```

Please reorder headers
https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes
___
*[src/out.cc, line 4 at r2](https://reviewable.io/reviews/pmem/pmemkv/914#-MT6A24E-Bt_8ou-woE5:-MT6A24E-Bt_8ou-woE6:b-mq2flg) ([raw file](https://github.com/pmem/pmemkv/blob/303d4d6b9d77d850d0b191f251064aeffde071b9/src/out.cc#L4)):*
> ```cpp
> /* Copyright 2019-2021, Intel Corporation */
> 
> #include "out.h"
> ```

Same as above:
https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/914)* status: all files reviewed, 5 unresolved discussions (waiting on @karczex and @KFilipek)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/914#-MT6Cmi8BAuBPB8hH04d:-MT6Cmi8BAuBPB8hH04e:b-byl6sc) (no related file):*
in commit message: `last satus` - misspell

---
___
*[src/out.h, line 7 at r2](https://reviewable.io/reviews/pmem/pmemkv/914#-MT69yMYEXMcqdXMUSTl:-MT6ATK-1JJH8NqaMsIs:b-qfewq0) ([raw file](https://github.com/pmem/pmemkv/blob/303d4d6b9d77d850d0b191f251064aeffde071b9/src/out.h#L7)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Please reorder headers
https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes
</blockquote></details>

// if we want to force some specific order, we should make a `make check/format-` command(s) for that
___
*[tests/error_msg_test.cc, line 25 at r2](https://reviewable.io/reviews/pmem/pmemkv/914#-MT6C2kM8wHHLCFtnRJ7:-MT6C2kM8wHHLCFtnRJ8:bvcuugb) ([raw file](https://github.com/pmem/pmemkv/blob/303d4d6b9d77d850d0b191f251064aeffde071b9/tests/error_msg_test.cc#L25)):*
> ```cpp
> 	err = pmem::kv::errormsg();
> 	UT_ASSERT(err == "");
> 	UT_ASSERT(err.size() == 0);
> ```

pls use UT_ASSERTeq
___
*[tests/error_msg_test.cc, line 26 at r2](https://reviewable.io/reviews/pmem/pmemkv/914#-MT6CaQp4LTTWCSv7Xv2:-MT6CaQp4LTTWCSv7Xv3:b-rg6v2s) ([raw file](https://github.com/pmem/pmemkv/blob/303d4d6b9d77d850d0b191f251064aeffde071b9/tests/error_msg_test.cc#L26)):*
> ```cpp
> 	UT_ASSERT(err == "");
> 	UT_ASSERT(err.size() == 0);
> }
> ```

pls add one more case with "proper" status returned, after the not_found

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/914)* status: 3 of 5 files reviewed, 5 unresolved discussions (waiting on @karczex, @KFilipek, and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/914#-MT6Cmi8BAuBPB8hH04d:-MT6EXjR5JnIItw6cxpJ:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

in commit message: `last satus` - misspell
</blockquote></details>

Done.

---
___
*[src/out.h, line 7 at r2](https://reviewable.io/reviews/pmem/pmemkv/914#-MT69yMYEXMcqdXMUSTl:-MT6DBe45Xn6Z5ED6ayg:b-qi4qqq) ([raw file](https://github.com/pmem/pmemkv/blob/303d4d6b9d77d850d0b191f251064aeffde071b9/src/out.h#L7)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

// if we want to force some specific order, we should make a `make check/format-` command(s) for that
</blockquote></details>

we use formatting based on LLVM style (not Google), which by default have set 
```
SortIncludes:    true
```
So if  CI passed, the sorting is OK. 
___
*[src/out.cc, line 4 at r2](https://reviewable.io/reviews/pmem/pmemkv/914#-MT6A24E-Bt_8ou-woE5:-MT6EB4u9QpD_Tvkn6tU:b3kqx) ([raw file](https://github.com/pmem/pmemkv/blob/303d4d6b9d77d850d0b191f251064aeffde071b9/src/out.cc#L4)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Same as above:
https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes
</blockquote></details>

.

**Review by KFilipek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/914)* status: 3 of 5 files reviewed, 5 unresolved discussions (waiting on @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[src/out.h, line 7 at r2](https://reviewable.io/reviews/pmem/pmemkv/914#-MT69yMYEXMcqdXMUSTl:-MT6GPiIEKaO6WoWKV5Q:b-93b3zj) ([raw file](https://github.com/pmem/pmemkv/blob/303d4d6b9d77d850d0b191f251064aeffde071b9/src/out.h#L7)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

we use formatting based on LLVM style (not Google), which by default have set 
```
SortIncludes:    true
```
So if  CI passed, the sorting is OK. 

</blockquote></details>

Sorting and grouping are two different sort of libraries.
Here should be an enter
___
*[src/out.cc, line 4 at r2](https://reviewable.io/reviews/pmem/pmemkv/914#-MT6A24E-Bt_8ou-woE5:-MT6Gcjf7QE2U42NLgN8:b48rvc4) ([raw file](https://github.com/pmem/pmemkv/blob/303d4d6b9d77d850d0b191f251064aeffde071b9/src/out.cc#L4)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

.
</blockquote></details>

out.h is declaration file for out.cc
libpmemkv.hpp is a external library
here should be a line break

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/914)* status: 3 of 5 files reviewed, 5 unresolved discussions (waiting on @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[src/out.h, line 7 at r2](https://reviewable.io/reviews/pmem/pmemkv/914#-MT69yMYEXMcqdXMUSTl:-MT6HQQX4KahtkdPg2Je:b4e0ncl) ([raw file](https://github.com/pmem/pmemkv/blob/303d4d6b9d77d850d0b191f251064aeffde071b9/src/out.h#L7)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Sorting and grouping are two different sort of libraries.
Here should be an enter
</blockquote></details>

external? this is all pmemkv ;d

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/914)* status: 3 of 5 files reviewed, 5 unresolved discussions (waiting on @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[src/out.cc, line 4 at r2](https://reviewable.io/reviews/pmem/pmemkv/914#-MT6A24E-Bt_8ou-woE5:-MT6HWm5EKv6NPwsDzVR:b-5zo03v) ([raw file](https://github.com/pmem/pmemkv/blob/303d4d6b9d77d850d0b191f251064aeffde071b9/src/out.cc#L4)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

out.h is declaration file for out.cc
libpmemkv.hpp is a external library
here should be a line break
</blockquote></details>

external? this is all pmemkv ;d

**Review by KFilipek — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/914)* status: all files reviewed, 6 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[src/out.h, line 7 at r2](https://reviewable.io/reviews/pmem/pmemkv/914#-MT69yMYEXMcqdXMUSTl:-MT6LFyI3mrCqqhHxJ2P:b-55abtv) ([raw file](https://github.com/pmem/pmemkv/blob/303d4d6b9d77d850d0b191f251064aeffde071b9/src/out.h#L7)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

external? this is all pmemkv ;d
</blockquote></details>

@igchor it doesn't matter, it's another group of headers that should be separated
___
*[src/out.cc, line 4 at r2](https://reviewable.io/reviews/pmem/pmemkv/914#-MT6A24E-Bt_8ou-woE5:-MT6M8IrEHdTeoOxvFNZ:b-xy8gjp) ([raw file](https://github.com/pmem/pmemkv/blob/303d4d6b9d77d850d0b191f251064aeffde071b9/src/out.cc#L4)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

external? this is all pmemkv ;d
</blockquote></details>

https://llvm.org/docs/CodingStandards.html#include-style out.h and sstream are still in different groups despite nomenclature
___
*[src/out.cc, line 5 at r2](https://reviewable.io/reviews/pmem/pmemkv/914#-MT6LuXb-5XDUCoTxC-i:-MT6LuXb-5XDUCoTxC-j:b-mnmwpe) ([raw file](https://github.com/pmem/pmemkv/blob/303d4d6b9d77d850d0b191f251064aeffde071b9/src/out.cc#L5)):*
> ```cpp
> 
> #include "out.h"
> #include "libpmemkv.hpp"
> ```

also, this file was previously included by out.h, so, I believe can be removed.
https://llvm.org/docs/CodingStandards.html#include-style 
out.h and sstream are different groups also in LLVM coding style

**Review by igchor — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/914)* status: all files reviewed, 6 unresolved discussions (waiting on @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[src/out.h, line 7 at r2](https://reviewable.io/reviews/pmem/pmemkv/914#-MT69yMYEXMcqdXMUSTl:-MT6P3dI2-GJYa-A49F7:b9rtwwg) ([raw file](https://github.com/pmem/pmemkv/blob/303d4d6b9d77d850d0b191f251064aeffde071b9/src/out.h#L7)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

@igchor it doesn't matter, it's another group of headers that should be separated
</blockquote></details>

Ok, I meant the out.cc case, but anyway, if we want to enforce  the ordering of include, we should add some script for checking this. If it's not possible to create a simple script/rule for formatter I think we should not enforce it - we will spend more time reviewing/fixing the include order then we gain by having them sorted.

**Comment by karczex** [comment]
___
*[src/out.cc, line 5 at r2](https://reviewable.io/reviews/pmem/pmemkv/914#-MT6LuXb-5XDUCoTxC-i:-MT6SnlH8JqRHg8oBDFK:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/303d4d6b9d77d850d0b191f251064aeffde071b9/src/out.cc#L5)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

also, this file was previously included by out.h, so, I believe can be removed.
https://llvm.org/docs/CodingStandards.html#include-style 
out.h and sstream are different groups also in LLVM coding style
</blockquote></details>

Done.

**Comment by karczex** [comment]
___
*[tests/error_msg_test.cc, line 26 at r2](https://reviewable.io/reviews/pmem/pmemkv/914#-MT6CaQp4LTTWCSv7Xv2:-MT6R4KV9IMwajLH07bM:b1m30hp) ([raw file](https://github.com/pmem/pmemkv/blob/303d4d6b9d77d850d0b191f251064aeffde071b9/tests/error_msg_test.cc#L26)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls add one more case with "proper" status returned, after the not_found 
</blockquote></details>

That was pretty good catch. Done.

**Comment by karczex** [comment]
___
*[tests/error_msg_test.cc, line 25 at r2](https://reviewable.io/reviews/pmem/pmemkv/914#-MT6C2kM8wHHLCFtnRJ7:-MT6R61z794wiB9NXnig:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/303d4d6b9d77d850d0b191f251064aeffde071b9/tests/error_msg_test.cc#L25)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls use UT_ASSERTeq
</blockquote></details>

Done.

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/914)* status: 2 of 5 files reviewed, 7 unresolved discussions (waiting on @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[src/libpmemkv.cc, line 87 at r4](https://reviewable.io/reviews/pmem/pmemkv/914#-MTAC8vc2Bf9iHLH_C9p:-MTAC8vc2Bf9iHLH_C9q:b-six4co) ([raw file](https://github.com/pmem/pmemkv/blob/28e837c0ff25f7baefffa927be334d74e481c6e6/src/libpmemkv.cc#L87)):*
> ```cpp
> 	} catch (pmem::kv::internal::error &e) {
> 		out_err_stream(func_name) << e.what();
> 		set_last_status(static_cast<pmem::kv::status>(e.status_code));
> ```

nit: we could probably have status variable defined before the try/catch and move the `set_last_status(s); return status_cast<int>(s);` after the whole try/catch block.

Also, wouldn't it be better to just store int in tls in out.cc instead of pmem::kv::status? This would avoid all those casts and we don't use pmem::kv::status until we are on C++ layer (libpmmekv.hpp)

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, 2 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/914)* status: 4 of 5 files reviewed, 4 unresolved discussions (waiting on @karczex, @KFilipek, and @lukaszstolarczuk)

**Review by KFilipek — COMMENTED** [review]
> Reviewed 1 of 3 files at r4, 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/914)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)

**Review by KFilipek — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/914#-:-MTAVuGs0ODPRmYPh1tr:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/914#-:-MTAcXJX0dvoaTk90gin:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/914)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)

___
*[src/out.h, line 7 at r5](https://reviewable.io/reviews/pmem/pmemkv/914#-MTAkKrl0vrwaLTfbG1K:-MTAkKrm7qQRWWtsm4cM:b-hfpv1m) ([raw file](https://github.com/pmem/pmemkv/blob/94d8ec9ad6dd71176196abcab583abc45fd076f0/src/out.h#L7)):*
> ```objc
> #define LIBPMEMKV_OUT_H
> 
> #include "libpmemkv.hpp"
> ```

remove?

**Review by KFilipek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/914)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[src/out.h, line 7 at r5](https://reviewable.io/reviews/pmem/pmemkv/914#-MTAkKrl0vrwaLTfbG1K:-MTAmMoH0GpFkski7gp6:bl08mrj) ([raw file](https://github.com/pmem/pmemkv/blob/94d8ec9ad6dd71176196abcab583abc45fd076f0/src/out.h#L7)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

remove?
</blockquote></details>

out.cc uses PMEMKV_STATUS_NOT_FOUND

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/914)* status: all files reviewed, 1 unresolved discussion (waiting on @KFilipek)

___
*[src/out.h, line 7 at r5](https://reviewable.io/reviews/pmem/pmemkv/914#-MTAkKrl0vrwaLTfbG1K:-MTAmncU-PixlSFhmW4L:b1eyzek) ([raw file](https://github.com/pmem/pmemkv/blob/94d8ec9ad6dd71176196abcab583abc45fd076f0/src/out.h#L7)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

out.cc uses PMEMKV_STATUS_NOT_FOUND
</blockquote></details>

och, true, but then `libpmemk.h`...?
and shouldn't it be included in out.cc, so it's not included any time someone needs just `out.h`...?

**Review by KFilipek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/914)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[src/out.h, line 7 at r5](https://reviewable.io/reviews/pmem/pmemkv/914#-MTAkKrl0vrwaLTfbG1K:-MTAp1OPCy3hJRjxPHdc:b-4n3ke8) ([raw file](https://github.com/pmem/pmemkv/blob/94d8ec9ad6dd71176196abcab583abc45fd076f0/src/out.h#L7)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

och, true, but then `libpmemk.h`...?
and shouldn't it be included in out.cc, so it's not included any time someone needs just `out.h`...?
</blockquote></details>

You're right. out.cc will be compiled once, but out.h can be included multiple times and this header will be included with guards few times during compilation

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/914)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @KFilipek and @lukaszstolarczuk)

___
*[src/out.h, line 7 at r5](https://reviewable.io/reviews/pmem/pmemkv/914#-MTAkKrl0vrwaLTfbG1K:-MTAv2hH-jcuPKNUGXmb:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/94d8ec9ad6dd71176196abcab583abc45fd076f0/src/out.h#L7)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

You're right. out.cc will be compiled once, but out.h can be included multiple times and this header will be included with guards few times during compilation
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/914#-:-MTAvYxI1PIPegbDVgv7:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)

**Review by KFilipek — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/914#-:-MTB-ozt7v7EcCpr88A_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)

**Pull request merged**
