### PR TITLE
tests: check assignment operator from self in db and config classes

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/795)

### CODE REVIEW

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/795)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[tests/config/config_cpp.cc, line 379 at r1](https://reviewable.io/reviews/pmem/pmemkv/795#-MIIqkFl3TLl47yneW8y:-MIIqkFmACFsz1ebMIYF:b-y22xbd) ([raw file](https://github.com/pmem/pmemkv/blob/48bd5bd106bd53cc25def604492560fe94ece109/tests/config/config_cpp.cc#L379)):*
> ```cpp
> 		from different and the same config */
> 	*move_assign = std::move(*cfg);
> 	config *move_assign2 = std::move(move_assign);
> ```

That's not self-assignment, it's just assigning pointers. What you want is probably:

```
*move_assign = std::move(*move_assign);
```

or (to fool static analyzers):

```
auto & move_assign2 = *move_assign;
*move_assign = std::move(*move_assign);
```

We should change those tests to use on-stack configs, instead of heap allocated ones one day...
___
*[tests/engine_scenarios/all/put_get_remove.cc, line 385 at r1](https://reviewable.io/reviews/pmem/pmemkv/795#-MIIrsY1AMT-coDtmr8t:-MIIrsY1AMT-coDtmr8u:bw472co) ([raw file](https://github.com/pmem/pmemkv/blob/48bd5bd106bd53cc25def604492560fe94ece109/tests/engine_scenarios/all/put_get_remove.cc#L385)):*
> ```cpp
> 
> 	db kv_assign_new = std::move(kv_new);
> 	db kv_assign_new2 = std::move(kv_assign_new);
> ```

Again, this is not self-asignment, it won't trigger the check within operator=.

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/795)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @igchor)

___
*[tests/config/config_cpp.cc, line 379 at r1](https://reviewable.io/reviews/pmem/pmemkv/795#-MIIqkFl3TLl47yneW8y:-MIO_ivABHGsg8tIWEJ3:bx7ox9c) ([raw file](https://github.com/pmem/pmemkv/blob/48bd5bd106bd53cc25def604492560fe94ece109/tests/config/config_cpp.cc#L379)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

That's not self-assignment, it's just assigning pointers. What you want is probably:

```
*move_assign = std::move(*move_assign);
```

or (to fool static analyzers):

```
auto & move_assign2 = *move_assign;
*move_assign = std::move(*move_assign);
```

We should change those tests to use on-stack configs, instead of heap allocated ones one day...
</blockquote></details>

Done. I guess I did something wrong previously, cause I have no warnings now; I also checked the code with clang analyzer and it shows no issues.

As for changes with config tests - I've updated the issue: #715
___
*[tests/engine_scenarios/all/put_get_remove.cc, line 385 at r1](https://reviewable.io/reviews/pmem/pmemkv/795#-MIIrsY1AMT-coDtmr8t:-MIOa0AbABuo6us74ADg:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/48bd5bd106bd53cc25def604492560fe94ece109/tests/engine_scenarios/all/put_get_remove.cc#L385)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Again, this is not self-asignment, it won't trigger the check within operator=.
</blockquote></details>

Done.

**Review by igchor — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/795#-:-MIPHPZB3Ywv4HCvtoHs:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by szyrom — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/795#-:-MIU46kP3DRrcsHYXVfu:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
