### PR TITLE
Fix vcmap

### PR DESCRIPTION
**Pull request by igchor**
Tests will be added in stable-1.2 (framework conflicts).

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/893)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/893)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/893#-MSCon3B4ahve91L3DuC:-MSCon3B4ahve91L3DuD:b-4rhd56) (no related file):*
isn't 1.0 branch closed already? pls rebase to stable-1.1

---

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/893)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/893#-MSCon3B4ahve91L3DuC:-MSD-adU94qIJ05OM_j_:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

isn't 1.0 branch closed already? pls rebase to stable-1.1
</blockquote></details>

Done.

---

**Review by lukaszstolarczuk — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/893#-:-MSDFro2B6rwmgHerJby:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Comment by KFilipek** [comment]
Please rerun checks, something went wrong

**Review by KFilipek — COMMENTED** [review]
:lgtm:
I like this kind of changes, that simplify a lot.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/893#-:-MSDLzkm7VEADk10FVs4:bbon4h7)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/893#-:-MSXYaSw4wCNi0OGfDS6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Pull request merged**
