### PR TITLE
Add info about adding new dependencies

### PR DESCRIPTION
**Pull request by igchor**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/969)

### CODE REVIEW

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/969)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[CONTRIBUTING.md, line 90 at r1](https://reviewable.io/reviews/pmem/pmemkv/969#-MVQXFOO45_T9sRV9usa:-MVQqaOR4XnzwbUvSxL_:b7hmzxx) ([raw file](https://github.com/pmem/pmemkv/blob/9b1923e256429686ea9f1ab4d7d7c83117fc6f65/CONTRIBUTING.md#L90)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

new docker image or new docker package (?)
</blockquote></details>

both actually

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/969)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)

___
*[CONTRIBUTING.md, line 90 at r1](https://reviewable.io/reviews/pmem/pmemkv/969#-MVQXFOO45_T9sRV9usa:-MVQvbj7AsuCQVn0XXw-:b-888bb0) ([raw file](https://github.com/pmem/pmemkv/blob/9b1923e256429686ea9f1ab4d7d7c83117fc6f65/CONTRIBUTING.md#L90)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

both actually
</blockquote></details>

sooo... add the second one here...? :D

**Review by KFilipek — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/969#-:-MVRlPhwCMDvH7YjRc1l:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/969)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[CONTRIBUTING.md, line 90 at r1](https://reviewable.io/reviews/pmem/pmemkv/969#-MVQXFOO45_T9sRV9usa:-MW3Hi8E2hvoNUzCRiD7:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/9b1923e256429686ea9f1ab4d7d7c83117fc6f65/CONTRIBUTING.md#L90)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

sooo... add the second one here...? :D
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/969#-:-MW3RX3E7p1MZxEw6rEL:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Pull request merged**
