### PR TITLE
Fix CI scripts

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
reading CMake version's failed in some specific circumstances,
fix CI workflow job - change to "nightly" (as in libpmemobj-cpp),
minor cleanups

// preview with all OSes: https://github.com/lukaszstolarczuk/pmemkv/runs/3053905161?check_suite_focus=true

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1017)

### CODE REVIEW

**Review by KFilipek — COMMENTED** [review]
> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1017)* status: all files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[.github/workflows/gha.yml, line 3 at r1](https://reviewable.io/reviews/pmem/pmemkv/1017#-MeUAt_CAdXXMPa0yeQP:-MeUAt_D2oXAPnLQ5qem:b-694a3o) ([raw file](https://github.com/pmem/pmemkv/blob/99d0e2d7fa95418fc7bfd52a88f72122c4dd32f0/.github/workflows/gha.yml#L3)):*
> ```YAML
> 
> name: pmemkv
> # It runs deafult OSes for each PR, push event or a new tag,
> ```

*default
___
*[.github/workflows/gha.yml, line 4 at r1](https://reviewable.io/reviews/pmem/pmemkv/1017#-MeUB-x96mEehxBVYiCH:-MeUB-x96mEehxBVYiCI:bqlrkhl) ([raw file](https://github.com/pmem/pmemkv/blob/99d0e2d7fa95418fc7bfd52a88f72122c4dd32f0/.github/workflows/gha.yml#L4)):*
> ```YAML
> name: pmemkv
> # It runs deafult OSes for each PR, push event or a new tag,
> # checks basic builds with various compilers and executes all sets of tests.
> ```

*the tests?
if yes, please change all occurrences

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1017)* status: 12 of 13 files reviewed, 2 unresolved discussions (waiting on @KFilipek)

___
*[.github/workflows/gha.yml, line 3 at r1](https://reviewable.io/reviews/pmem/pmemkv/1017#-MeUAt_CAdXXMPa0yeQP:-MeV0BoR9XEZR40lbdjr:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/99d0e2d7fa95418fc7bfd52a88f72122c4dd32f0/.github/workflows/gha.yml#L3)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

*default
</blockquote></details>

Done.
___
*[.github/workflows/gha.yml, line 4 at r1](https://reviewable.io/reviews/pmem/pmemkv/1017#-MeUB-x96mEehxBVYiCH:-MeV0CSGCpurX9MgHyeU:byank9w) ([raw file](https://github.com/pmem/pmemkv/blob/99d0e2d7fa95418fc7bfd52a88f72122c4dd32f0/.github/workflows/gha.yml#L4)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

*the tests?
if yes, please change all occurrences
</blockquote></details>

tbh, I don't think we need any article here

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1017)* status: 12 of 13 files reviewed, 7 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[.github/workflows/coverity.yml, line 3 at r2](https://reviewable.io/reviews/pmem/pmemkv/1017#-MeYatH18yVgqQRz97me:-MeYatH2ALYJpKlH20lP:bdlh7o6) ([raw file](https://github.com/pmem/pmemkv/blob/26b26e1d008fe65ea99c61bd038e6c4224ba604e/.github/workflows/coverity.yml#L3)):*
> ```
> It requires special token 
> ```
It doesn't help if I want to configure it on my fork :) 
___
*[utils/docker/prepare-for-build.sh, line 82 at r2](https://reviewable.io/reviews/pmem/pmemkv/1017#-MeYcKro5erTeVaQ5SEF:-MeYcKrpD8C_Dx9HH8vm:bds9xr0) ([raw file](https://github.com/pmem/pmemkv/blob/26b26e1d008fe65ea99c61bd038e6c4224ba604e/utils/docker/prepare-for-build.sh#L82)):*
> ```Shell
> 
> 	rm -f ${pool_path}
> 	cd -
> ```

nit:
as you are doing some code cleanups: `pushd  dir  ... popd` is less error prone than ` cd dir ... cd -`
___
*[utils/docker/prepare-for-build.sh, line 96 at r2](https://reviewable.io/reviews/pmem/pmemkv/1017#-MeYdQoV38jXMXWORSaj:-MeYdQoV38jXMXWORSak:b-f8rvbd) ([raw file](https://github.com/pmem/pmemkv/blob/26b26e1d008fe65ea99c61bd038e6c4224ba604e/utils/docker/prepare-for-build.sh#L96)):*
> ```
> has to contain a path to the root
> ```
so maybe 
```
WORKDIR=$(git rev-parse --show-toplevel) 
``` 
by default if run inside repository, and error with message to set WORKDIR if run without git/from tar file
___
*[utils/docker/prepare-for-build.sh, line 110 at r2](https://reviewable.io/reviews/pmem/pmemkv/1017#-MeYjhUvAn6D1g4ycwYw:-MeYjhUvAn6D1g4ycwYx:b-97r8vq) ([raw file](https://github.com/pmem/pmemkv/blob/26b26e1d008fe65ea99c61bd038e6c4224ba604e/utils/docker/prepare-for-build.sh#L110)):*
> ```Shell
> 
> # assign CMake's version to variable(s)  - a single number representation for easier comparison
> CMAKE_VERSION=$(cmake --version | head -n1 | grep -oE '[0-9]\.[0-9]*')
> ```

```
CMAKE_VERSION=$(cmake --version  | grep -P -o "\d+.\d+") 
```
?
___
*[utils/docker/prepare-for-build.sh, line 113 at r2](https://reviewable.io/reviews/pmem/pmemkv/1017#-MeYgrHHBYd_u_QVqaSg:-MeYgrHHBYd_u_QVqaSh:b-bbkssj) ([raw file](https://github.com/pmem/pmemkv/blob/26b26e1d008fe65ea99c61bd038e6c4224ba604e/utils/docker/prepare-for-build.sh#L113)):*
> ```Shell
> CMAKE_VERSION_MAJOR=$(echo ${CMAKE_VERSION} | cut -d. -f1)
> CMAKE_VERSION_MINOR=$(echo ${CMAKE_VERSION} | cut -d. -f2)
> CMAKE_VERSION_NUMBER=$((100 * ${CMAKE_VERSION_MAJOR} + ${CMAKE_VERSION_MINOR}))
> ```

why not just 
```
C=${A}${B} 
```

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1017)* status: 12 of 13 files reviewed, 6 unresolved discussions (waiting on @karczex and @KFilipek)

___
*[.github/workflows/coverity.yml, line 3 at r2](https://reviewable.io/reviews/pmem/pmemkv/1017#-MeYatH18yVgqQRz97me:-MeZ2EqZCdS6oWi2GTMM:by0txzn) ([raw file](https://github.com/pmem/pmemkv/blob/26b26e1d008fe65ea99c61bd038e6c4224ba604e/.github/workflows/coverity.yml#L3)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

> ```
> It requires special token 
> ```
It doesn't help if I want to configure it on my fork :) 
</blockquote></details>

you can see the token right below, in the env. vars ;)

but anyhow... I'm not sure how, but it works on my fork (I don't recall setting anything up):
https://app.codecov.io/gh/lukaszstolarczuk/pmemkv
___
*[.github/workflows/gha.yml, line 3 at r1](https://reviewable.io/reviews/pmem/pmemkv/1017#-MeUAt_CAdXXMPa0yeQP:-MeZ2RUvDValMXPuppXE:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/99d0e2d7fa95418fc7bfd52a88f72122c4dd32f0/.github/workflows/gha.yml#L3)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.
___
*[.github/workflows/gha.yml, line 4 at r1](https://reviewable.io/reviews/pmem/pmemkv/1017#-MeUB-x96mEehxBVYiCH:-MeZ2Rho46mSFbmIvpUh:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/99d0e2d7fa95418fc7bfd52a88f72122c4dd32f0/.github/workflows/gha.yml#L4)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

tbh, I don't think we need any article here
</blockquote></details>

Done.
___
*[utils/docker/prepare-for-build.sh, line 82 at r2](https://reviewable.io/reviews/pmem/pmemkv/1017#-MeYcKro5erTeVaQ5SEF:-MeZ63M79o5SKdpMmYsp:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/26b26e1d008fe65ea99c61bd038e6c4224ba604e/utils/docker/prepare-for-build.sh#L82)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

nit:
as you are doing some code cleanups: `pushd  dir  ... popd` is less error prone than ` cd dir ... cd -`
</blockquote></details>

Done.
___
*[utils/docker/prepare-for-build.sh, line 96 at r2](https://reviewable.io/reviews/pmem/pmemkv/1017#-MeYdQoV38jXMXWORSaj:-MeZ2frHCicyUjoW0euZ:b-ff8nnv) ([raw file](https://github.com/pmem/pmemkv/blob/26b26e1d008fe65ea99c61bd038e6c4224ba604e/utils/docker/prepare-for-build.sh#L96)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

> ```
> has to contain a path to the root
> ```
so maybe 
```
WORKDIR=$(git rev-parse --show-toplevel) 
``` 
by default if run inside repository, and error with message to set WORKDIR if run without git/from tar file
</blockquote></details>

it looks cool, but TBH I'm not sure if I want to magically set some path - if you run this in your env and it will set up a wrong path somehow, then I'm the guilty one :wink:
___
*[utils/docker/prepare-for-build.sh, line 110 at r2](https://reviewable.io/reviews/pmem/pmemkv/1017#-MeYjhUvAn6D1g4ycwYw:-MeZ3hS29dDl6TN9xBIo:b5icjgb) ([raw file](https://github.com/pmem/pmemkv/blob/26b26e1d008fe65ea99c61bd038e6c4224ba604e/utils/docker/prepare-for-build.sh#L110)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

```
CMAKE_VERSION=$(cmake --version  | grep -P -o "\d+.\d+") 
```
?
</blockquote></details>

why not :wink: (but the `\.` is very important, as stated e.g. in the commit message - version like `3.16.4-6` breaks the system :wink: )
Done.
___
*[utils/docker/prepare-for-build.sh, line 113 at r2](https://reviewable.io/reviews/pmem/pmemkv/1017#-MeYgrHHBYd_u_QVqaSg:-MeZ3FVS-6nWuAHKqIFw:b-djujbz) ([raw file](https://github.com/pmem/pmemkv/blob/26b26e1d008fe65ea99c61bd038e6c4224ba604e/utils/docker/prepare-for-build.sh#L113)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

why not just 
```
C=${A}${B} 
```

</blockquote></details>

:sweat_smile: haha.. I don't know why we had it like this, :+1: 
Done.

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1017#-:-MeZRbU9C6TDNebTZXUW:bnfp4nl)* status: 11 of 13 files reviewed, 2 unresolved discussions (waiting on @KFilipek)

**Pull request merged**
