### PR TITLE
Add blackhole iterator to test iterators API

### PR DESCRIPTION
**Pull request by JanDorniak99**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/880)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/880)* status: all files reviewed, 4 unresolved discussions (waiting on @JanDorniak99)

___
*[src/engines/blackhole.cc, line 154 at r1](https://reviewable.io/reviews/pmem/pmemkv/880#-MQWUSd50nU4eHUNcrxn:-MQWUSd6Dg3PrzHMTw8m:b-aewm79) ([raw file](https://github.com/pmem/pmemkv/blob/07df8fc471e64927329cda5764798baaaba7abbe/src/engines/blackhole.cc#L154)):*
> ```cpp
> 
> internal::iterator_base *blackhole::new_iterator()
> {
> ```

please use LOG()
___
*[tests/engines/blackhole/blackhole_test.cc, line 155 at r1](https://reviewable.io/reviews/pmem/pmemkv/880#-MQWUp3vBIwJzWN5I7d6:-MQWUp3vBIwJzWN5I7d7:b9gn88) ([raw file](https://github.com/pmem/pmemkv/blob/07df8fc471e64927329cda5764798baaaba7abbe/tests/engines/blackhole/blackhole_test.cc#L155)):*
> ```cpp
> typename std::enable_if<IsConst>::type test_write(iterator<IsConst> &it)
> {
> 	/* does nothing for a read iterator */
> ```

either "it does nothing" or "do nothing"
___
*[tests/engines/blackhole/blackhole_test.cc, line 165 at r1](https://reviewable.io/reviews/pmem/pmemkv/880#-MQWZtl8BEnUM2qRSCPq:-MQWZtl8BEnUM2qRSCPr:b66qr1z) ([raw file](https://github.com/pmem/pmemkv/blob/07df8fc471e64927329cda5764798baaaba7abbe/tests/engines/blackhole/blackhole_test.cc#L165)):*
> ```cpp
> 	ASSERT_STATUS(write_res.get_status(), status::NOT_SUPPORTED);
> 
> 	ASSERT_STATUS(it.commit(), status::NOT_SUPPORTED);
> ```

how about `abort`?
___
*[tests/engines/blackhole/blackhole_test.cc, line 176 at r1](https://reviewable.io/reviews/pmem/pmemkv/880#-MQWZ9WhBxPd9_SBtjSI:-MQWZ9WhBxPd9_SBtjSJ:bh2dqd) ([raw file](https://github.com/pmem/pmemkv/blob/07df8fc471e64927329cda5764798baaaba7abbe/tests/engines/blackhole/blackhole_test.cc#L176)):*
> ```cpp
> 
> 	auto it = new_iterator<IsConst>(kv);
> ```

new const iter?

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/880)* status: all files reviewed, 5 unresolved discussions (waiting on @JanDorniak99)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/880#-MQW_Ml85RreU1NMdSB4:-MQW_Ml85RreU1NMdSB5:b-zhp23e) (no related file):*
perhaps also update the PR title (and maybe commit msg a little too) to better describe what you're doing. I know the goal is to increase the coverage, but it should say (functionally) what you're doing in this PR

---

**Review by JanDorniak99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/880)* status: 1 of 3 files reviewed, 5 unresolved discussions (waiting on @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/880#-MQW_Ml85RreU1NMdSB4:-MQWnGHXCRsI5iNG2m-q:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps also update the PR title (and maybe commit msg a little too) to better describe what you're doing. I know the goal is to increase the coverage, but it should say (functionally) what you're doing in this PR
</blockquote></details>

Done.

---
___
*[src/engines/blackhole.cc, line 154 at r1](https://reviewable.io/reviews/pmem/pmemkv/880#-MQWUSd50nU4eHUNcrxn:-MQWhTGW4NXHHMUxKsDG:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/07df8fc471e64927329cda5764798baaaba7abbe/src/engines/blackhole.cc#L154)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

please use LOG()
</blockquote></details>

Done.
___
*[tests/engines/blackhole/blackhole_test.cc, line 155 at r1](https://reviewable.io/reviews/pmem/pmemkv/880#-MQWUp3vBIwJzWN5I7d6:-MQWhc4r1r0V7OH1daLg:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/07df8fc471e64927329cda5764798baaaba7abbe/tests/engines/blackhole/blackhole_test.cc#L155)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

either "it does nothing" or "do nothing"
</blockquote></details>

Done.
___
*[tests/engines/blackhole/blackhole_test.cc, line 165 at r1](https://reviewable.io/reviews/pmem/pmemkv/880#-MQWZtl8BEnUM2qRSCPq:-MQWiK5g7eBdVBIr0rX6:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/07df8fc471e64927329cda5764798baaaba7abbe/tests/engines/blackhole/blackhole_test.cc#L165)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

how about `abort`?
</blockquote></details>

Done.
___
*[tests/engines/blackhole/blackhole_test.cc, line 176 at r1](https://reviewable.io/reviews/pmem/pmemkv/880#-MQWZ9WhBxPd9_SBtjSI:-MQWlz1PAvVBZIPvTx4Y:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/07df8fc471e64927329cda5764798baaaba7abbe/tests/engines/blackhole/blackhole_test.cc#L176)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

new const iter?
</blockquote></details>

Done.

**Review by lukaszstolarczuk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/880#-:-MQWznm41_KDQ35ACGxS:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JanDorniak99)

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/880)* status: all files reviewed, 1 unresolved discussion (waiting on @JanDorniak99)

___
*[src/engines/blackhole.h, line 14 at r3](https://reviewable.io/reviews/pmem/pmemkv/880#-MQr8YsbC9LRMTPiw34p:-MQr8YsbC9LRMTPiw34q:bcsanr7) ([raw file](https://github.com/pmem/pmemkv/blob/c09fa3e6c5566a0e903ca45e14d34b29686ff4b2/src/engines/blackhole.h#L14)):*
> ```objc
> 
> class blackhole : public engine_base {
> 	class blackhole_iterator;
> ```

why not just "iterator"?
___
*[src/engines/blackhole.cc, line 168 at r3](https://reviewable.io/reviews/pmem/pmemkv/880#-MQr8PvbCtDEcfeaUGPY:-MQr8PvbCtDEcfeaUGPZ:b-idx9bi) ([raw file](https://github.com/pmem/pmemkv/blob/c09fa3e6c5566a0e903ca45e14d34b29686ff4b2/src/engines/blackhole.cc#L168)):*
> ```cpp
> 
> /* required for logging */
> std::string name()
> ```

is this used anywhere?

**Review by JanDorniak99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/880)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)

___
*[src/engines/blackhole.h, line 14 at r3](https://reviewable.io/reviews/pmem/pmemkv/880#-MQr8YsbC9LRMTPiw34p:-MQupBB00k-BXFumhe5b:bqowrbs) ([raw file](https://github.com/pmem/pmemkv/blob/c09fa3e6c5566a0e903ca45e14d34b29686ff4b2/src/engines/blackhole.h#L14)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

why not just "iterator"?
</blockquote></details>

In other engines we have [ENGINE_NAME]_iterator
___
*[src/engines/blackhole.cc, line 168 at r3](https://reviewable.io/reviews/pmem/pmemkv/880#-MQr8PvbCtDEcfeaUGPY:-MQuoBlM0OFAv22-6yQF:bz8plyq) ([raw file](https://github.com/pmem/pmemkv/blob/c09fa3e6c5566a0e903ca45e14d34b29686ff4b2/src/engines/blackhole.cc#L168)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

is this used anywhere?
</blockquote></details>

Yes, It's used by LOG in iterator's methods

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/880)* status: all files reviewed, 1 unresolved discussion (waiting on @JanDorniak99)

___
*[src/engines/blackhole.cc, line 168 at r3](https://reviewable.io/reviews/pmem/pmemkv/880#-MQr8PvbCtDEcfeaUGPY:-MR-pMzc5lLMCcivAxo4:bihto6m) ([raw file](https://github.com/pmem/pmemkv/blob/c09fa3e6c5566a0e903ca45e14d34b29686ff4b2/src/engines/blackhole.cc#L168)):*
<details><summary><i>Previously, JanDorniak99 (Jan Dorniak) wrote…</i></summary><blockquote>

Yes, It's used by LOG in iterator's methods
</blockquote></details>

But why it's a free function? Shouldn't it be a member of iterator?

**Review by JanDorniak99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/880)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @igchor and @lukaszstolarczuk)

___
*[src/engines/blackhole.cc, line 168 at r3](https://reviewable.io/reviews/pmem/pmemkv/880#-MQr8PvbCtDEcfeaUGPY:-MRTqJ27BuJJZAwvln2w:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/c09fa3e6c5566a0e903ca45e14d34b29686ff4b2/src/engines/blackhole.cc#L168)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

But why it's a free function? Shouldn't it be a member of iterator?
</blockquote></details>

Done.

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/880#-:-MRUIDjrCRbhXM4DkZWB:bnfp4nl)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Pull request merged**
