### PR TITLE
Add ChangeLog 1.3-rc1

### PR DESCRIPTION
**Pull request by szyrom**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/799)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/799)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @szyrom)

___
*[ChangeLog, line 5 at r1](https://reviewable.io/reviews/pmem/pmemkv/799#-MIOfCMNAroe7r_vB_WC:-MIOfCMNAroe7r_vB_WD:b-w3n35s) ([raw file](https://github.com/pmem/pmemkv/blob/a49f6a346ab4ffc0b988917e99c974c1051640f6/ChangeLog#L5)):*
> ```
> 	* Version 1.3-rc1
> 
> 	This release introduces a new experimantal engine - radix (single-threaded
> ```

experimantal -> experimental
___
*[ChangeLog, line 8 at r1](https://reviewable.io/reviews/pmem/pmemkv/799#-MIOkp1_2Mb3YI0_1eDm:-MIOkp1_2Mb3YI0_1eDn:bt2mqon) ([raw file](https://github.com/pmem/pmemkv/blob/a49f6a346ab4ffc0b988917e99c974c1051640f6/ChangeLog#L8)):*
> ```
> 	sorted map, backed by libpmemobj-cpp's radix_tree container).
> 
> 	We have also extended configuration class API and support custom setters.
> ```

what do you mean by `custom setters`? ;)
___
*[ChangeLog, line 10 at r1](https://reviewable.io/reviews/pmem/pmemkv/799#-MIOoCnDCMpsswG_8zzl:-MIOoCnDCMpsswG_8zzm:b-oza16a) ([raw file](https://github.com/pmem/pmemkv/blob/a49f6a346ab4ffc0b988917e99c974c1051640f6/ChangeLog#L10)):*
> ```
> 	We have also extended configuration class API and support custom setters.
> 
> 	Features:
> ```

stree rework? (#681)
___
*[ChangeLog, line 19 at r1](https://reviewable.io/reviews/pmem/pmemkv/799#-MIOeTDw8i4mZvsHG8xZ:-MIOeTDw8i4mZvsHG8x_:b10qawf) ([raw file](https://github.com/pmem/pmemkv/blob/a49f6a346ab4ffc0b988917e99c974c1051640f6/ChangeLog#L19)):*
> ```
> 
> 	Other changes:
> 	- operator<< for pmem::kv::statuse
> ```

statuse -> status
___
*[ChangeLog, line 20 at r1](https://reviewable.io/reviews/pmem/pmemkv/799#-MIOo75A7CSZ6si1X7is:-MIOo75B8MIMGomoGHfM:b-ib31xj) ([raw file](https://github.com/pmem/pmemkv/blob/a49f6a346ab4ffc0b988917e99c974c1051640f6/ChangeLog#L20)):*
> ```
> 	Other changes:
> 	- operator<< for pmem::kv::statuse
> 	- extended compatibility tests
> ```

that's not really big change, I believe

**Review by igchor — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/799)* status: all files reviewed, 5 unresolved discussions (waiting on @szyrom)

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/799)* status: all files reviewed, 6 unresolved discussions (waiting on @szyrom)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/799#-MIYXvO7BBoXIu3pPY1f:-MIYXvO7BBoXIu3pPY1g:bfkarzn) (no related file):*
Add "known issues" section? 

---

**Review by szyrom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/799)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @igchor, @lukaszstolarczuk, and @szyrom)

___
*[ChangeLog, line 5 at r1](https://reviewable.io/reviews/pmem/pmemkv/799#-MIOfCMNAroe7r_vB_WC:-MIYhc0eEzeUP_QmGt7J:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/a49f6a346ab4ffc0b988917e99c974c1051640f6/ChangeLog#L5)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

experimantal -> experimental
</blockquote></details>

Done.
___
*[ChangeLog, line 8 at r1](https://reviewable.io/reviews/pmem/pmemkv/799#-MIOkp1_2Mb3YI0_1eDm:-MIYhdd2D3Mo-l2WBlc8:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/a49f6a346ab4ffc0b988917e99c974c1051640f6/ChangeLog#L8)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

what do you mean by `custom setters`? ;)
</blockquote></details>

Done.
___
*[ChangeLog, line 10 at r1](https://reviewable.io/reviews/pmem/pmemkv/799#-MIOoCnDCMpsswG_8zzl:-MIYheN803bRWD9JsseJ:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/a49f6a346ab4ffc0b988917e99c974c1051640f6/ChangeLog#L10)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

stree rework? (#681)
</blockquote></details>

Done.
___
*[ChangeLog, line 19 at r1](https://reviewable.io/reviews/pmem/pmemkv/799#-MIOeTDw8i4mZvsHG8xZ:-MIYhgGo899-S3Tl6wOj:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/a49f6a346ab4ffc0b988917e99c974c1051640f6/ChangeLog#L19)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

statuse -> status
</blockquote></details>

Done.
___
*[ChangeLog, line 20 at r1](https://reviewable.io/reviews/pmem/pmemkv/799#-MIOo75A7CSZ6si1X7is:-MIYhgiG5jYlM2wtSXaT:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/a49f6a346ab4ffc0b988917e99c974c1051640f6/ChangeLog#L20)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

that's not really big change, I believe
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/799)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @igchor and @szyrom)

___
*[ChangeLog, line 19 at r1](https://reviewable.io/reviews/pmem/pmemkv/799#-MIYs5lc-9RN3uI2h0Tc:-MIYs5lc-9RN3uI2h0Td:b-1zzmxr) ([raw file](https://github.com/pmem/pmemkv/blob/a49f6a346ab4ffc0b988917e99c974c1051640f6/ChangeLog#L19)):*
> ```
> operator<< for pmem::kv::status
> ```
that was worth mention, I believe ;)
___
*[ChangeLog, line 13 at r2](https://reviewable.io/reviews/pmem/pmemkv/799#-MIYr9oc4QGXAhO_RCZu:-MIYr9oc4QGXAhO_RCZv:br30c1u) ([raw file](https://github.com/pmem/pmemkv/blob/df27170f5009fe2a60c9c5bf00466a551fe748e0/ChangeLog#L13)):*
> ```
> 	Features:
> 	- radix engine (single-threaded sorted map)
> 	- config setters
> ```

... with type safety for [common] config fields (?)
___
*[ChangeLog, line 14 at r2](https://reviewable.io/reviews/pmem/pmemkv/799#-MIYre25-shs444c3xhR:-MIYre25-shs444c3xhS:b-bv6o4c) ([raw file](https://github.com/pmem/pmemkv/blob/df27170f5009fe2a60c9c5bf00466a551fe748e0/ChangeLog#L14)):*
> ```
> 	- radix engine (single-threaded sorted map)
> 	- config setters
> 	- stree egnine optimization (single-threaded sorted map with custom
> ```

egnine -> engine ;)

**Review by szyrom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/799)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @igchor, @lukaszstolarczuk, and @szyrom)

___
*[ChangeLog, line 19 at r1](https://reviewable.io/reviews/pmem/pmemkv/799#-MIYs5lc-9RN3uI2h0Tc:-MIYuesQ3kYruvhn290U:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/a49f6a346ab4ffc0b988917e99c974c1051640f6/ChangeLog#L19)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

> ```
> operator<< for pmem::kv::status
> ```
that was worth mention, I believe ;)
</blockquote></details>

Done.
___
*[ChangeLog, line 13 at r2](https://reviewable.io/reviews/pmem/pmemkv/799#-MIYr9oc4QGXAhO_RCZu:-MIYuh2N2FkIubsnP829:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/df27170f5009fe2a60c9c5bf00466a551fe748e0/ChangeLog#L13)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

... with type safety for [common] config fields (?)
</blockquote></details>

Done.
___
*[ChangeLog, line 14 at r2](https://reviewable.io/reviews/pmem/pmemkv/799#-MIYre25-shs444c3xhR:-MIYuf_uDNatMWYxhzJ7:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/df27170f5009fe2a60c9c5bf00466a551fe748e0/ChangeLog#L14)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

egnine -> engine ;)
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/799)* status: all files reviewed, 2 unresolved discussions (waiting on @szyrom)

___
*[ChangeLog, line 8 at r3](https://reviewable.io/reviews/pmem/pmemkv/799#-MIYv5VmCq0_hvG0YCjX:-MIYv5VmCq0_hvG0YCjY:bhgwcgl) ([raw file](https://github.com/pmem/pmemkv/blob/95340200b3f5e0f438ef9cedf0a12b3828925d94/ChangeLog#L8)):*
> ```
> 	sorted map, backed by libpmemobj-cpp's radix_tree container).
> 
> 	We have also extended configuration class API and redesign optimized
> ```

och sorry, and yet: redesign -> redesigned

**Review by szyrom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/799)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk and @szyrom)

___
*[ChangeLog, line 8 at r3](https://reviewable.io/reviews/pmem/pmemkv/799#-MIYv5VmCq0_hvG0YCjX:-MIYw6Tx1EiNj48WbwTh:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/95340200b3f5e0f438ef9cedf0a12b3828925d94/ChangeLog#L8)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

och sorry, and yet: redesign -> redesigned
</blockquote></details>

Done.

**Review by lukaszstolarczuk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/799#-:-MIYwRwD9FsNJ23oaXKA:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @szyrom)

**Pull request closed without merging**
