### PR TITLE
Add testing python bindings on Travis

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/445)

### CODE REVIEW

**Comment by ldorau** [comment]
It depends on https://github.com/pmem/pmemkv-python/pull/9

**Comment by lukaszstolarczuk** [comment]
please fix commit message "Correct some comments" is not very useful ;) at least put somehow "Travis" or "in Travis' files" in there ;)

**Comment by ldorau** [comment]
Depends on: https://github.com/pmem/pmemkv-python/pull/9

**Comment by lukaszstolarczuk** [comment]
@ldorau, ready for update :)

**Comment by ldorau** [comment]
> please fix commit message "Correct some comments" is not very useful ;) at least put somehow "Travis" or "in Travis' files" in there ;)

Done

**Comment by ldorau** [comment]
> @ldorau, ready for update :)

Done

**Comment by ldorau** [comment]
@lukaszstolarczuk  ready for review

**Pull request merged**
