### PR TITLE
Replace allocator wrapper with allocator factory

### PR DESCRIPTION
**Pull request by igchor**
To fix compilation errors on CentOS

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/979)

### CODE REVIEW

**Comment by igchor** [comment]
Link to CentOS build (not yet sure if successful ;d) https://github.com/igchor/pmemkv/runs/2148823857?check_suite_focus=true

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/979#-:-MW9p6fFAXl5VBEUeMKW:bnfp4nl)* status: 0 of 3 files reviewed, all discussions resolved

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/979#-:-MW9qfVU7aZHy52-vCBT:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/979#-MW9od3c-urVFWinEAPH:-MW9od3d0__MQcAAn-4n:b4z8ox4) (no related file):*
This was also reproducible on ubuntu 18.04 and rhel 8 (so please confirm, at least the first one)

---

**Review by karczex — COMMENTED** [review]
Please wait for clang format for testing engines to be merged:  
https://github.com/pmem/pmemkv/pull/976/commits/a60db4fac588935a632c86cb6e19cfe8ecb6b2a0 

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/979#-:-MW9tIykDZlt0ZINvrE7:b-mnhaxr)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)

**Review by KFilipek — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/979#-:-MWA6SzI1YE8MBDCU3Kg:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)

**Pull request merged**
