### PR TITLE
Fail in case of CMake Errors in ctest

### PR DESCRIPTION
**Pull request by ldorau**
Ref: #293

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/294)

### CODE REVIEW

**Comment by lukaszstolarczuk** [comment]
I agree with @marcinslusarz we should file an issue for ctest (they might somehow not be aware of that) and we could check test names with whitelist
And I agree with @ldorau this is a good way to catch CMake errors, which may occur similarly to this one

**Comment by ldorau** [comment]
@igchor @szyrom @lukaszstolarczuk  what about this PR?

**Comment by lukaszstolarczuk** [comment]
I'm ok with these changes. Guys wanted to consider if there are any (better?) approach, but I guess we don't have any other idea for now... so we should merge it?

**Comment by ldorau** [comment]
The "Check if a test name contains forbidden characters" commit was moved to https://github.com/pmem/pmemkv/pull/323

**Pull request closed without merging**
