### PR TITLE
Add Persistent column to Engines table

### PR DESCRIPTION
**Pull request by karczex**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/990)

### CODE REVIEW

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/990)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @karczex)

___
*[README.md, line 81 at r1](https://reviewable.io/reviews/pmem/pmemkv/990#-M_-XsyF4kWbLQlIGS6R:-M_-XsyG9PCAdutKMx_O:b-x2m3iq) ([raw file](https://github.com/pmem/pmemkv/blob/6c86077e0eb2a347f6a782557b2e892ee7bbbbb9/README.md#L81)):*
> ```Markdown
> | [csmap](doc/ENGINES-experimental.md#csmap) | [Concurrent sorted map](https://pmem.io/libpmemobj-cpp/master/doxygen/classpmem_1_1obj_1_1experimental_1_1concurrent__map.html) | Yes | Yes | Yes | Yes |
> | [radix](doc/ENGINES-experimental.md#radix) | [Radix tree](https://pmem.io/libpmemobj-cpp/master/doxygen/classpmem_1_1obj_1_1experimental_1_1radix__tree.html) | Yes | No | Yes | Yes |
> | [tree3](doc/ENGINES-experimental.md#tree3) | Persistent B+ tree | Yes | No | No | Yes |
> ```

Should we keep the persistent/volatile prefixes then?

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/990)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @igchor and @karczex)

___
*[README.md, line 75 at r1](https://reviewable.io/reviews/pmem/pmemkv/990#-M_-fhJt3cOhAuHxq7ly:-M_-fhJt3cOhAuHxq7lz:b-ip4980) ([raw file](https://github.com/pmem/pmemkv/blob/6c86077e0eb2a347f6a782557b2e892ee7bbbbb9/README.md#L75)):*
> ```Markdown
> | Engine Name  | Description | Experimental | Concurrent | Sorted | Persistent |
> | ------------ | ----------- | :-------------: | :-----------: | :-------: | :-------: |
> | [blackhole](doc/libpmemkv.7.md#blackhole) | Accepts everything, returns nothing | No | Yes | No | No |
> ```

you could move the blackhole to the bottom and add something like a separate section in this table - with separator line e.g. "Testing engines" and below of that separator there would be the two engines for testing...? what you think? I'm not even sure if we can do this (perhaps a second table should be added right underneath)
___
*[README.md, line 81 at r1](https://reviewable.io/reviews/pmem/pmemkv/990#-M_-XsyF4kWbLQlIGS6R:-M_-hPel3yTOHqvzZ0Rj:b-ugdhox) ([raw file](https://github.com/pmem/pmemkv/blob/6c86077e0eb2a347f6a782557b2e892ee7bbbbb9/README.md#L81)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Should we keep the persistent/volatile prefixes then?
</blockquote></details>

@igchor, you want to rename the old engines? I guess we may omit the prefix letters in new engines (as we do right now), but renaming is tricky ;)

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/990)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

___
*[README.md, line 81 at r1](https://reviewable.io/reviews/pmem/pmemkv/990#-M_-XsyF4kWbLQlIGS6R:-M_0Dued7ufEtdIdMh8F:b-uogfv0) ([raw file](https://github.com/pmem/pmemkv/blob/6c86077e0eb2a347f6a782557b2e892ee7bbbbb9/README.md#L81)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

@igchor, you want to rename the old engines? I guess we may omit the prefix letters in new engines (as we do right now), but renaming is tricky ;)
</blockquote></details>

I actually just mean the description in this table, e.g. "Persistent B+ tree" -> "B+ tree"

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/990)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @igchor and @karczex)

___
*[README.md, line 81 at r1](https://reviewable.io/reviews/pmem/pmemkv/990#-M_-XsyF4kWbLQlIGS6R:-M_0LEzt2yrWqjlBD-Rp:bfjdeyr) ([raw file](https://github.com/pmem/pmemkv/blob/6c86077e0eb2a347f6a782557b2e892ee7bbbbb9/README.md#L81)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I actually just mean the description in this table, e.g. "Persistent B+ tree" -> "B+ tree"
</blockquote></details>

hmm ok. I'd personally leave them, without these prefixes ("sorted" is also a separate column) you'd have two "B+ tree's" here (tree3 & stree) ;)

**Review by igchor — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/990)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)

**Review by KFilipek — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/990#-:-Ma9Eh9s4rUslMSh85_l:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/990#-:-MexrvFc0aJ0gIoTOUZ9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)

**Pull request merged**
