### PR TITLE
Update testcases

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/734)

### CODE REVIEW

**Comment by karczex** [comment]
___
*[tests/engine_scenarios/all/put_get_remove.cc, line 336 at r2](https://reviewable.io/reviews/pmem/pmemkv/734#-MF0iLoE0l7yPTJc0Lcq:-MF0fc5Z-uCTbT8n9LJP:b3iskta) ([raw file](https://github.com/pmem/pmemkv/blob/ea70e9e5113bf37112532c67095b7cba9fc45297/tests/engine_scenarios/all/put_get_remove.cc#L336)):*
> ```cpp
> 	UT_ASSERT(kv_new.remove("key1") == status::OK);
> 	UT_ASSERT(kv_new.remove("key2") == status::OK);
> ```

What happen with kv object?

**Review by lukaszstolarczuk — COMMENTED** [review]
// re-based with latest changes on master

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/734#-:-MF7QFMz9DYW5KVuJbp4:b-118dfp)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @igchor and @karczex)

___
*[tests/engine_scenarios/all/put_get_remove.cc, line 336 at r2](https://reviewable.io/reviews/pmem/pmemkv/734#-MF0iLoE0l7yPTJc0Lcq:-MF7PgCcA4dqsp5ntfnD:b-uv9jkd) ([raw file](https://github.com/pmem/pmemkv/blob/ea70e9e5113bf37112532c67095b7cba9fc45297/tests/engine_scenarios/all/put_get_remove.cc#L336)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

What happen with kv object?
</blockquote></details>

as discussed on the meeting - we can't check for anything related to this old kv object, its private field is set to nullptr, but other than that

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/734)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[tests/engine_scenarios/all/put_get_remove.cc, line 369 at r3](https://reviewable.io/reviews/pmem/pmemkv/734#-MFBG05MBqEpXlfxxGaz:-MFBG05MBqEpXlfxxGb-:b-vjpxp6) ([raw file](https://github.com/pmem/pmemkv/blob/6f7e4358fc1e5a191362f1420b0b20c5c92d90e8/tests/engine_scenarios/all/put_get_remove.cc#L369)):*
> ```cpp
> 
> 	/* put key1 in original db */
> 	UT_ASSERT(kv.put("key1", "value1") == status::OK);
> ```

ASSERT_STATUS
___
*[tests/engine_scenarios/all/put_get_remove.cc, line 373 at r3](https://reviewable.io/reviews/pmem/pmemkv/734#-MFBG2Ul4gj-xX57_9ct:-MFBG2Ul4gj-xX57_9cu:b3kqx) ([raw file](https://github.com/pmem/pmemkv/blob/6f7e4358fc1e5a191362f1420b0b20c5c92d90e8/tests/engine_scenarios/all/put_get_remove.cc#L373)):*
> ```cpp
> 	db kv_new(std::move(kv));
> 
> 	UT_ASSERT(kv_new.put("key2", "value2") == status::OK);
> ```

.
___
*[tests/engine_scenarios/all/put_get_remove.cc, line 379 at r3](https://reviewable.io/reviews/pmem/pmemkv/734#-MFBFxW040BLbjphq41L:-MFBFxW040BLbjphq41M:b-5jhmc) ([raw file](https://github.com/pmem/pmemkv/blob/6f7e4358fc1e5a191362f1420b0b20c5c92d90e8/tests/engine_scenarios/all/put_get_remove.cc#L379)):*
> ```
> UT_ASSERT(kv_new.remove("key1") == status::OK);
> 	UT_ASSERT(kv_new.remove("key2") == status::OK);
> ```
ASSERT_STATUS

**Review by karczex — COMMENTED** [review]
> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/734)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/734)* status: 1 of 4 files reviewed, 6 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[tests/config/config_cpp.cc, line 280 at r3](https://reviewable.io/reviews/pmem/pmemkv/734#-MFBGF7XBw_RvyGRMjSR:-MFBGF7XBw_RvyGRMjSS:b3kqx) ([raw file](https://github.com/pmem/pmemkv/blob/6f7e4358fc1e5a191362f1420b0b20c5c92d90e8/tests/config/config_cpp.cc#L280)):*
> ```cpp
> 	cfg = new config();
> 	s = cfg->put_string("string", "config");
> 	UT_ASSERTeq(s, status::OK);
> ```

.
___
*[tests/config/config_cpp.cc, line 284 at r3](https://reviewable.io/reviews/pmem/pmemkv/734#-MFBGE56143vsle84nMv:-MFBGE56143vsle84nMw:b3kqx) ([raw file](https://github.com/pmem/pmemkv/blob/6f7e4358fc1e5a191362f1420b0b20c5c92d90e8/tests/config/config_cpp.cc#L284)):*
> ```cpp
> 	config *move_assign = new config();
> 	s = move_assign->put_string("move_string", "value");
> 	UT_ASSERTeq(s, status::OK);
> ```

.
___
*[tests/config/config_cpp.cc, line 291 at r3](https://reviewable.io/reviews/pmem/pmemkv/734#-MFBGCYD7H-kUydZkJY5:-MFBGCYD7H-kUydZkJY6:b3kqx) ([raw file](https://github.com/pmem/pmemkv/blob/6f7e4358fc1e5a191362f1420b0b20c5c92d90e8/tests/config/config_cpp.cc#L291)):*
> ```cpp
> 	std::string string_s;
> 	s = move_assign->get_string("move_string", string_s);
> 	UT_ASSERTeq(s, status::NOT_FOUND);
> ```

.

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/734)* status: 1 of 4 files reviewed, 6 unresolved discussions (waiting on @igchor and @karczex)

___
*[tests/config/config_cpp.cc, line 280 at r3](https://reviewable.io/reviews/pmem/pmemkv/734#-MFBGF7XBw_RvyGRMjSR:-MFCCR9Z7gtRv9SxJD8P:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/6f7e4358fc1e5a191362f1420b0b20c5c92d90e8/tests/config/config_cpp.cc#L280)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/config/config_cpp.cc, line 284 at r3](https://reviewable.io/reviews/pmem/pmemkv/734#-MFBGE56143vsle84nMv:-MFCCQaW6zmAdnbvdcYh:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/6f7e4358fc1e5a191362f1420b0b20c5c92d90e8/tests/config/config_cpp.cc#L284)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/config/config_cpp.cc, line 291 at r3](https://reviewable.io/reviews/pmem/pmemkv/734#-MFBGCYD7H-kUydZkJY5:-MFCCQnz65asLEgOhGgj:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/6f7e4358fc1e5a191362f1420b0b20c5c92d90e8/tests/config/config_cpp.cc#L291)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/engine_scenarios/all/put_get_remove.cc, line 369 at r3](https://reviewable.io/reviews/pmem/pmemkv/734#-MFBG05MBqEpXlfxxGaz:-MFCD4UfDGMm7ENZsp03:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/6f7e4358fc1e5a191362f1420b0b20c5c92d90e8/tests/engine_scenarios/all/put_get_remove.cc#L369)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

ASSERT_STATUS
</blockquote></details>

Done.
___
*[tests/engine_scenarios/all/put_get_remove.cc, line 373 at r3](https://reviewable.io/reviews/pmem/pmemkv/734#-MFBG2Ul4gj-xX57_9ct:-MFCD4mv3kNefPC4k9jL:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/6f7e4358fc1e5a191362f1420b0b20c5c92d90e8/tests/engine_scenarios/all/put_get_remove.cc#L373)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/engine_scenarios/all/put_get_remove.cc, line 379 at r3](https://reviewable.io/reviews/pmem/pmemkv/734#-MFBFxW040BLbjphq41L:-MFCD5heENgNm9lfjRdu:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/6f7e4358fc1e5a191362f1420b0b20c5c92d90e8/tests/engine_scenarios/all/put_get_remove.cc#L379)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

> ```
> UT_ASSERT(kv_new.remove("key1") == status::OK);
> 	UT_ASSERT(kv_new.remove("key2") == status::OK);
> ```
ASSERT_STATUS
</blockquote></details>

Done.

**Review by karczex — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/734#-:-MFElQyo9cavk8RnlHaP:bnfp4nl)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @igchor)

**Pull request merged**
