### PR TITLE
Null config

### PR DESCRIPTION
**Pull request by karczex**
---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/998)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/998)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @karczex)

___
*[src/libpmemkv_json_config.cc, line 50 at r1](https://reviewable.io/reviews/pmem/pmemkv/998#-McNgSMzBla0a7A4pMDb:-McNgSN-AvsPSreBD43J:brvd671) ([raw file](https://github.com/pmem/pmemkv/blob/3763648e8d4b0f8b50e8f287d619ada8380e3fd3/src/libpmemkv_json_config.cc#L50)):*
> ```cpp
> 	try {
> 		if (!config) {
> 			throw std::runtime_error("Config have to be specified");
> ```

has to be
___
*[src/libpmemkv_json_config.cc, line 54 at r1](https://reviewable.io/reviews/pmem/pmemkv/998#-McNgUzV1pgmFoawPGdk:-McNgUzV1pgmFoawPGdl:b3kqx) ([raw file](https://github.com/pmem/pmemkv/blob/3763648e8d4b0f8b50e8f287d619ada8380e3fd3/src/libpmemkv_json_config.cc#L54)):*
> ```cpp
> 		if (!json) {
> 			throw std::runtime_error(
> 				"Configuration json have to be specified");
> ```

.
___
*[tests/config/json_to_config.cc, line 100 at r1](https://reviewable.io/reviews/pmem/pmemkv/998#-McNgh1b5TJ2d__jP9qd:-McNgh1b5TJ2d__jP9qe:b3kqx) ([raw file](https://github.com/pmem/pmemkv/blob/3763648e8d4b0f8b50e8f287d619ada8380e3fd3/tests/config/json_to_config.cc#L100)):*
> ```cpp
> 	ASSERT_EQ(ret, PMEMKV_STATUS_CONFIG_PARSING_ERROR);
> 	ASSERT_EQ(std::string(pmemkv_config_from_json_errormsg()),
> 		  "[pmemkv_config_from_json] Configuration json have to be specified");
> ```

.

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/998)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[src/libpmemkv_json_config.cc, line 50 at r1](https://reviewable.io/reviews/pmem/pmemkv/998#-McNgSMzBla0a7A4pMDb:-McOEHKP8LnoDO_zBlBS:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/3763648e8d4b0f8b50e8f287d619ada8380e3fd3/src/libpmemkv_json_config.cc#L50)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

has to be
</blockquote></details>

Done.
___
*[src/libpmemkv_json_config.cc, line 54 at r1](https://reviewable.io/reviews/pmem/pmemkv/998#-McNgUzV1pgmFoawPGdk:-McOEHk0BvTO65j83tI1:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/3763648e8d4b0f8b50e8f287d619ada8380e3fd3/src/libpmemkv_json_config.cc#L54)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/config/json_to_config.cc, line 100 at r1](https://reviewable.io/reviews/pmem/pmemkv/998#-McNgh1b5TJ2d__jP9qd:-McOEK2FCodd2i9ZavNm:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/3763648e8d4b0f8b50e8f287d619ada8380e3fd3/tests/config/json_to_config.cc#L100)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/998#-:-McOFCT-9Q-sJ5P3C823:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/998#-:-McTItd50AzNrBwMyBVb:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)

**Pull request merged**
