### PR TITLE
Iterator result

### PR DESCRIPTION
**Pull request by karczex**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1011)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1011)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/1011#-MdwETywAkxKRn9LgtjX:-MdwETywAkxKRn9LgtjY:b-nwrcww) (no related file):*
pls rebase to 1.4

---

**Review by igchor — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 7 of 7 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1011#-:-Mdzs7U17AI5Xdiip3B9:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1011)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/1011#-MdwETywAkxKRn9LgtjX:-Mdzu5isDp2LdgxaJjEw:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls rebase to 1.4
</blockquote></details>

Done.

---

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 6 of 7 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1011#-:-Mdzy-Lo8TygV86ArpOS:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)

**Pull request merged**
