### PR TITLE
Update memkind version to v1.13.0

### PR DESCRIPTION
**Pull request by PatKamin**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1053)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1053)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Comment by lukaszstolarczuk** [comment]
Before merging this we have to update the docker files (Ubuntu 20.10 is EOL now).

**Comment by lukaszstolarczuk** [comment]
@PatKamin can you please rebase and push it one more time - the CI should be green now 😉

**Review by PatKamin — COMMENTED** [review]
Rebased.

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1053#-:-Muk42AL69JjQG2R52Ld:bncvegj)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Review by lukaszstolarczuk — COMMENTED** [review]
Thx!
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1053#-:-MukNDI13KOyWrZtcSSB:bdcn47o)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PatKamin)

**Pull request merged**
