### PR TITLE
Docs cleanups

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
preview: https://github.com/lukaszstolarczuk/pmemkv/tree/small-doc-cleanups#pmemkv

- [x] update release steps, if we agree to remove multiple links to C++ API

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/829)

### CODE REVIEW

**Review by igchor — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/829#-:-MJkclBzBWWTXxEGNjJz:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/829)* status: all files reviewed, 1 unresolved discussion

___
*[README.md, line 21 at r1](https://reviewable.io/reviews/pmem/pmemkv/829#-MJkwMNB8pTQyvFAurD4:-MJkwMNB8pTQyvFAurD5:b7kp0e8) ([raw file](https://github.com/pmem/pmemkv/blob/5e62b9be341c0c23fa4f67c2d03e6580e07e00ad/README.md#L21)):*
> ```Markdown
> and **C++ API** docs in form of Doxygen html files see: https://pmem.io/pmemkv.
> Documentation is available for each branch/release. For most recent always see
> **master**'s version.
> ```

add link to master (cpp only?)

**Review by igchor — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/829#-:-MJztRKl5ohRUkzsYBma:bnfp4nl)* status: 7 of 9 files reviewed, all discussions resolved (waiting on @igchor)

**Review by karczex — COMMENTED** [review]
> Reviewed 7 of 8 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/829)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @igchor and @lukaszstolarczuk)

___
*[README.md, line 24 at r2](https://reviewable.io/reviews/pmem/pmemkv/829#-MK11bhl51googY3NuR9:-MK11bhl51googY3NuRA:bgy0kf0) ([raw file](https://github.com/pmem/pmemkv/blob/16d8f5e01c5496c583dda9e5231f163990ad19f1/README.md#L24)):*
> ```Markdown
> The C++ API of pmemkv is documented in the Doxygen documentation listed below:
> 
> - [master](https://pmem.io/pmemkv/master/doxygen/index.html)
> ```

Please, leave link to  documentation of master branch.

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/829)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @igchor and @karczex)

___
*[README.md, line 24 at r2](https://reviewable.io/reviews/pmem/pmemkv/829#-MK11bhl51googY3NuR9:-MK3vBk35dmgMQMZyjM8:b4oqpd6) ([raw file](https://github.com/pmem/pmemkv/blob/16d8f5e01c5496c583dda9e5231f163990ad19f1/README.md#L24)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

Please, leave link to  documentation of master branch.
</blockquote></details>

there's one (actually two - for C and C++) just few lines above

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/829)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @igchor and @karczex)

___
*[README.md, line 24 at r2](https://reviewable.io/reviews/pmem/pmemkv/829#-MK11bhl51googY3NuR9:-MK3yXekDj0yrhpminSM:bq723tk) ([raw file](https://github.com/pmem/pmemkv/blob/16d8f5e01c5496c583dda9e5231f163990ad19f1/README.md#L24)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

there's one (actually two - for C and C++) just few lines above
</blockquote></details>

I've rewritten it a little, for links to be more distinct, more visible

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/829#-:-MK4TDcK6gm3hxxg5YTk:bnfp4nl)* status: 8 of 9 files reviewed, all discussions resolved (waiting on @igchor)

**Pull request merged**
