### PR TITLE
Update memkind version in installation script

### PR DESCRIPTION
**Pull request by michalbiesek**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/684)

### CODE REVIEW

**Comment by lukaszstolarczuk** [comment]
I allowed myself to convert it into draft, so we won't merge it until it's officially released.

**Comment by michalbiesek** [comment]
> I allowed myself to convert it into draft, so we won't merge it until it's officially released.

I bump the version to 1.10.1 - it is an official release.

**Review by lukaszstolarczuk — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/684)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by lukaszstolarczuk — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/684#-:-MHQDXRCAwUl6xGGsD1G:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/684#-:-MHQUYsT7W0B4pT62LTd:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
