### PR TITLE
[bug template] change body to have tables instead of questions

### PR DESCRIPTION
**Pull request by KFilipek**
Intention of this PR is to make bug reports a little bit clearer. I've created issue with such formatting here: #950.
[Preview of this template is here](https://github.com/pmem/pmemkv/blob/014a138c1ed428526ea01f9dea5c5d6132baad0e/.github/ISSUE_TEMPLATE/bug_report.md)

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/951)

### CODE REVIEW

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/951#-:-MUhpUxgDNOquB0YtML7:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @KFilipek)

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/951)* status: all files reviewed, 3 unresolved discussions (waiting on @KFilipek)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/951#-MUhsHVp84NEzGll0Idu:-MUhsHVp84NEzGll0Idv:bui4lg4) (no related file):*
I'll just say it, it's non-blocking:
people who are not familiar with md-style tables may break this and it may end up looking like rubbish ;) :D 

---
___
*[.github/ISSUE_TEMPLATE/bug_report.md, line 22 at r1](https://reviewable.io/reviews/pmem/pmemkv/951#-MUhqzaiD98k_DPcSfnF:-MUhqzaiD98k_DPcSfnG:bz5oucn) ([raw file](https://github.com/pmem/pmemkv/blob/014a138c1ed428526ea01f9dea5c5d6132baad0e/.github/ISSUE_TEMPLATE/bug_report.md#L22)):*
> ```Markdown
> | pmemkv version(s)            |  |
> | libpmemobj-cpp version(s)    |  |
> | PMDK (libpmem/libpmemobj) package version(s) |  |
> ```

perhaps BTW drop "package" in this line
___
*[.github/ISSUE_TEMPLATE/bug_report.md, line 27 at r1](https://reviewable.io/reviews/pmem/pmemkv/951#-MUhsCBY1G_cJL6wlMGz:-MUhsCBY1G_cJL6wlMH-:b-pbed79) ([raw file](https://github.com/pmem/pmemkv/blob/014a138c1ed428526ea01f9dea5c5d6132baad0e/.github/ISSUE_TEMPLATE/bug_report.md#L27)):*
> ```Markdown
> | compiler, libraries, packaging and other related tools version(s) |  |
> 
> and if used:
> ```

perhaps `and if applicable:`

**Review by KFilipek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/951)* status: all files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/951#-MUhsHVp84NEzGll0Idu:-MUjSj65EZrutTO0roPP:b-oduiaf) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I'll just say it, it's non-blocking:
people who are not familiar with md-style tables may break this and it may end up looking like rubbish ;) :D 
</blockquote></details>

People who are not familiar will have chance to learn something new.
Done.

---
___
*[.github/ISSUE_TEMPLATE/bug_report.md, line 22 at r1](https://reviewable.io/reviews/pmem/pmemkv/951#-MUhqzaiD98k_DPcSfnF:-MUjSgNWDeyk41tRDO89:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/014a138c1ed428526ea01f9dea5c5d6132baad0e/.github/ISSUE_TEMPLATE/bug_report.md#L22)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps BTW drop "package" in this line
</blockquote></details>

Done.
___
*[.github/ISSUE_TEMPLATE/bug_report.md, line 27 at r1](https://reviewable.io/reviews/pmem/pmemkv/951#-MUhsCBY1G_cJL6wlMGz:-MUjSTYzEjvjjn4qPQTN:bkoinqt) ([raw file](https://github.com/pmem/pmemkv/blob/014a138c1ed428526ea01f9dea5c5d6132baad0e/.github/ISSUE_TEMPLATE/bug_report.md#L27)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps `and if applicable:`
</blockquote></details>

It's a synonym, but okey.
Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/951)* status: all files reviewed, 2 unresolved discussions (waiting on @KFilipek)

___
*[.github/ISSUE_TEMPLATE/bug_report.md, line 22 at r1](https://reviewable.io/reviews/pmem/pmemkv/951#-MUhqzaiD98k_DPcSfnF:-MUo1n3X0PJi0PpdLLUx:b-9qg1u4) ([raw file](https://github.com/pmem/pmemkv/blob/014a138c1ed428526ea01f9dea5c5d6132baad0e/.github/ISSUE_TEMPLATE/bug_report.md#L22)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

not done
___
*[.github/ISSUE_TEMPLATE/bug_report.md, line 27 at r1](https://reviewable.io/reviews/pmem/pmemkv/951#-MUhsCBY1G_cJL6wlMGz:-MUo1s7Z362rAoso86eU:b2l4tam) ([raw file](https://github.com/pmem/pmemkv/blob/014a138c1ed428526ea01f9dea5c5d6132baad0e/.github/ISSUE_TEMPLATE/bug_report.md#L27)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

It's a synonym, but okey.
Done.
</blockquote></details>

memkind/tbb are used in pmemkv almost all the time (vc/vs-map are turned on by default), but it may be not **applicable** in the current issue...

also not done ;)

**Review by KFilipek — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/951)* status: all files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[.github/ISSUE_TEMPLATE/bug_report.md, line 22 at r1](https://reviewable.io/reviews/pmem/pmemkv/951#-MUhqzaiD98k_DPcSfnF:-MUo3-xN6QOq7dkQB91j:bam0awn) ([raw file](https://github.com/pmem/pmemkv/blob/014a138c1ed428526ea01f9dea5c5d6132baad0e/.github/ISSUE_TEMPLATE/bug_report.md#L22)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

not done
</blockquote></details>

done, but was not pushed
___
*[.github/ISSUE_TEMPLATE/bug_report.md, line 27 at r1](https://reviewable.io/reviews/pmem/pmemkv/951#-MUhsCBY1G_cJL6wlMGz:-MUo32ro8My7odjoB_ly:bam0awn) ([raw file](https://github.com/pmem/pmemkv/blob/014a138c1ed428526ea01f9dea5c5d6132baad0e/.github/ISSUE_TEMPLATE/bug_report.md#L27)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

memkind/tbb are used in pmemkv almost all the time (vc/vs-map are turned on by default), but it may be not **applicable** in the current issue...

also not done ;)
</blockquote></details>

done, but was not pushed

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/951#-:-MUo4XML69kurwU8pUh6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KFilipek)

**Review by JanDorniak99 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/951)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KFilipek)

**Pull request merged**
