### PR TITLE
Add option to turn BUILD_JSON_CONFIG off on Travis

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/529)

### CODE REVIEW

**Comment by lukaszstolarczuk** [comment]
I think the syntax is "${BUILD_JSON_CONFIG:ON}" -> "${BUILD_JSON_CONFIG:-ON}"

**Comment by ldorau** [comment]
> I think the syntax is "${BUILD_JSON_CONFIG:ON}" -> "${BUILD_JSON_CONFIG:-ON}"

Thanks! Done.

**Comment by ldorau** [comment]
> You from future would be pleased, if you write some cool "why" story in commit message.
> 

@karczex Done

**Comment by lukaszstolarczuk** [comment]
@ldorau, need to rebase and resolve conflict

**Pull request merged**
