### PR TITLE
cmake: prioritize TBB_DIR to find TBB module

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/932)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/932)* status: 0 of 1 files reviewed, 1 unresolved discussion

___
*[cmake/tbb.cmake, line 15 at r1](https://reviewable.io/reviews/pmem/pmemkv/932#-MT_xZd20rNhejQnnp4E:-MT_xZd20rNhejQnnp4F:b-oa4zei) ([raw file](https://github.com/pmem/pmemkv/blob/5954ef6fce7aba69ed5c8c05746188a66e714f3a/cmake/tbb.cmake#L15)):*
> ```CMake
> if(TBB_DIR)
> 	message(STATUS "  CMake param TBB_DIR was set, look in there (${TBB_DIR})")
> 	find_package(TBB REQUIRED tbb NO_DEFAULT_PATH) # XXX or should it be quiet? right now it fails if TBB_DIR does not contain TBB
> ```

right now (as it says in the comment) I set it to REQUIRE and check only for within of the TBB_DIR. If we set TBB_DIR it means we know what we're doing, right...?

as an alternative, we could make it quiet and just easily go to another ways of finding TBB... This seems like an easier approach for newcomers, but it may lead to quietly omit the TBB_DIR (e.g. when we're debugging something with custom tbb). It's all in the logs, so maybe it's just me, being picky...

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/932)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[cmake/tbb.cmake, line 15 at r1](https://reviewable.io/reviews/pmem/pmemkv/932#-MT_xZd20rNhejQnnp4E:-MTaC-bD8UeLJBqfD-5I:b-x0m8qk) ([raw file](https://github.com/pmem/pmemkv/blob/5954ef6fce7aba69ed5c8c05746188a66e714f3a/cmake/tbb.cmake#L15)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

right now (as it says in the comment) I set it to REQUIRE and check only for within of the TBB_DIR. If we set TBB_DIR it means we know what we're doing, right...?

as an alternative, we could make it quiet and just easily go to another ways of finding TBB... This seems like an easier approach for newcomers, but it may lead to quietly omit the TBB_DIR (e.g. when we're debugging something with custom tbb). It's all in the logs, so maybe it's just me, being picky...
</blockquote></details>

I think it's OK as it is, maybe just add additional message if TBB is not found by find_package saying: "you can unset TBB_DIR to use pkg-config" or something?
___
*[cmake/tbb.cmake, line 29 at r1](https://reviewable.io/reviews/pmem/pmemkv/932#-MTaCSOG5nOEnfZSEqEF:-MTaCSOG5nOEnfZSEqEG:bopjelf) ([raw file](https://github.com/pmem/pmemkv/blob/5954ef6fce7aba69ed5c8c05746188a66e714f3a/cmake/tbb.cmake#L29)):*
> ```CMake
> 	endif()
> 
> 	unset(TBB_FOUND CACHE)
> ```

maybe just put this code in some function to avoid duplication?

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/932)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @igchor)

___
*[cmake/tbb.cmake, line 15 at r1](https://reviewable.io/reviews/pmem/pmemkv/932#-MT_xZd20rNhejQnnp4E:-MTdnAHq5Cgr6L2Kf_hG:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/5954ef6fce7aba69ed5c8c05746188a66e714f3a/cmake/tbb.cmake#L15)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think it's OK as it is, maybe just add additional message if TBB is not found by find_package saying: "you can unset TBB_DIR to use pkg-config" or something?
</blockquote></details>

Done.
___
*[cmake/tbb.cmake, line 29 at r1](https://reviewable.io/reviews/pmem/pmemkv/932#-MTaCSOG5nOEnfZSEqEF:-MTdnCHQ0_t-ZcAOwS1a:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/5954ef6fce7aba69ed5c8c05746188a66e714f3a/cmake/tbb.cmake#L29)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

maybe just put this code in some function to avoid duplication?
</blockquote></details>

Done.

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/932)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[cmake/tbb.cmake, line 7 at r2](https://reviewable.io/reviews/pmem/pmemkv/932#-MTuCxzCAqDtJtgdheyu:-MTuCxzCAqDtJtgdheyv:b-y188fp) ([raw file](https://github.com/pmem/pmemkv/blob/1808879cb42cc7701c4caaddf60ede0375729248/cmake/tbb.cmake#L7)):*
> ```CMake
> 
> function(found_info)
> 	set(TBB_LIBRARIES ${TBB_IMPORTED_TARGETS} PARENT_SCOPE)
> ```

Hm, the name of the function suggests it only prints info but here you also set the global variable - maybe change the name?

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/932)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @igchor)

___
*[cmake/tbb.cmake, line 7 at r2](https://reviewable.io/reviews/pmem/pmemkv/932#-MTuCxzCAqDtJtgdheyu:-MTum1CQEJDsQvlGQuYg:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/1808879cb42cc7701c4caaddf60ede0375729248/cmake/tbb.cmake#L7)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Hm, the name of the function suggests it only prints info but here you also set the global variable - maybe change the name?
</blockquote></details>

Done.

**Review by igchor — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/932#-:-MU8Entk89J4mVyXLq8Z:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Review by KFilipek — APPROVED** [review]

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/932#-:-MUJlHme2hMfZhagqPzE:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @igchor)

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/932#-:-MUJoZFAAoOJF7JK2wX1:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @igchor)

**Pull request merged**
