### PR TITLE
Print signal name in tests backtrace

### PR DESCRIPTION
**Pull request by karczex**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/764)

### CODE REVIEW

**Review by szyrom — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/764#-:-MGI9Md483Vz0PqfNUEL:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/764)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)

___
*[tests/common/test_backtrace.c, line 31 at r1](https://reviewable.io/reviews/pmem/pmemkv/764#-MGIRvj5D7VI0ahFjK0l:-MGIRvj5D7VI0ahFjK0m:b-ba8gb2) ([raw file](https://github.com/pmem/pmemkv/blob/7db9216420a88e8b2348ea6c412ceb3eddb812cb/tests/common/test_backtrace.c#L31)):*
> ```C
> 
> static const Signal signals[] = {
> 	{SIGINT, "SIGINT"},	  {SIGILL, "SIGILL"},	{SIGABRT, "SIGABRT"},
> ```

FYI, the signals are numberd from 1 to some value (the domain is continuous). Howver, the order is wrong here (e.g. SIGINT is equal to 2, not to 1).

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/764)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @igchor and @szyrom)

___
*[tests/common/test_backtrace.c, line 31 at r1](https://reviewable.io/reviews/pmem/pmemkv/764#-MGIRvj5D7VI0ahFjK0l:-MGJ1tF62Ou7VW9tMHx2:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/7db9216420a88e8b2348ea6c412ceb3eddb812cb/tests/common/test_backtrace.c#L31)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

FYI, the signals are numberd from 1 to some value (the domain is continuous). Howver, the order is wrong here (e.g. SIGINT is equal to 2, not to 1).
</blockquote></details>

Done.

**Review by igchor — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/764#-:-MGO2P7KBQrRCRhjFt6Y:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
