### PR TITLE
Implement radix engine on top of radix_tree

### PR DESCRIPTION
**Pull request by igchor**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/750)

### CODE REVIEW

**Review by szyrom — CHANGES_REQUESTED** [review]
update libpmemkv.7.md line 137

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/750#-:-MF1k4fF24Mn-3HguX5V:b-dmhqj4)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)

___
*[src/engines-experimental/radix.h, line 48 at r1](https://reviewable.io/reviews/pmem/pmemkv/750#-MF1jwgM1IkEYFl_dEwA:-MF1jwgN3GasBdbBtSM7:brjnhpa) ([raw file](https://github.com/pmem/pmemkv/blob/0d0353d044c20d1d6ace28e3b8b8da589afd7cce/src/engines-experimental/radix.h#L48)):*
> ```objc
> } /* namespace internal */
> 
> class radix : public pmemobj_engine_base<internal::radix::pmem_type> {
> ```

please describe briefly the algorithm and add a link to original implementation

**Review by igchor — COMMENTED** [review]
Done. (Also, was wondering if we should wait for implementing the final version of pmem::obj::string before switching to using it here. I don't see any problems with merging it as it though. As long as we relase the final string_view in libpmemobj-cpp before pmemkv it's fine).

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/750#-:-MF5V6xL-K5VBGDbKrkG:b-oc8xh6)* status: all files reviewed, 1 unresolved discussion (waiting on @szyrom)

___
*[src/engines-experimental/radix.h, line 48 at r1](https://reviewable.io/reviews/pmem/pmemkv/750#-MF1jwgM1IkEYFl_dEwA:-MF5SDlG-T-wC5kJuzwE:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/0d0353d044c20d1d6ace28e3b8b8da589afd7cce/src/engines-experimental/radix.h#L48)):*
<details><summary><i>Previously, szyrom (Szymon Romik) wrote…</i></summary><blockquote>

please describe briefly the algorithm and add a link to original implementation
</blockquote></details>

Done.

**Review by szyrom — APPROVED** [review]
I don't see any problems either. 

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/750#-:-MFB228UB7Lv8iaFFNU4:b-hk5lu2)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by szyrom — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/750#-:-MFB25cwB30ewUngfy4w:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by lukaszstolarczuk — CHANGES_REQUESTED** [review]
> Reviewed 5 of 8 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/750)* status: all files reviewed, 11 unresolved discussions (waiting on @igchor)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/750#-MFBLt_WBRo8oAxm7VMN:-MFBLt_XD7Vmp77kvrFy:b-wqgtf0) (no related file):*
`radix` -> `sradix` ?

---
*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/750#-MFBc6-OE-7QYyEooX2H:-MFBc6-OE-7QYyEooX2I:by8xxav) (no related file):*
Please update `ENGINES-experimental.md` file and "Storage Engines" section in `README.md`

---
___
*[CMakeLists.txt, line 54 at r2](https://reviewable.io/reviews/pmem/pmemkv/750#-MFBEjbaB_QYmKMcsz8O:-MFBEjbaB_QYmKMcsz8P:bwjwvg1) ([raw file](https://github.com/pmem/pmemkv/blob/1c6fdfb8b125b128fd29b69d60cbeaa76ad4689c/CMakeLists.txt#L54)):*
> ```CMake
> 		CACHE STRING "Choose a type of build (Debug, Release or RelWithDebInfo)" FORCE)
> endif()
> if(ENGINE_RADIX)
> ```

please move it down below, with other status messages
(part of the file with comment `Setup defines and check status of each engine`)
___
*[doc/libpmemkv.7.md, line 132 at r2](https://reviewable.io/reviews/pmem/pmemkv/750#-MFBEx354MCkwt4RYCAF:-MFBEx354MCkwt4RYCAG:b9px0z2) ([raw file](https://github.com/pmem/pmemkv/blob/1c6fdfb8b125b128fd29b69d60cbeaa76ad4689c/doc/libpmemkv.7.md#L132)):*
> ```Markdown
> 
> There are also more engines in various states of development, for details see <https://github.com/pmem/pmemkv/blob/master/ENGINES-experimental.md>.
> Three of them (radix, tree3, stree and csmap) requires the config parameters like cmap and similarly to cmap should not be used within libpmemobj transaction(s).
> ```

"Three of them" -> "Four.." or "Some.."
___
*[src/engines-experimental/radix.h, line 10 at r2](https://reviewable.io/reviews/pmem/pmemkv/750#-MFBLnf4AgIquoy6hx5R:-MFBLnf558RpQR9wJXcx:b3kre) ([raw file](https://github.com/pmem/pmemkv/blob/1c6fdfb8b125b128fd29b69d60cbeaa76ad4689c/src/engines-experimental/radix.h#L10)):*
> ```objc
> 
> #include <libpmemobj++/container/string.hpp>
> #include <libpmemobj++/experimental/concurrent_map.hpp>
> ```

?
___
*[src/engines-experimental/radix.h, line 52 at r2](https://reviewable.io/reviews/pmem/pmemkv/750#-MFBZ_ra0d7C4qHIL9-n:-MFBZ_ra0d7C4qHIL9-o:bwcjxt3) ([raw file](https://github.com/pmem/pmemkv/blob/1c6fdfb8b125b128fd29b69d60cbeaa76ad4689c/src/engines-experimental/radix.h#L52)):*
> ```objc
>  * https://github.com/pmem/libpmemobj-cpp/blob/master/include/libpmemobj%2B%2B/experimental/radix_tree.hpp
>  *
>  * It is a sorted, singlethreaded engine. Unlike other sorted engine it does not support
> ```

"other sorted engine**s**"
___
*[src/engines-experimental/radix.cc, line 231 at r2](https://reviewable.io/reviews/pmem/pmemkv/750#-MFB_yIA8LpVoN1f0IW-:-MFB_yIA8LpVoN1f0IW0:bf1908e) ([raw file](https://github.com/pmem/pmemkv/blob/1c6fdfb8b125b128fd29b69d60cbeaa76ad4689c/src/engines-experimental/radix.cc#L231)):*
> ```cpp
> {
> 	LOG("put key=" << std::string(key.data(), key.size())
> 		       << ", value.size=" << std::to_string(value.size()));
> ```

why we log value.size ?
___
*[src/engines-experimental/radix.cc, line 238 at r2](https://reviewable.io/reviews/pmem/pmemkv/750#-MFBbKni0E6lAc5mv-j9:-MFBbKni0E6lAc5mv-jA:bsg5cjk) ([raw file](https://github.com/pmem/pmemkv/blob/1c6fdfb8b125b128fd29b69d60cbeaa76ad4689c/src/engines-experimental/radix.cc#L238)):*
> ```cpp
> 	if (result.second == false) {
> 		pmem::obj::transaction::run(pmpool,
> 					    [&] { result.first.assign_val(value); });
> ```

what if this fails?
___
*[src/engines-experimental/radix.cc, line 254 at r2](https://reviewable.io/reviews/pmem/pmemkv/750#-MFBbqCjDQVgYNDpkEeG:-MFBbqCjDQVgYNDpkEeH:bpllu37) ([raw file](https://github.com/pmem/pmemkv/blob/1c6fdfb8b125b128fd29b69d60cbeaa76ad4689c/src/engines-experimental/radix.cc#L254)):*
> ```cpp
> 		return status::NOT_FOUND;
> 
> 	container->erase(it);
> ```

what if it fails?
___
*[tests/CMakeLists.txt, line 1401 at r2](https://reviewable.io/reviews/pmem/pmemkv/750#-MFBN4MUAQr71O2RLR5F:-MFBN4MVEfwNHCOZjlJM:b-artsmj) ([raw file](https://github.com/pmem/pmemkv/blob/1c6fdfb8b125b128fd29b69d60cbeaa76ad4689c/tests/CMakeLists.txt#L1401)):*
> ```CMake
> 			SCRIPT pmemobj_based/pmemobj/error_handling_tx_path.cmake)
> 
> 	# # XXX - defrag not supported
> ```

a single "#" should be enough, I guess ;)
___
*[utils/docker/run-build.sh, line 1 at r2](https://reviewable.io/reviews/pmem/pmemkv/750#-MFBNfwr-dj2GnMebf82:-MFBNfws3w7yWtWbGzUF:bl50966) ([raw file](https://github.com/pmem/pmemkv/blob/1c6fdfb8b125b128fd29b69d60cbeaa76ad4689c/utils/docker/run-build.sh#L1)):*
> ```Shell
> #!/usr/bin/env bash
> ```

please update also `run-test-building.sh` script

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/750)* status: all files reviewed, 12 unresolved discussions (waiting on @igchor)

___
*[tests/CMakeLists.txt, line 71 at r2](https://reviewable.io/reviews/pmem/pmemkv/750#-MFC0nCK4gKb1KdXxLqo:-MFC0nCK4gKb1KdXxLqp:brpe7o1) ([raw file](https://github.com/pmem/pmemkv/blob/1c6fdfb8b125b128fd29b69d60cbeaa76ad4689c/tests/CMakeLists.txt#L71)):*
> ```CMake
> 
> ## Common tests
> build_test(wrong_engine_name_test wrong_engine_name_test.cc)
> ```

please extend wrong engine name test

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/750)* status: 5 of 12 files reviewed, 12 unresolved discussions (waiting on @lukaszstolarczuk and @szyrom)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/750#-MFBLt_WBRo8oAxm7VMN:-MFUy-eP5z9jUasey06t:b8hydbs) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`radix` -> `sradix` ?
</blockquote></details>

Hm, I'm not sure, this is not the same as for stree, where you can use custom comparator. I think it's better to leave it as is.

---
*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/750#-MFBc6-OE-7QYyEooX2H:-MFUyLnR5f_z9ruvkS7B:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

Please update `ENGINES-experimental.md` file and "Storage Engines" section in `README.md`
</blockquote></details>

Done.

---
___
*[CMakeLists.txt, line 54 at r2](https://reviewable.io/reviews/pmem/pmemkv/750#-MFBEjbaB_QYmKMcsz8O:-MFUzNRN79xa-m2TS9Be:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/1c6fdfb8b125b128fd29b69d60cbeaa76ad4689c/CMakeLists.txt#L54)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

please move it down below, with other status messages
(part of the file with comment `Setup defines and check status of each engine`)
</blockquote></details>

Done.
___
*[doc/libpmemkv.7.md, line 132 at r2](https://reviewable.io/reviews/pmem/pmemkv/750#-MFBEx354MCkwt4RYCAF:-MFUzTjX40AK9dsHEdv5:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/1c6fdfb8b125b128fd29b69d60cbeaa76ad4689c/doc/libpmemkv.7.md#L132)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

"Three of them" -> "Four.." or "Some.."
</blockquote></details>

Done.
___
*[src/engines-experimental/radix.h, line 10 at r2](https://reviewable.io/reviews/pmem/pmemkv/750#-MFBLnf4AgIquoy6hx5R:-MFUz_WtCXMdyLPqmbkn:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/1c6fdfb8b125b128fd29b69d60cbeaa76ad4689c/src/engines-experimental/radix.h#L10)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.
___
*[src/engines-experimental/radix.h, line 52 at r2](https://reviewable.io/reviews/pmem/pmemkv/750#-MFBZ_ra0d7C4qHIL9-n:-MFUzbfx4tlUBH0ZFeCP:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/1c6fdfb8b125b128fd29b69d60cbeaa76ad4689c/src/engines-experimental/radix.h#L52)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

"other sorted engine**s**"
</blockquote></details>

Done.
___
*[src/engines-experimental/radix.cc, line 231 at r2](https://reviewable.io/reviews/pmem/pmemkv/750#-MFB_yIA8LpVoN1f0IW-:-MFV-8zU379nz1pHy2oJ:b50d6ep) ([raw file](https://github.com/pmem/pmemkv/blob/1c6fdfb8b125b128fd29b69d60cbeaa76ad4689c/src/engines-experimental/radix.cc#L231)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

why we log value.size ?
</blockquote></details>

We do the same for other engines already. For now, the logs are disabled anyway.
I think that we must finally came up with some solution for logging and then we can refactor the logs (to introduces log levels, decide what should actually be logged, etc.) For now, it does not really matter.
___
*[src/engines-experimental/radix.cc, line 238 at r2](https://reviewable.io/reviews/pmem/pmemkv/750#-MFBbKni0E6lAc5mv-j9:-MFV-19P-loW6lghTNlp:bk6d7yh) ([raw file](https://github.com/pmem/pmemkv/blob/1c6fdfb8b125b128fd29b69d60cbeaa76ad4689c/src/engines-experimental/radix.cc#L238)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

what if this fails?
</blockquote></details>

Then a proper exceptions will be thrown and we will catch it in libpmemkv.cc
___
*[src/engines-experimental/radix.cc, line 254 at r2](https://reviewable.io/reviews/pmem/pmemkv/750#-MFBbqCjDQVgYNDpkEeG:-MFV-QfU3Wxmiq1PJZkF:b3kqx) ([raw file](https://github.com/pmem/pmemkv/blob/1c6fdfb8b125b128fd29b69d60cbeaa76ad4689c/src/engines-experimental/radix.cc#L254)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

what if it fails?
</blockquote></details>

.
___
*[tests/CMakeLists.txt, line 71 at r2](https://reviewable.io/reviews/pmem/pmemkv/750#-MFC0nCK4gKb1KdXxLqo:-MFV-coI3I1K2_pY70i6:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/1c6fdfb8b125b128fd29b69d60cbeaa76ad4689c/tests/CMakeLists.txt#L71)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

please extend wrong engine name test
</blockquote></details>

Done.
___
*[tests/CMakeLists.txt, line 1401 at r2](https://reviewable.io/reviews/pmem/pmemkv/750#-MFBN4MUAQr71O2RLR5F:-MFV-gYGDRBcNhkoTMV-:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/1c6fdfb8b125b128fd29b69d60cbeaa76ad4689c/tests/CMakeLists.txt#L1401)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

a single "#" should be enough, I guess ;)
</blockquote></details>

Done.
___
*[utils/docker/run-build.sh, line 1 at r2](https://reviewable.io/reviews/pmem/pmemkv/750#-MFBNfwr-dj2GnMebf82:-MFV0bYW3Hm6FKn-dAk3:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/1c6fdfb8b125b128fd29b69d60cbeaa76ad4689c/utils/docker/run-build.sh#L1)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

please update also `run-test-building.sh` script
</blockquote></details>

Done.

**Review by szyrom — APPROVED** [review]
> Reviewed 1 of 8 files at r1, 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/750)* status: all files reviewed, 12 unresolved discussions (waiting on @lukaszstolarczuk)

**Pull request merged**
