### PR TITLE
CI: use GH Container Registry instead of Docker Hub to store images

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
and minor fixes in utils' scripts along these changes.

- [ ] after we merge this PR and first images are pushed, we have to make them public

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/832)

### CODE REVIEW

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/832)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[utils/docker/pull-or-rebuild-image.sh, line 90 at r1](https://reviewable.io/reviews/pmem/pmemkv/832#-MKFEkMa8kJVzdCQ934P:-MKFEkMa8kJVzdCQ934Q:b2dqqfo) ([raw file](https://github.com/pmem/pmemkv/blob/c3f9c1d002966315417d1bdf999023268f9429ca/utils/docker/pull-or-rebuild-image.sh#L90)):*
> ```Shell
> 			&& $PUSH_IMAGE == "1" ]]
> 		then
> 			echo "The image will be pushed to the Container Registry"
> ```

nit:
```
The image will be pushed to the Container Registry: ${CONTAINER_REG}
```
___
*[utils/docker/images/build-image.sh, line 16 at r1](https://reviewable.io/reviews/pmem/pmemkv/832#-MKFG9p23V_nTIrC67MI:-MKFG9p23V_nTIrC67MJ:b-ftbna4) ([raw file](https://github.com/pmem/pmemkv/blob/c3f9c1d002966315417d1bdf999023268f9429ca/utils/docker/images/build-image.sh#L16)):*
> ```Shell
> set -e
> 
> OS__OS_VER=${1}
> ```

I don't get the tricky name of this variable. 
However ``` ${OS__OS} ``` looks like emot :)

**Review by karczex — COMMENTED** [review]
> Reviewed 6 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/832)* status: 6 of 9 files reviewed, 4 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[.github/workflows/gha.yml, line 8 at r1](https://reviewable.io/reviews/pmem/pmemkv/832#-MKFIVYI0q7yzrknixGM:-MKFIVYJ4Sf8_dVqGATv:b-pbc849) ([raw file](https://github.com/pmem/pmemkv/blob/c3f9c1d002966315417d1bdf999023268f9429ca/.github/workflows/gha.yml#L8)):*
> ```YAML
>   REPO:           pmemkv
>   GITHUB_REPO:    pmem/pmemkv
>   CONTAINER_REG:  ghcr.io/${{github.repository_owner}}/pmemkv
> ```

Probably ```github.repository``` variable would be even better here. 
___
*[.github/workflows/other_OSes.yml, line 11 at r1](https://reviewable.io/reviews/pmem/pmemkv/832#-MKFIs9LDOLgGpiZXu24:-MKFIs9LDOLgGpiZXu25:b3kqx) ([raw file](https://github.com/pmem/pmemkv/blob/c3f9c1d002966315417d1bdf999023268f9429ca/.github/workflows/other_OSes.yml#L11)):*
> ```YAML
>   REPO:           pmemkv
>   GITHUB_REPO:    pmem/pmemkv
>   CONTAINER_REG:  ghcr.io/${{github.repository_owner}}/pmemkv
> ```

.

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/832)* status: 4 of 9 files reviewed, 3 unresolved discussions (waiting on @karczex)

___
*[.github/workflows/gha.yml, line 8 at r1](https://reviewable.io/reviews/pmem/pmemkv/832#-MKFIVYI0q7yzrknixGM:-MKFViyU75zslJQ1BXaG:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/c3f9c1d002966315417d1bdf999023268f9429ca/.github/workflows/gha.yml#L8)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

Probably ```github.repository``` variable would be even better here. 
</blockquote></details>

Done.
___
*[.github/workflows/other_OSes.yml, line 11 at r1](https://reviewable.io/reviews/pmem/pmemkv/832#-MKFIs9LDOLgGpiZXu24:-MKFVjf5A8vjIhAuFuXE:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/c3f9c1d002966315417d1bdf999023268f9429ca/.github/workflows/other_OSes.yml#L11)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[utils/docker/images/build-image.sh, line 16 at r1](https://reviewable.io/reviews/pmem/pmemkv/832#-MKFG9p23V_nTIrC67MI:-MKFVoHh8csjdwBFe9A-:b-2940st) ([raw file](https://github.com/pmem/pmemkv/blob/c3f9c1d002966315417d1bdf999023268f9429ca/utils/docker/images/build-image.sh#L16)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

I don't get the tricky name of this variable. 
However ``` ${OS__OS} ``` looks like emot :) 
</blockquote></details>

it's described above, in the comment - "<OS-VER>", we use the same var name in libpmemobj-cpp, if you have better name, pls tell ;)

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/832#-:-MKFdZ8dAx8w1K8PNhGo:bnfp4nl)* status: 4 of 9 files reviewed, all discussions resolved (waiting on @karczex)

**Review by szyrom — APPROVED** [review]
:lgtm:

> Reviewed 5 of 9 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/832#-:-MKZ7ME14DF2UtI62ELu:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
