### PR TITLE
bump libpmemobj-cpp requirement to 1.11

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/801)

### CODE REVIEW

**Review by igchor — COMMENTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/801)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by igchor — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/801#-:-MIYNyUgAvnGWbACU4IF:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by karczex — COMMENTED** [review]
> Reviewed 1 of 6 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/801)* status: all files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[utils/docker/images/Dockerfile.centos-8, line 29 at r2](https://reviewable.io/reviews/pmem/pmemkv/801#-MIYVHsF41LpDvPAf47Q:-MIYVHsF41LpDvPAf47R:b-crm4uv) ([raw file](https://github.com/pmem/pmemkv/blob/aa374fef75e532fc49594f4d059e964f6d9c298a/utils/docker/images/Dockerfile.centos-8#L29)):*
> ```
> RUN dnf config-manager --set-enabled PowerTools
> 
> ENV LIBPMEMOBJ_CPP_DEPS "\
> ```

It's needed only at build time, so please change it to ARG ...
___
*[utils/docker/images/Dockerfile.centos-8, line 62 at r2](https://reviewable.io/reviews/pmem/pmemkv/801#-MIYVnVa6ZXBGwQxyIu3:-MIYVnVa6ZXBGwQxyIu4:bvpj7xd) ([raw file](https://github.com/pmem/pmemkv/blob/aa374fef75e532fc49594f4d059e964f6d9c298a/utils/docker/images/Dockerfile.centos-8#L62)):*
> ```
> 	wget \
> 	which \
> 	$LIBPMEMOBJ_CPP_DEPS \
> ```

.... however if you think, it's useful to separate libpmemobj++ dependencies, move it to separate layer. (in all dockerfiles)

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/801#-:-MIYhLMnDZ-iEPkP2OBD:bnfp4nl)* status: 3 of 6 files reviewed, all discussions resolved (waiting on @igchor)

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/801)* status: 3 of 6 files reviewed, all discussions resolved (waiting on @igchor)

___
*[utils/docker/images/Dockerfile.centos-8, line 29 at r2](https://reviewable.io/reviews/pmem/pmemkv/801#-MIYVHsF41LpDvPAf47Q:-MIYfYIg4x1dlX5Z9fNX:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/aa374fef75e532fc49594f4d059e964f6d9c298a/utils/docker/images/Dockerfile.centos-8#L29)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

It's needed only at build time, so please change it to ARG ...
</blockquote></details>

Done.
___
*[utils/docker/images/Dockerfile.centos-8, line 62 at r2](https://reviewable.io/reviews/pmem/pmemkv/801#-MIYVnVa6ZXBGwQxyIu3:-MIYhRHUExqY4TkcIeWk:b-x4wcdf) ([raw file](https://github.com/pmem/pmemkv/blob/aa374fef75e532fc49594f4d059e964f6d9c298a/utils/docker/images/Dockerfile.centos-8#L62)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

.... however if you think, it's useful to separate libpmemobj++ dependencies, move it to separate layer. (in all dockerfiles)
</blockquote></details>

sep. layer may not be possible, because various distros may use various packages names

**Review by szyrom — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/801#-:-MIYu31D2jCmlxfgdEhW:bnfp4nl)* status: 3 of 6 files reviewed, all discussions resolved (waiting on @igchor)

**Comment by karczex** [comment]
___
*[utils/docker/images/Dockerfile.centos-8, line 62 at r2](https://reviewable.io/reviews/pmem/pmemkv/801#-MIYVnVa6ZXBGwQxyIu3:-MIYtyU77PDgk1oTSCaS:b-w7abca) ([raw file](https://github.com/pmem/pmemkv/blob/aa374fef75e532fc49594f4d059e964f6d9c298a/utils/docker/images/Dockerfile.centos-8#L62)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

sep. layer may not be possible, because various distros may use various packages names
</blockquote></details>

I mean separate RUN command (each RUN is separate layer) . Anyhow, please, leave it as is. I hope we may do it as is in pmdk.

**Pull request merged**
