### PR TITLE
[gh-pages] add bindings docs links

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
- add links and info about bindings.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/860)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/860)* status: 0 of 1 files reviewed, 1 unresolved discussion

___
*[index.md, line 14 at r1](https://reviewable.io/reviews/pmem/pmemkv/860#-MOH828m-us-caMJwE02:-MOH828m-us-caMJwE03:bqkedxx) ([raw file](https://github.com/pmem/pmemkv/blob/5cb3f62ada2ffab5e7b158e5b63864022d2b2e86/index.md#L14)):*
> ```Markdown
> The **C API** of pmemkv is documented in the following manuals:
> 
> | Version branch | libpmemkv(3) | libpmemkv(7) | libpmemkv_config(3) | libpmemkv_json_config(3) |
> ```

it's either this table or the list below - please vote :wink: 

table links descriptions may be different - I'm open for suggestions.

**Comment by lukaszstolarczuk** [comment]
Update this PR, when gh-pages contains new manpage (for iterator and transactions: ref. #831 & #830)

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/860)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[index.md, line 14 at r1](https://reviewable.io/reviews/pmem/pmemkv/860#-MOH828m-us-caMJwE02:-MOfCqHB0_vJMPbloH68:b-snr3ot) ([raw file](https://github.com/pmem/pmemkv/blob/5cb3f62ada2ffab5e7b158e5b63864022d2b2e86/index.md#L14)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

it's either this table or the list below - please vote :wink: 

table links descriptions may be different - I'm open for suggestions.
</blockquote></details>

I think I'd prefer to have a list with just 'master' and lastest stable release and some single linke for all older releases (to some main pmem.io doc page or something)

**Review by szyrom — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/860#-:-MPEBFzZ3lRFo_DmNu1U:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

**Comment by lukaszstolarczuk** [comment]
@igchor, the change with manpages "look" will be done in separate PR.

**Pull request merged**
