### PR TITLE
Update memkind version

### PR DESCRIPTION
**Pull request by PatKamin**
This PR contains memkind version 1.12.0.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1007)

### CODE REVIEW

**Comment by lukaszstolarczuk** [comment]
@PatKamin, ping ^^ 😉

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1007)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @PatKamin)

___
*[-- commits, line 5 at r1](https://reviewable.io/reviews/pmem/pmemkv/1007#-Mia0opH5ulGlZNI0mJj):*
it seems that CI was all green, so you can drop this commit and we're good to go with this PR.
___
*[utils/docker/images/install-memkind.sh, line 13 at r1](https://reviewable.io/reviews/pmem/pmemkv/1007#-Mia-g9KEFkiCupnvJ0o:-Mia-g9L2RI4emT8uwlJ:bc856t2) ([raw file](https://github.com/pmem/pmemkv/blob/917363332c35b44a45d68fa81a046a4fef0124d3/utils/docker/images/install-memkind.sh#L13)):*
> ```Shell
> 
> # contains better error handling in pmem_allocator
> MEMKIND_VERSION=v1.12.0
> ```

pls use hash commit instead of a tag (

**Review by PatKamin — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1007#-:-Mia3pF447uCJkgNJuSk:b-896fix)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[-- commits, line 5 at r1](https://reviewable.io/reviews/pmem/pmemkv/1007#-Mia0opH5ulGlZNI0mJj):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

it seems that CI was all green, so you can drop this commit and we're good to go with this PR.
</blockquote></details>

Done.
___
*[utils/docker/images/install-memkind.sh, line 13 at r1](https://reviewable.io/reviews/pmem/pmemkv/1007#-Mia-g9KEFkiCupnvJ0o:-Mia3vvr-CaCTNwREX9M:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/917363332c35b44a45d68fa81a046a4fef0124d3/utils/docker/images/install-memkind.sh#L13)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls use hash commit instead of a tag (
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1007)* status: all files reviewed, 1 unresolved discussion (waiting on @PatKamin)

___
*[utils/docker/images/install-memkind.sh, line 13 at r1](https://reviewable.io/reviews/pmem/pmemkv/1007#-Mia-g9KEFkiCupnvJ0o:-MiaBGtrB7otQHP-dagk:b-2sp98j) ([raw file](https://github.com/pmem/pmemkv/blob/917363332c35b44a45d68fa81a046a4fef0124d3/utils/docker/images/install-memkind.sh#L13)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

actually, you can replace the above comment ("contains...") with your (version) comment

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1007)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[utils/docker/images/install-memkind.sh, line 13 at r1](https://reviewable.io/reviews/pmem/pmemkv/1007#-Mia-g9KEFkiCupnvJ0o:-MiaCRbq9a10VBwy1QyM:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/917363332c35b44a45d68fa81a046a4fef0124d3/utils/docker/images/install-memkind.sh#L13)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

actually, you can replace the above comment ("contains...") with your (version) comment
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1007#-:-MiaJP785376sHCvbxGW:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PatKamin)

___
*[utils/docker/images/install-memkind.sh, line 13 at r1](https://reviewable.io/reviews/pmem/pmemkv/1007#-Mia-g9KEFkiCupnvJ0o:-MiaJDLC7fwU1Lf8vWja:b2nid0f) ([raw file](https://github.com/pmem/pmemkv/blob/917363332c35b44a45d68fa81a046a4fef0124d3/utils/docker/images/install-memkind.sh#L13)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

thx

**Pull request merged**
