### PR TITLE
Add automatic update of documentation on master

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/413)

### CODE REVIEW

**Comment by marcinslusarz** [comment]
I don't see any reference to Doxygen anywhere in pmemkv...

**Comment by ldorau** [comment]
> I don't see any reference to Doxygen anywhere in pmemkv...

https://github.com/pmem/pmemkv/pull/416

**Comment by ldorau** [comment]
@lukaszstolarczuk @igchor @karczex @szyrom please review

**Comment by lukaszstolarczuk** [comment]
> > _[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/413)_ status: all files reviewed, 1 unresolved discussion (waiting on @igchor and @karczex)
> 
> _[utils/docker/run-doc-update.sh, line 40 at r2](https://reviewable.io/reviews/pmem/pmemkv/413#-LoyhGQxA2Bvo3ZZR6Xq:-LozDt5HBnaDSCX4-iel:b-4n5jwz) ([raw file](https://github.com/pmem/pmemkv/blob/6e38831a0f429070cc380219c6e0497a0da98766/utils/docker/run-doc-update.sh#L40)):_
> 
> Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…
> But why do you want to set a new variable just for this one line: `cd pmemkv` ?

as discussed for all the copying with relative paths like "../.."

**Pull request merged**
