### PR TITLE
Make get callback return value (can be used in future to communicate …

### PR DESCRIPTION
**Pull request by igchor**
…with engine)

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/328)

### CODE REVIEW

**Comment by igchor** [comment]
TODO: clang-format

**Comment by marcinslusarz** [comment]
Please verify that the return value is 0 on the pmemkv side.

**Comment by igchor** [comment]
Done

**Comment by marcinslusarz** [comment]
___
*[src/libpmemkv.cc, line 687 at r3](https://reviewable.io/reviews/pmem/pmemkv/328#-LiPOeCd5pPHhRwI3AUZ:-LiPOeCd5pPHhRwI3AU_:b9fjci2) ([raw file](https://github.com/pmem/pmemkv/blob/d37d2f1723694395ad8f57db9886fa7c229c9d59/src/libpmemkv.cc#L687)):*
> ```cpp
> 	}
> 
> 	c->result = PMEMKV_STATUS_OK;
> ```

something is not right here - you overwrite result set 2 lines above

**Pull request merged**
