### PR TITLE
Reserve space on open/create

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/827)

### CODE REVIEW

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/827)* status: 0 of 11 files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[examples/pmemkv_config_c/pmemkv_basic_config.c, line 78 at r2](https://reviewable.io/reviews/pmem/pmemkv/827#-MJkYoCY6C9YkbsUsM8J:-MJkYoCY6C9YkbsUsM8K:b-1cxagy) ([raw file](https://github.com/pmem/pmemkv/blob/0fc7856e22e49e895e5b829f3493379c584bc0f9/examples/pmemkv_config_c/pmemkv_basic_config.c#L78)):*
> ```C
> 	 * possible allocations will be done on open/create and there will be
> 	 * less container's resizing during actual database usage. */
> 	status = pmemkv_config_put_reserve(config, 100);
> ```

I'm not sure about the name, maybe like Pawel said, it would be better to just have `pmemkv_config_reserve` or `pmemkv_config_set_initial_capacity`?
___
*[tests/engine_scenarios/pmemobj/put_get_std_map_reserve.cc, line 31 at r2](https://reviewable.io/reviews/pmem/pmemkv/827#-MJkYN6b25boTNHiUylo:-MJkYN6b25boTNHiUylp:badqzad) ([raw file](https://github.com/pmem/pmemkv/blob/0fc7856e22e49e895e5b829f3493379c584bc0f9/tests/engine_scenarios/pmemobj/put_get_std_map_reserve.cc#L31)):*
> ```cpp
> 		UT_FATAL("usage: %s engine json_config", argv[0]);
> 
> 	/* reserve more elements than inserting */
> ```

It would also be nice to test that following scenario:
1. Create db and put some data and close it
2. Open db with reserve set to some lower value than number of elements
3. Check if all elements are accessible and size is correct.

**Review by KFilipek — COMMENTED** [review]
> Reviewed 6 of 6 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/827)* status: all files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[src/libpmemkv.hpp, line 702 at r2](https://reviewable.io/reviews/pmem/pmemkv/827#-MJkgH5L3zyOTzQacX9N:-MJkgH5L3zyOTzQacX9O:b-8skbgv) ([raw file](https://github.com/pmem/pmemkv/blob/0fc7856e22e49e895e5b829f3493379c584bc0f9/src/libpmemkv.hpp#L702)):*
> ```cpp
> /**
>  * Puts reserve_count to a config
>  * XXX: add more description
> ```

When? PR is not a draft.

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/827)* status: 10 of 11 files reviewed, 3 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[src/libpmemkv.hpp, line 702 at r2](https://reviewable.io/reviews/pmem/pmemkv/827#-MJkgH5L3zyOTzQacX9N:-MJkjHHZ1Q6hPyl3hB2U:b-k3nt1a) ([raw file](https://github.com/pmem/pmemkv/blob/0fc7856e22e49e895e5b829f3493379c584bc0f9/src/libpmemkv.hpp#L702)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

When? PR is not a draft.
</blockquote></details>

when we figure out the naming and how this affects other engines
___
*[tests/engine_scenarios/pmemobj/put_get_std_map_reserve.cc, line 31 at r2](https://reviewable.io/reviews/pmem/pmemkv/827#-MJkYN6b25boTNHiUylo:-MJkjX_9BD2F8vhI7D48:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/0fc7856e22e49e895e5b829f3493379c584bc0f9/tests/engine_scenarios/pmemobj/put_get_std_map_reserve.cc#L31)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

It would also be nice to test that following scenario:
1. Create db and put some data and close it
2. Open db with reserve set to some lower value than number of elements
3. Check if all elements are accessible and size is correct.
</blockquote></details>

Done.

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/827)* status: 10 of 11 files reviewed, 3 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[tests/engine_scenarios/pmemobj/put_get_std_map_reserve.cc, line 65 at r3](https://reviewable.io/reviews/pmem/pmemkv/827#-MJkkjVi0BbIgTfJQhuq:-MJkkjVjE5l_gGfaU28x:b-27zo8j) ([raw file](https://github.com/pmem/pmemkv/blob/ed23d3ec7866f9c0f0720e5ea33efb05f9439fcb/tests/engine_scenarios/pmemobj/put_get_std_map_reserve.cc#L65)):*
> ```cpp
> 
> 	/* insert, reopen database and reserve less elements */
> 	insert_and_reserve(argv[1], argv[2], 100, 10);
> ```

Could you use some slightly bigger values here? Like 2048 and 1024 or even bigger. The reason is that there is some embedded segment in hash map. (you can also use some bigger values in the functions above).

**Review by karczex — COMMENTED** [review]
You should check at open, if reserved capacity is not bigger than size. 
Also some parameter to reserve whole database size at open may be useful. Maybe some macro like MAX_SIZE, or something.  

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/827#-:-MJl0Ata9i97klpSbN4P:b-rrqc79)* status: 10 of 11 files reviewed, 3 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

**Review by igchor — COMMENTED** [review]
> You should check at open, if reserved capacity is not bigger than size.
If the're not enough space reverve (or for now, rehash) will throw out_of_memory exception. In pmemkv open should just retunr OUT_OF_MEMORY status. And we should actually have test for that: @lukaszstolarczuk 

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/827#-:-MJl521DEcrCmE1pBqUV:bk1elj4)* status: 10 of 11 files reviewed, 3 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

**Review by lukaszstolarczuk — COMMENTED** [review]
Actually we are prepared well, bad_alloc (which is thrown here) is already caught in libpmemkv.cc and proper status is already returned. I've added test for that.

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/827#-:-MJlOmnDAKy9zCgEsGq8:bfp66hj)* status: 10 of 11 files reviewed, 3 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[examples/pmemkv_config_c/pmemkv_basic_config.c, line 78 at r2](https://reviewable.io/reviews/pmem/pmemkv/827#-MJkYoCY6C9YkbsUsM8J:-MJlWpWG2bdHlcjH57e9:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/0fc7856e22e49e895e5b829f3493379c584bc0f9/examples/pmemkv_config_c/pmemkv_basic_config.c#L78)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I'm not sure about the name, maybe like Pawel said, it would be better to just have `pmemkv_config_reserve` or `pmemkv_config_set_initial_capacity`?
</blockquote></details>

Done.
___
*[src/libpmemkv.hpp, line 702 at r2](https://reviewable.io/reviews/pmem/pmemkv/827#-MJkgH5L3zyOTzQacX9N:-MJlWqEY9t4B1908pdED:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/0fc7856e22e49e895e5b829f3493379c584bc0f9/src/libpmemkv.hpp#L702)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

when we figure out the naming and how this affects other engines
</blockquote></details>

Done.
___
*[tests/engine_scenarios/pmemobj/put_get_std_map_reserve.cc, line 65 at r3](https://reviewable.io/reviews/pmem/pmemkv/827#-MJkkjVi0BbIgTfJQhuq:-MJlFfQc6WcrE0lT8iSf:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/ed23d3ec7866f9c0f0720e5ea33efb05f9439fcb/tests/engine_scenarios/pmemobj/put_get_std_map_reserve.cc#L65)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Could you use some slightly bigger values here? Like 2048 and 1024 or even bigger. The reason is that there is some embedded segment in hash map. (you can also use some bigger values in the functions above).
</blockquote></details>

Done.

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/827)* status: 1 of 14 files reviewed, 2 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[src/libpmemkv.hpp, line 704 at r4](https://reviewable.io/reviews/pmem/pmemkv/827#-MJlb8UT9oxfuthyEKNz:-MJlb8UT9oxfuthyEKO-:baevwsb) ([raw file](https://github.com/pmem/pmemkv/blob/7534f21b21117224716fc11e7bdb12eebc80702d/src/libpmemkv.hpp#L704)):*
> ```cpp
>  * space/memory in the database at pmem::kv::open() call. 0 means no reserving, any other
>  * number should increase container's capacity (or leave it as is if the value is less or
>  * equal to the current capacity). If reservation exceeds database size, pmem::kv::open()
> ```

maybe "exceeds available storage" since size might be confused with number of elements

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/827#-:-MJlbRF8-2qseioNLlO4:bnfp4nl)* status: 1 of 14 files reviewed, 2 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

**Review by karczex — COMMENTED** [review]
> Reviewed 10 of 13 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/827)* status: 13 of 14 files reviewed, 2 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[tests/engine_scenarios/pmemobj/error_handling_reserve.cc, line 7 at r5](https://reviewable.io/reviews/pmem/pmemkv/827#-MK10FUGDsW2Qyhb1WNk:-MK1-3L85Cilw4bPJXsP:b-jfysis) ([raw file](https://github.com/pmem/pmemkv/blob/c12b2febe9eb88d267fafd31f3db2b04b6ea7956/tests/engine_scenarios/pmemobj/error_handling_reserve.cc#L7)):*
> ```cpp
> 
> /* this elements' count should exceed db size */
> const size_t COUNT_EXCEEDING_DB_SIZE = 5000000;
> ```

Test also some edge cases? (i.e. max value of size_t)

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/827)* status: 11 of 14 files reviewed, 2 unresolved discussions (waiting on @karczex and @KFilipek)

___
*[tests/engine_scenarios/pmemobj/error_handling_reserve.cc, line 7 at r5](https://reviewable.io/reviews/pmem/pmemkv/827#-MK10FUGDsW2Qyhb1WNk:-MK4fLOu40oRP5xwxxZ6:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/c12b2febe9eb88d267fafd31f3db2b04b6ea7956/tests/engine_scenarios/pmemobj/error_handling_reserve.cc#L7)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

Test also some edge cases? (i.e. max value of size_t)
</blockquote></details>

Done.

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/827#-:-MKsw-UzEjCSN16_PF8h:bnfp4nl)* status: 11 of 14 files reviewed, 1 unresolved discussion (waiting on @karczex and @KFilipek)

**Pull request closed without merging**
