### PR TITLE
readme: style fixes to readme.md

### PR DESCRIPTION
**Pull request by KFilipek**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/851)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/851)* status: 0 of 1 files reviewed, 9 unresolved discussions (waiting on @KFilipek)

___
*[README.md, line 1 at r1](https://reviewable.io/reviews/pmem/pmemkv/851#-MNOYrY6-0U3oNBmMmYD:-MNOYrY6-0U3oNBmMmYE:bhioi) ([raw file](https://github.com/pmem/pmemkv/blob/04b46a23609fbf29b8fbaa40c3b1598db2d7ee34/README.md#L1)):*
> ```Markdown
> # **pmemkv**
> ```

I don't believe there's any change if you use `**` - you can drop them
___
*[README.md, line 10 at r1](https://reviewable.io/reviews/pmem/pmemkv/851#-MNOYYRX0eRDSOSSHJuq:-MNOYYRYAwz24C93gv_3:b6iq3xu) ([raw file](https://github.com/pmem/pmemkv/blob/04b46a23609fbf29b8fbaa40c3b1598db2d7ee34/README.md#L10)):*
> ```Markdown
> [Packaging status](https://repology.org/project/pmemkv/versions)
> 
> ## Overview
> ```

in cpp we don't have the overview section and I believe it's good to remove it here too
___
*[README.md, line 32 at r1](https://reviewable.io/reviews/pmem/pmemkv/851#-MNOZSWjBf2_jtGSv-1H:-MNOZSWjBf2_jtGSv-1I:b-uj7tu1) ([raw file](https://github.com/pmem/pmemkv/blob/04b46a23609fbf29b8fbaa40c3b1598db2d7ee34/README.md#L32)):*
> ```Markdown
> 1. [Installation](#installation)
> 2. [Language Bindings](#language-bindings)
>     - [C/C++ Examples](#c/c++-examples)
> ```

did you test these links? I believe proper one for this is: `#cc-examples`
___
*[README.md, line 48 at r1](https://reviewable.io/reviews/pmem/pmemkv/851#-MNOZCX58-m9ZkVEwaNn:-MNOZCX58-m9ZkVEwaNo:b-lsac83) ([raw file](https://github.com/pmem/pmemkv/blob/04b46a23609fbf29b8fbaa40c3b1598db2d7ee34/README.md#L48)):*
> ```Markdown
> - [Installing on Ubuntu](INSTALLING.md#installing-on-ubuntu)
> - [Using Experimental Engines](INSTALLING.md#using-experimental-engines)
> - [Packages Building](INSTALLING.md#packages-building)
> ```

1. there's nothing wrong with "building packages" - it's proper English ;)
2. link in INSTALLING.md looks like this: https://github.com/pmem/pmemkv/blob/master/INSTALLING.md#building-packages - so right now it points to invalid link
___
*[README.md, line 53 at r1](https://reviewable.io/reviews/pmem/pmemkv/851#-MNOZz6B6_b3gQJ9rUUN:-MNOZz6B6_b3gQJ9rUUO:b-xjixtu) ([raw file](https://github.com/pmem/pmemkv/blob/04b46a23609fbf29b8fbaa40c3b1598db2d7ee34/README.md#L53)):*
> ```Markdown
> ## Language Bindings
> 
> `pmemkv` is written in C/C++ and can used by bindings for Java, Node.js,
> ```

I agree it can, but it is used as for now :) so it was properly written before.

If you want to write it can be used, then make it perhaps something like `... and can be used in other languages - Java, ...` 
___
*[README.md, line 64 at r1](https://reviewable.io/reviews/pmem/pmemkv/851#-MNO_AVUAmgJksnJmMby:-MNO_AVUAmgJksnJmMbz:b-6yr8zp) ([raw file](https://github.com/pmem/pmemkv/blob/04b46a23609fbf29b8fbaa40c3b1598db2d7ee34/README.md#L64)):*
> ```Markdown
> ### Other Languages
> 
> Mentioned above bindings are maintained in separate GitHub repositories, but are still kept in sync with the main `pmemkv` distribution.
> ```

`Abovementioned` is proper English
___
*[README.md, line 73 at r1](https://reviewable.io/reviews/pmem/pmemkv/851#-MNO_uLXEFL5EgUUT3as:-MNO_uLXEFL5EgUUT3at:b-c2mefd) ([raw file](https://github.com/pmem/pmemkv/blob/04b46a23609fbf29b8fbaa40c3b1598db2d7ee34/README.md#L73)):*
> ```Markdown
> ## Storage Engines
> 
> `pmemkv` provides multiple storage engines that share common API, so every engine can be used with
> ```

they not exactly share, there are some differences, that's why we used the word "conform to" - meaning they "comply with"
___
*[README.md, line 98 at r1](https://reviewable.io/reviews/pmem/pmemkv/851#-MNOaPEGBQTk6C_lLRjt:-MNOaPEGBQTk6C_lLRju:b-5jnmi3) ([raw file](https://github.com/pmem/pmemkv/blob/04b46a23609fbf29b8fbaa40c3b1598db2d7ee34/README.md#L98)):*
> ```Markdown
> 
> ## Contact us
> For more information about **pmemkv**, contact Szymon Romik (szymon.romik@intel.com), Piotr Balcer (piotr.balcer@intel.com) or post on our **#pmem** Slack channel using [this invite link](https://join.slack.com/t/pmem-io/shared_invite/enQtNzU4MzQ2Mzk3MDQwLWQ1YThmODVmMGFkZWI0YTdhODg4ODVhODdhYjg3NmE4N2ViZGI5NTRmZTBiNDYyOGJjYTIyNmZjYzQxODcwNDg).
> ```

please break the line
___
*[README.md, line 98 at r1](https://reviewable.io/reviews/pmem/pmemkv/851#-MNOacon0jV6IndTvpMl:-MNOacon0jV6IndTvpMm:bive9iy) ([raw file](https://github.com/pmem/pmemkv/blob/04b46a23609fbf29b8fbaa40c3b1598db2d7ee34/README.md#L98)):*
> ```Markdown
> 
> ## Contact us
> For more information about **pmemkv**, contact Szymon Romik (szymon.romik@intel.com), Piotr Balcer (piotr.balcer@intel.com) or post on our **#pmem** Slack channel using [this invite link](https://join.slack.com/t/pmem-io/shared_invite/enQtNzU4MzQ2Mzk3MDQwLWQ1YThmODVmMGFkZWI0YTdhODg4ODVhODdhYjg3NmE4N2ViZGI5NTRmZTBiNDYyOGJjYTIyNmZjYzQxODcwNDg).
> ```

'or post to our google group' ?

**Review by KFilipek — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/851)* status: 1 of 2 files reviewed, 9 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[README.md, line 1 at r1](https://reviewable.io/reviews/pmem/pmemkv/851#-MNOYrY6-0U3oNBmMmYD:-MNSm7If95UrFafNCgap:b-tdq3uu) ([raw file](https://github.com/pmem/pmemkv/blob/04b46a23609fbf29b8fbaa40c3b1598db2d7ee34/README.md#L1)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I don't believe there's any change if you use `**` - you can drop them
</blockquote></details>

Trust me, I see change on preview
___
*[README.md, line 10 at r1](https://reviewable.io/reviews/pmem/pmemkv/851#-MNOYYRX0eRDSOSSHJuq:-MNSmB6o-SmpRhF261zS:b-g00jrh) ([raw file](https://github.com/pmem/pmemkv/blob/04b46a23609fbf29b8fbaa40c3b1598db2d7ee34/README.md#L10)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

in cpp we don't have the overview section and I believe it's good to remove it here too
</blockquote></details>

But why? It's more useful here than description for C++ bindings. PMDK as main project for bindings has description.
https://github.com/pmem/pmdk 
___
*[README.md, line 32 at r1](https://reviewable.io/reviews/pmem/pmemkv/851#-MNOZSWjBf2_jtGSv-1H:-MNSsXWV7YMU8e1FygNg:b-hd0ty) ([raw file](https://github.com/pmem/pmemkv/blob/04b46a23609fbf29b8fbaa40c3b1598db2d7ee34/README.md#L32)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

did you test these links? I believe proper one for this is: `#cc-examples`
</blockquote></details>

You are right
___
*[README.md, line 48 at r1](https://reviewable.io/reviews/pmem/pmemkv/851#-MNOZCX58-m9ZkVEwaNn:-MNSwbdK3YQ-4CdPkfev:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/04b46a23609fbf29b8fbaa40c3b1598db2d7ee34/README.md#L48)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

1. there's nothing wrong with "building packages" - it's proper English ;)
2. link in INSTALLING.md looks like this: https://github.com/pmem/pmemkv/blob/master/INSTALLING.md#building-packages - so right now it points to invalid link
</blockquote></details>

Done.
___
*[README.md, line 53 at r1](https://reviewable.io/reviews/pmem/pmemkv/851#-MNOZz6B6_b3gQJ9rUUN:-MNT3hf52MgwwzGUG8ob:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/04b46a23609fbf29b8fbaa40c3b1598db2d7ee34/README.md#L53)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I agree it can, but it is used as for now :) so it was properly written before.

If you want to write it can be used, then make it perhaps something like `... and can be used in other languages - Java, ...` 
</blockquote></details>

Done.
___
*[README.md, line 64 at r1](https://reviewable.io/reviews/pmem/pmemkv/851#-MNO_AVUAmgJksnJmMby:-MNSxFbs6eHUHtWeESXj:b-y28vzc) ([raw file](https://github.com/pmem/pmemkv/blob/04b46a23609fbf29b8fbaa40c3b1598db2d7ee34/README.md#L64)):*
> Abovementioned
"Mentioned above" looks more clearly, but... let it be: https://dictionary.cambridge.org/pl/dictionary/english/above-mentioned
___
*[README.md, line 73 at r1](https://reviewable.io/reviews/pmem/pmemkv/851#-MNO_uLXEFL5EgUUT3as:-MNT1ZEx-OoQW8MvJH1O:byacfkt) ([raw file](https://github.com/pmem/pmemkv/blob/04b46a23609fbf29b8fbaa40c3b1598db2d7ee34/README.md#L73)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

they not exactly share, there are some differences, that's why we used the word "conform to" - meaning they "comply with"
</blockquote></details>

Every engine implements interface named pmemobj_engine_base, so they share common API between engine and pmemkv itself. Every engine have the same API,  so they share common API (there are some additional helper functions for engine purpose). 
___
*[README.md, line 98 at r1](https://reviewable.io/reviews/pmem/pmemkv/851#-MNOaPEGBQTk6C_lLRjt:-MNT3cfYEXzpCpS1Qlq3:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/04b46a23609fbf29b8fbaa40c3b1598db2d7ee34/README.md#L98)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

please break the line
</blockquote></details>

Done.
___
*[README.md, line 98 at r1](https://reviewable.io/reviews/pmem/pmemkv/851#-MNOacon0jV6IndTvpMl:-MNT3d9JCwGCrp80drhh:buqw9yk) ([raw file](https://github.com/pmem/pmemkv/blob/04b46a23609fbf29b8fbaa40c3b1598db2d7ee34/README.md#L98)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

'or post to our google group' ?
</blockquote></details>

It was discussed with Szymon

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/851)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @KFilipek)

___
*[README.md, line 1 at r1](https://reviewable.io/reviews/pmem/pmemkv/851#-MNOYrY6-0U3oNBmMmYD:-MNh4VJt8sJ9ZtG3ZRoE:b-idkrb4) ([raw file](https://github.com/pmem/pmemkv/blob/04b46a23609fbf29b8fbaa40c3b1598db2d7ee34/README.md#L1)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Trust me, I see change on preview
</blockquote></details>

Trust me, on the GH page, on my browser, there's no change :D anyway, marked as resolved
___
*[README.md, line 10 at r1](https://reviewable.io/reviews/pmem/pmemkv/851#-MNOYYRX0eRDSOSSHJuq:-MNh4uKDE-b6Z84fXsAY:b-f1j0vn) ([raw file](https://github.com/pmem/pmemkv/blob/04b46a23609fbf29b8fbaa40c3b1598db2d7ee34/README.md#L10)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

But why? It's more useful here than description for C++ bindings. PMDK as main project for bindings has description.
https://github.com/pmem/pmdk 
</blockquote></details>

hah, noo, I'm not saying to remove the entire section, mea culpa - to be more precise this time - please just remove the header `## Overview`, the rest is fine :)
___
*[README.md, line 64 at r1](https://reviewable.io/reviews/pmem/pmemkv/851#-MNO_AVUAmgJksnJmMby:-MNh6vOf4fb2SPSnlwmR:b-e1djxj) ([raw file](https://github.com/pmem/pmemkv/blob/04b46a23609fbf29b8fbaa40c3b1598db2d7ee34/README.md#L64)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> Abovementioned
"Mentioned above" looks more clearly, but... let it be: https://dictionary.cambridge.org/pl/dictionary/english/above-mentioned
</blockquote></details>

it looks good
___
*[README.md, line 98 at r1](https://reviewable.io/reviews/pmem/pmemkv/851#-MNOacon0jV6IndTvpMl:-MNh7ljV1E41dJhxIoOr:bg817lh) ([raw file](https://github.com/pmem/pmemkv/blob/04b46a23609fbf29b8fbaa40c3b1598db2d7ee34/README.md#L98)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

It was discussed with Szymon
</blockquote></details>

as i commented on libpmemobj-cpp - IMHO, it may be of use, for some people, to know there's a mailing list, as an alternative...
___
*[README.md, line 77 at r3](https://reviewable.io/reviews/pmem/pmemkv/851#-MNh7SQU7j3RV2uOxebH:-MNh7SQU7j3RV2uOxebI:bqqtfnv) ([raw file](https://github.com/pmem/pmemkv/blob/af2a3a18e21d32b880d49c0ead0e4e8a5ac13908/README.md#L77)):*
> ```Markdown
> 
> | Engine Name  | Description | Experimental | Concurrent | Sorted |
> | ------------ | ----------- | :-------------: | :-----------: | :-------: |
> ```

that's a good trick, it's good to know! (it makes that col align=center)

**Review by KFilipek — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/851)* status: all files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[README.md, line 10 at r1](https://reviewable.io/reviews/pmem/pmemkv/851#-MNOYYRX0eRDSOSSHJuq:-MOWVaPv2jqrYmR9luJG:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/04b46a23609fbf29b8fbaa40c3b1598db2d7ee34/README.md#L10)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hah, noo, I'm not saying to remove the entire section, mea culpa - to be more precise this time - please just remove the header `## Overview`, the rest is fine :)
</blockquote></details>

Done.
___
*[README.md, line 98 at r1](https://reviewable.io/reviews/pmem/pmemkv/851#-MNOacon0jV6IndTvpMl:-MOWWV49D6hqqaWoBRm3:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/04b46a23609fbf29b8fbaa40c3b1598db2d7ee34/README.md#L98)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

as i commented on libpmemobj-cpp - IMHO, it may be of use, for some people, to know there's a mailing list, as an alternative...
</blockquote></details>

Done.

**Review by KFilipek — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/851)* status: all files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

**Review by lukaszstolarczuk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/851)* status: all files reviewed, 2 unresolved discussions (waiting on @KFilipek)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/851#-MOY2q8e3S2Zm51VU6l8:-MOY2q8e3S2Zm51VU6l9:b-qj6y38) (no related file):*
something is no-yes - you committed/pushed Igor's merge commit

---
___
*[README.md, line 52 at r5](https://reviewable.io/reviews/pmem/pmemkv/851#-MOY3QFa0Ne90cHUPIwQ:-MOY3QFa0Ne90cHUPIwR:b-hplui7) ([raw file](https://github.com/pmem/pmemkv/blob/4004d273acc3ead9e5b0d1a6ee7e01d6539a6cc0/README.md#L52)):*
> ```Markdown
> 
> `pmemkv` is written in C/C++ and can be used in other languages - Java, Node.js,
> Python, and Ruby applications.
> ```

you can drop "applications" here, I believe

**Review by KFilipek — COMMENTED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/851)* status: all files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/851#-MOY2q8e3S2Zm51VU6l8:-MOaeklT7GN_AAI9WERL:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

something is no-yes - you committed/pushed Igor's merge commit
</blockquote></details>

Done.

---
___
*[README.md, line 52 at r5](https://reviewable.io/reviews/pmem/pmemkv/851#-MOY3QFa0Ne90cHUPIwQ:-MOaelRs-K5OyBJndZ_4:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/4004d273acc3ead9e5b0d1a6ee7e01d6539a6cc0/README.md#L52)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you can drop "applications" here, I believe
</blockquote></details>

Done.

**Review by lukaszstolarczuk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/851#-:-MObVlQv9v53-mLfWgun:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KFilipek)

**Review by igchor — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/851)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KFilipek)

**Pull request merged**
