### PR TITLE
Merge stable-1.4 into stable-1.5

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1082)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 13 files at r1, 5 of 24 files at r2, 1 of 19 files at r3, 18 of 19 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1082)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Comment by KFilipek** [comment]
[Invalid workflow file: .github/workflows/gha.yml#L32](https://github.com/pmem/pmemkv/actions/runs/2979355675/workflow)
You have an error in your yaml syntax on line 32

**Review by lukaszstolarczuk — COMMENTED** [review]
> [Invalid workflow file: .github/workflows/gha.yml#L32](https://github.com/pmem/pmemkv/actions/runs/2979355675/workflow) You have an error in your yaml syntax on line 32

Done.

> Reviewed 2 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1082#-:-NBC7xMpE5QHipU32P71:b9rsf69)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Comment by lukaszstolarczuk** [comment]
As of right now 3 tests (`vcmap__concurrent_put_get_remove*`) are failing on Fedora distributions. It will be fixed in later PR(s).

**Pull request merged**
