### PR TITLE
CMake fixes

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
- fix for default build type - it was set improperly
- fix pmreorder finding function `VERSION_LESS` should be used instead of just `LESS`
- minor cleanups, including:
  - extending comments,
  - extending printed messages,
  - fix minor todo,
  - fix tabs in one cmake file.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/975)

### CODE REVIEW

**Review by igchor — APPROVED** [review]
:lgtm:

> Reviewed 6 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/975#-:-MW3IgAv980OzyGW0bmt:bnfp4nl)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Comment by lukaszstolarczuk** [comment]
I've added small update for pmreorder finding function.

**Comment by KFilipek** [comment]
Some '.' missing on end of the message (in the last message was a dot), but it's not a stopper for this PR.

**Comment by lukaszstolarczuk** [comment]
> Some '.' missing on end of the message (in the last message was a dot), but it's not a stopper for this PR.

hmm.. can you pls be more precise? Most of our messages do not end with dot

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/975#-:-MWYRpfBDKGbp8aaIlu2:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/975)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[cmake/helpers.cmake, line 127 at r2](https://reviewable.io/reviews/pmem/pmemkv/975#-MWchK5h6PRlLlOopqaj:-MWchK5h6PRlLlOopqak:b1wrcww) ([raw file](https://github.com/pmem/pmemkv/blob/08e4382c78213902779e50e84af67fe5148d1a3d/cmake/helpers.cmake#L127)):*
> ```
> ([0-9]+.)([0-9]+)
> ```
Why do you need to match first dot? 
I would rather say, the regex should be 
```
(\d+).(\d+)
```
https://regex101.com/r/biusSN/1/

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/975)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @igchor, @karczex, and @KFilipek)

___
*[cmake/helpers.cmake, line 127 at r2](https://reviewable.io/reviews/pmem/pmemkv/975#-MWchK5h6PRlLlOopqaj:-MWdzd3ADex_vyNCVfLm:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/08e4382c78213902779e50e84af67fe5148d1a3d/cmake/helpers.cmake#L127)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

> ```
> ([0-9]+.)([0-9]+)
> ```
Why do you need to match first dot? 
I would rather say, the regex should be 
```
(\d+).(\d+)
```
https://regex101.com/r/biusSN/1/
</blockquote></details>

Done.

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/975#-:-MWxWgyv60g2bVTyF7Ra:bnfp4nl)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @igchor and @KFilipek)

**Pull request merged**
