### PR TITLE
WIP: Add maven and openjdk-8-jdk to Ubuntu Docker image

### PR DESCRIPTION
**Pull request by ldorau**
It will be needed by bindings tests.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/263)

### CODE REVIEW

**Comment by lukaszstolarczuk** [comment]
@annamarcink, can you see if that packages are enough for your work with java bindings?

**Comment by ldorau** [comment]
The log from Travis build:
https://travis-ci.org/pmem/pmemkv/jobs/536306834
contains the message:
`After this operation, 1557 MB of additional disk space will be used.`
Maybe we should consider creating a separate image for java bindings?

**Comment by ldorau** [comment]
> The log from Travis build:
> https://travis-ci.org/pmem/pmemkv/jobs/536306834
> contains the message:
> `After this operation, 1557 MB of additional disk space will be used.`
> Maybe we should consider creating a separate image for java bindings?

I have verified it - the size grows from **418 MB** to **612 MB** so IMHO it is acceptable:
current: https://cloud.docker.com/repository/registry-1.docker.io/pmem/pmemkv/tags
with java & maven: https://cloud.docker.com/repository/registry-1.docker.io/ldorau/pmemkv/tags

**Comment by ldorau** [comment]
Let's wait and check if we need add more packages for other bindings

**Comment by ldorau** [comment]
I think @annamarcink should submit such PR when all needed packages will be known.

**Pull request closed without merging**
