### PR TITLE
tests: parameterize most of remaining tests to work with fixed-size keys

### PR DESCRIPTION
**Pull request by JanDorniak99**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/941)

### CODE REVIEW

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/941)* status: 0 of 9 files reviewed, 3 unresolved discussions (waiting on @JanDorniak99)

___
*[tests/engine_scenarios/all/put_get_remove.cc, line 35 at r1](https://reviewable.io/reviews/pmem/pmemkv/941#-MTkeiFe5G0F0y0ByYz2:-MTkeiFe5G0F0y0ByYz3:bupryvb) ([raw file](https://github.com/pmem/pmemkv/blob/08bcbc19603afa35befe60f53b43946c7fbe9818/tests/engine_scenarios/all/put_get_remove.cc#L35)):*
> ```cpp
> }
> 
> static void EmptyKeyTest(pmem::kv::db &kv)
> ```

You shouldn't use entry_from_string() in this test, as for robinhood all entries would be filled with 'x'. If it's not possible to put empty key into robinhood, you probably should move this test to separate binary, and do not run it for radix.   
___
*[tests/engine_scenarios/all/put_get_remove.cc, line 69 at r1](https://reviewable.io/reviews/pmem/pmemkv/941#-MTkfn_tBodC_PWp8RWp:-MTkfn_tBodC_PWp8RWq:bvvqwl1) ([raw file](https://github.com/pmem/pmemkv/blob/08bcbc19603afa35befe60f53b43946c7fbe9818/tests/engine_scenarios/all/put_get_remove.cc#L69)):*
> ```cpp
> }
> 
> static void EmptyValueTest(pmem::kv::db &kv)
> ```

Same as EmptyKeyTest and PutValuesOfDifferentSizes
___
*[tests/engine_scenarios/all/put_get_remove.cc, line 251 at r1](https://reviewable.io/reviews/pmem/pmemkv/941#-MTkdLGd8CYSNnOLAx24:-MTkdLGd8CYSNnOLAx25:bo86b1z) ([raw file](https://github.com/pmem/pmemkv/blob/08bcbc19603afa35befe60f53b43946c7fbe9818/tests/engine_scenarios/all/put_get_remove.cc#L251)):*
> ```cpp
> }
> 
> static void PutValuesOfDifferentSizesTest(pmem::kv::db &kv)
> ```

It's little bit misleading, if you run  `PutValuesOfDifferentSizesTest` for fixed size engine.
Probably, you need to move this test to separate binary, and do not convert those strings by entry_from_string().

**Review by KFilipek — COMMENTED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/941)* status: all files reviewed, 3 unresolved discussions (waiting on @JanDorniak99)

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/941)* status: all files reviewed, 4 unresolved discussions (waiting on @JanDorniak99 and @karczex)

___
*[tests/engine_scenarios/all/put_get_remove.cc, line 35 at r1](https://reviewable.io/reviews/pmem/pmemkv/941#-MTkeiFe5G0F0y0ByYz2:-MU8CLuJ5GkmWq6bAiVk:b32v57) ([raw file](https://github.com/pmem/pmemkv/blob/08bcbc19603afa35befe60f53b43946c7fbe9818/tests/engine_scenarios/all/put_get_remove.cc#L35)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

You shouldn't use entry_from_string() in this test, as for robinhood all entries would be filled with 'x'. If it's not possible to put empty key into robinhood, you probably should move this test to separate binary, and do not run it for radix.   
</blockquote></details>

+1
___
*[tests/engine_scenarios/all/put_get_remove.cc, line 251 at r1](https://reviewable.io/reviews/pmem/pmemkv/941#-MTkdLGd8CYSNnOLAx24:-MU8CRsH1wk4U8ixR_9P:b-2g5giw) ([raw file](https://github.com/pmem/pmemkv/blob/08bcbc19603afa35befe60f53b43946c7fbe9818/tests/engine_scenarios/all/put_get_remove.cc#L251)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

It's little bit misleading, if you run  `PutValuesOfDifferentSizesTest` for fixed size engine.
Probably, you need to move this test to separate binary, and do not convert those strings by entry_from_string().  
</blockquote></details>

+1, don't forget to enable the new test for all engines
___
*[tests/engine_scenarios/all/put_get_remove_params.cc, line 11 at r1](https://reviewable.io/reviews/pmem/pmemkv/941#-MU8ChFXDVg5r2NYNC-8:-MU8ChFXDVg5r2NYNC-9:b-x0z1dn) ([raw file](https://github.com/pmem/pmemkv/blob/08bcbc19603afa35befe60f53b43946c7fbe9818/tests/engine_scenarios/all/put_get_remove_params.cc#L11)):*
> ```cpp
> {
> 	for (size_t i = 1; i <= iterations; i++) {
> 		std::string istr = entry_from_number(i);
> ```

What if number of iterations is so big that entry_from_number will have to shrink the string? it could lead to key collisions.
As I know think about this, the function align_to_size from unittest.hpp should return an error (UT_FATAL) in case string is longer than 8 bytes for radix tree. And just do not run any tests with such long strings for radix_tree.

Could you please change the align_size?

**Review by JanDorniak99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/941)* status: 7 of 12 files reviewed, 4 unresolved discussions (waiting on @igchor, @karczex, and @KFilipek)

___
*[tests/engine_scenarios/all/put_get_remove.cc, line 35 at r1](https://reviewable.io/reviews/pmem/pmemkv/941#-MTkeiFe5G0F0y0ByYz2:-MUDxcE67YV5KB9vKluE:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/08bcbc19603afa35befe60f53b43946c7fbe9818/tests/engine_scenarios/all/put_get_remove.cc#L35)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[tests/engine_scenarios/all/put_get_remove.cc, line 69 at r1](https://reviewable.io/reviews/pmem/pmemkv/941#-MTkfn_tBodC_PWp8RWp:-MUDxci71VRXIFc6GUQi:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/08bcbc19603afa35befe60f53b43946c7fbe9818/tests/engine_scenarios/all/put_get_remove.cc#L69)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Same as EmptyKeyTest and PutValuesOfDifferentSizes
</blockquote></details>

Done.
___
*[tests/engine_scenarios/all/put_get_remove.cc, line 251 at r1](https://reviewable.io/reviews/pmem/pmemkv/941#-MTkdLGd8CYSNnOLAx24:-MUDxdnm01fygCh5IgCt:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/08bcbc19603afa35befe60f53b43946c7fbe9818/tests/engine_scenarios/all/put_get_remove.cc#L251)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

+1, don't forget to enable the new test for all engines
</blockquote></details>

Done.
___
*[tests/engine_scenarios/all/put_get_remove_params.cc, line 11 at r1](https://reviewable.io/reviews/pmem/pmemkv/941#-MU8ChFXDVg5r2NYNC-8:-MUHyBjc2n57Nvx0GZtb:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/08bcbc19603afa35befe60f53b43946c7fbe9818/tests/engine_scenarios/all/put_get_remove_params.cc#L11)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

What if number of iterations is so big that entry_from_number will have to shrink the string? it could lead to key collisions.
As I know think about this, the function align_to_size from unittest.hpp should return an error (UT_FATAL) in case string is longer than 8 bytes for radix tree. And just do not run any tests with such long strings for radix_tree.

Could you please change the align_size?
</blockquote></details>

Done.

**Review by KFilipek — COMMENTED** [review]
> Reviewed 4 of 8 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/941)* status: 11 of 15 files reviewed, 5 unresolved discussions (waiting on @igchor, @JanDorniak99, and @karczex)

___
*[tests/common/unittest.hpp, line 235 at r2](https://reviewable.io/reviews/pmem/pmemkv/941#-MUJERZ676cPEYfRc3Iv:-MUJERZ676cPEYfRc3Iw:b-bqfqk0) ([raw file](https://github.com/pmem/pmemkv/blob/2b4248e4526a0d27cb023cffadf2573383dd0a7c/tests/common/unittest.hpp#L235)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> static inline std::string uint64_to_string(uint64_t &key)
> {
> 	return std::string(reinterpret_cast<const char *>(&key), 8);
> }
> ```
</details>

What is purpose of this function? This function don't convert uint64_t to string in the way of std::to_string().
https://en.cppreference.com/w/cpp/string/basic_string/to_string

**Review by JanDorniak99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/941)* status: 11 of 15 files reviewed, 5 unresolved discussions (waiting on @igchor, @karczex, and @KFilipek)

___
*[tests/common/unittest.hpp, line 235 at r2](https://reviewable.io/reviews/pmem/pmemkv/941#-MUJERZ676cPEYfRc3Iv:-MUN91wj483MqYaUNmKj:b-lp8cha) ([raw file](https://github.com/pmem/pmemkv/blob/2b4248e4526a0d27cb023cffadf2573383dd0a7c/tests/common/unittest.hpp#L235)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> static inline std::string uint64_to_string(uint64_t &key)
> {
> 	return std::string(reinterpret_cast<const char *>(&key), 8);
> }
> ```
What is purpose of this function? This function don't convert uint64_t to string in the way of std::to_string().
https://en.cppreference.com/w/cpp/string/basic_string/to_string
</blockquote></details>

This uint64_t is there more like 8 random bytes to generate a random string with a size of 8.

**Review by KFilipek — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/941#-:-MUTQUVXAPSBuCKcsJEj:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @igchor, @JanDorniak99, and @karczex)

___
*[tests/common/unittest.hpp, line 235 at r2](https://reviewable.io/reviews/pmem/pmemkv/941#-MUJERZ676cPEYfRc3Iv:-MUTQIho4AN-rmolKVCo:byju1w8) ([raw file](https://github.com/pmem/pmemkv/blob/2b4248e4526a0d27cb023cffadf2573383dd0a7c/tests/common/unittest.hpp#L235)):*
> ```
> uint64_to_string
> ```
Very strange, but ok.

**Review by igchor — APPROVED** [review]
> Reviewed 7 of 9 files at r1, 7 of 8 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/941)* status: all files reviewed, 4 unresolved discussions (waiting on @JanDorniak99 and @karczex)

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 7 of 9 files at r1, 6 of 8 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/941)* status: all files reviewed, 13 unresolved discussions (waiting on @JanDorniak99 and @karczex)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/941#-MUtJ0r--9GzBt86FTV9:-MUtJ0r--9GzBt86FTVA:b-nimv2l) (no related file):*
please add in commit msg also an info that all const keys and values in our tests were shorten to fit within 8 bytes

---
___
*[tests/common/unittest.hpp, line 230 at r3](https://reviewable.io/reviews/pmem/pmemkv/941#-MUt3xeS4SLvFwOiixxS:-MUt3xeS4SLvFwOiixxT:b-8lmb27) ([raw file](https://github.com/pmem/pmemkv/blob/1d7069cfb5e46151b15724a49581e3984cd66e26/tests/common/unittest.hpp#L230)):*
> ```cpp
> #endif /* JSON_TESTS_SUPPORT */
> 
> static inline pmem::kv::string_view uint64_to_strv(uint64_t &key)
> ```

pls add comments to all these (new/almost new) functions
___
*[tests/common/unittest.hpp, line 243 at r3](https://reviewable.io/reviews/pmem/pmemkv/941#-MUt4BmQ3tnvHM7hc1z5:-MUt4BmRBL0jNAkmtyJ9:b2r7821) ([raw file](https://github.com/pmem/pmemkv/blob/1d7069cfb5e46151b15724a49581e3984cd66e26/tests/common/unittest.hpp#L243)):*
> ```cpp
> 					char char_to_fill = 'x')
> {
> 	std::string res;
> ```

you don't need this `res` var, I believe...? ut_fatal aborts the execution
___
*[tests/engine_scenarios/all/put_get_remove_charset_params.cc, line 19 at r3](https://reviewable.io/reviews/pmem/pmemkv/941#-MUtE2asBThAB-8njAYr:-MUtE2asBThAB-8njAYs:b5cfif0) ([raw file](https://github.com/pmem/pmemkv/blob/1d7069cfb5e46151b15724a49581e3984cd66e26/tests/engine_scenarios/all/put_get_remove_charset_params.cc#L19)):*
> ```cpp
> static constexpr size_t CHARSET_LEN = CHARSET_RANGE_END - CHARSET_RANGE_START + 1;
> 
> std::vector<std::string> generate_binary_strings(const size_t cnt,
> ```

perhaps pls add a short description for this, to describe what kind of keys are generated
___
*[tests/engine_scenarios/all/put_get_remove_charset_params.cc, line 25 at r3](https://reviewable.io/reviews/pmem/pmemkv/941#-MUtChhL7Tl78gGjrsPD:-MUtChhL7Tl78gGjrsPE:bfx0r08) ([raw file](https://github.com/pmem/pmemkv/blob/1d7069cfb5e46151b15724a49581e3984cd66e26/tests/engine_scenarios/all/put_get_remove_charset_params.cc#L25)):*
> ```cpp
> 	for (size_t s = 0; s < cnt; ++s) {
> 		std::string gen_str = std::to_string(s);
> 		/* various lenght of string, min: len of prefix */
> ```

you said prefix, but you're not using the PREFIX variable - did you mean the len of `str(s)` ?
___
*[tests/engine_scenarios/all/put_get_remove_not_aligned.cc, line 7 at r3](https://reviewable.io/reviews/pmem/pmemkv/941#-MUtELpZ8SJd1ohzk1Af:-MUtELpZ8SJd1ohzk1Ag:b5udd1) ([raw file](https://github.com/pmem/pmemkv/blob/1d7069cfb5e46151b15724a49581e3984cd66e26/tests/engine_scenarios/all/put_get_remove_not_aligned.cc#L7)):*
> ```cpp
> 
> /**
>  * Tests adding, reading and removing data; basic short, tests. Only for engines with no
> ```

I'm missing from this description info it's not accidental they are not suitable for fixed-size keys... pls add info they are for whitespace keys/values and different key sizes, etc...
___
*[tests/engine_scenarios/pmemobj/error_handling_tx_oid.cc, line 2 at r3](https://reviewable.io/reviews/pmem/pmemkv/941#-MUtHsOODJ3te8zGEKfu:-MUtHsOODJ3te8zGEKfv:bi6b16d) ([raw file](https://github.com/pmem/pmemkv/blob/1d7069cfb5e46151b15724a49581e3984cd66e26/tests/engine_scenarios/pmemobj/error_handling_tx_oid.cc#L2)):*
> ```cpp
> // SPDX-License-Identifier: BSD-3-Clause
> /* Copyright 2020-2021, Intel Corporation */
> ```

no changes here...? why update license?
___
*[tests/engine_scenarios/pmreorder/erase.cc, line 10 at r3](https://reviewable.io/reviews/pmem/pmemkv/941#-MUtIBfr9Bh3JYoHdgpx:-MUtIBfs62ZrclIvKN6x:b-6ve43p) ([raw file](https://github.com/pmem/pmemkv/blob/1d7069cfb5e46151b15724a49581e3984cd66e26/tests/engine_scenarios/pmreorder/erase.cc#L10)):*
> ```cpp
> #include "unittest.hpp"
> 
> static constexpr int len_elements = 10;
> ```

shouldn't this be updated to size_t...? some static analysis will warn about it (or am I mistaken...?)
___
*[tests/engine_scenarios/pmreorder/insert.cc, line 10 at r3](https://reviewable.io/reviews/pmem/pmemkv/941#-MUtIeXn9OP5uq-AMloy:-MUtIeXn9OP5uq-AMloz:b3kqx) ([raw file](https://github.com/pmem/pmemkv/blob/1d7069cfb5e46151b15724a49581e3984cd66e26/tests/engine_scenarios/pmreorder/insert.cc#L10)):*
> ```cpp
> #include "unittest.hpp"
> 
> static constexpr int len_elements = 10;
> ```

.

**Review by JanDorniak99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/941)* status: 9 of 15 files reviewed, 13 unresolved discussions (waiting on @igchor, @JanDorniak99, @karczex, @KFilipek, and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/941#-MUtJ0r--9GzBt86FTV9:-MUwdaSsE5X9IOVe2UCh:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

please add in commit msg also an info that all const keys and values in our tests were shorten to fit within 8 bytes
</blockquote></details>

Done.

---
___
*[tests/common/unittest.hpp, line 230 at r3](https://reviewable.io/reviews/pmem/pmemkv/941#-MUt3xeS4SLvFwOiixxS:-MUwPtMx9AhlaFazDFa4:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/1d7069cfb5e46151b15724a49581e3984cd66e26/tests/common/unittest.hpp#L230)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls add comments to all these (new/almost new) functions
</blockquote></details>

Done.
___
*[tests/common/unittest.hpp, line 243 at r3](https://reviewable.io/reviews/pmem/pmemkv/941#-MUt4BmQ3tnvHM7hc1z5:-MUwQU0G7nop6nJMqzMb:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/1d7069cfb5e46151b15724a49581e3984cd66e26/tests/common/unittest.hpp#L243)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you don't need this `res` var, I believe...? ut_fatal aborts the execution
</blockquote></details>

Done.
___
*[tests/engine_scenarios/all/put_get_remove_charset_params.cc, line 19 at r3](https://reviewable.io/reviews/pmem/pmemkv/941#-MUtE2asBThAB-8njAYr:-MUwS0EW5WbXS5degeCq:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/1d7069cfb5e46151b15724a49581e3984cd66e26/tests/engine_scenarios/all/put_get_remove_charset_params.cc#L19)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps pls add a short description for this, to describe what kind of keys are generated
</blockquote></details>

Done.
___
*[tests/engine_scenarios/all/put_get_remove_charset_params.cc, line 25 at r3](https://reviewable.io/reviews/pmem/pmemkv/941#-MUtChhL7Tl78gGjrsPD:-MUwS1ReBRT1ktCquGJF:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/1d7069cfb5e46151b15724a49581e3984cd66e26/tests/engine_scenarios/all/put_get_remove_charset_params.cc#L25)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you said prefix, but you're not using the PREFIX variable - did you mean the len of `str(s)` ?
</blockquote></details>

Done.
___
*[tests/engine_scenarios/all/put_get_remove_not_aligned.cc, line 7 at r3](https://reviewable.io/reviews/pmem/pmemkv/941#-MUtELpZ8SJd1ohzk1Af:-MUw_umF3pLUsLRRCKJ6:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/1d7069cfb5e46151b15724a49581e3984cd66e26/tests/engine_scenarios/all/put_get_remove_not_aligned.cc#L7)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I'm missing from this description info it's not accidental they are not suitable for fixed-size keys... pls add info they are for whitespace keys/values and different key sizes, etc...
</blockquote></details>

Done.
___
*[tests/engine_scenarios/pmemobj/error_handling_tx_oid.cc, line 2 at r3](https://reviewable.io/reviews/pmem/pmemkv/941#-MUtHsOODJ3te8zGEKfu:-MUwa1sR6wxDWuS0g1Mv:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/1d7069cfb5e46151b15724a49581e3984cd66e26/tests/engine_scenarios/pmemobj/error_handling_tx_oid.cc#L2)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

no changes here...? why update license?
</blockquote></details>

Done.
___
*[tests/engine_scenarios/pmreorder/erase.cc, line 10 at r3](https://reviewable.io/reviews/pmem/pmemkv/941#-MUtIBfr9Bh3JYoHdgpx:-MUwaGHk2wwAZg13Q0I8:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/1d7069cfb5e46151b15724a49581e3984cd66e26/tests/engine_scenarios/pmreorder/erase.cc#L10)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

shouldn't this be updated to size_t...? some static analysis will warn about it (or am I mistaken...?)
</blockquote></details>

Done.
___
*[tests/engine_scenarios/pmreorder/insert.cc, line 10 at r3](https://reviewable.io/reviews/pmem/pmemkv/941#-MUtIeXn9OP5uq-AMloy:-MUwaGwV4RrmitKjrZuL:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/1d7069cfb5e46151b15724a49581e3984cd66e26/tests/engine_scenarios/pmreorder/insert.cc#L10)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 8 files at r2, 7 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/941#-:-MUx2zh_DpZE7jzrE2af:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @JanDorniak99 and @karczex)

**Pull request merged**
