### PR TITLE
Dram vcmap engine

### PR DESCRIPTION
**Pull request by karczex**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/952)

### CODE REVIEW

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/952)* status: 0 of 13 files reviewed, 1 unresolved discussion

___
*[src/engines/basic_vcmap.h, line 82 at r1](https://reviewable.io/reviews/pmem/pmemkv/952#-MUwbiBs4mr8AmDhLpPd:-MUwbiBs4mr8AmDhLpPe:b-exdi23) ([raw file](https://github.com/pmem/pmemkv/blob/867771a58948e1ae56dc082933d52b4e153ce0d8/src/engines/basic_vcmap.h#L82)):*
> ```
> name
> ```
This is wrong, and we have no test for it

**Review by KFilipek — COMMENTED** [review]
> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/952)* status: all files reviewed, 2 unresolved discussions (waiting on @karczex)

___
*[src/engines/vcmap.h, line 50 at r1](https://reviewable.io/reviews/pmem/pmemkv/952#-MUwlUHP852DBM30GChz:-MUwlUHQ6XewT0Fv2hYN:b-liz2t0) ([raw file](https://github.com/pmem/pmemkv/blob/867771a58948e1ae56dc082933d52b4e153ce0d8/src/engines/vcmap.h#L50)):*
> ```
> using vcmap = basic_vcmap<internal::memkind_allocator_wrapper>;
> ```
Can we move it to the top? Probably this will need forward declaration.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/952)* status: all files reviewed, 7 unresolved discussions (waiting on @karczex)

___
*[CMakeLists.txt, line 296 at r1](https://reviewable.io/reviews/pmem/pmemkv/952#-MUxBhVeEsNC5dqagKcR:-MUxBhVeEsNC5dqagKcS:b-ecv0at) ([raw file](https://github.com/pmem/pmemkv/blob/867771a58948e1ae56dc082933d52b4e153ce0d8/CMakeLists.txt#L296)):*
> ```CMake
> 
> target_link_libraries(pmemkv PRIVATE ${LIBPMEMOBJ++_LIBRARIES})
> if(ENGINE_VSMAP OR ENGINE_VCMAP)
> ```

`OR` here as well...?
___
*[CONTRIBUTING.md, line 103 at r1](https://reviewable.io/reviews/pmem/pmemkv/952#-MUwdrQMBKwmtTQaK1wN:-MUwdrQMBKwmtTQaK1wO:b-wr4bpq) ([raw file](https://github.com/pmem/pmemkv/blob/867771a58948e1ae56dc082933d52b4e153ce0d8/CONTRIBUTING.md#L103)):*
> ```Markdown
> * Formatted in all lower-case
> * No whitespace or special characters
> * For this example: `mytree` (persistent, single-threaded, unsorted)
> ```

pls update this line too, then
___
*[src/engines/basic_vcmap.h, line 82 at r1](https://reviewable.io/reviews/pmem/pmemkv/952#-MUwbiBs4mr8AmDhLpPd:-MUwdxyN2jAhsAGDGDMq:bpjxa6h) ([raw file](https://github.com/pmem/pmemkv/blob/867771a58948e1ae56dc082933d52b4e153ce0d8/src/engines/basic_vcmap.h#L82)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

> ```
> name
> ```
This is wrong, and we have no test for it
</blockquote></details>

hah, I just realized the same thing yesterday, while browsing some codecov report.
___
*[tests/CMakeLists.txt, line 1837 at r1](https://reviewable.io/reviews/pmem/pmemkv/952#-MUxEe2U7hY8sjDob8-H:-MUxEe2U7hY8sjDob8-I:b-e90xee) ([raw file](https://github.com/pmem/pmemkv/blob/867771a58948e1ae56dc082933d52b4e153ce0d8/tests/CMakeLists.txt#L1837)):*
> ```CMake
> endif()
> ################################################################################
> ###################################### dram_vcmap ###################################
> ```

pls uppercase ;)
___
*[tests/engines/dram/default.cmake, line 2 at r1](https://reviewable.io/reviews/pmem/pmemkv/952#-MUxEuVCEC6v6Pgk4MA3:-MUxEuVCEC6v6Pgk4MA4:bb6ht36) ([raw file](https://github.com/pmem/pmemkv/blob/867771a58948e1ae56dc082933d52b4e153ce0d8/tests/engines/dram/default.cmake#L2)):*
> ```CMake
> # SPDX-License-Identifier: BSD-3-Clause
> # Copyright 2020, Intel Corporation
> ```

2021
___
*[utils/docker/run-build.sh, line 1 at r1](https://reviewable.io/reviews/pmem/pmemkv/952#-MUxF1Ss2hfFgZYD2Zwg:-MUxF1Ss2hfFgZYD2Zwh:ba6prm9) ([raw file](https://github.com/pmem/pmemkv/blob/a1d8918b7b117418c130277fac2974e7afc8237e/utils/docker/run-build.sh#L1)):*
> ```Shell
> #!/usr/bin/env bash
> ```

pls also extend run-test-building.sh

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/952)* status: 7 of 15 files reviewed, 7 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[CMakeLists.txt, line 296 at r1](https://reviewable.io/reviews/pmem/pmemkv/952#-MUxBhVeEsNC5dqagKcR:-MUxMhPt2z64BI-k5o_H:b-439cui) ([raw file](https://github.com/pmem/pmemkv/blob/867771a58948e1ae56dc082933d52b4e153ce0d8/CMakeLists.txt#L296)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`OR` here as well...?
</blockquote></details>

Nope. Memkind is not needed for std::allocator based engine. 
___
*[CONTRIBUTING.md, line 103 at r1](https://reviewable.io/reviews/pmem/pmemkv/952#-MUwdrQMBKwmtTQaK1wN:-MUxSSXSDPf0cVySDQcv:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/867771a58948e1ae56dc082933d52b4e153ce0d8/CONTRIBUTING.md#L103)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls update this line too, then
</blockquote></details>

Done.
___
*[src/engines/basic_vcmap.h, line 82 at r1](https://reviewable.io/reviews/pmem/pmemkv/952#-MUwbiBs4mr8AmDhLpPd:-MUxSEwk8KpNwHeNVtLq:bw9s7j6) ([raw file](https://github.com/pmem/pmemkv/blob/867771a58948e1ae56dc082933d52b4e153ce0d8/src/engines/basic_vcmap.h#L82)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hah, I just realized the same thing yesterday, while browsing some codecov report.
</blockquote></details>

Fixed with added `name()` overloads in specialization classes
___
*[src/engines/vcmap.h, line 50 at r1](https://reviewable.io/reviews/pmem/pmemkv/952#-MUwlUHP852DBM30GChz:-MUxOfAj7drUorc7zZNZ:b-7yulx8) ([raw file](https://github.com/pmem/pmemkv/blob/867771a58948e1ae56dc082933d52b4e153ce0d8/src/engines/vcmap.h#L50)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> using vcmap = basic_vcmap<internal::memkind_allocator_wrapper>;
> ```
Can we move it to the top? Probably this will need forward declaration.
</blockquote></details>

Why? 
___
*[tests/CMakeLists.txt, line 1837 at r1](https://reviewable.io/reviews/pmem/pmemkv/952#-MUxEe2U7hY8sjDob8-H:-MUxP5rqBWXdwAjgP0XM:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/867771a58948e1ae56dc082933d52b4e153ce0d8/tests/CMakeLists.txt#L1837)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls uppercase ;)
</blockquote></details>

Done.
___
*[tests/engines/dram/default.cmake, line 2 at r1](https://reviewable.io/reviews/pmem/pmemkv/952#-MUxEuVCEC6v6Pgk4MA3:-MUxPFr276iP22fo_pU-:bx6xqsv) ([raw file](https://github.com/pmem/pmemkv/blob/867771a58948e1ae56dc082933d52b4e153ce0d8/tests/engines/dram/default.cmake#L2)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

2021
</blockquote></details>

Life is so short....
___
*[utils/docker/run-build.sh, line 1 at r1](https://reviewable.io/reviews/pmem/pmemkv/952#-MUxF1Ss2hfFgZYD2Zwg:-MUxSYLbEUttPYdEfQe6:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/a1d8918b7b117418c130277fac2974e7afc8237e/utils/docker/run-build.sh#L1)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls also extend run-test-building.sh
</blockquote></details>

Done.

**Review by KFilipek — COMMENTED** [review]
:lgtm:

> Reviewed 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/952#-:-MV15_nZ59Ylji9Ya9jX:bnfp4nl)* status: all files reviewed, 6 unresolved discussions (waiting on @lukaszstolarczuk)

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 7 of 13 files at r1, 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/952)* status: all files reviewed, 4 unresolved discussions (waiting on @karczex)

___
*[src/engines/basic_vcmap.h, line 7 at r2](https://reviewable.io/reviews/pmem/pmemkv/952#-MV1Jjr_Dly1KX0xfz1I:-MV1Jjr_Dly1KX0xfz1J:b94jl31) ([raw file](https://github.com/pmem/pmemkv/blob/a1fc0ba8e3fa6504cc5179339399bec71b3993b7/src/engines/basic_vcmap.h#L7)):*
> ```objc
> 
> #include "../out.h"
> #include <libpmemobj++/transaction.hpp>
> ```

do we need obj-cpp's transactions here...?
___
*[src/engines/basic_vcmap.h, line 10 at r2](https://reviewable.io/reviews/pmem/pmemkv/952#-MV1JcfX-3KwgxVZLXGV:-MV1JcfX-3KwgxVZLXGW:b-bwr8ro) ([raw file](https://github.com/pmem/pmemkv/blob/a1fc0ba8e3fa6504cc5179339399bec71b3993b7/src/engines/basic_vcmap.h#L10)):*
> ```objc
> 
> #include "../engine.h"
> #include "pmem_allocator.h"
> ```

isn't this memkind include?
___
*[src/engines-testing/dram_vcmap.cc, line 2 at r2](https://reviewable.io/reviews/pmem/pmemkv/952#-MV1Jxiq17E9-e1T2Pxt:-MV1Jxiq17E9-e1T2Pxu:b-5qhht3) ([raw file](https://github.com/pmem/pmemkv/blob/a1fc0ba8e3fa6504cc5179339399bec71b3993b7/src/engines-testing/dram_vcmap.cc#L2)):*
> ```cpp
> // SPDX-License-Identifier: BSD-3-Clause
> /* Copyright 2017-2021, Intel Corporation */
> ```

2021 should be enough, it's new file, I guess

**Review by igchor — APPROVED** [review]
:lgtm:

> Reviewed 2 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/952#-:-MV1Z4_J4QvQd2liMmOw:bnfp4nl)* status: 11 of 15 files reviewed, 4 unresolved discussions (waiting on @karczex, @KFilipek, and @lukaszstolarczuk)

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/952)* status: 11 of 15 files reviewed, 3 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[src/engines/basic_vcmap.h, line 7 at r2](https://reviewable.io/reviews/pmem/pmemkv/952#-MV1Jjr_Dly1KX0xfz1I:-MV1QECxByz8KHaPUs9i:brw1h9b) ([raw file](https://github.com/pmem/pmemkv/blob/a1fc0ba8e3fa6504cc5179339399bec71b3993b7/src/engines/basic_vcmap.h#L7)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

do we need obj-cpp's transactions here...?
</blockquote></details>

hmm... that's interesting :) 
It's not needed, and for some reason, it's included in vcmap.cc on current master. 
Done.
___
*[src/engines/basic_vcmap.h, line 10 at r2](https://reviewable.io/reviews/pmem/pmemkv/952#-MV1JcfX-3KwgxVZLXGV:-MV1QTa34CCPE08YFCJC:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/a1fc0ba8e3fa6504cc5179339399bec71b3993b7/src/engines/basic_vcmap.h#L10)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

isn't this memkind include?
</blockquote></details>

Done.
___
*[src/engines-testing/dram_vcmap.cc, line 2 at r2](https://reviewable.io/reviews/pmem/pmemkv/952#-MV1Jxiq17E9-e1T2Pxt:-MV1b1IIBXRJkVuKX8Oc:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/a1fc0ba8e3fa6504cc5179339399bec71b3993b7/src/engines-testing/dram_vcmap.cc#L2)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

2021 should be enough, it's new file, I guess
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/952#-:-MV1j0KW-5jhi_8IZQ_z:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)

**Pull request merged**
