### PR TITLE
gha: change IMG_VER from latest to tag version on release

### PR DESCRIPTION
**Pull request by igchor**
and for stables, use version from the branch name

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/933)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/933)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @igchor)

___
*[.github/workflows/gha.yml, line 46 at r1](https://reviewable.io/reviews/pmem/pmemkv/933#-MTa8kiq3YulsYW93SG7:-MTa8kiq3YulsYW93SG8:brud1yz) ([raw file](https://github.com/pmem/pmemkv/blob/7c93ccb3c934e2377f142887b2a6754163b207ab/.github/workflows/gha.yml#L46)):*
> ```YAML
>         if: github.event_name == 'release'
>         id: get_release_version
>         run: echo ::set-output name=VERSION::$(echo ${{ github.event.release.tag_name }} | grep -E "^[0-9]+.[0-9]+(-rc[0-9]+)?$" | cut -f 1,2 -d . | cut -f 1 -d -)
> ```

As I said on previous PR - I'm not sure if we require to run this workload "on release". The release itself will be covered on stable branch, on push event. 
___
*[.github/workflows/gha.yml, line 46 at r1](https://reviewable.io/reviews/pmem/pmemkv/933#-MTa9-itDLFbf5QPw56L:-MTa9-itDLFbf5QPw56M:b-r0ke8q) ([raw file](https://github.com/pmem/pmemkv/blob/7c93ccb3c934e2377f142887b2a6754163b207ab/.github/workflows/gha.yml#L46)):*
> ```YAML
>         if: github.event_name == 'release'
>         id: get_release_version
>         run: echo ::set-output name=VERSION::$(echo ${{ github.event.release.tag_name }} | grep -E "^[0-9]+.[0-9]+(-rc[0-9]+)?$" | cut -f 1,2 -d . | cut -f 1 -d -)
> ```

anyway, will this work for patch release?
___
*[.github/workflows/gha.yml, line 52 at r1](https://reviewable.io/reviews/pmem/pmemkv/933#-MTa9FfL9gQOgbKEFnN5:-MTa9FfL9gQOgbKEFnN6:b-x8q8tj) ([raw file](https://github.com/pmem/pmemkv/blob/7c93ccb3c934e2377f142887b2a6754163b207ab/.github/workflows/gha.yml#L52)):*
> ```YAML
>         run: |
>           echo "IMG_VER=${{ steps.get_release_version.outputs.VERSION }}" >> $GITHUB_ENV
>           echo "FORCE_IMAGE_ACTION=rebuild" >> $GITHUB_ENV
> ```

we want to force the rebuild for the actual release?
___
*[.github/workflows/gha.yml, line 57 at r1](https://reviewable.io/reviews/pmem/pmemkv/933#-MTa9xGb3zsA_HqCbzfd:-MTa9xGb3zsA_HqCbzfe:b-hvmw2j) ([raw file](https://github.com/pmem/pmemkv/blob/7c93ccb3c934e2377f142887b2a6754163b207ab/.github/workflows/gha.yml#L57)):*
> ```YAML
>         if: startsWith(github.ref, 'refs/heads/stable-')
>         run: |
>           echo "IMG_VER=$(echo ${GITHUB_REF#refs/heads/} | cut -d - -f 2)" >> $GITHUB_ENV
> ```

this will not be set for 'docs' job
(see stable-1.12 on libpmemobj-cpp: https://github.com/pmem/libpmemobj-cpp/runs/1903247411?check_suite_focus=true )

I'm not sure this will be a problem, but maaaybe...?
___
*[.github/workflows/gha.yml, line 60 at r1](https://reviewable.io/reviews/pmem/pmemkv/933#-MTa9WRs0FiQ5H2CPN3f:-MTa9WRs0FiQ5H2CPN3g:b-nsqcu9) ([raw file](https://github.com/pmem/pmemkv/blob/7c93ccb3c934e2377f142887b2a6754163b207ab/.github/workflows/gha.yml#L60)):*
> ```YAML
>           echo "FORCE_IMAGE_ACTION=rebuild" >> $GITHUB_ENV
> ```

redundant empty line

**Review by KFilipek — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/933)* status: all files reviewed, 6 unresolved discussions (waiting on @igchor)

___
*[.github/workflows/gha.yml, line 10 at r1](https://reviewable.io/reviews/pmem/pmemkv/933#-MTqAJfCB-S605m1LpwI:-MTqAJfD5TUFVSA5yCki:bt006ng) ([raw file](https://github.com/pmem/pmemkv/blob/7c93ccb3c934e2377f142887b2a6754163b207ab/.github/workflows/gha.yml#L10)):*
> ```YAML
>       - created
> ```

empty line

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/933)* status: all files reviewed, 6 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[.github/workflows/gha.yml, line 10 at r1](https://reviewable.io/reviews/pmem/pmemkv/933#-MTqAJfCB-S605m1LpwI:-MU8liWfDBT5mC12B5ak:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/7c93ccb3c934e2377f142887b2a6754163b207ab/.github/workflows/gha.yml#L10)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

empty line
</blockquote></details>

Done.
___
*[.github/workflows/gha.yml, line 46 at r1](https://reviewable.io/reviews/pmem/pmemkv/933#-MTa8kiq3YulsYW93SG7:-MU8lGDCDTWcvng9bebF:bwcdbk) ([raw file](https://github.com/pmem/pmemkv/blob/7c93ccb3c934e2377f142887b2a6754163b207ab/.github/workflows/gha.yml#L46)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

As I said on previous PR - I'm not sure if we require to run this workload "on release". The release itself will be covered on stable branch, on push event. 
</blockquote></details>

Right, but maybe it could be useful for some other activities (like auto request for vcpkg update ;d). Besides, I think it would be good to have a build for the release (tag) itself.
___
*[.github/workflows/gha.yml, line 46 at r1](https://reviewable.io/reviews/pmem/pmemkv/933#-MTa9-itDLFbf5QPw56L:-MU8lE8v1rKmSfxFTB1s:b-or2i9t) ([raw file](https://github.com/pmem/pmemkv/blob/7c93ccb3c934e2377f142887b2a6754163b207ab/.github/workflows/gha.yml#L46)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

anyway, will this work for patch release?
</blockquote></details>

Yes, it should work
___
*[.github/workflows/gha.yml, line 52 at r1](https://reviewable.io/reviews/pmem/pmemkv/933#-MTa9FfL9gQOgbKEFnN5:-MU8m3LJDqnxwNbHEhhA:b-8ictw5) ([raw file](https://github.com/pmem/pmemkv/blob/7c93ccb3c934e2377f142887b2a6754163b207ab/.github/workflows/gha.yml#L52)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

we want to force the rebuild for the actual release?
</blockquote></details>

I would say yes
___
*[.github/workflows/gha.yml, line 57 at r1](https://reviewable.io/reviews/pmem/pmemkv/933#-MTa9xGb3zsA_HqCbzfd:-MU8mKH28Ppi4BVPeQ1R:b62o8fp) ([raw file](https://github.com/pmem/pmemkv/blob/7c93ccb3c934e2377f142887b2a6754163b207ab/.github/workflows/gha.yml#L57)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

this will not be set for 'docs' job
(see stable-1.12 on libpmemobj-cpp: https://github.com/pmem/libpmemobj-cpp/runs/1903247411?check_suite_focus=true )

I'm not sure this will be a problem, but maaaybe...?
</blockquote></details>

Hm, so, should we copy this step to doc also?
___
*[.github/workflows/gha.yml, line 60 at r1](https://reviewable.io/reviews/pmem/pmemkv/933#-MTa9WRs0FiQ5H2CPN3f:-MU8mNDQBx5WSsGvIlzk:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/7c93ccb3c934e2377f142887b2a6754163b207ab/.github/workflows/gha.yml#L60)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

redundant empty line
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/933)* status: all files reviewed, 3 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[.github/workflows/gha.yml, line 46 at r1](https://reviewable.io/reviews/pmem/pmemkv/933#-MTa9-itDLFbf5QPw56L:-MU9RYEhBz441-F2qmNh:b-9p3co9) ([raw file](https://github.com/pmem/pmemkv/blob/7c93ccb3c934e2377f142887b2a6754163b207ab/.github/workflows/gha.yml#L46)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Yes, it should work
</blockquote></details>

I don't see catching the second possibly dot; shouldn't it be something like `^[0-9]+(.[0-9]+){0,1}(-rc...`
___
*[.github/workflows/gha.yml, line 57 at r1](https://reviewable.io/reviews/pmem/pmemkv/933#-MTa9xGb3zsA_HqCbzfd:-MU9Soa_CkuCJblm9nZb:b6feirs) ([raw file](https://github.com/pmem/pmemkv/blob/7c93ccb3c934e2377f142887b2a6754163b207ab/.github/workflows/gha.yml#L57)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Hm, so, should we copy this step to doc also?
</blockquote></details>

I believe we should set it properly, so yes - it should be copied (unless there's some trick in GHA workflow, I don't know, to inherit the variables for the docs job...)

**Review by KFilipek — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/933#-:-MU9WDAJ4yJTeSNmSzBF:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @igchor)

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/933)* status: all files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[.github/workflows/gha.yml, line 46 at r1](https://reviewable.io/reviews/pmem/pmemkv/933#-MTa9-itDLFbf5QPw56L:-MV1ZSctD7GoOFlBasLB:b-47qlxp) ([raw file](https://github.com/pmem/pmemkv/blob/7c93ccb3c934e2377f142887b2a6754163b207ab/.github/workflows/gha.yml#L46)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I don't see catching the second possibly dot; shouldn't it be something like `^[0-9]+(.[0-9]+){0,1}(-rc...`
</blockquote></details>

Ok, I just removed the release step ;d 
___
*[.github/workflows/gha.yml, line 57 at r1](https://reviewable.io/reviews/pmem/pmemkv/933#-MTa9xGb3zsA_HqCbzfd:-MV1_Yi40Setu_uVBLvc:b-q0i5au) ([raw file](https://github.com/pmem/pmemkv/blob/7c93ccb3c934e2377f142887b2a6754163b207ab/.github/workflows/gha.yml#L57)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I believe we should set it properly, so yes - it should be copied (unless there's some trick in GHA workflow, I don't know, to inherit the variables for the docs job...)
</blockquote></details>

Done. Since the code is duplicated in two places - I decided to remove the logic for release. If we will ever need this, we can add it again.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/933#-:-MVFrOhN7nLzO-8UllV1:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Pull request merged**
