### PR TITLE
tests: add concurrent put and remove test

### PR DESCRIPTION
**Pull request by igchor**
It verifies if put() behaves correctly in case other threads are
concurrently removing the same element.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/921)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/921)* status: all files reviewed, 3 unresolved discussions (waiting on @igchor)

___
*[tests/engine_scenarios/concurrent/put_get_remove_params.cc, line 2 at r1](https://reviewable.io/reviews/pmem/pmemkv/921#-MTFcDVN0hDUTjfxFERF:-MTFcDVN0hDUTjfxFERG:b-8mxykb) ([raw file](https://github.com/pmem/pmemkv/blob/1a96a128c663c03727f3a661f15d8e85e1c618b0/tests/engine_scenarios/concurrent/put_get_remove_params.cc#L2)):*
> ```cpp
> // SPDX-License-Identifier: BSD-3-Clause
> /* Copyright 2020, Intel Corporation */
> ```

-2021
___
*[tests/engine_scenarios/concurrent/put_get_remove_params.cc, line 81 at r1](https://reviewable.io/reviews/pmem/pmemkv/921#-MTFvJ5zAEJl6sU4r-9n:-MTFvJ5zAEJl6sU4r-9o:b-zaod7q) ([raw file](https://github.com/pmem/pmemkv/blob/1a96a128c663c03727f3a661f15d8e85e1c618b0/tests/engine_scenarios/concurrent/put_get_remove_params.cc#L81)):*
> ```cpp
> 	parallel_exec(threads_number, [&](size_t thread_id) {
> 		size_t begin = 0;
> 		size_t end = initial_items;
> ```

why do you need these begin/end vars?
___
*[tests/engine_scenarios/concurrent/put_get_remove_params.cc, line 97 at r1](https://reviewable.io/reviews/pmem/pmemkv/921#-MTFvZ6vDPCqxwJRihmT:-MTFvZ6vDPCqxwJRihmU:bbezj9n) ([raw file](https://github.com/pmem/pmemkv/blob/1a96a128c663c03727f3a661f15d8e85e1c618b0/tests/engine_scenarios/concurrent/put_get_remove_params.cc#L97)):*
> ```cpp
> 
> 	for (size_t i = 0; i < initial_items; i++) {
> 		std::string istr = "init_" + std::to_string(i);
> ```

remove "init_", I believe

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/921)* status: all files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[tests/engine_scenarios/concurrent/put_get_remove_params.cc, line 2 at r1](https://reviewable.io/reviews/pmem/pmemkv/921#-MTFcDVN0hDUTjfxFERF:-MTFwCV32aL7cW8y0qhK:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/1a96a128c663c03727f3a661f15d8e85e1c618b0/tests/engine_scenarios/concurrent/put_get_remove_params.cc#L2)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

-2021
</blockquote></details>

Done.
___
*[tests/engine_scenarios/concurrent/put_get_remove_params.cc, line 81 at r1](https://reviewable.io/reviews/pmem/pmemkv/921#-MTFvJ5zAEJl6sU4r-9n:-MTFwPUIAgCM8F4LsDQe:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/1a96a128c663c03727f3a661f15d8e85e1c618b0/tests/engine_scenarios/concurrent/put_get_remove_params.cc#L81)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

why do you need these begin/end vars?
</blockquote></details>

Done.
___
*[tests/engine_scenarios/concurrent/put_get_remove_params.cc, line 97 at r1](https://reviewable.io/reviews/pmem/pmemkv/921#-MTFvZ6vDPCqxwJRihmT:-MTFx-tkBst7hRaXpdrO:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/1a96a128c663c03727f3a661f15d8e85e1c618b0/tests/engine_scenarios/concurrent/put_get_remove_params.cc#L97)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

remove "init_", I believe
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/921#-:-MTFyt8T8bXREY-BdN1X:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Comment by karczex** [comment]
___
*[tests/CMakeLists.txt, line 502 at r3](https://reviewable.io/reviews/pmem/pmemkv/921#-MTGgbUU4RZYQSyt5GdE:-MTGgbUU4RZYQSyt5GdF:b-q93yzl) ([raw file](https://github.com/pmem/pmemkv/blob/060ed51ae0595dbd63669d83086ef68e83a9c5f5/tests/CMakeLists.txt#L502)):*
> ```CMake
> 			PARAMS 8 50)
> 
> 	if (TESTS_PMEMOBJ_DRD_HELGRIND AND TESTS_LONG)
> ```

Wouldn't it make coverage lower? Maybe move this test to separate binary?

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/921)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @karczex)

___
*[tests/CMakeLists.txt, line 502 at r3](https://reviewable.io/reviews/pmem/pmemkv/921#-MTGgbUU4RZYQSyt5GdE:-MTKM_eKBC3zcMNFRr_Z:b-dbt4an) ([raw file](https://github.com/pmem/pmemkv/blob/060ed51ae0595dbd63669d83086ef68e83a9c5f5/tests/CMakeLists.txt#L502)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Wouldn't it make coverage lower? Maybe move this test to separate binary?
</blockquote></details>

No, coverage is not measured for valgrind

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/921#-:-MTKbDmy36_yscWsU4ZZ:bnfp4nl)* status: 1 of 2 files reviewed, all discussions resolved

**Pull request merged**
