### PR TITLE
Disable tests to limit dependencies in default build

### PR DESCRIPTION
**Pull request by KFilipek**
- installing: dependencies update
- CMakeFile: disable tests compilation as default option

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/853)

### CODE REVIEW

**Review by lukaszstolarczuk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/853)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @KFilipek)

___
*[CMakeLists.txt, line 13 at r1](https://reviewable.io/reviews/pmem/pmemkv/853#-MNdC3US5Z3Fg2NBWfzF:-MNdC3UT08WcXyAo0JPL:b-xn79eo) ([raw file](https://github.com/pmem/pmemkv/blob/b905c808ec42c6e1a2e3549697e72eabf113c7cb/CMakeLists.txt#L13)):*
> ```CMake
> option(BUILD_DOC "build documentation" ON)
> option(BUILD_EXAMPLES "build examples" ON)
> option(BUILD_TESTS "build tests" OFF)
> ```

I would personally leave it as ON, by default.

What's the time gain on the build without tests?
___
*[INSTALLING.md, line 45 at r1](https://reviewable.io/reviews/pmem/pmemkv/853#-MNdCK9pDn-_kQwsCyCi:-MNdCK9pDn-_kQwsCyCj:b-2ea8cj) ([raw file](https://github.com/pmem/pmemkv/blob/b905c808ec42c6e1a2e3549697e72eabf113c7cb/INSTALLING.md#L45)):*
> ```Markdown
> mkdir ./build
> cd ./build
> cmake ..                # run CMake
> ```

if you disabled tests by default, you have to turn them on explicitly here (and probably in CI...)

**Review by KFilipek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/853)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[CMakeLists.txt, line 13 at r1](https://reviewable.io/reviews/pmem/pmemkv/853#-MNdC3US5Z3Fg2NBWfzF:-MNdF8Tc78AzgI5KWciI:b-91o1cl) ([raw file](https://github.com/pmem/pmemkv/blob/b905c808ec42c6e1a2e3549697e72eabf113c7cb/CMakeLists.txt#L13)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I would personally leave it as ON, by default.

What's the time gain on the build without tests?
</blockquote></details>

I can measure it for you, but intention of this PR is to limit number of dependencies at simply executing "make". For now pmempool tool is needed, but it was not enumerated anywhere.
___
*[INSTALLING.md, line 45 at r1](https://reviewable.io/reviews/pmem/pmemkv/853#-MNdCK9pDn-_kQwsCyCi:-MNdFZ_z3if6K85JHxFc:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/b905c808ec42c6e1a2e3549697e72eabf113c7cb/INSTALLING.md#L45)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

if you disabled tests by default, you have to turn them on explicitly here (and probably in CI...)
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/853)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[CMakeLists.txt, line 13 at r1](https://reviewable.io/reviews/pmem/pmemkv/853#-MNdC3US5Z3Fg2NBWfzF:-MNdNDX4Cpwliqn7YlBw:ba0v8e3) ([raw file](https://github.com/pmem/pmemkv/blob/b905c808ec42c6e1a2e3549697e72eabf113c7cb/CMakeLists.txt#L13)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

I can measure it for you, but intention of this PR is to limit number of dependencies at simply executing "make". For now pmempool tool is needed, but it was not enumerated anywhere.
</blockquote></details>

och, sorry, I thought you want to speed up the build process itself. Anyway, I agree we should explicitly put pmempool as dependency for test, but it doesn't mean we have to disable tests by default.

My reasoning is, nobody complained to install tests' dependencies (yet, as far as I know) and people I was helping with installation of pmemkv rather wanted to enable tests and run them on their machines than disable it and have easier build.

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/853)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[CMakeLists.txt, line 13 at r1](https://reviewable.io/reviews/pmem/pmemkv/853#-MNdC3US5Z3Fg2NBWfzF:-MO0nCb13sEbtvPPLOT7:b-1rudhv) ([raw file](https://github.com/pmem/pmemkv/blob/b905c808ec42c6e1a2e3549697e72eabf113c7cb/CMakeLists.txt#L13)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

och, sorry, I thought you want to speed up the build process itself. Anyway, I agree we should explicitly put pmempool as dependency for test, but it doesn't mean we have to disable tests by default.

My reasoning is, nobody complained to install tests' dependencies (yet, as far as I know) and people I was helping with installation of pmemkv rather wanted to enable tests and run them on their machines than disable it and have easier build.
</blockquote></details>

I also prefer to leve it as on. pmemobj is a required dependency of pmemkv and if you do have pmemobj installed you also have pmempool.
___
*[INSTALLING.md, line 32 at r2](https://reviewable.io/reviews/pmem/pmemkv/853#-MO0nLTn0DQJeMfdAIuP:-MO0nLTn0DQJeMfdAIuQ:b-f4vhx9) ([raw file](https://github.com/pmem/pmemkv/blob/6894951b1120d1347011b141842e327f87a7ed25/INSTALLING.md#L32)):*
> ```Markdown
> 	* [**valgrind**](https://github.com/pmem/valgrind) - tool for profiling and memory leak detection. *pmem* forked version with *pmemcheck*
> 		tool is recommended, but upstream/original [valgrind](https://valgrind.org/) is also compatible (package valgrind-devel is required).
> 	* [**pandoc**](https://pandoc.org/) - markup converter to generate manpages
> ```

Hm, I'm wondering if it wouldn't be better to split those dependecies into separate "testing" dependencies and "dev" dependecies. For example, you only need doxygen, graphiz, perl, clang-format and pandoc if you build docs and run style checker (which user probably won't do).

**Review by KFilipek — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/853)* status: all files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[CMakeLists.txt, line 13 at r1](https://reviewable.io/reviews/pmem/pmemkv/853#-MNdC3US5Z3Fg2NBWfzF:-MOVuc3r49pf_UhpMg8X:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/b905c808ec42c6e1a2e3549697e72eabf113c7cb/CMakeLists.txt#L13)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I also prefer to leve it as on. pmemobj is a required dependency of pmemkv and if you do have pmemobj installed you also have pmempool.
</blockquote></details>

Done.

**Review by lukaszstolarczuk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/853#-:-MOW1zy_8vmSkaNk1xqs:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KFilipek)

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/853)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KFilipek)

**Review by igchor — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/853)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KFilipek)

**Pull request merged**
